.DEFINE TILE_1BPP_SIZE TILE_SIZE / 2 ; bytes

.DEFINE BLOCK_WIDTH 4 ; tiles
.DEFINE BLOCK_HEIGHT BLOCK_WIDTH ; tiles
.DEFINE SCREEN_BLOCK_WIDTH 6 ; blocks
.DEFINE SCREEN_BLOCK_HEIGHT 5 ; blocks
.DEFINE SURROUNDING_WIDTH SCREEN_BLOCK_WIDTH * BLOCK_WIDTH ; tiles
.DEFINE SURROUNDING_HEIGHT SCREEN_BLOCK_HEIGHT * BLOCK_HEIGHT ; tiles

.DEFINE PIC_WIDTH 7 ; tiles
.DEFINE PIC_HEIGHT PIC_WIDTH ; tiles
.DEFINE PIC_SIZE PIC_WIDTH * PIC_HEIGHT ; tiles

.DEFINE SPRITEBUFFERSIZE PIC_WIDTH * PIC_HEIGHT * TILE_1BPP_SIZE

; HP bar
.DEFINE HP_BAR_GREEN 0
.DEFINE HP_BAR_YELLOW 1
.DEFINE HP_BAR_RED 2

; hAutoBGTransferEnabled
.DEFINE TRANSFERTOP 0
.DEFINE TRANSFERMIDDLE 1
.DEFINE TRANSFERBOTTOM 2

; hRedrawRowOrColumnMode
.DEFINE REDRAW_COL 1
.DEFINE REDRAW_ROW 2

; hUILayoutFlags
	const_def
	const BIT_PARTY_MENU_HP_BAR   ; 0
	const BIT_DOUBLE_SPACED_MENU  ; 1
	const BIT_SINGLE_SPACED_LINES ; 2

; tile list ids
; TileIDListPointerTable indexes (see data/tilemaps.asm)
	const_def
	const TILEMAP_MON_PIC
	const TILEMAP_SLIDE_DOWN_MON_PIC_7X5
	const TILEMAP_SLIDE_DOWN_MON_PIC_7X3
	const TILEMAP_GENGAR_INTRO_1
	const TILEMAP_GENGAR_INTRO_2
	const TILEMAP_GENGAR_INTRO_3
	const TILEMAP_GAME_BOY
	const TILEMAP_LINK_CABLE
.DEFINE NUM_TILEMAPS const_value
