; spritestatedata1 struct members (see macros/ram.asm)
	const_def
	const SPRITESTATEDATA1_PICTUREID             ; 0
	const SPRITESTATEDATA1_MOVEMENTSTATUS        ; 1
	const SPRITESTATEDATA1_IMAGEINDEX            ; 2
	const SPRITESTATEDATA1_YSTEPVECTOR           ; 3
	const SPRITESTATEDATA1_YPIXELS               ; 4
	const SPRITESTATEDATA1_XSTEPVECTOR           ; 5
	const SPRITESTATEDATA1_XPIXELS               ; 6
	const SPRITESTATEDATA1_INTRAANIMFRAMECOUNTER ; 7
	const SPRITESTATEDATA1_ANIMFRAMECOUNTER      ; 8
	const SPRITESTATEDATA1_FACINGDIRECTION       ; 9
	const SPRITESTATEDATA1_YADJUSTED             ; a
	const SPRITESTATEDATA1_XADJUSTED             ; b
	const SPRITESTATEDATA1_COLLISIONDATA         ; c
	const SPRITESTATEDATA1_0D                    ; d
	const SPRITESTATEDATA1_0E                    ; e
	const SPRITESTATEDATA1_0F                    ; f
.DEFINE SPRITESTATEDATA1_LENGTH const_value

; spritestatedata2 struct members (see macros/ram.asm)
	const_def
	const SPRITESTATEDATA2_WALKANIMATIONCOUNTER ; 0
	const SPRITESTATEDATA2_01                   ; 1
	const SPRITESTATEDATA2_YDISPLACEMENT        ; 2
	const SPRITESTATEDATA2_XDISPLACEMENT        ; 3
	const SPRITESTATEDATA2_MAPY                 ; 4
	const SPRITESTATEDATA2_MAPX                 ; 5
	const SPRITESTATEDATA2_MOVEMENTBYTE1        ; 6
	const SPRITESTATEDATA2_GRASSPRIORITY        ; 7
	const SPRITESTATEDATA2_MOVEMENTDELAY        ; 8
	const SPRITESTATEDATA2_ORIGFACINGDIRECTION  ; 9
	const SPRITESTATEDATA2_0A                   ; a
	const SPRITESTATEDATA2_0B                   ; b
	const SPRITESTATEDATA2_0C                   ; c
	const SPRITESTATEDATA2_PICTUREID            ; d
	const SPRITESTATEDATA2_IMAGEBASEOFFSET      ; e
	const SPRITESTATEDATA2_0F                   ; f
.DEFINE SPRITESTATEDATA2_LENGTH const_value

.DEFINE NUM_SPRITESTATEDATA_STRUCTS 16

	const_def 6
	const BIT_TRAINER ; 6
	const BIT_ITEM    ; 7

; different kinds of people events
.DEFINE TRAINER 1 << BIT_TRAINER
.DEFINE ITEM 1 << BIT_ITEM

; movement status
.DEFINE BIT_FACE_PLAYER 7

.DEFINE WALK $FE
.DEFINE STAY $FF

.DEFINE ANY_DIR $00
.DEFINE UP_DOWN $01
.DEFINE LEFT_RIGHT $02
.DEFINE DOWN $D0
.DEFINE UP $D1
.DEFINE LEFT $D2
.DEFINE RIGHT $D3
.DEFINE NONE $FF

.DEFINE BOULDER_MOVEMENT_BYTE_2 $10
