.DEFINE NUM_PLAYER_NAMES 3

.IF defined(_RED)
.DEFINE PLAYERNAME1 "RED"
.DEFINE PLAYERNAME2 "ASH"
.DEFINE PLAYERNAME3 "JACK"

.DEFINE RIVALNAME1 "BLUE"
.DEFINE RIVALNAME2 "GARY"
.DEFINE RIVALNAME3 "JOHN"
.ENDIF

.IF defined(_BLUE)
.DEFINE PLAYERNAME1 "BLUE"
.DEFINE PLAYERNAME2 "GARY"
.DEFINE PLAYERNAME3 "JOHN"

.DEFINE RIVALNAME1 "RED"
.DEFINE RIVALNAME2 "ASH"
.DEFINE RIVALNAME3 "JACK"
.ENDIF
