.DEFINE ESTABLISH_CONNECTION_WITH_INTERNAL_CLOCK $01
.DEFINE ESTABLISH_CONNECTION_WITH_EXTERNAL_CLOCK $02

.DEFINE USING_EXTERNAL_CLOCK $01
.DEFINE USING_INTERNAL_CLOCK $02
.DEFINE CONNECTION_NOT_ESTABLISHED $ff

; signals the start of an array of bytes transferred over the link cable
.DEFINE SERIAL_PREAMBLE_BYTE $FD

; this byte is used when there is no data to send
.DEFINE SERIAL_NO_DATA_BYTE $FE

; signals the end of one part of a patch list (there are two parts) for player/enemy party data
.DEFINE SERIAL_PATCH_LIST_PART_TERMINATOR $FF

.DEFINE SERIAL_PREAMBLE_LENGTH 6
.DEFINE SERIAL_RN_PREAMBLE_LENGTH 7
.DEFINE SERIAL_RNS_LENGTH 10

.DEFINE LINK_STATE_NONE $00 ; not using link
.DEFINE LINK_STATE_IN_CABLE_CLUB $01 ; in a cable club room (Colosseum or Trade Centre)
.DEFINE LINK_STATE_START_TRADE $02 ; pre-trade selection screen initialisation
.DEFINE LINK_STATE_START_BATTLE $03 ; pre-battle initialisation
.DEFINE LINK_STATE_BATTLING $04 ; in a link battle
.DEFINE LINK_STATE_RESET $05 ; reset game (unused)
.DEFINE LINK_STATE_TRADING $32 ; in a link trade

.DEFINE LINKBATTLE_RUN $F
.DEFINE LINKBATTLE_STRUGGLE $E
.DEFINE LINKBATTLE_NO_ACTION $D
