; sprite facing directions
	const_def 0, $04
	const SPRITE_FACING_DOWN  ; $00
	const SPRITE_FACING_UP    ; $04
	const SPRITE_FACING_LEFT  ; $08
	const SPRITE_FACING_RIGHT ; $0C

	const_def 0, $40
	const NPC_MOVEMENT_DOWN  ; $00
	const NPC_MOVEMENT_UP    ; $40
	const NPC_MOVEMENT_LEFT  ; $80
	const NPC_MOVEMENT_RIGHT ; $C0

.DEFINE NPC_CHANGE_FACING $E0

; player direction constants
	const_def
	const PLAYER_DIR_BIT_RIGHT ; 0
	const PLAYER_DIR_BIT_LEFT  ; 1
	const PLAYER_DIR_BIT_DOWN  ; 2
	const PLAYER_DIR_BIT_UP    ; 3

.DEFINE PLAYER_DIR_RIGHT 1 << PLAYER_DIR_BIT_RIGHT
.DEFINE PLAYER_DIR_LEFT 1 << PLAYER_DIR_BIT_LEFT
.DEFINE PLAYER_DIR_DOWN 1 << PLAYER_DIR_BIT_DOWN
.DEFINE PLAYER_DIR_UP 1 << PLAYER_DIR_BIT_UP
