.DEFINE PLAYER_NAME_LENGTH 8
.DEFINE STAT_NAME_LENGTH 10
.DEFINE NAME_LENGTH 11
.DEFINE ITEM_NAME_LENGTH 13
.DEFINE TRAINER_NAME_LENGTH 13
.DEFINE MOVE_NAME_LENGTH 14
.DEFINE GYM_CITY_LENGTH 17
.DEFINE NAME_BUFFER_LENGTH 20

; PrintNumber, PrintBCDNumber
	const_def 5
	const BIT_MONEY_SIGN     ; 5
	const BIT_LEFT_ALIGN     ; 6
	const BIT_LEADING_ZEROES ; 7

.DEFINE MONEY_SIGN 1 << BIT_MONEY_SIGN
.DEFINE LEFT_ALIGN 1 << BIT_LEFT_ALIGN
.DEFINE LEADING_ZEROES 1 << BIT_LEADING_ZEROES

; special text IDs (see home/text_script.asm)
	const_def $d0
	const TEXT_MON_FAINTED      ; $d0
	const TEXT_BLACKED_OUT      ; $d1
	const TEXT_REPEL_WORE_OFF   ; $d2
	const TEXT_SAFARI_GAME_OVER ; $d3

.DEFINE TEXT_START_MENU $00
