; Structured replacement for data/events/slot_machine_wheels.asm.
SlotMachineWheel1:
	.DW SLOTS7
	.DW SLOTSMOUSE
	.DW SLOTSFISH
	.DW SLOTSBAR
	.DW SLOTSCHERRY
	.DW SLOTS7
	.DW SLOTSFISH
	.DW SLOTSBIRD
	.DW SLOTSBAR
	.DW SLOTSCHERRY
	.DW SLOTS7
	.DW SLOTSMOUSE
	.DW SLOTSBIRD
	.DW SLOTSBAR
	.DW SLOTSCHERRY
	.DW SLOTS7
	.DW SLOTSMOUSE
	.DW SLOTSFISH

SlotMachineWheel1End:

SlotMachineWheel2:
	.DW SLOTS7
	.DW SLOTSFISH
	.DW SLOTSCHERRY
	.DW SLOTSBIRD
	.DW SLOTSMOUSE
	.DW SLOTSBAR
	.DW SLOTSCHERRY
	.DW SLOTSFISH
	.DW SLOTSBIRD
	.DW SLOTSCHERRY
	.DW SLOTSBAR
	.DW SLOTSFISH
	.DW SLOTSBIRD
	.DW SLOTSCHERRY
	.DW SLOTSMOUSE
	.DW SLOTS7
	.DW SLOTSFISH
	.DW SLOTSCHERRY

SlotMachineWheel2End:

SlotMachineWheel3:
	.DW SLOTS7
	.DW SLOTSBIRD
	.DW SLOTSFISH

	.DW SLOTSCHERRY
	.DW SLOTSMOUSE
	.DW SLOTSBIRD
	.DW SLOTSFISH
	.DW SLOTSCHERRY
	.DW SLOTSMOUSE
	.DW SLOTSBIRD
	.DW SLOTSFISH
	.DW SLOTSCHERRY
	.DW SLOTSMOUSE
	.DW SLOTSBIRD
	.DW SLOTSBAR
	.DW SLOTS7
	.DW SLOTSBIRD
	.DW SLOTSFISH
SlotMachineWheel3End:
SlotMachineWheelsEnd:
