; Generated by convert_text_bank.py from:
;   data/text/text_1.asm
;   text/ViridianForest.asm
;   text/MtMoon1F.asm
;   text/MtMoonB1F.asm
;   text/MtMoonB2F.asm
;   text/SSAnne1F.asm
;   text/SSAnne2F.asm
;   text/SSAnne3F.asm
;   text/SSAnneBow.asm
;   text/SSAnneKitchen.asm
;   text/SSAnneCaptainsRoom.asm
;   text/SSAnne1FRooms.asm
;   text/SSAnne2FRooms.asm
;   text/SSAnneB1FRooms.asm
;   text/VictoryRoad3F.asm
;   text/RocketHideoutB1F.asm
;   text/RocketHideoutB2F.asm
;   text/RocketHideoutB3F.asm
;   text/RocketHideoutB4F.asm
;   text/RocketHideoutElevator.asm
;   text/SilphCo2F.asm
;   text/SilphCo3F.asm
;   text/SilphCo4F.asm
;   text/SilphCo5F.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; data/text/text_1.asm
_CardKeySuccessText1::
	.DB $00
	.STRINGMAP pokemon, "Bingo!@"
	.DB $50
_CardKeySuccessText2::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "The CARD KEY"
	.DB $55
	.STRINGMAP pokemon, "opened the door!"
	.DB $57
_CardKeyFailText::
	.DB $00
	.STRINGMAP pokemon, "Darn! It needs a"
	.DB $4f
	.STRINGMAP pokemon, "CARD KEY!"
	.DB $57
_TrainerNameText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, ": @"
	.DB $50
_NoNibbleText::
	.DB $00
	.STRINGMAP pokemon, "Not even a nibble!"
	.DB $58
_NothingHereText::
	.DB $00
	.STRINGMAP pokemon, "Looks like there's"
	.DB $4f
	.STRINGMAP pokemon, "nothing here."
	.DB $58
_ItsABiteText::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "It's a bite!"
	.DB $58
_ExclamationText::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_GroundRoseText::
	.DB $00
	.STRINGMAP pokemon, "Ground rose up"
	.DB $4f
	.STRINGMAP pokemon, "somewhere!"
	.DB $57
_BoulderText::
	.DB $00
	.STRINGMAP pokemon, "This requires"
	.DB $4f
	.STRINGMAP pokemon, "STRENGTH to move!"
	.DB $57
_MartSignText::
	.DB $00
	.STRINGMAP pokemon, "All your item"
	.DB $4f
	.STRINGMAP pokemon, "needs fulfilled!"
	.DB $55
	.STRINGMAP pokemon, "#MON MART"
	.DB $57
_PokeCenterSignText::
	.DB $00
	.STRINGMAP pokemon, "Heal Your #MON!"
	.DB $4f
	.STRINGMAP pokemon, "#MON CENTER"
	.DB $57
_FoundItemText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> found"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_NoMoreRoomForItemText::
	.DB $00
	.STRINGMAP pokemon, "No more room for"
	.DB $4f
	.STRINGMAP pokemon, "items!"
	.DB $57
_OaksAideHiText::
	.DB $00
	.STRINGMAP pokemon, "Hi! Remember me?"
	.DB $4f
	.STRINGMAP pokemon, "I'm PROF.OAK's"
	.DB $55
	.STRINGMAP pokemon, "AIDE!"
	.DB $51
	.STRINGMAP pokemon, "If you caught @"
	.DB $09
	.DW hOaksAideRequirement
	.DB $13
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "kinds of #MON,"
	.DB $55
	.STRINGMAP pokemon, "I'm supposed to"
	.DB $55
	.STRINGMAP pokemon, "give you an"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wOaksAideRewardItemName
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "So, <PLAYER>! Have"
	.DB $4f
	.STRINGMAP pokemon, "you caught at"
	.DB $55
	.STRINGMAP pokemon, "least @"
	.DB $09
	.DW hOaksAideRequirement
	.DB $13
	.DB $00
	.STRINGMAP pokemon, " kinds of"
	.DB $55
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_OaksAideUhOhText::
	.DB $00
	.STRINGMAP pokemon, "Let's see..."
	.DB $4f
	.STRINGMAP pokemon, "Uh-oh! You have"
	.DB $55
	.STRINGMAP pokemon, "caught only @"
	.DB $09
	.DW hOaksAideNumMonsOwned
	.DB $13
	.DB $00
	.DB $55
	.STRINGMAP pokemon, "kinds of #MON!"
	.DB $51
	.STRINGMAP pokemon, "You need @"
	.DB $09
	.DW hOaksAideRequirement
	.DB $13
	.DB $00
	.STRINGMAP pokemon, " kinds"
	.DB $4f
	.STRINGMAP pokemon, "if you want the"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wOaksAideRewardItemName
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $57
_OaksAideComeBackText::
	.DB $00
	.STRINGMAP pokemon, "Oh. I see."
	.DB $51
	.STRINGMAP pokemon, "When you get @"
	.DB $09
	.DW hOaksAideRequirement
	.DB $13
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "kinds, come back"
	.DB $55
	.STRINGMAP pokemon, "for @"
	.DB $01
	.DW wOaksAideRewardItemName
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $57
_OaksAideHereYouGoText::
	.DB $00
	.STRINGMAP pokemon, "Great! You have"
	.DB $4f
	.STRINGMAP pokemon, "caught @"
	.DB $09
	.DW hOaksAideNumMonsOwned
	.DB $13
	.DB $00
	.STRINGMAP pokemon, " kinds "
	.DB $55
	.STRINGMAP pokemon, "of #MON!"
	.DB $55
	.STRINGMAP pokemon, "Congratulations!"
	.DB $51
	.STRINGMAP pokemon, "Here you go!"
	.DB $58
_OaksAideGotItemText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got the"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wOaksAideRewardItemName
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_OaksAideNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Oh! I see you"
	.DB $4f
	.STRINGMAP pokemon, "don't have any"
	.DB $55
	.STRINGMAP pokemon, "room for the"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wOaksAideRewardItemName
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $57

; text/ViridianForest.asm
_ViridianForestYoungster1Text::
	.DB $00
	.STRINGMAP pokemon, "I came here with"
	.DB $4f
	.STRINGMAP pokemon, "some friends!"
	.DB $51
	.STRINGMAP pokemon, "They're out for"
	.DB $4f
	.STRINGMAP pokemon, "#MON fights!"
	.DB $57
_ViridianForestYoungster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey! You have"
	.DB $4f
	.STRINGMAP pokemon, "#MON! Come on!"
	.DB $55
	.STRINGMAP pokemon, "Let's battle'em!"
	.DB $57
_ViridianForestYoungster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "No!"
	.DB $4f
	.STRINGMAP pokemon, "CATERPIE can't"
	.DB $55
	.STRINGMAP pokemon, "cut it!"
	.DB $58
_ViridianForestYoungster2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ssh! You'll scare"
	.DB $4f
	.STRINGMAP pokemon, "the bugs away!"
	.DB $57
_ViridianForestYoungster3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Yo! You can't jam"
	.DB $4f
	.STRINGMAP pokemon, "out if you're a"
	.DB $55
	.STRINGMAP pokemon, "#MON trainer!"
	.DB $57
_ViridianForestYoungster3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Huh?"
	.DB $4f
	.STRINGMAP pokemon, "I ran out of"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $58
_ViridianForestYoungster3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Darn! I'm going"
	.DB $4f
	.STRINGMAP pokemon, "to catch some"
	.DB $55
	.STRINGMAP pokemon, "stronger ones!"
	.DB $57
_ViridianForestYoungster4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey, wait up!"
	.DB $4f
	.STRINGMAP pokemon, "What's the hurry?"
	.DB $57
_ViridianForestYoungster4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "give! You're good"
	.DB $55
	.STRINGMAP pokemon, "at this!"
	.DB $58
_ViridianForestYoungster4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Sometimes, you"
	.DB $4f
	.STRINGMAP pokemon, "can find stuff on"
	.DB $55
	.STRINGMAP pokemon, "the ground!"
	.DB $51
	.STRINGMAP pokemon, "I'm looking for"
	.DB $4f
	.STRINGMAP pokemon, "the stuff I"
	.DB $55
	.STRINGMAP pokemon, "dropped!"
	.DB $57
_ViridianForestYoungster5Text::
	.DB $00
	.STRINGMAP pokemon, "I ran out of #"
	.DB $4f
	.STRINGMAP pokemon, "BALLs to catch"
	.DB $55
	.STRINGMAP pokemon, "#MON with!"
	.DB $51
	.STRINGMAP pokemon, "You should carry"
	.DB $4f
	.STRINGMAP pokemon, "extras!"
	.DB $57
_ViridianForestTrainerTips1Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "If you want to"
	.DB $4f
	.STRINGMAP pokemon, "avoid battles,"
	.DB $55
	.STRINGMAP pokemon, "stay away from"
	.DB $55
	.STRINGMAP pokemon, "grassy areas!"
	.DB $57
_ViridianForestUseAntidoteSignText::
	.DB $00
	.STRINGMAP pokemon, "For poison, use"
	.DB $4f
	.STRINGMAP pokemon, "ANTIDOTE! Get it"
	.DB $55
	.STRINGMAP pokemon, "at #MON MARTs!"
	.DB $57
_ViridianForestTrainerTips2Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Contact PROF.OAK"
	.DB $4f
	.STRINGMAP pokemon, "via PC to get"
	.DB $55
	.STRINGMAP pokemon, "your #DEX"
	.DB $55
	.STRINGMAP pokemon, "evaluated!"
	.DB $57
_ViridianForestTrainerTips3Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "No stealing of"
	.DB $4f
	.STRINGMAP pokemon, "#MON from"
	.DB $55
	.STRINGMAP pokemon, "other trainers!"
	.DB $55
	.STRINGMAP pokemon, "Catch only wild"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_ViridianForestTrainerTips4Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Weaken #MON"
	.DB $4f
	.STRINGMAP pokemon, "before attempting"
	.DB $55
	.STRINGMAP pokemon, "capture!"
	.DB $51
	.STRINGMAP pokemon, "When healthy,"
	.DB $4f
	.STRINGMAP pokemon, "they may escape!"
	.DB $57
_ViridianForestLeavingSignText::
	.DB $00
	.STRINGMAP pokemon, "LEAVING"
	.DB $4f
	.STRINGMAP pokemon, "VIRIDIAN FOREST"
	.DB $55
	.STRINGMAP pokemon, "PEWTER CITY AHEAD"
	.DB $57

; text/MtMoon1F.asm
_MtMoon1FHikerBattleText::
	.DB $00
	.STRINGMAP pokemon, "WHOA! You shocked"
	.DB $4f
	.STRINGMAP pokemon, "me! Oh, you're"
	.DB $55
	.STRINGMAP pokemon, "just a kid!"
	.DB $57
_MtMoon1FHikerEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wow!"
	.DB $4f
	.STRINGMAP pokemon, "Shocked again!"
	.DB $58
_MtMoon1FHikerAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Kids like you"
	.DB $4f
	.STRINGMAP pokemon, "shouldn't be"
	.DB $55
	.STRINGMAP pokemon, "here!"
	.DB $57
_MtMoon1FYoungster1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Did you come to"
	.DB $4f
	.STRINGMAP pokemon, "explore too?"
	.DB $57
_MtMoon1FYoungster1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Losing"
	.DB $4f
	.STRINGMAP pokemon, "stinks!"
	.DB $58
_MtMoon1FYoungster1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I came down here"
	.DB $4f
	.STRINGMAP pokemon, "to show off to"
	.DB $55
	.STRINGMAP pokemon, "girls."
	.DB $57
_MtMoon1FCooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Wow! It's way"
	.DB $4f
	.STRINGMAP pokemon, "bigger in here"
	.DB $55
	.STRINGMAP pokemon, "than I thought!"
	.DB $57
_MtMoon1FCooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "I lost it!"
	.DB $58
_MtMoon1FCooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "How do you get"
	.DB $4f
	.STRINGMAP pokemon, "out of here?"
	.DB $57
_MtMoon1FSuperNerdBattleText::
	.DB $00
	.STRINGMAP pokemon, "What! Don't sneak"
	.DB $4f
	.STRINGMAP pokemon, "up on me!"
	.DB $57
_MtMoon1FSuperNerdEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "My"
	.DB $4f
	.STRINGMAP pokemon, "#MON won't do!"
	.DB $58
_MtMoon1FSuperNerdAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I have to find"
	.DB $4f
	.STRINGMAP pokemon, "stronger #MON."
	.DB $57
_MtMoon1FCooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "What? I'm waiting"
	.DB $4f
	.STRINGMAP pokemon, "for my friends to"
	.DB $55
	.STRINGMAP pokemon, "find me here."
	.DB $57
_MtMoon1FCooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I lost?"
	.DB $58
_MtMoon1FCooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I heard there are"
	.DB $4f
	.STRINGMAP pokemon, "some very rare"
	.DB $55
	.STRINGMAP pokemon, "fossils here."
	.DB $57
_MtMoon1FYoungster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Suspicious men"
	.DB $4f
	.STRINGMAP pokemon, "are in the cave."
	.DB $55
	.STRINGMAP pokemon, "What about you?"
	.DB $57
_MtMoon1FYoungster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "got me!"
	.DB $58
_MtMoon1FYoungster2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I saw them! I'm"
	.DB $4f
	.STRINGMAP pokemon, "sure they're from"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET!"
	.DB $57
_MtMoon1FYoungster3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Go through this"
	.DB $4f
	.STRINGMAP pokemon, "cave to get to"
	.DB $55
	.STRINGMAP pokemon, "CERULEAN CITY!"
	.DB $57
_MtMoon1FYoungster3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "lost."
	.DB $58
_MtMoon1FYoungster3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "ZUBAT is tough!"
	.DB $4f
	.STRINGMAP pokemon, "But, it can be"
	.DB $55
	.STRINGMAP pokemon, "useful if you"
	.DB $55
	.STRINGMAP pokemon, "catch one."
	.DB $57
_MtMoon1FBewareZubatSign::
	.DB $00
	.STRINGMAP pokemon, "Beware! ZUBAT is"
	.DB $4f
	.STRINGMAP pokemon, "a blood sucker!"
	.DB $57

; text/MtMoonB1F.asm
_MtMoonB1FUnusedText::
	.DB $00
	.DB $57

; text/MtMoonB2F.asm
_MtMoonB2FDomeFossilYouWantText::
	.DB $00
	.STRINGMAP pokemon, "You want the"
	.DB $4f
	.STRINGMAP pokemon, "DOME FOSSIL?"
	.DB $57
_MtMoonB2FHelixFossilYouWantText::
	.DB $00
	.STRINGMAP pokemon, "You want the"
	.DB $4f
	.STRINGMAP pokemon, "HELIX FOSSIL?"
	.DB $57
_MtMoonB2FReceivedFossilText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got the"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_MtMoonB2FYouHaveNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Look, you've got"
	.DB $4f
	.STRINGMAP pokemon, "no room for this.@"
	.DB $50
_MtMoonB2FSuperNerdTheyreBothMineText::
	.DB $00
	.STRINGMAP pokemon, "Hey, stop!"
	.DB $51
	.STRINGMAP pokemon, "I found these"
	.DB $4f
	.STRINGMAP pokemon, "fossils! They're"
	.DB $55
	.STRINGMAP pokemon, "both mine!"
	.DB $57
_MtMoonB2FSuperNerdOkIllShareText::
	.DB $00
	.STRINGMAP pokemon, "OK!"
	.DB $4f
	.STRINGMAP pokemon, "I'll share!"
	.DB $58
_MtMoonB2fSuperNerdEachTakeOneText::
	.DB $00
	.STRINGMAP pokemon, "We'll each take"
	.DB $4f
	.STRINGMAP pokemon, "one!"
	.DB $55
	.STRINGMAP pokemon, "No being greedy!"
	.DB $57
_MtMoonB2FSuperNerdTheresAPokemonLabText::
	.DB $00
	.STRINGMAP pokemon, "Far away, on"
	.DB $4f
	.STRINGMAP pokemon, "CINNABAR ISLAND,"
	.DB $55
	.STRINGMAP pokemon, "there's a #MON"
	.DB $55
	.STRINGMAP pokemon, "LAB."
	.DB $51
	.STRINGMAP pokemon, "They do research"
	.DB $4f
	.STRINGMAP pokemon, "on regenerating"
	.DB $55
	.STRINGMAP pokemon, "fossils."
	.DB $57
_MtMoonB2FSuperNerdThenThisIsMineText::
	.DB $00
	.STRINGMAP pokemon, "All right. Then"
	.DB $4f
	.STRINGMAP pokemon, "this is mine!@"
	.DB $50
_MtMoonB2FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET will"
	.DB $4f
	.STRINGMAP pokemon, "find the fossils,"
	.DB $55
	.STRINGMAP pokemon, "revive and sell"
	.DB $55
	.STRINGMAP pokemon, "them for cash!"
	.DB $57
_MtMoonB2FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Urgh!"
	.DB $4f
	.STRINGMAP pokemon, "Now I'm mad!"
	.DB $58
_MtMoonB2FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You made me mad!"
	.DB $4f
	.STRINGMAP pokemon, "TEAM ROCKET will"
	.DB $55
	.STRINGMAP pokemon, "blacklist you!"
	.DB $57
_MtMoonB2FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "We, TEAM ROCKET,"
	.DB $4f
	.STRINGMAP pokemon, "are #MON"
	.DB $55
	.STRINGMAP pokemon, "gangsters!"
	.DB $57
_MtMoonB2FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I blew"
	.DB $4f
	.STRINGMAP pokemon, "it!"
	.DB $58
_MtMoonB2FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Darn it all! My"
	.DB $4f
	.STRINGMAP pokemon, "associates won't"
	.DB $55
	.STRINGMAP pokemon, "stand for this!"
	.DB $57
_MtMoonB2FRocket3BattleText::
	.DB $00
	.STRINGMAP pokemon, "We're pulling a"
	.DB $4f
	.STRINGMAP pokemon, "big job here!"
	.DB $55
	.STRINGMAP pokemon, "Get lost, kid!"
	.DB $57
_MtMoonB2FRocket3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "So, you"
	.DB $4f
	.STRINGMAP pokemon, "are good."
	.DB $58
_MtMoonB2FRocket3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If you find a"
	.DB $4f
	.STRINGMAP pokemon, "fossil, give it"
	.DB $55
	.STRINGMAP pokemon, "to me and scram!"
	.DB $57
_MtMoonB2FRocket4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Little kids"
	.DB $4f
	.STRINGMAP pokemon, "should leave"
	.DB $55
	.STRINGMAP pokemon, "grown-ups alone!"
	.DB $57
_MtMoonB2FRocket4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "steamed!"
	.DB $58
_MtMoonB2FRocket4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON lived"
	.DB $4f
	.STRINGMAP pokemon, "here long before"
	.DB $55
	.STRINGMAP pokemon, "people came."
	.DB $57

; text/SSAnne1F.asm
_SSAnne1FWaiterText::
	.DB $00
	.STRINGMAP pokemon, "Bonjour!"
	.DB $4f
	.STRINGMAP pokemon, "I am le waiter on"
	.DB $55
	.STRINGMAP pokemon, "this ship!"
	.DB $51
	.STRINGMAP pokemon, "I will be happy"
	.DB $4f
	.STRINGMAP pokemon, "to serve you any-"
	.DB $55
	.STRINGMAP pokemon, "thing you please!"
	.DB $51
	.STRINGMAP pokemon, "Ah! Le strong"
	.DB $4f
	.STRINGMAP pokemon, "silent type!"
	.DB $57
_SSAnne1FSailorText::
	.DB $00
	.STRINGMAP pokemon, "The passengers"
	.DB $4f
	.STRINGMAP pokemon, "are restless!"
	.DB $51
	.STRINGMAP pokemon, "You might be"
	.DB $4f
	.STRINGMAP pokemon, "challenged by the"
	.DB $55
	.STRINGMAP pokemon, "more bored ones!"
	.DB $57

; text/SSAnne2F.asm
_SSAnne2FWaiterText::
	.DB $00
	.STRINGMAP pokemon, "This ship, she is"
	.DB $4f
	.STRINGMAP pokemon, "a luxury liner"
	.DB $55
	.STRINGMAP pokemon, "for trainers!"
	.DB $51
	.STRINGMAP pokemon, "At every port, we"
	.DB $4f
	.STRINGMAP pokemon, "hold parties with"
	.DB $55
	.STRINGMAP pokemon, "invited trainers!"
	.DB $57
_SSAnne2FRivalText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Bonjour!"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "Imagine seeing"
	.DB $4f
	.STRINGMAP pokemon, "you here!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>, were you"
	.DB $4f
	.STRINGMAP pokemon, "really invited?"
	.DB $51
	.STRINGMAP pokemon, "So how's your"
	.DB $4f
	.STRINGMAP pokemon, "#DEX coming?"
	.DB $51
	.STRINGMAP pokemon, "I already caught"
	.DB $4f
	.STRINGMAP pokemon, "40 kinds, pal!"
	.DB $51
	.STRINGMAP pokemon, "Different kinds"
	.DB $4f
	.STRINGMAP pokemon, "are everywhere!"
	.DB $51
	.STRINGMAP pokemon, "Crawl around in"
	.DB $4f
	.STRINGMAP pokemon, "grassy areas!"
	.DB $57
_SSAnne2FRivalDefeatedText::
	.DB $00
	.STRINGMAP pokemon, "Humph!"
	.DB $51
	.STRINGMAP pokemon, "At least you're"
	.DB $4f
	.STRINGMAP pokemon, "raising your"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $58
_SSAnne2FRivalVictoryText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER>! What are"
	.DB $4f
	.STRINGMAP pokemon, "you, seasick?"
	.DB $51
	.STRINGMAP pokemon, "You should shape"
	.DB $4f
	.STRINGMAP pokemon, "up, pal!"
	.DB $58
_SSAnne2FRivalCutMasterText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: I heard"
	.DB $4f
	.STRINGMAP pokemon, "there was a CUT"
	.DB $55
	.STRINGMAP pokemon, "master on board."
	.DB $51
	.STRINGMAP pokemon, "But, he was just a"
	.DB $4f
	.STRINGMAP pokemon, "seasick, old man!"
	.DB $51
	.STRINGMAP pokemon, "But, CUT itself is"
	.DB $4f
	.STRINGMAP pokemon, "really useful!"
	.DB $51
	.STRINGMAP pokemon, "You should go see"
	.DB $4f
	.STRINGMAP pokemon, "him! Smell ya!"
	.DB $57

; text/SSAnne3F.asm
_SSAnne3FSailorText::
	.DB $00
	.STRINGMAP pokemon, "Our CAPTAIN is a"
	.DB $4f
	.STRINGMAP pokemon, "sword master!"
	.DB $51
	.STRINGMAP pokemon, "He even teaches"
	.DB $4f
	.STRINGMAP pokemon, "CUT to #MON!"
	.DB $57

; text/SSAnneBow.asm
_SSAnneBowSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "The party's over."
	.DB $4f
	.STRINGMAP pokemon, "The ship will be"
	.DB $55
	.STRINGMAP pokemon, "departing soon."
	.DB $57
_SSAnneBowSailor1Text::
	.DB $00
	.STRINGMAP pokemon, "Scrubbing decks"
	.DB $4f
	.STRINGMAP pokemon, "is hard work!"
	.DB $57
_SSAnneBowCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "Urf. I feel ill."
	.DB $51
	.STRINGMAP pokemon, "I stepped out to"
	.DB $4f
	.STRINGMAP pokemon, "get some air."
	.DB $57
_SSAnneBowSailor2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey matey!"
	.DB $51
	.STRINGMAP pokemon, "Let's do a little"
	.DB $4f
	.STRINGMAP pokemon, "jig!"
	.DB $57
_SSAnneBowSailor2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're"
	.DB $4f
	.STRINGMAP pokemon, "impressive!"
	.DB $58
_SSAnneBowSailor2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "How many kinds of"
	.DB $4f
	.STRINGMAP pokemon, "#MON do you"
	.DB $55
	.STRINGMAP pokemon, "think there are?"
	.DB $57
_SSAnneBowSailor3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Ahoy there!"
	.DB $4f
	.STRINGMAP pokemon, "Are you seasick?"
	.DB $57
_SSAnneBowSailor3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I was"
	.DB $4f
	.STRINGMAP pokemon, "just careless!"
	.DB $58
_SSAnneBowSailor3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "My Pa said there"
	.DB $4f
	.STRINGMAP pokemon, "are 100 kinds of"
	.DB $55
	.STRINGMAP pokemon, "#MON. I think"
	.DB $55
	.STRINGMAP pokemon, "there are more."
	.DB $57

; text/SSAnneKitchen.asm
_SSAnneKitchenCook1Text::
	.DB $00
	.STRINGMAP pokemon, "You, mon petit!"
	.DB $4f
	.STRINGMAP pokemon, "We're busy here!"
	.DB $55
	.STRINGMAP pokemon, "Out of the way!"
	.DB $57
_SSAnneKitchenCook2Text::
	.DB $00
	.STRINGMAP pokemon, "I saw an odd ball"
	.DB $4f
	.STRINGMAP pokemon, "in the trash."
	.DB $57
_SSAnneKitchenCook3Text::
	.DB $00
	.STRINGMAP pokemon, "I'm so busy I'm"
	.DB $4f
	.STRINGMAP pokemon, "getting dizzy!"
	.DB $57
_SSAnneKitchenCook4Text::
	.DB $00
	.STRINGMAP pokemon, "Hum-de-hum-de-"
	.DB $4f
	.STRINGMAP pokemon, "ho..."
	.DB $51
	.STRINGMAP pokemon, "I peel spuds"
	.DB $4f
	.STRINGMAP pokemon, "every day!"
	.DB $55
	.STRINGMAP pokemon, "Hum-hum..."
	.DB $57
_SSAnneKitchenCook5Text::
	.DB $00
	.STRINGMAP pokemon, "Did you hear about"
	.DB $4f
	.STRINGMAP pokemon, "SNORLAX?"
	.DB $51
	.STRINGMAP pokemon, "All it does is"
	.DB $4f
	.STRINGMAP pokemon, "eat and sleep!"
	.DB $57
_SSAnneKitchenCook6Text::
	.DB $00
	.STRINGMAP pokemon, "Snivel...Sniff..."
	.DB $51
	.STRINGMAP pokemon, "I only get to"
	.DB $4f
	.STRINGMAP pokemon, "peel onions..."
	.DB $55
	.STRINGMAP pokemon, "Snivel..."
	.DB $57
_SSAnneKitchenCook7MainCourseIsText::
	.DB $00
	.STRINGMAP pokemon, "Er-hem! Indeed I"
	.DB $4f
	.STRINGMAP pokemon, "am le CHEF!"
	.DB $51
	.STRINGMAP pokemon, "Le main course is"
	.DB $58
SSAnneKitchenCook7SalmonDuSaladText::
	.DB $00
	.STRINGMAP pokemon, "Salmon du Salad!"
	.DB $51
	.STRINGMAP pokemon, "Les guests may"
	.DB $4f
	.STRINGMAP pokemon, "gripe it's fish"
	.DB $55
	.STRINGMAP pokemon, "again, however!"
	.DB $57
SSAnneKitchenCook7EelsAuBarbecueText::
	.DB $00
	.STRINGMAP pokemon, "Eels au Barbecue!"
	.DB $51
	.STRINGMAP pokemon, "Les guests will"
	.DB $4f
	.STRINGMAP pokemon, "mutiny, I fear."
	.DB $57
SSAnneKitchenCook7PrimeBeefSteakText::
	.DB $00
	.STRINGMAP pokemon, "Prime Beef Steak!"
	.DB $51
	.STRINGMAP pokemon, "But, have I enough"
	.DB $4f
	.STRINGMAP pokemon, "fillets du beef?"
	.DB $57

; text/SSAnneCaptainsRoom.asm
_SSAnneCaptainsRoomRubCaptainsBackText::
	.DB $00
	.STRINGMAP pokemon, "CAPTAIN: Ooargh..."
	.DB $4f
	.STRINGMAP pokemon, "I feel hideous..."
	.DB $55
	.STRINGMAP pokemon, "Urrp! Seasick..."
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> rubbed"
	.DB $4f
	.STRINGMAP pokemon, "the CAPTAIN's"
	.DB $55
	.STRINGMAP pokemon, "back!"
	.DB $51
	.STRINGMAP pokemon, "Rub-rub..."
	.DB $4f
	.STRINGMAP pokemon, "Rub-rub...@"
	.DB $50
_SSAnneCaptainsRoomCaptainIFeelMuchBetterText::
	.DB $00
	.STRINGMAP pokemon, "CAPTAIN: Whew!"
	.DB $4f
	.STRINGMAP pokemon, "Thank you! I"
	.DB $55
	.STRINGMAP pokemon, "feel much better!"
	.DB $51
	.STRINGMAP pokemon, "You want to see"
	.DB $4f
	.STRINGMAP pokemon, "my CUT technique?"
	.DB $51
	.STRINGMAP pokemon, "I could show you"
	.DB $4f
	.STRINGMAP pokemon, "if I wasn't ill..."
	.DB $51
	.STRINGMAP pokemon, "I know! You can"
	.DB $4f
	.STRINGMAP pokemon, "have this!"
	.DB $51
	.STRINGMAP pokemon, "Teach it to your"
	.DB $4f
	.STRINGMAP pokemon, "#MON and you"
	.DB $55
	.STRINGMAP pokemon, "can see it CUT"
	.DB $55
	.STRINGMAP pokemon, "any time!"
	.DB $58
_SSAnneCaptainsRoomCaptainReceivedHM01Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_SSAnneCaptainsRoomCaptainNotSickAnymoreText::
	.DB $00
	.STRINGMAP pokemon, "CAPTAIN: Whew!"
	.DB $51
	.STRINGMAP pokemon, "Now that I'm not"
	.DB $4f
	.STRINGMAP pokemon, "sick any more, I"
	.DB $55
	.STRINGMAP pokemon, "guess it's time."
	.DB $57
_SSAnneCaptainsRoomCaptainHM01NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Oh no! You have"
	.DB $4f
	.STRINGMAP pokemon, "no room for this!"
	.DB $57
_SSAnneCaptainsRoomTrashText::
	.DB $00
	.STRINGMAP pokemon, "Yuck! Shouldn't"
	.DB $4f
	.STRINGMAP pokemon, "have looked!"
	.DB $57
_SSAnneCaptainsRoomSeasickBookText::
	.DB $00
	.STRINGMAP pokemon, "How to Conquer"
	.DB $4f
	.STRINGMAP pokemon, "Seasickness..."
	.DB $55
	.STRINGMAP pokemon, "The CAPTAIN's"
	.DB $55
	.STRINGMAP pokemon, "reading this!"
	.DB $57

; text/SSAnne1FRooms.asm
_SSAnne1FRoomsWigglytuffText::
	.DB $00
	.STRINGMAP pokemon, "WIGGLYTUFF: Puup"
	.DB $4f
	.STRINGMAP pokemon, "pupuu!@"
	.DB $50
_SSAnne1FRoomsGentleman1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I travel alone"
	.DB $4f
	.STRINGMAP pokemon, "on my journeys!"
	.DB $51
	.STRINGMAP pokemon, "My #MON are my"
	.DB $4f
	.STRINGMAP pokemon, "only friends!"
	.DB $57
_SSAnne1FRoomsGentleman1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "My, my"
	.DB $4f
	.STRINGMAP pokemon, "friends..."
	.DB $58
_SSAnne1FRoomsGentleman1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You should be"
	.DB $4f
	.STRINGMAP pokemon, "nice to friends!"
	.DB $57
_SSAnne1FRoomsGentleman2BattleText::
	.DB $00
	.STRINGMAP pokemon, "You pup! How dare"
	.DB $4f
	.STRINGMAP pokemon, "you barge in!"
	.DB $57
_SSAnne1FRoomsGentleman2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Humph!"
	.DB $4f
	.STRINGMAP pokemon, "You rude child!"
	.DB $58
_SSAnne1FRoomsGentleman2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wish to be left"
	.DB $4f
	.STRINGMAP pokemon, "alone! Get out!"
	.DB $57
_SSAnne1FRoomsYoungsterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I love #MON!"
	.DB $4f
	.STRINGMAP pokemon, "Do you?"
	.DB $57
_SSAnne1FRoomsYoungsterEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wow! "
	.DB $4f
	.STRINGMAP pokemon, "You're great!"
	.DB $58
_SSAnne1FRoomsYoungsterAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Let me be your"
	.DB $4f
	.STRINGMAP pokemon, "friend, OK?"
	.DB $51
	.STRINGMAP pokemon, "Then we can trade"
	.DB $4f
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_SSAnne1FRoomsCooltrainerFBattleText::
	.DB $00
	.STRINGMAP pokemon, "I collected these"
	.DB $4f
	.STRINGMAP pokemon, "#MON from all"
	.DB $55
	.STRINGMAP pokemon, "around the world!"
	.DB $57
_SSAnne1FRoomsCooltrainerFEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh no!"
	.DB $4f
	.STRINGMAP pokemon, "I went around the"
	.DB $55
	.STRINGMAP pokemon, "world for these!"
	.DB $58
_SSAnne1FRoomsCooltrainerFAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You hurt my poor"
	.DB $4f
	.STRINGMAP pokemon, "worldly #MON!"
	.DB $51
	.STRINGMAP pokemon, "I demand that you"
	.DB $4f
	.STRINGMAP pokemon, "heal them at a"
	.DB $55
	.STRINGMAP pokemon, "#MON CENTER!"
	.DB $57
_SSAnne1FRoomsGirl1Text::
	.DB $00
	.STRINGMAP pokemon, "Waiter, I would"
	.DB $4f
	.STRINGMAP pokemon, "like a cherry pie"
	.DB $55
	.STRINGMAP pokemon, "please!"
	.DB $57
_SSAnne1FRoomsMiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "A cruise is so"
	.DB $4f
	.STRINGMAP pokemon, "elegant yet cozy!"
	.DB $57
_SSAnne1FRoomsLittleGirlText::
	.DB $00
	.STRINGMAP pokemon, "I always travel"
	.DB $4f
	.STRINGMAP pokemon, "with WIGGLYTUFF!"
	.DB $57
_SSAnne1FRoomsGirl2Text::
	.DB $00
	.STRINGMAP pokemon, "We are cruising"
	.DB $4f
	.STRINGMAP pokemon, "around the world."
	.DB $57
_SSAnne1FRoomsGentleman3Text::
	.DB $00
	.STRINGMAP pokemon, "Ssh! I'm a GLOBAL"
	.DB $4f
	.STRINGMAP pokemon, "POLICE agent!"
	.DB $51
	.STRINGMAP pokemon, "I'm on the trail"
	.DB $4f
	.STRINGMAP pokemon, "of TEAM ROCKET!"
	.DB $57

; text/SSAnne2FRooms.asm
_SSAnne2FRoomsGentleman3Text::
	.DB $00
	.STRINGMAP pokemon, "In all my travels"
	.DB $4f
	.STRINGMAP pokemon, "I've never seen"
	.DB $55
	.STRINGMAP pokemon, "any #MON sleep"
	.DB $55
	.STRINGMAP pokemon, "like this one!"
	.DB $51
	.STRINGMAP pokemon, "It was something"
	.DB $4f
	.STRINGMAP pokemon, "like this!"
	.DB $58
_SSAnne2FRoomsGentleman4Text::
	.DB $00
	.STRINGMAP pokemon, "Ah yes, I have"
	.DB $4f
	.STRINGMAP pokemon, "seen some #MON"
	.DB $55
	.STRINGMAP pokemon, "ferry people"
	.DB $55
	.STRINGMAP pokemon, "across the water!"
	.DB $57
_SSAnne2FRoomsGrampsText::
	.DB $00
	.STRINGMAP pokemon, "#MON can CUT"
	.DB $4f
	.STRINGMAP pokemon, "down small bushes."
	.DB $57
_SSAnne2FRoomsGentleman5Text::
	.DB $00
	.STRINGMAP pokemon, "Have you gone to"
	.DB $4f
	.STRINGMAP pokemon, "the SAFARI ZONE"
	.DB $55
	.STRINGMAP pokemon, "in FUCHSIA CITY?"
	.DB $51
	.STRINGMAP pokemon, "It had many rare"
	.DB $4f
	.STRINGMAP pokemon, "kinds of #MON!!"
	.DB $57
_SSAnne2FRoomsLittleBoyText::
	.DB $00
	.STRINGMAP pokemon, "Me and my Daddy"
	.DB $4f
	.STRINGMAP pokemon, "think the SAFARI"
	.DB $55
	.STRINGMAP pokemon, "ZONE is awesome!"
	.DB $57
_SSAnne2FRoomsBrunetteGirlText::
	.DB $00
	.STRINGMAP pokemon, "The CAPTAIN looked"
	.DB $4f
	.STRINGMAP pokemon, "really sick and"
	.DB $55
	.STRINGMAP pokemon, "pale!"
	.DB $57
_SSAnne2FRoomsBeautyText::
	.DB $00
	.STRINGMAP pokemon, "I hear many people"
	.DB $4f
	.STRINGMAP pokemon, "get seasick!"
	.DB $57
_SSAnne2FRoomsGentleman1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Competing against"
	.DB $4f
	.STRINGMAP pokemon, "the young keeps"
	.DB $55
	.STRINGMAP pokemon, "me youthful."
	.DB $57
_SSAnne2FRoomsGentleman1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Good"
	.DB $4f
	.STRINGMAP pokemon, "fight! Ah, I feel"
	.DB $55
	.STRINGMAP pokemon, "young again!"
	.DB $58
_SSAnne2FRoomsGentleman1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "15 years ago, I"
	.DB $4f
	.STRINGMAP pokemon, "would have won!"
	.DB $57
_SSAnne2FRoomsFisherBattleText::
	.DB $00
	.STRINGMAP pokemon, "Check out what I"
	.DB $4f
	.STRINGMAP pokemon, "fished up!"
	.DB $57
_SSAnne2FRoomsFisherEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "all out!"
	.DB $58
_SSAnne2FRoomsFisherAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Party?"
	.DB $51
	.STRINGMAP pokemon, "The cruise ship's"
	.DB $4f
	.STRINGMAP pokemon, "party should be"
	.DB $55
	.STRINGMAP pokemon, "over by now."
	.DB $57
_SSAnne2FRoomsGentleman2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Which do you like,"
	.DB $4f
	.STRINGMAP pokemon, "a strong or a"
	.DB $55
	.STRINGMAP pokemon, "rare #MON?"
	.DB $57
_SSAnne2FRoomsGentleman2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I must"
	.DB $4f
	.STRINGMAP pokemon, "salute you!"
	.DB $58
_SSAnne2FRoomsGentleman2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I prefer strong"
	.DB $4f
	.STRINGMAP pokemon, "and rare #MON."
	.DB $57
_SSAnne2FRoomsCooltrainerFBattleText::
	.DB $00
	.STRINGMAP pokemon, "I never saw you"
	.DB $4f
	.STRINGMAP pokemon, "at the party."
	.DB $57
_SSAnne2FRoomsCooltrainerFEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Take"
	.DB $4f
	.STRINGMAP pokemon, "it easy!"
	.DB $58
_SSAnne2FRoomsCooltrainerFAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh, I adore your"
	.DB $4f
	.STRINGMAP pokemon, "strong #MON!"
	.DB $57

; text/SSAnneB1FRooms.asm
_SSAnneB1FRoomsMachokeText::
	.DB $00
	.STRINGMAP pokemon, "MACHOKE: Gwoh!"
	.DB $4f
	.STRINGMAP pokemon, "Goggoh!@"
	.DB $50
_SSAnneB1FRoomsSailor1BattleText::
	.DB $00
	.STRINGMAP pokemon, "You know what they"
	.DB $4f
	.STRINGMAP pokemon, "say about sailors"
	.DB $55
	.STRINGMAP pokemon, "and fighting!"
	.DB $57
_SSAnneB1FRoomsSailor1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Right!"
	.DB $4f
	.STRINGMAP pokemon, "Good fight, mate!"
	.DB $58
_SSAnneB1FRoomsSailor1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Haha! Want to be"
	.DB $4f
	.STRINGMAP pokemon, "a sailor, mate?"
	.DB $57
_SSAnneB1FRoomsSailor2BattleText::
	.DB $00
	.STRINGMAP pokemon, "My sailor's pride"
	.DB $4f
	.STRINGMAP pokemon, "is at stake!"
	.DB $57
_SSAnneB1FRoomsSailor2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Your"
	.DB $4f
	.STRINGMAP pokemon, "spirit sank me!"
	.DB $58
_SSAnneB1FRoomsSailor2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Did you see the"
	.DB $4f
	.STRINGMAP pokemon, "FISHING GURU in"
	.DB $55
	.STRINGMAP pokemon, "VERMILION CITY?"
	.DB $57
_SSAnneB1FRoomsSailor3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Us sailors have"
	.DB $4f
	.STRINGMAP pokemon, "#MON too!"
	.DB $57
_SSAnneB1FRoomsSailor3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "OK, "
	.DB $4f
	.STRINGMAP pokemon, "you're not bad."
	.DB $58
_SSAnneB1FRoomsSailor3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "We caught all our"
	.DB $4f
	.STRINGMAP pokemon, "#MON while"
	.DB $55
	.STRINGMAP pokemon, "out at sea!"
	.DB $57
_SSAnneB1FRoomsSailor4BattleText::
	.DB $00
	.STRINGMAP pokemon, "I like feisty"
	.DB $4f
	.STRINGMAP pokemon, "kids like you!@"
	.DB $50
_SSAnneB1FRoomsSailor4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Argh!"
	.DB $4f
	.STRINGMAP pokemon, "Lost it!"
	.DB $58
_SSAnneB1FRoomsSailor4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Sea #MON live"
	.DB $4f
	.STRINGMAP pokemon, "in deep water."
	.DB $55
	.STRINGMAP pokemon, "You'll need a ROD!"
	.DB $57
_SSAnneB1FRoomsSailor5BattleText::
	.DB $00
	.STRINGMAP pokemon, "Matey, you're"
	.DB $4f
	.STRINGMAP pokemon, "walking the plank"
	.DB $55
	.STRINGMAP pokemon, "if you lose!"
	.DB $57
_SSAnneB1FRoomsSailor5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Argh!"
	.DB $4f
	.STRINGMAP pokemon, "Beaten by a kid!"
	.DB $58
_SSAnneB1FRoomsSailor5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Jellyfish some-"
	.DB $4f
	.STRINGMAP pokemon, "times drift into"
	.DB $55
	.STRINGMAP pokemon, "the ship."
	.DB $57
_SSAnneB1FRoomsFisherBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hello stranger!"
	.DB $4f
	.STRINGMAP pokemon, "Stop and chat!"
	.DB $51
	.STRINGMAP pokemon, "All my #MON"
	.DB $4f
	.STRINGMAP pokemon, "are from the sea!"
	.DB $57
_SSAnneB1FRoomsFisherEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Darn!"
	.DB $4f
	.STRINGMAP pokemon, "I let that one"
	.DB $55
	.STRINGMAP pokemon, "get away!"
	.DB $58
_SSAnneB1FRoomsFisherAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I was going to"
	.DB $4f
	.STRINGMAP pokemon, "make you my"
	.DB $55
	.STRINGMAP pokemon, "assistant too!"
	.DB $57
_SSAnneB1FRoomsSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "My buddy, MACHOKE,"
	.DB $4f
	.STRINGMAP pokemon, "is super strong!"
	.DB $51
	.STRINGMAP pokemon, "He has enough"
	.DB $4f
	.STRINGMAP pokemon, "STRENGTH to move"
	.DB $55
	.STRINGMAP pokemon, "big rocks!"
	.DB $57

; text/VictoryRoad3F.asm
_VictoryRoad3FCooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I heard rumors of"
	.DB $4f
	.STRINGMAP pokemon, "a child prodigy!"
	.DB $57
_VictoryRoad3FCooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "The"
	.DB $4f
	.STRINGMAP pokemon, "rumors were true!"
	.DB $58
_VictoryRoad3FCooltrainerM1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You beat GIOVANNI"
	.DB $4f
	.STRINGMAP pokemon, "of TEAM ROCKET?"
	.DB $57
_VictoryRoad3FCooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'll show you just"
	.DB $4f
	.STRINGMAP pokemon, "how good you are!"
	.DB $57
_VictoryRoad3FCooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "furious!"
	.DB $58
_VictoryRoad3FCooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You showed me just"
	.DB $4f
	.STRINGMAP pokemon, "how good I was!"
	.DB $57
_VictoryRoad3FCooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Only the chosen"
	.DB $4f
	.STRINGMAP pokemon, "can pass here!"
	.DB $57
_VictoryRoad3FCooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "don't believe it!"
	.DB $58
_VictoryRoad3FCooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "All trainers here"
	.DB $4f
	.STRINGMAP pokemon, "are headed to the"
	.DB $55
	.STRINGMAP pokemon, "#MON LEAGUE!"
	.DB $55
	.STRINGMAP pokemon, "Be careful!"
	.DB $57
_VictoryRoad3FCooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Trainers live to"
	.DB $4f
	.STRINGMAP pokemon, "seek stronger"
	.DB $55
	.STRINGMAP pokemon, "opponents!"
	.DB $57
_VictoryRoad3FCooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "So strong!"
	.DB $58
_VictoryRoad3FCooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "By fighting tough"
	.DB $4f
	.STRINGMAP pokemon, "battles, you get"
	.DB $55
	.STRINGMAP pokemon, "stronger!"
	.DB $57

; text/RocketHideoutB1F.asm
_RocketHideoutB1FRocket5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Why...?@"
	.DB $50
_RocketHideoutB1FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Who are you? How"
	.DB $4f
	.STRINGMAP pokemon, "did you get here?"
	.DB $57
_RocketHideoutB1FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oww!"
	.DB $4f
	.STRINGMAP pokemon, "Beaten!"
	.DB $58
_RocketHideoutB1FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you dissing"
	.DB $4f
	.STRINGMAP pokemon, "TEAM ROCKET?"
	.DB $57
_RocketHideoutB1FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "You broke into"
	.DB $4f
	.STRINGMAP pokemon, "our operation?"
	.DB $57
_RocketHideoutB1FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Burnt!"
	.DB $58
_RocketHideoutB1FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're not going"
	.DB $4f
	.STRINGMAP pokemon, "to get away with"
	.DB $55
	.STRINGMAP pokemon, "this, brat!"
	.DB $57
_RocketHideoutB1FRocket3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Intruder alert!"
	.DB $57
_RocketHideoutB1FRocket3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "can't do it!"
	.DB $58
_RocketHideoutB1FRocket3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "SILPH SCOPE?"
	.DB $4f
	.STRINGMAP pokemon, "I don't know"
	.DB $55
	.STRINGMAP pokemon, "where it is!"
	.DB $57
_RocketHideoutB1FRocket4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Why did you come"
	.DB $4f
	.STRINGMAP pokemon, "here?"
	.DB $57
_RocketHideoutB1FRocket4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "This"
	.DB $4f
	.STRINGMAP pokemon, "won't do!"
	.DB $58
_RocketHideoutB1FRocket4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "OK, I'll talk!"
	.DB $4f
	.STRINGMAP pokemon, "Take the elevator"
	.DB $55
	.STRINGMAP pokemon, "to see my BOSS!"
	.DB $57
_RocketHideoutB1FRocket5BattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you lost, you"
	.DB $4f
	.STRINGMAP pokemon, "little rat?"
	.DB $57
_RocketHideoutB1FRocket5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Uh-oh, that fight"
	.DB $4f
	.STRINGMAP pokemon, "opened the door!"
	.DB $57

; text/RocketHideoutB2F.asm
_RocketHideoutB2FRocketBattleText::
	.DB $00
	.STRINGMAP pokemon, "BOSS said you can"
	.DB $4f
	.STRINGMAP pokemon, "see GHOSTs with"
	.DB $55
	.STRINGMAP pokemon, "the SILPH SCOPE!"
	.DB $57
_RocketHideoutB2FRocketEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "surrender!"
	.DB $58
_RocketHideoutB2FRocketAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The TEAM ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "HQ has 4 basement"
	.DB $55
	.STRINGMAP pokemon, "floors. Can you"
	.DB $55
	.STRINGMAP pokemon, "reach the BOSS?"
	.DB $57

; text/RocketHideoutB3F.asm
_RocketHideoutB3FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Stop meddling in"
	.DB $4f
	.STRINGMAP pokemon, "TEAM ROCKET's"
	.DB $55
	.STRINGMAP pokemon, "affairs!"
	.DB $57
_RocketHideoutB3FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oof!"
	.DB $4f
	.STRINGMAP pokemon, "Taken down!"
	.DB $58
_RocketHideoutB3FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "SILPH SCOPE?"
	.DB $4f
	.STRINGMAP pokemon, "The machine the"
	.DB $55
	.STRINGMAP pokemon, "BOSS stole. It's"
	.DB $55
	.STRINGMAP pokemon, "here somewhere."
	.DB $57
_RocketHideout3BattleText::
	.DB $00
	.STRINGMAP pokemon, "We got word from"
	.DB $4f
	.STRINGMAP pokemon, "upstairs that you"
	.DB $55
	.STRINGMAP pokemon, "were coming!"
	.DB $57
_RocketHideout3EndBattleText3::
	.DB $00
	.STRINGMAP pokemon, "What?"
	.DB $4f
	.STRINGMAP pokemon, "I lost? No!"
	.DB $58
_RocketHide3AfterBattleText3::
	.DB $00
	.STRINGMAP pokemon, "Go ahead and go!"
	.DB $4f
	.STRINGMAP pokemon, "But, you need the"
	.DB $55
	.STRINGMAP pokemon, "LIFT KEY to run"
	.DB $55
	.STRINGMAP pokemon, "the elevator!"
	.DB $57

; text/RocketHideoutB4F.asm
_RocketHideoutB4FGiovanniImpressedYouGotHereText::
	.DB $00
	.STRINGMAP pokemon, "So! I must say, I"
	.DB $4f
	.STRINGMAP pokemon, "am impressed you"
	.DB $55
	.STRINGMAP pokemon, "got here!"
	.DB $57
_RocketHideoutB4FGiovanniWhatCannotBeText::
	.DB $00
	.STRINGMAP pokemon, "WHAT!"
	.DB $4f
	.STRINGMAP pokemon, "This cannot be!"
	.DB $58
_RocketHideoutB4FGiovanniHopeWeMeetAgainText::
	.DB $00
	.STRINGMAP pokemon, "I see that you"
	.DB $4f
	.STRINGMAP pokemon, "raise #MON"
	.DB $55
	.STRINGMAP pokemon, "with utmost care."
	.DB $51
	.STRINGMAP pokemon, "A child like you"
	.DB $4f
	.STRINGMAP pokemon, "would never"
	.DB $55
	.STRINGMAP pokemon, "understand what I"
	.DB $55
	.STRINGMAP pokemon, "hope to achieve."
	.DB $51
	.STRINGMAP pokemon, "I shall step"
	.DB $4f
	.STRINGMAP pokemon, "aside this time!"
	.DB $51
	.STRINGMAP pokemon, "I hope we meet"
	.DB $4f
	.STRINGMAP pokemon, "again..."
	.DB $57
_RocketHideoutB4FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I know you! You"
	.DB $4f
	.STRINGMAP pokemon, "ruined our plans"
	.DB $55
	.STRINGMAP pokemon, "at MT.MOON!"
	.DB $57
_RocketHideoutB4FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Burned"
	.DB $4f
	.STRINGMAP pokemon, "again!"
	.DB $58
_RocketHideoutB4FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Do you have"
	.DB $4f
	.STRINGMAP pokemon, "something against"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET?"
	.DB $57
_RocketHideoutB4FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "How can you not"
	.DB $4f
	.STRINGMAP pokemon, "see the beauty of"
	.DB $55
	.STRINGMAP pokemon, "our evil?"
	.DB $57
_RocketHideoutB4FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ayaya!"
	.DB $58
_RocketHideoutB4FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "BOSS! I'm sorry I"
	.DB $4f
	.STRINGMAP pokemon, "failed you!"
	.DB $57
_RocketHideoutB4FRocket3BattleText::
	.DB $00
	.STRINGMAP pokemon, "The elevator"
	.DB $4f
	.STRINGMAP pokemon, "doesn't work? Who"
	.DB $55
	.STRINGMAP pokemon, "has the LIFT KEY?"
	.DB $57
_RocketHideoutB4FRocket3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "No!"
	.DB $58
_RocketHideoutB4FRocket3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh no! I dropped"
	.DB $4f
	.STRINGMAP pokemon, "the LIFT KEY!"
	.DB $57

; text/RocketHideoutElevator.asm
_RocketHideoutElevatorAppearsToNeedKeyText::
	.DB $00
	.STRINGMAP pokemon, "It appears to"
	.DB $4f
	.STRINGMAP pokemon, "need a key.@"
	.DB $50

; text/SilphCo2F.asm
SilphCo2FSilphWorkerFPleaseTakeThisText::
	.DB $00
	.STRINGMAP pokemon, "Eeek!"
	.DB $4f
	.STRINGMAP pokemon, "No! Stop! Help!"
	.DB $51
	.STRINGMAP pokemon, "Oh, you're not"
	.DB $4f
	.STRINGMAP pokemon, "with TEAM ROCKET."
	.DB $55
	.STRINGMAP pokemon, "I thought..."
	.DB $55
	.STRINGMAP pokemon, "I'm sorry. Here,"
	.DB $55
	.STRINGMAP pokemon, "please take this!"
	.DB $58
_SilphCo2FSilphWorkerFReceivedTM36Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_SilphCo2FSilphWorkerFTM36ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "TM36 is"
	.DB $4f
	.STRINGMAP pokemon, "SELFDESTRUCT!"
	.DB $51
	.STRINGMAP pokemon, "It's powerful, but"
	.DB $4f
	.STRINGMAP pokemon, "the #MON that"
	.DB $55
	.STRINGMAP pokemon, "uses it faints!"
	.DB $55
	.STRINGMAP pokemon, "Be careful."
	.DB $57
_SilphCo2FSilphWorkerFTM36NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You don't have any"
	.DB $4f
	.STRINGMAP pokemon, "room for this."
	.DB $57
_SilphCo2FScientist1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Help! I'm a SILPH"
	.DB $4f
	.STRINGMAP pokemon, "employee."
	.DB $57
_SilphCo2FScientist1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "How"
	.DB $4f
	.STRINGMAP pokemon, "did you know I"
	.DB $55
	.STRINGMAP pokemon, "was a ROCKET?"
	.DB $58
_SilphCo2FScientist1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I work for both"
	.DB $4f
	.STRINGMAP pokemon, "SILPH and TEAM"
	.DB $55
	.STRINGMAP pokemon, "ROCKET!"
	.DB $57
_SilphCo2FScientist2BattleText::
	.DB $00
	.STRINGMAP pokemon, "It's off limits"
	.DB $4f
	.STRINGMAP pokemon, "here! Go home!"
	.DB $57
_SilphCo2FScientist2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're"
	.DB $4f
	.STRINGMAP pokemon, "good."
	.DB $58
_SilphCo2FScientist2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Can you solve the"
	.DB $4f
	.STRINGMAP pokemon, "maze in here?"
	.DB $57
_SilphCo2FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "No kids are"
	.DB $4f
	.STRINGMAP pokemon, "allowed in here!"
	.DB $57
_SilphCo2FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Tough!"
	.DB $58
_SilphCo2FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Diamond shaped"
	.DB $4f
	.STRINGMAP pokemon, "tiles are"
	.DB $55
	.STRINGMAP pokemon, "teleport blocks!"
	.DB $51
	.STRINGMAP pokemon, "They're hi-tech"
	.DB $4f
	.STRINGMAP pokemon, "transporters!"
	.DB $57
_SilphCo2FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey kid! What are"
	.DB $4f
	.STRINGMAP pokemon, "you doing here?"
	.DB $57
_SilphCo2FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I goofed!"
	.DB $58
_SilphCo2FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "SILPH CO. will"
	.DB $4f
	.STRINGMAP pokemon, "be merged with"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET!"
	.DB $57

; text/SilphCo3F.asm
_SilphCo3FSilphWorkerMWhatShouldIDoText::
	.DB $00
	.STRINGMAP pokemon, "I work for SILPH."
	.DB $4f
	.STRINGMAP pokemon, "What should I do?"
	.DB $57
_SilphCo3FSilphWorkerMYouSavedUsText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER>! You and"
	.DB $4f
	.STRINGMAP pokemon, "your #MON"
	.DB $55
	.STRINGMAP pokemon, "saved us!"
	.DB $57
_SilphCo3FRocketBattleText::
	.DB $00
	.STRINGMAP pokemon, "Quit messing with"
	.DB $4f
	.STRINGMAP pokemon, "us, kid!"
	.DB $57
_SilphCo3FRocketEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I give"
	.DB $4f
	.STRINGMAP pokemon, "up!"
	.DB $58
_SilphCo3FRocketAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "A hint? You can"
	.DB $4f
	.STRINGMAP pokemon, "open doors with a"
	.DB $55
	.STRINGMAP pokemon, "CARD KEY!"
	.DB $57
_SilphCo3FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "I support TEAM"
	.DB $4f
	.STRINGMAP pokemon, "ROCKET more than"
	.DB $55
	.STRINGMAP pokemon, "I support SILPH!"
	.DB $57
_SilphCo3FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "really got me!"
	.DB $58
_SilphCo3FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Humph..."
	.DB $51
	.STRINGMAP pokemon, "TEAM ROCKET said"
	.DB $4f
	.STRINGMAP pokemon, "that if I helped"
	.DB $55
	.STRINGMAP pokemon, "them, they'd let"
	.DB $55
	.STRINGMAP pokemon, "me study #MON!"
	.DB $57

; text/SilphCo4F.asm
_SilphCo4FSilphWorkerMImHidingText::
	.DB $00
	.STRINGMAP pokemon, "Sssh! Can't you"
	.DB $4f
	.STRINGMAP pokemon, "see I'm hiding?"
	.DB $57
_SilphCo4FSilphWorkerMTeamRocketIsGoneText::
	.DB $00
	.STRINGMAP pokemon, "Huh? TEAM ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "is gone?"
	.DB $57
_SilphCo4FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET has"
	.DB $4f
	.STRINGMAP pokemon, "taken command of"
	.DB $55
	.STRINGMAP pokemon, "SILPH CO.!"
	.DB $57
_SilphCo4FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Arrgh!"
	.DB $58
_SilphCo4FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Fwahahaha!"
	.DB $4f
	.STRINGMAP pokemon, "My BOSS has been"
	.DB $55
	.STRINGMAP pokemon, "after this place!"
	.DB $57
_SilphCo4FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "My #MON are my"
	.DB $4f
	.STRINGMAP pokemon, "loyal soldiers!"
	.DB $57
_SilphCo4FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Darn!"
	.DB $4f
	.STRINGMAP pokemon, "You weak #MON!"
	.DB $58
_SilphCo4FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The doors are"
	.DB $4f
	.STRINGMAP pokemon, "electronically"
	.DB $55
	.STRINGMAP pokemon, "locked! A CARD"
	.DB $55
	.STRINGMAP pokemon, "KEY opens them!"
	.DB $57
_SilphCo4FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Intruder spotted!"
	.DB $57
_SilphCo4FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Who"
	.DB $4f
	.STRINGMAP pokemon, "are you?"
	.DB $58
_SilphCo4FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I better tell the"
	.DB $4f
	.STRINGMAP pokemon, "BOSS on 11F!"
	.DB $57

; text/SilphCo5F.asm
_SilphCo5FSilphWorkerMThatsYouRightText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET is"
	.DB $4f
	.STRINGMAP pokemon, "in an uproar over"
	.DB $55
	.STRINGMAP pokemon, "some intruder."
	.DB $55
	.STRINGMAP pokemon, "That's you right?"
	.DB $57
_SilphCo5FSilphWorkerMYoureOurHeroText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET took"
	.DB $4f
	.STRINGMAP pokemon, "off! You're our"
	.DB $55
	.STRINGMAP pokemon, "hero! Thank you!"
	.DB $57
_SilphCo5FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I heard a kid was"
	.DB $4f
	.STRINGMAP pokemon, "wandering around."
	.DB $57
_SilphCo5FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Boom!"
	.DB $58
_SilphCo5FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "It's not smart"
	.DB $4f
	.STRINGMAP pokemon, "to pick a fight"
	.DB $55
	.STRINGMAP pokemon, "with TEAM ROCKET!"
	.DB $57
_SilphCo5FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "We study #"
	.DB $4f
	.STRINGMAP pokemon, "BALL technology"
	.DB $55
	.STRINGMAP pokemon, "on this floor!"
	.DB $57
_SilphCo5FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Dang!"
	.DB $4f
	.STRINGMAP pokemon, "Blast it!"
	.DB $58
_SilphCo5FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "We worked on the"
	.DB $4f
	.STRINGMAP pokemon, "ultimate #"
	.DB $55
	.STRINGMAP pokemon, "BALL which would"
	.DB $55
	.STRINGMAP pokemon, "catch anything!"
	.DB $57
_SilphCo5FRockerBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whaaat? There"
	.DB $4f
	.STRINGMAP pokemon, "shouldn't be any"
	.DB $55
	.STRINGMAP pokemon, "children here?"
	.DB $57

Bank32TextEnd::
