; Generated by convert_text_bank.py from:
;   text/Route24_2.asm
;   text/Route25.asm
;   data/text/text_3.asm
;   text/RedsHouse1F.asm
;   text/BluesHouse.asm
;   text/OaksLab.asm
;   text/pokedex_ratings.asm
;   text/ViridianPokecenter.asm
;   text/ViridianMart.asm
;   text/ViridianSchoolHouse.asm
;   text/ViridianNicknameHouse.asm
;   text/ViridianGym.asm
;   text/Museum1F.asm
;   text/Museum2F.asm
;   text/PewterGym.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; text/Route24_2.asm
_Route24CooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "thought not!"
	.DB $58
_Route24CooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I hid because the"
	.DB $4f
	.STRINGMAP pokemon, "people on the"
	.DB $55
	.STRINGMAP pokemon, "bridge scared me!"
	.DB $57
_Route24CooltrainerM3BattleText::
	.DB $00
	.STRINGMAP pokemon, "OK! I'm No. 5!"
	.DB $4f
	.STRINGMAP pokemon, "I'll stomp you!"
	.DB $57
_Route24CooltrainerM3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whoa!"
	.DB $4f
	.STRINGMAP pokemon, "Too much!"
	.DB $58
_Route24CooltrainerM3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I did my best, I"
	.DB $4f
	.STRINGMAP pokemon, "have no regrets!"
	.DB $57
_Route24CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm No. 4!"
	.DB $4f
	.STRINGMAP pokemon, "Getting tired?"
	.DB $57
_Route24CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I lost"
	.DB $4f
	.STRINGMAP pokemon, "too!"
	.DB $58
_Route24CooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I did my best, so"
	.DB $4f
	.STRINGMAP pokemon, "I've no regrets!"
	.DB $57
_Route24Youngster1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Here's No. 3!"
	.DB $4f
	.STRINGMAP pokemon, "I won't be easy!"
	.DB $57
_Route24Youngster1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ow!"
	.DB $4f
	.STRINGMAP pokemon, "Stomped flat!"
	.DB $58
_Route24Youngster1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I did my best, I"
	.DB $4f
	.STRINGMAP pokemon, "have no regrets!"
	.DB $57
_Route24CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm second!"
	.DB $4f
	.STRINGMAP pokemon, "Now it's serious!"
	.DB $57
_Route24CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "How could I"
	.DB $4f
	.STRINGMAP pokemon, "lose?"
	.DB $58
_Route24CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I did my best, I"
	.DB $4f
	.STRINGMAP pokemon, "have no regrets!"
	.DB $57
_Route24Youngster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "This is NUGGET"
	.DB $4f
	.STRINGMAP pokemon, "BRIDGE! Beat us 5"
	.DB $55
	.STRINGMAP pokemon, "trainers and win"
	.DB $55
	.STRINGMAP pokemon, "a fabulous prize!"
	.DB $51
	.STRINGMAP pokemon, "Think you got"
	.DB $4f
	.STRINGMAP pokemon, "what it takes?"
	.DB $57
_Route24Youngster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whoo!"
	.DB $4f
	.STRINGMAP pokemon, "Good stuff!"
	.DB $58
_Route24Youngster2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I did my best, I"
	.DB $4f
	.STRINGMAP pokemon, "have no regrets!"
	.DB $57

; text/Route25.asm
_Route25Youngster1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Local trainers"
	.DB $4f
	.STRINGMAP pokemon, "come here to"
	.DB $55
	.STRINGMAP pokemon, "practice!"
	.DB $57
_Route25Youngster1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're"
	.DB $4f
	.STRINGMAP pokemon, "decent."
	.DB $58
_Route25Youngster1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "All #MON have"
	.DB $4f
	.STRINGMAP pokemon, "weaknesses. It's"
	.DB $55
	.STRINGMAP pokemon, "best to raise"
	.DB $55
	.STRINGMAP pokemon, "different kinds."
	.DB $57
_Route25Youngster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Dad took me to a"
	.DB $4f
	.STRINGMAP pokemon, "great party on"
	.DB $55
	.STRINGMAP pokemon, "S.S.ANNE at"
	.DB $55
	.STRINGMAP pokemon, "VERMILION CITY!"
	.DB $57
_Route25Youngster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "not mad!"
	.DB $58
_Route25Youngster2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "On S.S.ANNE, I"
	.DB $4f
	.STRINGMAP pokemon, "saw trainers from"
	.DB $55
	.STRINGMAP pokemon, "around the world."
	.DB $57
_Route25CooltrainerMBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm a cool guy."
	.DB $4f
	.STRINGMAP pokemon, "I've got a girl"
	.DB $55
	.STRINGMAP pokemon, "friend!"
	.DB $57
_Route25CooltrainerMEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Aww,"
	.DB $4f
	.STRINGMAP pokemon, "darn..."
	.DB $58
_Route25CooltrainerMAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh well. My girl"
	.DB $4f
	.STRINGMAP pokemon, "will cheer me up."
	.DB $57
_Route25CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hi! My boy"
	.DB $4f
	.STRINGMAP pokemon, "friend is cool!"
	.DB $57
_Route25CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I was in"
	.DB $4f
	.STRINGMAP pokemon, "bad condition!"
	.DB $58
_Route25CooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wish my guy was"
	.DB $4f
	.STRINGMAP pokemon, "as good as you!"
	.DB $57
_Route25Youngster3BattleText::
	.DB $00
	.STRINGMAP pokemon, "I knew I had to"
	.DB $4f
	.STRINGMAP pokemon, "fight you!"
	.DB $57
_Route25Youngster3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I knew"
	.DB $4f
	.STRINGMAP pokemon, "I'd lose too!"
	.DB $58
_Route25Youngster3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If your #MON"
	.DB $4f
	.STRINGMAP pokemon, "gets confused or"
	.DB $55
	.STRINGMAP pokemon, "falls asleep,"
	.DB $55
	.STRINGMAP pokemon, "switch it!"
	.DB $57
_Route25CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "My friend has a"
	.DB $4f
	.STRINGMAP pokemon, "cute #MON."
	.DB $55
	.STRINGMAP pokemon, "I'm so jealous!"
	.DB $57
_Route25CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "not so jealous!"
	.DB $58
_Route25CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You came from MT."
	.DB $4f
	.STRINGMAP pokemon, "MOON? May I have"
	.DB $55
	.STRINGMAP pokemon, "a CLEFAIRY?"
	.DB $57
_Route25Hiker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I just got down"
	.DB $4f
	.STRINGMAP pokemon, "from MT.MOON,"
	.DB $55
	.STRINGMAP pokemon, "but I'm ready!"
	.DB $57
_Route25Hiker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "worked hard!"
	.DB $58
_Route25Hiker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Drat!"
	.DB $4f
	.STRINGMAP pokemon, "A ZUBAT bit me"
	.DB $55
	.STRINGMAP pokemon, "back in there."
	.DB $57
_Route25Hiker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm off to see a"
	.DB $4f
	.STRINGMAP pokemon, "#MON collector"
	.DB $55
	.STRINGMAP pokemon, "at the cape!"
	.DB $57
_Route25Hiker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "got me."
	.DB $58
_Route25Hiker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The collector has"
	.DB $4f
	.STRINGMAP pokemon, "many rare kinds"
	.DB $55
	.STRINGMAP pokemon, "of #MON."
	.DB $57
_Route25Hiker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "You're going to"
	.DB $4f
	.STRINGMAP pokemon, "see BILL? First,"
	.DB $55
	.STRINGMAP pokemon, "let's fight!"
	.DB $57
_Route25Hiker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're"
	.DB $4f
	.STRINGMAP pokemon, "something."
	.DB $58
_Route25Hiker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The trail below"
	.DB $4f
	.STRINGMAP pokemon, "is a shortcut to"
	.DB $55
	.STRINGMAP pokemon, "CERULEAN CITY."
	.DB $57
_Route25BillSignText::
	.DB $00
	.STRINGMAP pokemon, "SEA COTTAGE"
	.DB $4f
	.STRINGMAP pokemon, "BILL lives here!"
	.DB $57

; data/text/text_3.asm
_FileDataDestroyedText::
	.DB $00
	.STRINGMAP pokemon, "The file data is"
	.DB $4f
	.STRINGMAP pokemon, "destroyed!"
	.DB $58
_WouldYouLikeToSaveText::
	.DB $00
	.STRINGMAP pokemon, "Would you like to"
	.DB $4f
	.STRINGMAP pokemon, "SAVE the game?"
	.DB $57
_GameSavedText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> saved"
	.DB $4f
	.STRINGMAP pokemon, "the game!"
	.DB $57
_OlderFileWillBeErasedText::
	.DB $00
	.STRINGMAP pokemon, "The older file"
	.DB $4f
	.STRINGMAP pokemon, "will be erased to"
	.DB $55
	.STRINGMAP pokemon, "save. Okay?"
	.DB $57
_WhenYouChangeBoxText::
	.DB $00
	.STRINGMAP pokemon, "When you change a"
	.DB $4f
	.STRINGMAP pokemon, "#MON BOX, data"
	.DB $55
	.STRINGMAP pokemon, "will be saved."
	.DB $51
	.STRINGMAP pokemon, "Is that okay?"
	.DB $57
_ChooseABoxText::
	.DB $00
	.STRINGMAP pokemon, "Choose a"
	.DB $4f
	.STRINGMAP pokemon, "<PKMN> BOX.@"
	.DB $50
_EvolvedText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " evolved"
	.DB $57
_IntoText::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "into @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_StoppedEvolvingText::
	.DB $00
	.STRINGMAP pokemon, "Huh? @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "stopped evolving!"
	.DB $58
_IsEvolvingText::
	.DB $00
	.STRINGMAP pokemon, "What? @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "is evolving!"
	.DB $57
_FellAsleepText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "fell asleep!"
	.DB $58
_AlreadyAsleepText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>'s"
	.DB $4f
	.STRINGMAP pokemon, "already asleep!"
	.DB $58
_PoisonedText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "was poisoned!"
	.DB $58
_BadlyPoisonedText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>'s"
	.DB $4f
	.STRINGMAP pokemon, "badly poisoned!"
	.DB $58
_BurnedText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "was burned!"
	.DB $58
_FrozenText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "was frozen solid!"
	.DB $58
_FireDefrostedText::
	.DB $00
	.STRINGMAP pokemon, "Fire defrosted"
	.DB $4f
	.STRINGMAP pokemon, "<TARGET>!"
	.DB $58
_MonsStatsRoseText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "@"
	.DB $50
_GreatlyRoseText::
	.DB $00
	.STRINGMAP pokemon, "<SCROLL>greatly@"
	.DB $50
_RoseText::
	.DB $00
	.STRINGMAP pokemon, " rose!"
	.DB $58
_MonsStatsFellText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>'s"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "@"
	.DB $50
_GreatlyFellText::
	.DB $00
	.STRINGMAP pokemon, "<SCROLL>greatly@"
	.DB $50
_FellText::
	.DB $00
	.STRINGMAP pokemon, " fell!"
	.DB $58
_RanFromBattleText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "ran from battle!"
	.DB $58
_RanAwayScaredText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "ran away scared!"
	.DB $58
_WasBlownAwayText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "was blown away!"
	.DB $58
_ChargeMoveEffectText::
	.DB $00
	.STRINGMAP pokemon, "<USER>@"
	.DB $50
_MadeWhirlwindText::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "made a whirlwind!"
	.DB $58
_TookInSunlightText::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "took in sunlight!"
	.DB $58
_LoweredItsHeadText::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "lowered its head!"
	.DB $58
_SkyAttackGlowingText::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "is glowing!"
	.DB $58
_FlewUpHighText::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "flew up high!"
	.DB $58
_DugAHoleText::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "dug a hole!"
	.DB $58
_BecameConfusedText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "became confused!"
	.DB $58
_MimicLearnedMoveText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "learned"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_MoveWasDisabledText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>'s"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $55
	.STRINGMAP pokemon, "disabled!"
	.DB $58
_NothingHappenedText::
	.DB $00
	.STRINGMAP pokemon, "Nothing happened!"
	.DB $58
_NoEffectText::
	.DB $00
	.STRINGMAP pokemon, "No effect!"
	.DB $58
_ButItFailedText::
	.DB $00
	.STRINGMAP pokemon, "But, it failed! "
	.DB $58
_DidntAffectText::
	.DB $00
	.STRINGMAP pokemon, "It didn't affect"
	.DB $4f
	.STRINGMAP pokemon, "<TARGET>!"
	.DB $58
_IsUnaffectedText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "is unaffected!"
	.DB $58
_ParalyzedMayNotAttackText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>'s"
	.DB $4f
	.STRINGMAP pokemon, "paralyzed! It may"
	.DB $55
	.STRINGMAP pokemon, "not attack!"
	.DB $58
_SubstituteText::
	.DB $00
	.STRINGMAP pokemon, "It created a"
	.DB $4f
	.STRINGMAP pokemon, "SUBSTITUTE!"
	.DB $58
_HasSubstituteText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "has a SUBSTITUTE!"
	.DB $58
_TooWeakSubstituteText::
	.DB $00
	.STRINGMAP pokemon, "Too weak to make"
	.DB $4f
	.STRINGMAP pokemon, "a SUBSTITUTE!"
	.DB $58
_CoinsScatteredText::
	.DB $00
	.STRINGMAP pokemon, "Coins scattered"
	.DB $4f
	.STRINGMAP pokemon, "everywhere!"
	.DB $58
_GettingPumpedText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "getting pumped!"
	.DB $58
_WasSeededText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "was seeded!"
	.DB $58
_EvadedAttackText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>"
	.DB $4f
	.STRINGMAP pokemon, "evaded attack!"
	.DB $58
_HitWithRecoilText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "hit with recoil!"
	.DB $58
_ConvertedTypeText::
	.DB $00
	.STRINGMAP pokemon, "Converted type to"
	.DB $4f
	.STRINGMAP pokemon, "<TARGET>'s!"
	.DB $58
_StatusChangesEliminatedText::
	.DB $00
	.STRINGMAP pokemon, "All STATUS changes"
	.DB $4f
	.STRINGMAP pokemon, "are eliminated!"
	.DB $58
_StartedSleepingEffect::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "started sleeping!"
	.DB $57
_FellAsleepBecameHealthyText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "fell asleep and"
	.DB $55
	.STRINGMAP pokemon, "became healthy!"
	.DB $57
_RegainedHealthText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "regained health!"
	.DB $58
_TransformedText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "transformed into"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_LightScreenProtectedText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "protected against"
	.DB $55
	.STRINGMAP pokemon, "special attacks!"
	.DB $58
_ReflectGainedArmorText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "gained armor!"
	.DB $58
_ShroudedInMistText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "shrouded in mist!"
	.DB $58
_SuckedHealthText::
	.DB $00
	.STRINGMAP pokemon, "Sucked health from"
	.DB $4f
	.STRINGMAP pokemon, "<TARGET>!"
	.DB $58
_DreamWasEatenText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>'s"
	.DB $4f
	.STRINGMAP pokemon, "dream was eaten!"
	.DB $58
_TradeCenterOpponentText::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_ColosseumOpponentText::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57

; text/RedsHouse1F.asm
_RedsHouse1FMomWakeUpText::
	.DB $00
	.STRINGMAP pokemon, "MOM: Right."
	.DB $4f
	.STRINGMAP pokemon, "All boys leave"
	.DB $55
	.STRINGMAP pokemon, "home some day."
	.DB $55
	.STRINGMAP pokemon, "It said so on TV."
	.DB $51
	.STRINGMAP pokemon, "PROF.OAK, next"
	.DB $4f
	.STRINGMAP pokemon, "door, is looking"
	.DB $55
	.STRINGMAP pokemon, "for you."
	.DB $57
_RedsHouse1FMomYouShouldRestText::
	.DB $00
	.STRINGMAP pokemon, "MOM: <PLAYER>!"
	.DB $4f
	.STRINGMAP pokemon, "You should take a"
	.DB $55
	.STRINGMAP pokemon, "quick rest."
	.DB $58
_RedsHouse1FMomLookingGreatText::
	.DB $00
	.STRINGMAP pokemon, "MOM: Oh good!"
	.DB $4f
	.STRINGMAP pokemon, "You and your"
	.DB $55
	.STRINGMAP pokemon, "#MON are"
	.DB $55
	.STRINGMAP pokemon, "looking great!"
	.DB $55
	.STRINGMAP pokemon, "Take care now!"
	.DB $57
_RedsHouse1FTVStandByMeMovieText::
	.DB $00
	.STRINGMAP pokemon, "There's a movie"
	.DB $4f
	.STRINGMAP pokemon, "on TV. Four boys"
	.DB $55
	.STRINGMAP pokemon, "are walking on"
	.DB $55
	.STRINGMAP pokemon, "railroad tracks."
	.DB $51
	.STRINGMAP pokemon, "I better go too."
	.DB $57
_RedsHouse1FTVWrongSideText::
	.DB $00
	.STRINGMAP pokemon, "Oops, wrong side."
	.DB $57

; text/BluesHouse.asm
_BluesHouseDaisyRivalAtLabText::
	.DB $00
	.STRINGMAP pokemon, "Hi <PLAYER>!"
	.DB $4f
	.STRINGMAP pokemon, "<RIVAL> is out at"
	.DB $55
	.STRINGMAP pokemon, "Grandpa's lab."
	.DB $57
_BluesHouseDaisyOfferMapText::
	.DB $00
	.STRINGMAP pokemon, "Grandpa asked you"
	.DB $4f
	.STRINGMAP pokemon, "to run an errand?"
	.DB $55
	.STRINGMAP pokemon, "Here, this will"
	.DB $55
	.STRINGMAP pokemon, "help you!"
	.DB $58
_GotMapText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got a"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_BluesHouseDaisyBagFullText::
	.DB $00
	.STRINGMAP pokemon, "You have too much"
	.DB $4f
	.STRINGMAP pokemon, "stuff with you."
	.DB $57
_BluesHouseDaisyUseMapText::
	.DB $00
	.STRINGMAP pokemon, "Use the TOWN MAP"
	.DB $4f
	.STRINGMAP pokemon, "to find out where"
	.DB $55
	.STRINGMAP pokemon, "you are."
	.DB $57
_BluesHouseDaisyWalkingText::
	.DB $00
	.STRINGMAP pokemon, "#MON are living"
	.DB $4f
	.STRINGMAP pokemon, "things! If they"
	.DB $55
	.STRINGMAP pokemon, "get tired, give"
	.DB $55
	.STRINGMAP pokemon, "them a rest!"
	.DB $57
_BluesHouseTownMapText::
	.DB $00
	.STRINGMAP pokemon, "It's a big map!"
	.DB $4f
	.STRINGMAP pokemon, "This is useful!"
	.DB $57

; text/OaksLab.asm
_OaksLabRivalGrampsIsntAroundText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Yo"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>! Gramps"
	.DB $55
	.STRINGMAP pokemon, "isn't around!"
	.DB $57
_OaksLabRivalGoAheadAndChooseText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Heh, I"
	.DB $4f
	.STRINGMAP pokemon, "don't need to be"
	.DB $55
	.STRINGMAP pokemon, "greedy like you!"
	.DB $51
	.STRINGMAP pokemon, "Go ahead and"
	.DB $4f
	.STRINGMAP pokemon, "choose, <PLAYER>!"
	.DB $57
_OaksLabRivalMyPokemonLooksStrongerText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: My"
	.DB $4f
	.STRINGMAP pokemon, "#MON looks a"
	.DB $55
	.STRINGMAP pokemon, "lot stronger."
	.DB $57
_OaksLabThoseArePokeBallsText::
	.DB $00
	.STRINGMAP pokemon, "Those are #"
	.DB $4f
	.STRINGMAP pokemon, "BALLs. They"
	.DB $55
	.STRINGMAP pokemon, "contain #MON!"
	.DB $57
_OaksLabYouWantCharmanderText::
	.DB $00
	.STRINGMAP pokemon, "So! You want the"
	.DB $4f
	.STRINGMAP pokemon, "fire #MON,"
	.DB $55
	.STRINGMAP pokemon, "CHARMANDER?"
	.DB $57
_OaksLabYouWantSquirtleText::
	.DB $00
	.STRINGMAP pokemon, "So! You want the"
	.DB $4f
	.STRINGMAP pokemon, "water #MON,"
	.DB $55
	.STRINGMAP pokemon, "SQUIRTLE?"
	.DB $57
_OaksLabYouWantBulbasaurText::
	.DB $00
	.STRINGMAP pokemon, "So! You want the"
	.DB $4f
	.STRINGMAP pokemon, "plant #MON,"
	.DB $55
	.STRINGMAP pokemon, "BULBASAUR?"
	.DB $57
_OaksLabMonEnergeticText::
	.DB $00
	.STRINGMAP pokemon, "This #MON is"
	.DB $4f
	.STRINGMAP pokemon, "really energetic!"
	.DB $58
_OaksLabReceivedMonText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "a @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_OaksLabLastMonText::
	.DB $00
	.STRINGMAP pokemon, "That's PROF.OAK's"
	.DB $4f
	.STRINGMAP pokemon, "last #MON!"
	.DB $57
_OaksLabOak1WhichPokemonDoYouWantText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Now, <PLAYER>,"
	.DB $4f
	.STRINGMAP pokemon, "which #MON do"
	.DB $55
	.STRINGMAP pokemon, "you want?"
	.DB $57
_OaksLabOak1YourPokemonCanFightText::
	.DB $00
	.STRINGMAP pokemon, "OAK: If a wild"
	.DB $4f
	.STRINGMAP pokemon, "#MON appears,"
	.DB $55
	.STRINGMAP pokemon, "your #MON can"
	.DB $55
	.STRINGMAP pokemon, "fight against it!"
	.DB $57
_OaksLabOak1RaiseYourYoungPokemonText::
	.DB $00
	.STRINGMAP pokemon, "OAK: <PLAYER>,"
	.DB $4f
	.STRINGMAP pokemon, "raise your young"
	.DB $55
	.STRINGMAP pokemon, "#MON by making"
	.DB $55
	.STRINGMAP pokemon, "it fight!"
	.DB $57
_OaksLabOak1DeliverParcelText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Oh, <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "How is my old"
	.DB $4f
	.STRINGMAP pokemon, "#MON?"
	.DB $51
	.STRINGMAP pokemon, "Well, it seems to"
	.DB $4f
	.STRINGMAP pokemon, "like you a lot."
	.DB $51
	.STRINGMAP pokemon, "You must be"
	.DB $4f
	.STRINGMAP pokemon, "talented as a"
	.DB $55
	.STRINGMAP pokemon, "#MON trainer!"
	.DB $51
	.STRINGMAP pokemon, "What? You have"
	.DB $4f
	.STRINGMAP pokemon, "something for me?"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> delivered"
	.DB $4f
	.STRINGMAP pokemon, "OAK's PARCEL.@"
	.DB $50
_OaksLabOak1ParcelThanksText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "Ah! This is the"
	.DB $4f
	.STRINGMAP pokemon, "custom # BALL"
	.DB $55
	.STRINGMAP pokemon, "I ordered!"
	.DB $55
	.STRINGMAP pokemon, "Thank you!"
	.DB $57
_OaksLabOak1PokemonAroundTheWorldText::
	.DB $00
	.STRINGMAP pokemon, "#MON around the"
	.DB $4f
	.STRINGMAP pokemon, "world wait for"
	.DB $55
	.STRINGMAP pokemon, "you, <PLAYER>!"
	.DB $57
_OaksLabOak1ReceivedPokeballsText::
	.DB $00
	.STRINGMAP pokemon, "OAK: You can't get"
	.DB $4f
	.STRINGMAP pokemon, "detailed data on"
	.DB $55
	.STRINGMAP pokemon, "#MON by just"
	.DB $55
	.STRINGMAP pokemon, "seeing them."
	.DB $51
	.STRINGMAP pokemon, "You must catch"
	.DB $4f
	.STRINGMAP pokemon, "them! Use these"
	.DB $55
	.STRINGMAP pokemon, "to capture wild"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> got 5"
	.DB $4f
	.STRINGMAP pokemon, "# BALLs!@"
	.DB $50
_OaksLabGivePokeballsExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "When a wild"
	.DB $4f
	.STRINGMAP pokemon, "#MON appears,"
	.DB $55
	.STRINGMAP pokemon, "it's fair game."
	.DB $51
	.STRINGMAP pokemon, "Just throw a #"
	.DB $4f
	.STRINGMAP pokemon, "BALL at it and try"
	.DB $4f
	.STRINGMAP pokemon, "to catch it!"
	.DB $51
	.STRINGMAP pokemon, "This won't always"
	.DB $4f
	.STRINGMAP pokemon, "work, though."
	.DB $51
	.STRINGMAP pokemon, "A healthy #MON"
	.DB $4f
	.STRINGMAP pokemon, "could escape. You"
	.DB $55
	.STRINGMAP pokemon, "have to be lucky!"
	.DB $57
_OaksLabOak1ComeSeeMeSometimesText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Come see me"
	.DB $4f
	.STRINGMAP pokemon, "sometimes."
	.DB $51
	.STRINGMAP pokemon, "I want to know how"
	.DB $4f
	.STRINGMAP pokemon, "your #DEX is"
	.DB $55
	.STRINGMAP pokemon, "coming along."
	.DB $57
_OaksLabOak1HowIsYourPokedexComingText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Good to see "
	.DB $4f
	.STRINGMAP pokemon, "you! How is your "
	.DB $55
	.STRINGMAP pokemon, "#DEX coming? "
	.DB $55
	.STRINGMAP pokemon, "Here, let me take"
	.DB $55
	.STRINGMAP pokemon, "a look!"
	.DB $58
_OaksLabPokedexText::
	.DB $00
	.STRINGMAP pokemon, "It's encyclopedia-"
	.DB $4f
	.STRINGMAP pokemon, "like, but the"
	.DB $55
	.STRINGMAP pokemon, "pages are blank!"
	.DB $57
_OaksLabOak2Text::
	.DB $00
	.STRINGMAP pokemon, "?"
	.DB $57
_OaksLabGirlText::
	.DB $00
	.STRINGMAP pokemon, "PROF.OAK is the"
	.DB $4f
	.STRINGMAP pokemon, "authority on"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $51
	.STRINGMAP pokemon, "Many #MON"
	.DB $4f
	.STRINGMAP pokemon, "trainers hold him"
	.DB $55
	.STRINGMAP pokemon, "in high regard!"
	.DB $57
_OaksLabRivalFedUpWithWaitingText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Gramps!"
	.DB $4f
	.STRINGMAP pokemon, "I'm fed up with"
	.DB $55
	.STRINGMAP pokemon, "waiting!"
	.DB $57
_OaksLabOakChooseMonText::
	.DB $00
	.STRINGMAP pokemon, "OAK: <RIVAL>?"
	.DB $4f
	.STRINGMAP pokemon, "Let me think..."
	.DB $51
	.STRINGMAP pokemon, "Oh, that's right,"
	.DB $4f
	.STRINGMAP pokemon, "I told you to"
	.DB $55
	.STRINGMAP pokemon, "come! Just wait!"
	.DB $51
	.STRINGMAP pokemon, "Here, <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "There are 3"
	.DB $4f
	.STRINGMAP pokemon, "#MON here!"
	.DB $51
	.STRINGMAP pokemon, "Haha!"
	.DB $51
	.STRINGMAP pokemon, "They are inside"
	.DB $4f
	.STRINGMAP pokemon, "the # BALLs."
	.DB $51
	.STRINGMAP pokemon, "When I was young,"
	.DB $4f
	.STRINGMAP pokemon, "I was a serious"
	.DB $55
	.STRINGMAP pokemon, "#MON trainer!"
	.DB $51
	.STRINGMAP pokemon, "In my old age, I"
	.DB $4f
	.STRINGMAP pokemon, "have only 3 left,"
	.DB $55
	.STRINGMAP pokemon, "but you can have"
	.DB $55
	.STRINGMAP pokemon, "one! Choose!"
	.DB $57
_OaksLabRivalWhatAboutMeText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Hey!"
	.DB $4f
	.STRINGMAP pokemon, "Gramps! What"
	.DB $55
	.STRINGMAP pokemon, "about me?"
	.DB $57
_OaksLabOakBePatientText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Be patient!"
	.DB $4f
	.STRINGMAP pokemon, "<RIVAL>, you can"
	.DB $55
	.STRINGMAP pokemon, "have one too!"
	.DB $57
_OaksLabOakDontGoAwayYetText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Hey! Don't go"
	.DB $4f
	.STRINGMAP pokemon, "away yet!"
	.DB $57
_OaksLabRivalIllTakeThisOneText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: I'll take"
	.DB $4f
	.STRINGMAP pokemon, "this one, then!"
	.DB $57
_OaksLabRivalReceivedMonText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL> received"
	.DB $4f
	.STRINGMAP pokemon, "a @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_OaksLabRivalIllTakeYouOnText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Wait"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $55
	.STRINGMAP pokemon, "Let's check out"
	.DB $55
	.STRINGMAP pokemon, "our #MON!"
	.DB $51
	.STRINGMAP pokemon, "Come on, I'll take"
	.DB $4f
	.STRINGMAP pokemon, "you on!"
	.DB $57
_OaksLabRivalIPickedTheWrongPokemonText::
	.DB $00
	.STRINGMAP pokemon, "WHAT?"
	.DB $4f
	.STRINGMAP pokemon, "Unbelievable!"
	.DB $55
	.STRINGMAP pokemon, "I picked the"
	.DB $55
	.STRINGMAP pokemon, "wrong #MON!"
	.DB $58
_OaksLabRivalAmIGreatOrWhatText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Yeah! Am"
	.DB $4f
	.STRINGMAP pokemon, "I great or what?"
	.DB $58
_OaksLabRivalSmellYouLaterText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Okay!"
	.DB $4f
	.STRINGMAP pokemon, "I'll make my"
	.DB $55
	.STRINGMAP pokemon, "#MON fight to"
	.DB $55
	.STRINGMAP pokemon, "toughen it up!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>! Gramps!"
	.DB $4f
	.STRINGMAP pokemon, "Smell you later!"
	.DB $57
_OaksLabRivalGrampsText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Gramps!"
	.DB $57
_OaksLabRivalWhatDidYouCallMeForText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: What did"
	.DB $4f
	.STRINGMAP pokemon, "you call me for?"
	.DB $57
_OaksLabOakIHaveARequestText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Oh right! I"
	.DB $4f
	.STRINGMAP pokemon, "have a request"
	.DB $55
	.STRINGMAP pokemon, "of you two."
	.DB $57
_OaksLabOakMyInventionPokedexText::
	.DB $00
	.STRINGMAP pokemon, "On the desk there"
	.DB $4f
	.STRINGMAP pokemon, "is my invention,"
	.DB $55
	.STRINGMAP pokemon, "#DEX!"
	.DB $51
	.STRINGMAP pokemon, "It automatically"
	.DB $4f
	.STRINGMAP pokemon, "records data on"
	.DB $55
	.STRINGMAP pokemon, "#MON you've"
	.DB $55
	.STRINGMAP pokemon, "seen or caught!"
	.DB $51
	.STRINGMAP pokemon, "It's a hi-tech"
	.DB $4f
	.STRINGMAP pokemon, "encyclopedia!"
	.DB $57
_OaksLabOakGotPokedexText::
	.DB $00
	.STRINGMAP pokemon, "OAK: <PLAYER> and"
	.DB $4f
	.STRINGMAP pokemon, "<RIVAL>! Take"
	.DB $55
	.STRINGMAP pokemon, "these with you!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> got"
	.DB $4f
	.STRINGMAP pokemon, "#DEX from OAK!@"
	.DB $50
_OaksLabOakThatWasMyDreamText::
	.DB $00
	.STRINGMAP pokemon, "To make a complete"
	.DB $4f
	.STRINGMAP pokemon, "guide on all the"
	.DB $55
	.STRINGMAP pokemon, "#MON in the"
	.DB $55
	.STRINGMAP pokemon, "world..."
	.DB $51
	.STRINGMAP pokemon, "That was my dream!"
	.DB $51
	.STRINGMAP pokemon, "But, I'm too old!"
	.DB $4f
	.STRINGMAP pokemon, "I can't do it!"
	.DB $51
	.STRINGMAP pokemon, "So, I want you two"
	.DB $4f
	.STRINGMAP pokemon, "to fulfill my"
	.DB $55
	.STRINGMAP pokemon, "dream for me!"
	.DB $51
	.STRINGMAP pokemon, "Get moving, you"
	.DB $4f
	.STRINGMAP pokemon, "two!"
	.DB $51
	.STRINGMAP pokemon, "This is a great"
	.DB $4f
	.STRINGMAP pokemon, "undertaking in"
	.DB $55
	.STRINGMAP pokemon, "#MON history!"
	.DB $57
_OaksLabRivalLeaveItAllToMeText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Alright"
	.DB $4f
	.STRINGMAP pokemon, "Gramps! Leave it"
	.DB $55
	.STRINGMAP pokemon, "all to me!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>, I hate to"
	.DB $4f
	.STRINGMAP pokemon, "say it, but I"
	.DB $55
	.STRINGMAP pokemon, "don't need you!"
	.DB $51
	.STRINGMAP pokemon, "I know! I'll"
	.DB $4f
	.STRINGMAP pokemon, "borrow a TOWN MAP"
	.DB $55
	.STRINGMAP pokemon, "from my sis!"
	.DB $51
	.STRINGMAP pokemon, "I'll tell her not"
	.DB $4f
	.STRINGMAP pokemon, "to lend you one,"
	.DB $55
	.STRINGMAP pokemon, "<PLAYER>! Hahaha!"
	.DB $57
_OaksLabScientistText::
	.DB $00
	.STRINGMAP pokemon, "I study #MON as"
	.DB $4f
	.STRINGMAP pokemon, "PROF.OAK's AIDE."
	.DB $57

; text/pokedex_ratings.asm
_DexCompletionText::
	.DB $00
	.STRINGMAP pokemon, "#DEX comp-"
	.DB $4f
	.STRINGMAP pokemon, "letion is:"
	.DB $51
	.STRINGMAP pokemon, "@"
	.DB $09
	.DW hDexRatingNumMonsSeen
	.DB $13
	.DB $00
	.STRINGMAP pokemon, " #MON seen"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $09
	.DW hDexRatingNumMonsOwned
	.DB $13
	.DB $00
	.STRINGMAP pokemon, " #MON owned"
	.DB $51
	.STRINGMAP pokemon, "PROF.OAK's"
	.DB $4f
	.STRINGMAP pokemon, "Rating:"
	.DB $58
_DexRatingText_Own0To9::
	.DB $00
	.STRINGMAP pokemon, "You still have"
	.DB $4f
	.STRINGMAP pokemon, "lots to do."
	.DB $55
	.STRINGMAP pokemon, "Look for #MON"
	.DB $55
	.STRINGMAP pokemon, "in grassy areas!"
	.DB $57
_DexRatingText_Own10To19::
	.DB $00
	.STRINGMAP pokemon, "You're on the"
	.DB $4f
	.STRINGMAP pokemon, "right track! "
	.DB $55
	.STRINGMAP pokemon, "Get a FLASH HM"
	.DB $55
	.STRINGMAP pokemon, "from my AIDE!"
	.DB $57
_DexRatingText_Own20To29::
	.DB $00
	.STRINGMAP pokemon, "You still need"
	.DB $4f
	.STRINGMAP pokemon, "more #MON!"
	.DB $55
	.STRINGMAP pokemon, "Try to catch"
	.DB $55
	.STRINGMAP pokemon, "other species!"
	.DB $57
_DexRatingText_Own30To39::
	.DB $00
	.STRINGMAP pokemon, "Good, you're"
	.DB $4f
	.STRINGMAP pokemon, "trying hard!"
	.DB $55
	.STRINGMAP pokemon, "Get an ITEMFINDER"
	.DB $55
	.STRINGMAP pokemon, "from my AIDE!"
	.DB $57
_DexRatingText_Own40To49::
	.DB $00
	.STRINGMAP pokemon, "Looking good!"
	.DB $4f
	.STRINGMAP pokemon, "Go find my AIDE"
	.DB $55
	.STRINGMAP pokemon, "when you get 50!"
	.DB $57
_DexRatingText_Own50To59::
	.DB $00
	.STRINGMAP pokemon, "You finally got at"
	.DB $4f
	.STRINGMAP pokemon, "least 50 species!"
	.DB $55
	.STRINGMAP pokemon, "Be sure to get"
	.DB $55
	.STRINGMAP pokemon, "EXP.ALL from my"
	.DB $55
	.STRINGMAP pokemon, "AIDE!"
	.DB $57
_DexRatingText_Own60To69::
	.DB $00
	.STRINGMAP pokemon, "Ho! This is geting"
	.DB $4f
	.STRINGMAP pokemon, "even better!"
	.DB $57
_DexRatingText_Own70To79::
	.DB $00
	.STRINGMAP pokemon, "Very good!"
	.DB $4f
	.STRINGMAP pokemon, "Go fish for some"
	.DB $55
	.STRINGMAP pokemon, "marine #MON!"
	.DB $57
_DexRatingText_Own80To89::
	.DB $00
	.STRINGMAP pokemon, "Wonderful!"
	.DB $4f
	.STRINGMAP pokemon, "Do you like to"
	.DB $55
	.STRINGMAP pokemon, "collect things?"
	.DB $57
_DexRatingText_Own90To99::
	.DB $00
	.STRINGMAP pokemon, "I'm impressed!"
	.DB $4f
	.STRINGMAP pokemon, "It must have been"
	.DB $55
	.STRINGMAP pokemon, "difficult to do!"
	.DB $57
_DexRatingText_Own100To109::
	.DB $00
	.STRINGMAP pokemon, "You finally got at"
	.DB $4f
	.STRINGMAP pokemon, "least 100 species!"
	.DB $55
	.STRINGMAP pokemon, "I can't believe"
	.DB $55
	.STRINGMAP pokemon, "how good you are!"
	.DB $57
_DexRatingText_Own110To119::
	.DB $00
	.STRINGMAP pokemon, "You even have the"
	.DB $4f
	.STRINGMAP pokemon, "evolved forms of"
	.DB $55
	.STRINGMAP pokemon, "#MON! Super!"
	.DB $57
_DexRatingText_Own120To129::
	.DB $00
	.STRINGMAP pokemon, "Excellent! Trade"
	.DB $4f
	.STRINGMAP pokemon, "with friends to"
	.DB $55
	.STRINGMAP pokemon, "get some more!"
	.DB $57
_DexRatingText_Own130To139::
	.DB $00
	.STRINGMAP pokemon, "Outstanding!"
	.DB $4f
	.STRINGMAP pokemon, "You've become a"
	.DB $55
	.STRINGMAP pokemon, "real pro at this!"
	.DB $57
_DexRatingText_Own140To149::
	.DB $00
	.STRINGMAP pokemon, "I have nothing"
	.DB $4f
	.STRINGMAP pokemon, "left to say!"
	.DB $55
	.STRINGMAP pokemon, "You're the"
	.DB $55
	.STRINGMAP pokemon, "authority now!"
	.DB $57
_DexRatingText_Own150To151::
	.DB $00
	.STRINGMAP pokemon, "Your #DEX is"
	.DB $4f
	.STRINGMAP pokemon, "entirely complete!"
	.DB $55
	.STRINGMAP pokemon, "Congratulations!"
	.DB $57

; text/ViridianPokecenter.asm
_ViridianPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "You can use that"
	.DB $4f
	.STRINGMAP pokemon, "PC in the corner."
	.DB $51
	.STRINGMAP pokemon, "The receptionist"
	.DB $4f
	.STRINGMAP pokemon, "told me. So kind!"
	.DB $57
_ViridianPokecenterCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "There's a #MON"
	.DB $4f
	.STRINGMAP pokemon, "CENTER in every"
	.DB $55
	.STRINGMAP pokemon, "town ahead."
	.DB $51
	.STRINGMAP pokemon, "They don't charge"
	.DB $4f
	.STRINGMAP pokemon, "any money either!"
	.DB $57

; text/ViridianMart.asm
_ViridianMartClerkSayHiToOakText::
	.DB $00
	.STRINGMAP pokemon, "Okay! Say hi to"
	.DB $4f
	.STRINGMAP pokemon, "PROF.OAK for me!"
	.DB $57
_ViridianMartClerkYouCameFromPalletTownText::
	.DB $00
	.STRINGMAP pokemon, "Hey! You came from"
	.DB $4f
	.STRINGMAP pokemon, "PALLET TOWN?"
	.DB $57
_ViridianMartClerkParcelQuestText::
	.DB $00
	.STRINGMAP pokemon, "You know PROF."
	.DB $4f
	.STRINGMAP pokemon, "OAK, right?"
	.DB $51
	.STRINGMAP pokemon, "His order came in."
	.DB $4f
	.STRINGMAP pokemon, "Will you take it"
	.DB $55
	.STRINGMAP pokemon, "to him?"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> got"
	.DB $4f
	.STRINGMAP pokemon, "OAK's PARCEL!@"
	.DB $50
_ViridianMartYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "This shop sells"
	.DB $4f
	.STRINGMAP pokemon, "many ANTIDOTEs."
	.DB $57
_ViridianMartCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "No! POTIONs are"
	.DB $4f
	.STRINGMAP pokemon, "all sold out."
	.DB $57

; text/ViridianSchoolHouse.asm
_ViridianSchoolHouseBrunetteGirlText::
	.DB $00
	.STRINGMAP pokemon, "Whew! I'm trying"
	.DB $4f
	.STRINGMAP pokemon, "to memorize all"
	.DB $55
	.STRINGMAP pokemon, "my notes."
	.DB $57
_ViridianSchoolHouseCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "Okay!"
	.DB $51
	.STRINGMAP pokemon, "Be sure to read"
	.DB $4f
	.STRINGMAP pokemon, "the blackboard"
	.DB $55
	.STRINGMAP pokemon, "carefully!"
	.DB $57

; text/ViridianNicknameHouse.asm
_ViridianNicknameHouseBaldingGuyText::
	.DB $00
	.STRINGMAP pokemon, "Coming up with"
	.DB $4f
	.STRINGMAP pokemon, "nicknames is fun,"
	.DB $55
	.STRINGMAP pokemon, "but hard."
	.DB $51
	.STRINGMAP pokemon, "Simple names are"
	.DB $4f
	.STRINGMAP pokemon, "the easiest to"
	.DB $55
	.STRINGMAP pokemon, "remember."
	.DB $57
_ViridianNicknameHouseLittleGirlText::
	.DB $00
	.STRINGMAP pokemon, "My Daddy loves"
	.DB $4f
	.STRINGMAP pokemon, "#MON too."
	.DB $57
_ViridianNicknameHouseSpearowText::
	.DB $00
	.STRINGMAP pokemon, "SPEARY: Tetweet!"
	.DB $57
_ViridianNicknameHouseSpearySignText::
	.DB $00
	.STRINGMAP pokemon, "SPEAROW"
	.DB $4f
	.STRINGMAP pokemon, "Name: SPEARY"
	.DB $57

; text/ViridianGym.asm
_ViridianGymGiovanniPreBattleText::
	.DB $00
	.STRINGMAP pokemon, "Fwahahaha! This is"
	.DB $4f
	.STRINGMAP pokemon, "my hideout!"
	.DB $51
	.STRINGMAP pokemon, "I planned to"
	.DB $4f
	.STRINGMAP pokemon, "resurrect TEAM"
	.DB $55
	.STRINGMAP pokemon, "ROCKET here!"
	.DB $51
	.STRINGMAP pokemon, "But, you have"
	.DB $4f
	.STRINGMAP pokemon, "caught me again!"
	.DB $55
	.STRINGMAP pokemon, "So be it! This"
	.DB $55
	.STRINGMAP pokemon, "time, I'm not"
	.DB $55
	.STRINGMAP pokemon, "holding back!"
	.DB $51
	.STRINGMAP pokemon, "Once more, you"
	.DB $4f
	.STRINGMAP pokemon, "shall face"
	.DB $55
	.STRINGMAP pokemon, "GIOVANNI, the"
	.DB $55
	.STRINGMAP pokemon, "greatest trainer!"
	.DB $57
_ViridianGymGiovanniReceivedEarthBadgeText::
	.DB $00
	.STRINGMAP pokemon, "Ha!"
	.DB $4f
	.STRINGMAP pokemon, "That was a truly"
	.DB $55
	.STRINGMAP pokemon, "intense fight!"
	.DB $55
	.STRINGMAP pokemon, "You have won!"
	.DB $55
	.STRINGMAP pokemon, "As proof, here is"
	.DB $55
	.STRINGMAP pokemon, "the EARTHBADGE!@"
	.DB $50
_ViridianGymGiovanniPostBattleAdviceText::
	.DB $00
	.STRINGMAP pokemon, "Having lost, I"
	.DB $4f
	.STRINGMAP pokemon, "cannot face my"
	.DB $55
	.STRINGMAP pokemon, "underlings!"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET is"
	.DB $55
	.STRINGMAP pokemon, "finished forever!"
	.DB $51
	.STRINGMAP pokemon, "I will dedicate my"
	.DB $4f
	.STRINGMAP pokemon, "life to the study"
	.DB $55
	.STRINGMAP pokemon, "of #MON!"
	.DB $51
	.STRINGMAP pokemon, "Let us meet again"
	.DB $4f
	.STRINGMAP pokemon, "some day!"
	.DB $55
	.STRINGMAP pokemon, "Farewell!@"
	.DB $50
_ViridianGymGiovanniEarthBadgeInfoText::
	.DB $00
	.STRINGMAP pokemon, "The EARTHBADGE"
	.DB $4f
	.STRINGMAP pokemon, "makes #MON of"
	.DB $55
	.STRINGMAP pokemon, "any level obey!"
	.DB $51
	.STRINGMAP pokemon, "It is evidence of"
	.DB $4f
	.STRINGMAP pokemon, "your mastery as a"
	.DB $55
	.STRINGMAP pokemon, "#MON trainer!"
	.DB $51
	.STRINGMAP pokemon, "With it, you can"
	.DB $4f
	.STRINGMAP pokemon, "enter the #MON"
	.DB $55
	.STRINGMAP pokemon, "LEAGUE!"
	.DB $51
	.STRINGMAP pokemon, "It is my gift for"
	.DB $4f
	.STRINGMAP pokemon, "your #MON"
	.DB $55
	.STRINGMAP pokemon, "LEAGUE challenge!"
	.DB $57
_ViridianGymGiovanniReceivedTM27Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "TM27!@"
	.DB $50
_ViridianGymGiovanniTM27ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "TM27 is FISSURE!"
	.DB $4f
	.STRINGMAP pokemon, "It will take out"
	.DB $55
	.STRINGMAP pokemon, "#MON with just"
	.DB $55
	.STRINGMAP pokemon, "one hit!"
	.DB $51
	.STRINGMAP pokemon, "I made it when I"
	.DB $4f
	.STRINGMAP pokemon, "ran the GYM here,"
	.DB $55
	.STRINGMAP pokemon, "too long ago..."
	.DB $57
_ViridianGymGiovanniTM27NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You do not have"
	.DB $4f
	.STRINGMAP pokemon, "space for this!"
	.DB $57
_ViridianGymCooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Heh! You must be"
	.DB $4f
	.STRINGMAP pokemon, "running out of"
	.DB $55
	.STRINGMAP pokemon, "steam by now!"
	.DB $57
_ViridianGymCooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "ran out of gas!"
	.DB $58
_ViridianGymCooltrainerM1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You need power to"
	.DB $4f
	.STRINGMAP pokemon, "keep up with our"
	.DB $55
	.STRINGMAP pokemon, "GYM LEADER!"
	.DB $57
_ViridianGymHiker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Rrrroar! I'm"
	.DB $4f
	.STRINGMAP pokemon, "working myself"
	.DB $55
	.STRINGMAP pokemon, "into a rage!"
	.DB $57
_ViridianGymHiker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wargh!"
	.DB $58
_ViridianGymHiker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm still not"
	.DB $4f
	.STRINGMAP pokemon, "worthy!"
	.DB $57
_ViridianGymRocker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON and I, we"
	.DB $4f
	.STRINGMAP pokemon, "make wonderful"
	.DB $55
	.STRINGMAP pokemon, "music together!"
	.DB $57
_ViridianGymRocker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You are in"
	.DB $4f
	.STRINGMAP pokemon, "perfect harmony!"
	.DB $58
_ViridianGymRocker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Do you know the"
	.DB $4f
	.STRINGMAP pokemon, "identity of our"
	.DB $55
	.STRINGMAP pokemon, "GYM LEADER?"
	.DB $57
_ViridianGymHiker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Karate is the"
	.DB $4f
	.STRINGMAP pokemon, "ultimate form of"
	.DB $55
	.STRINGMAP pokemon, "martial arts!"
	.DB $57
_ViridianGymHiker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Atcho!"
	.DB $58
_ViridianGymHiker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If my #MON"
	.DB $4f
	.STRINGMAP pokemon, "were as good at"
	.DB $55
	.STRINGMAP pokemon, "Karate as I..."
	.DB $57
_ViridianGymCooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "The truly talented"
	.DB $4f
	.STRINGMAP pokemon, "win with style!"
	.DB $57
_ViridianGymCooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "lost my grip!"
	.DB $58
_ViridianGymCooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The LEADER will"
	.DB $4f
	.STRINGMAP pokemon, "scold me!"
	.DB $57
_ViridianGymHiker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm the KARATE"
	.DB $4f
	.STRINGMAP pokemon, "KING! Your fate"
	.DB $55
	.STRINGMAP pokemon, "rests with me!"
	.DB $57
_ViridianGymHiker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ayah!"
	.DB $58
_ViridianGymHiker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON LEAGUE?"
	.DB $4f
	.STRINGMAP pokemon, "You? Don't get"
	.DB $55
	.STRINGMAP pokemon, "cocky!"
	.DB $57
_ViridianGymRocker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Your #MON will"
	.DB $4f
	.STRINGMAP pokemon, "cower at the"
	.DB $55
	.STRINGMAP pokemon, "crack of my whip!"
	.DB $57
_ViridianGymRocker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Yowch!"
	.DB $4f
	.STRINGMAP pokemon, "Whiplash!"
	.DB $58
_ViridianGymRocker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wait! I was just"
	.DB $4f
	.STRINGMAP pokemon, "careless!"
	.DB $57
_ViridianGymCooltrainerM3BattleText::
	.DB $00
	.STRINGMAP pokemon, "VIRIDIAN GYM was"
	.DB $4f
	.STRINGMAP pokemon, "closed for a long"
	.DB $55
	.STRINGMAP pokemon, "time, but now our"
	.DB $55
	.STRINGMAP pokemon, "LEADER is back!"
	.DB $57
_ViridianGymCooltrainerM3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "was beaten?"
	.DB $58
_ViridianGymCooltrainerM3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You can go onto"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE"
	.DB $55
	.STRINGMAP pokemon, "only by defeating"
	.DB $55
	.STRINGMAP pokemon, "our GYM LEADER!"
	.DB $57
_ViridianGymGuidePreBattleText::
	.DB $00
	.STRINGMAP pokemon, "Yo! Champ in"
	.DB $4f
	.STRINGMAP pokemon, "making!"
	.DB $51
	.STRINGMAP pokemon, "Even I don't know"
	.DB $4f
	.STRINGMAP pokemon, "VIRIDIAN LEADER's"
	.DB $55
	.STRINGMAP pokemon, "identity!"
	.DB $51
	.STRINGMAP pokemon, "This will be the"
	.DB $4f
	.STRINGMAP pokemon, "toughest of all"
	.DB $55
	.STRINGMAP pokemon, "the GYM LEADERs!"
	.DB $51
	.STRINGMAP pokemon, "I heard that the"
	.DB $4f
	.STRINGMAP pokemon, "trainers here"
	.DB $55
	.STRINGMAP pokemon, "like ground-type"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_ViridianGymGuidePostBattleText::
	.DB $00
	.STRINGMAP pokemon, "Blow me away!"
	.DB $4f
	.STRINGMAP pokemon, "GIOVANNI was the"
	.DB $55
	.STRINGMAP pokemon, "GYM LEADER here?"
	.DB $57

; text/Museum1F.asm
_Museum1FScientist1ComeAgainText::
	.DB $00
	.STRINGMAP pokemon, "Come again!"
	.DB $57
_Museum1FScientist1WouldYouLikeToComeInText::
	.DB $00
	.STRINGMAP pokemon, "It's ¥50 for a"
	.DB $4f
	.STRINGMAP pokemon, "child's ticket."
	.DB $51
	.STRINGMAP pokemon, "Would you like to"
	.DB $4f
	.STRINGMAP pokemon, "come in?"
	.DB $57
_Museum1FScientist1ThankYouText::
	.DB $00
	.STRINGMAP pokemon, "Right, ¥50!"
	.DB $4f
	.STRINGMAP pokemon, "Thank you!"
	.DB $57
_Museum1FScientist1DontHaveEnoughMoneyText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "enough money."
	.DB $58
_Museum1FScientist1DoYouKnowWhatAmberIsText::
	.DB $00
	.STRINGMAP pokemon, "You can't sneak"
	.DB $4f
	.STRINGMAP pokemon, "in the back way!"
	.DB $51
	.STRINGMAP pokemon, "Oh, whatever!"
	.DB $4f
	.STRINGMAP pokemon, "Do you know what"
	.DB $55
	.STRINGMAP pokemon, "AMBER is?"
	.DB $57
_Museum1FScientist1TheresALabSomewhereText::
	.DB $00
	.STRINGMAP pokemon, "There's a lab"
	.DB $4f
	.STRINGMAP pokemon, "somewhere trying"
	.DB $55
	.STRINGMAP pokemon, "to resurrect"
	.DB $55
	.STRINGMAP pokemon, "ancient #MON"
	.DB $55
	.STRINGMAP pokemon, "from AMBER."
	.DB $57
_Museum1FScientist1AmberIsFossilizedTreeSapText::
	.DB $00
	.STRINGMAP pokemon, "AMBER is fossil-"
	.DB $4f
	.STRINGMAP pokemon, "ized tree sap."
	.DB $57
_Museum1FScientist1GoToOtherSideText::
	.DB $00
	.STRINGMAP pokemon, "Please go to the"
	.DB $4f
	.STRINGMAP pokemon, "other side!"
	.DB $57
_Museum1FScientist1TakePlentyOfTimeText::
	.DB $00
	.STRINGMAP pokemon, "Take plenty of"
	.DB $4f
	.STRINGMAP pokemon, "time to look!"
	.DB $57
_Museum1FGamblerText::
	.DB $00
	.STRINGMAP pokemon, "That is one"
	.DB $4f
	.STRINGMAP pokemon, "magnificent"
	.DB $55
	.STRINGMAP pokemon, "fossil!"
	.DB $57
_Museum1FScientist2TakeThisToAPokemonLabText::
	.DB $00
	.STRINGMAP pokemon, "Ssh! I think that"
	.DB $4f
	.STRINGMAP pokemon, "this chunk of"
	.DB $55
	.STRINGMAP pokemon, "AMBER contains"
	.DB $55
	.STRINGMAP pokemon, "#MON DNA!"
	.DB $51
	.STRINGMAP pokemon, "It would be great"
	.DB $4f
	.STRINGMAP pokemon, "if #MON could"
	.DB $55
	.STRINGMAP pokemon, "be resurrected"
	.DB $55
	.STRINGMAP pokemon, "from it!"
	.DB $51
	.STRINGMAP pokemon, "But, my colleagues"
	.DB $4f
	.STRINGMAP pokemon, "just ignore me!"
	.DB $51
	.STRINGMAP pokemon, "So I have a favor"
	.DB $4f
	.STRINGMAP pokemon, "to ask!"
	.DB $51
	.STRINGMAP pokemon, "Take this to a"
	.DB $4f
	.STRINGMAP pokemon, "#MON LAB and"
	.DB $55
	.STRINGMAP pokemon, "get it examined!"
	.DB $58
_Museum1FScientist2ReceivedOldAmberText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "OLD AMBER!@"
	.DB $50
_Museum1FScientist2GetTheOldAmberCheckText::
	.DB $00
	.STRINGMAP pokemon, "Ssh! Get the OLD"
	.DB $4f
	.STRINGMAP pokemon, "AMBER checked!"
	.DB $57
_Museum1FScientist2YouDontHaveSpaceText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "space for this!"
	.DB $57
_Museum1FScientist3Text::
	.DB $00
	.STRINGMAP pokemon, "We are proud of 2"
	.DB $4f
	.STRINGMAP pokemon, "fossils of very"
	.DB $55
	.STRINGMAP pokemon, "rare, prehistoric"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_Museum1FOldAmberText::
	.DB $00
	.STRINGMAP pokemon, "The AMBER is"
	.DB $4f
	.STRINGMAP pokemon, "clear and gold!"
	.DB $57

; text/Museum2F.asm
_Museum2FYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "MOON STONE?"
	.DB $51
	.STRINGMAP pokemon, "What's so special"
	.DB $4f
	.STRINGMAP pokemon, "about it?"
	.DB $57
_Museum2FGrampsText::
	.DB $00
	.STRINGMAP pokemon, "July 20, 1969!"
	.DB $51
	.STRINGMAP pokemon, "The 1st lunar"
	.DB $4f
	.STRINGMAP pokemon, "landing!"
	.DB $51
	.STRINGMAP pokemon, "I bought a color"
	.DB $4f
	.STRINGMAP pokemon, "TV to watch it!"
	.DB $57
_Museum2FScientistText::
	.DB $00
	.STRINGMAP pokemon, "We have a space"
	.DB $4f
	.STRINGMAP pokemon, "exhibit now."
	.DB $57
_Museum2FBrunetteGirlText::
	.DB $00
	.STRINGMAP pokemon, "I want a PIKACHU!"
	.DB $4f
	.STRINGMAP pokemon, "It's so cute!"
	.DB $51
	.STRINGMAP pokemon, "I asked my Daddy"
	.DB $4f
	.STRINGMAP pokemon, "to catch me one!"
	.DB $57
_Museum2FHikerText::
	.DB $00
	.STRINGMAP pokemon, "Yeah, a PIKACHU"
	.DB $4f
	.STRINGMAP pokemon, "soon, I promise!"
	.DB $57
_Museum2FSpaceShuttleSignText::
	.DB $00
	.STRINGMAP pokemon, "SPACE SHUTTLE"
	.DB $4f
	.STRINGMAP pokemon, "COLUMBIA"
	.DB $57
_Museum2FMoonStoneSignText::
	.DB $00
	.STRINGMAP pokemon, "Meteorite that"
	.DB $4f
	.STRINGMAP pokemon, "fell on MT.MOON."
	.DB $55
	.STRINGMAP pokemon, "(MOON STONE?)"
	.DB $57

; text/PewterGym.asm
_PewterGymBrockPreBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm BROCK!"
	.DB $4f
	.STRINGMAP pokemon, "I'm PEWTER's GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER!"
	.DB $51
	.STRINGMAP pokemon, "I believe in rock"
	.DB $4f
	.STRINGMAP pokemon, "hard defense and"
	.DB $55
	.STRINGMAP pokemon, "determination!"
	.DB $51
	.STRINGMAP pokemon, "That's why my"
	.DB $4f
	.STRINGMAP pokemon, "#MON are all"
	.DB $55
	.STRINGMAP pokemon, "the rock-type!"
	.DB $51
	.STRINGMAP pokemon, "Do you still want"
	.DB $4f
	.STRINGMAP pokemon, "to challenge me?"
	.DB $55
	.STRINGMAP pokemon, "Fine then! Show"
	.DB $55
	.STRINGMAP pokemon, "me your best!"
	.DB $57

Bank37TextEnd::
