; Generated by convert_text_bank.py from:
;   text/Route11_2.asm
;   text/Route12.asm
;   text/Route13.asm
;   text/Route14.asm
;   text/Route15.asm
;   text/Route16.asm
;   text/Route17.asm
;   text/Route18.asm
;   text/Route19.asm
;   text/Route20.asm
;   text/Route21.asm
;   text/Route22.asm
;   text/Route23.asm
;   text/Route24.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; text/Route11_2.asm
_Route11SuperNerd2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whoa!"
	.DB $4f
	.STRINGMAP pokemon, "You spark plug!"
	.DB $58
_Route11SuperNerd2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Well, better get"
	.DB $4f
	.STRINGMAP pokemon, "back to work."
	.DB $57
_Route11Youngster4BattleText::
	.DB $00
	.STRINGMAP pokemon, "My #MON should"
	.DB $4f
	.STRINGMAP pokemon, "be ready by now!"
	.DB $57
_Route11Youngster4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Too"
	.DB $4f
	.STRINGMAP pokemon, "much, too young!"
	.DB $58
_Route11Youngster4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I better go find"
	.DB $4f
	.STRINGMAP pokemon, "stronger ones!"
	.DB $57
_Route11DiglettsCaveSignText::
	.DB $00
	.STRINGMAP pokemon, "DIGLETT's CAVE"
	.DB $57

; text/Route12.asm
_Route12SnorlaxText::
	.DB $00
	.STRINGMAP pokemon, "A sleeping #MON"
	.DB $4f
	.STRINGMAP pokemon, "blocks the way!"
	.DB $57
_Route12SnorlaxWokeUpText::
	.DB $00
	.STRINGMAP pokemon, "SNORLAX woke up!"
	.DB $51
	.STRINGMAP pokemon, "It attacked in a"
	.DB $4f
	.STRINGMAP pokemon, "grumpy rage!"
	.DB $57
_Route12SnorlaxCalmedDownText::
	.DB $00
	.STRINGMAP pokemon, "SNORLAX calmed"
	.DB $4f
	.STRINGMAP pokemon, "down! With a big"
	.DB $55
	.STRINGMAP pokemon, "yawn, it returned"
	.DB $55
	.STRINGMAP pokemon, "to the mountains!"
	.DB $57
_Route12Fisher1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Yeah! I got a"
	.DB $4f
	.STRINGMAP pokemon, "bite, here!"
	.DB $57
_Route12Fisher1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Tch!"
	.DB $4f
	.STRINGMAP pokemon, "Just a small fry!"
	.DB $58
_Route12Fisher1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hang on! My line's"
	.DB $4f
	.STRINGMAP pokemon, "snagged!"
	.DB $57
_Route12Fisher2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Be patient!"
	.DB $4f
	.STRINGMAP pokemon, "Fishing is a"
	.DB $55
	.STRINGMAP pokemon, "waiting game!"
	.DB $57
_Route12Fisher2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "That"
	.DB $4f
	.STRINGMAP pokemon, "one got away!"
	.DB $58
_Route12Fisher2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "With a better ROD,"
	.DB $4f
	.STRINGMAP pokemon, "I could catch"
	.DB $55
	.STRINGMAP pokemon, "better #MON!"
	.DB $57
_Route12CooltrainerMBattleText::
	.DB $00
	.STRINGMAP pokemon, "Have you found a"
	.DB $4f
	.STRINGMAP pokemon, "MOON STONE?"
	.DB $57
_Route12CooltrainerMEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oww!"
	.DB $58
_Route12CooltrainerMAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I could have made"
	.DB $4f
	.STRINGMAP pokemon, "my #MON evolve"
	.DB $55
	.STRINGMAP pokemon, "with MOON STONE!"
	.DB $57
_Route12SuperNerdBattleText::
	.DB $00
	.STRINGMAP pokemon, "Electricity is my"
	.DB $4f
	.STRINGMAP pokemon, "specialty!"
	.DB $57
_Route12SuperNerdEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Unplugged!"
	.DB $58
_Route12SuperNerdAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Water conducts"
	.DB $4f
	.STRINGMAP pokemon, "electricity, so"
	.DB $55
	.STRINGMAP pokemon, "you should zap"
	.DB $55
	.STRINGMAP pokemon, "sea #MON!"
	.DB $57
_Route12Fisher3BattleText::
	.DB $00
	.STRINGMAP pokemon, "The FISHING FOOL"
	.DB $4f
	.STRINGMAP pokemon, "vs. #MON KID!"
	.DB $57
_Route12Fisher3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Too"
	.DB $4f
	.STRINGMAP pokemon, "much!"
	.DB $58
_Route12Fisher3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You beat me at"
	.DB $4f
	.STRINGMAP pokemon, "#MON, but I'm"
	.DB $55
	.STRINGMAP pokemon, "good at fishing!"
	.DB $57
_Route12Fisher4BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'd rather be"
	.DB $4f
	.STRINGMAP pokemon, "working!"
	.DB $57
_Route12Fisher4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "It's"
	.DB $4f
	.STRINGMAP pokemon, "not easy..."
	.DB $58
_Route12Fisher4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "It's all right."
	.DB $4f
	.STRINGMAP pokemon, "Losing doesn't"
	.DB $55
	.STRINGMAP pokemon, "bug me any more."
	.DB $57
_Route12Fisher5BattleText::
	.DB $00
	.STRINGMAP pokemon, "You never know"
	.DB $4f
	.STRINGMAP pokemon, "what you could"
	.DB $55
	.STRINGMAP pokemon, "catch!"
	.DB $57
_Route12Fisher5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Lost"
	.DB $4f
	.STRINGMAP pokemon, "it!"
	.DB $58
_Route12Fisher5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I catch MAGIKARP"
	.DB $4f
	.STRINGMAP pokemon, "all the time, but"
	.DB $55
	.STRINGMAP pokemon, "they're so weak!"
	.DB $57
_Route12SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 12 "
	.DB $4f
	.STRINGMAP pokemon, "North to LAVENDER"
	.DB $57
_Route12SportFishingSignText::
	.DB $00
	.STRINGMAP pokemon, "SPORT FISHING AREA"
	.DB $57

; text/Route13.asm
_Route13CooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "My bird #MON"
	.DB $4f
	.STRINGMAP pokemon, "want to scrap!"
	.DB $57
_Route13CooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "My"
	.DB $4f
	.STRINGMAP pokemon, "bird combo lost?"
	.DB $58
_Route13CooltrainerM1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "My #MON look"
	.DB $4f
	.STRINGMAP pokemon, "happy even though"
	.DB $55
	.STRINGMAP pokemon, "they lost."
	.DB $57
_Route13CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm told I'm good"
	.DB $4f
	.STRINGMAP pokemon, "for a kid!"
	.DB $57
_Route13CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ohh!"
	.DB $4f
	.STRINGMAP pokemon, "I lost!"
	.DB $58
_Route13CooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I want to become"
	.DB $4f
	.STRINGMAP pokemon, "a good trainer."
	.DB $55
	.STRINGMAP pokemon, "I'll train hard."
	.DB $57
_Route13CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Wow! Your BADGEs"
	.DB $4f
	.STRINGMAP pokemon, "are too cool!"
	.DB $57
_Route13CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Not"
	.DB $4f
	.STRINGMAP pokemon, "enough!"
	.DB $58
_Route13CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You got those"
	.DB $4f
	.STRINGMAP pokemon, "BADGEs from GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADERs. I know!"
	.DB $57
_Route13CooltrainerF3BattleText::
	.DB $00
	.STRINGMAP pokemon, "My cute #MON"
	.DB $4f
	.STRINGMAP pokemon, "wish to make your"
	.DB $55
	.STRINGMAP pokemon, "acquaintance."
	.DB $57
_Route13CooltrainerF3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wow!"
	.DB $4f
	.STRINGMAP pokemon, "You totally won!"
	.DB $58
_Route13CooltrainerF3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You have to make"
	.DB $4f
	.STRINGMAP pokemon, "#MON fight to"
	.DB $55
	.STRINGMAP pokemon, "toughen them up!"
	.DB $57
_Route13CooltrainerF4BattleText::
	.DB $00
	.STRINGMAP pokemon, "I found CARBOS in"
	.DB $4f
	.STRINGMAP pokemon, "a cave once."
	.DB $57
_Route13CooltrainerF4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Just"
	.DB $4f
	.STRINGMAP pokemon, "messed up!"
	.DB $58
_Route13CooltrainerF4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "CARBOS boosted"
	.DB $4f
	.STRINGMAP pokemon, "the SPEED of my"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $57
_Route13CooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "The wind's blowing"
	.DB $4f
	.STRINGMAP pokemon, "my way!"
	.DB $57
_Route13CooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "The"
	.DB $4f
	.STRINGMAP pokemon, "wind turned!"
	.DB $58
_Route13CooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm beat. I guess"
	.DB $4f
	.STRINGMAP pokemon, "I'll FLY home."
	.DB $57
_Route13Beauty1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Sure, I'll play"
	.DB $4f
	.STRINGMAP pokemon, "with you!"
	.DB $57
_Route13Beauty1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "You little brute!"
	.DB $58
_Route13Beauty1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wonder which is"
	.DB $4f
	.STRINGMAP pokemon, "stronger, male or"
	.DB $55
	.STRINGMAP pokemon, "female #MON?"
	.DB $57
_Route13Beauty2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Do you want to"
	.DB $4f
	.STRINGMAP pokemon, "#MON with me?"
	.DB $57
_Route13Beauty2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "It's over"
	.DB $4f
	.STRINGMAP pokemon, "already?"
	.DB $58
_Route13Beauty2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I don't know"
	.DB $4f
	.STRINGMAP pokemon, "anything about"
	.DB $55
	.STRINGMAP pokemon, "#MON. I just"
	.DB $55
	.STRINGMAP pokemon, "like cool ones!"
	.DB $57
_Route13BikerBattleText::
	.DB $00
	.STRINGMAP pokemon, "What're you"
	.DB $4f
	.STRINGMAP pokemon, "lookin' at?"
	.DB $57
_Route13BikerEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Dang!"
	.DB $4f
	.STRINGMAP pokemon, "Stripped gears!"
	.DB $58
_Route13BikerAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Get lost!"
	.DB $57
_Route13CooltrainerM3BattleText::
	.DB $00
	.STRINGMAP pokemon, "I always go with"
	.DB $4f
	.STRINGMAP pokemon, "bird #MON!"
	.DB $57
_Route13CooltrainerM3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Out"
	.DB $4f
	.STRINGMAP pokemon, "of power!"
	.DB $58
_Route13CooltrainerM3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wish I could"
	.DB $4f
	.STRINGMAP pokemon, "fly like PIDGEY"
	.DB $55
	.STRINGMAP pokemon, "and PIDGEOTTO..."
	.DB $57
_Route13TrainerTips1Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Look to the left"
	.DB $4f
	.STRINGMAP pokemon, "of that post!"
	.DB $57
_Route13TrainerTips2Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Use SELECT to"
	.DB $4f
	.STRINGMAP pokemon, "switch items in"
	.DB $55
	.STRINGMAP pokemon, "the ITEM window!"
	.DB $57
_Route13SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 13"
	.DB $4f
	.STRINGMAP pokemon, "North to SILENCE"
	.DB $55
	.STRINGMAP pokemon, "BRIDGE"
	.DB $57

; text/Route14.asm
_Route14CooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "You need to use"
	.DB $4f
	.STRINGMAP pokemon, "TMs to teach good"
	.DB $55
	.STRINGMAP pokemon, "moves to #MON!"
	.DB $57
_Route14CooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Not"
	.DB $4f
	.STRINGMAP pokemon, "good enough!"
	.DB $58
_Route14CooltrainerM1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You have some HMs"
	.DB $4f
	.STRINGMAP pokemon, "right? #MON"
	.DB $55
	.STRINGMAP pokemon, "can't ever forget"
	.DB $55
	.STRINGMAP pokemon, "those moves."
	.DB $57
_Route14CooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "My bird #MON"
	.DB $4f
	.STRINGMAP pokemon, "should be ready"
	.DB $55
	.STRINGMAP pokemon, "for battle."
	.DB $57
_Route14CooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Not"
	.DB $4f
	.STRINGMAP pokemon, "ready yet!"
	.DB $58
_Route14CooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "They need to learn"
	.DB $4f
	.STRINGMAP pokemon, "better moves."
	.DB $57
_Route14CooltrainerM3BattleText::
	.DB $00
	.STRINGMAP pokemon, "TMs are on sale"
	.DB $4f
	.STRINGMAP pokemon, "in CELADON!"
	.DB $55
	.STRINGMAP pokemon, "But, only a few"
	.DB $55
	.STRINGMAP pokemon, "people have HMs!"
	.DB $57
_Route14CooltrainerM3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Aww,"
	.DB $4f
	.STRINGMAP pokemon, "bummer!"
	.DB $58
_Route14CooltrainerM3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Teach #MON"
	.DB $4f
	.STRINGMAP pokemon, "moves of the same"
	.DB $55
	.STRINGMAP pokemon, "element type for"
	.DB $55
	.STRINGMAP pokemon, "more power."
	.DB $57
_Route14CooltrainerM4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Have you taught"
	.DB $4f
	.STRINGMAP pokemon, "your bird #MON"
	.DB $55
	.STRINGMAP pokemon, "how to FLY?"
	.DB $57
_Route14CooltrainerM4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Shot"
	.DB $4f
	.STRINGMAP pokemon, "down in flames!"
	.DB $58
_Route14CooltrainerM4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Bird #MON are"
	.DB $4f
	.STRINGMAP pokemon, "my true love!"
	.DB $57
_Route14CooltrainerM5BattleText::
	.DB $00
	.STRINGMAP pokemon, "Have you heard of"
	.DB $4f
	.STRINGMAP pokemon, "the legendary"
	.DB $55
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_Route14CooltrainerM5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Why?"
	.DB $4f
	.STRINGMAP pokemon, "Why'd I lose?"
	.DB $58
_Route14CooltrainerM5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The 3 legendary"
	.DB $4f
	.STRINGMAP pokemon, "#MON are all"
	.DB $55
	.STRINGMAP pokemon, "birds of prey."
	.DB $57
_Route14CooltrainerM6BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm not into it,"
	.DB $4f
	.STRINGMAP pokemon, "but OK! Let's go!"
	.DB $57
_Route14CooltrainerM6EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "knew it!"
	.DB $58
_Route14CooltrainerM6AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Winning, losing,"
	.DB $4f
	.STRINGMAP pokemon, "it doesn't matter"
	.DB $55
	.STRINGMAP pokemon, "in the long run!"
	.DB $57
_Route14Biker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "C'mon, c'mon."
	.DB $4f
	.STRINGMAP pokemon, "Let's go, let's"
	.DB $55
	.STRINGMAP pokemon, "go, let's go!"
	.DB $57
_Route14Biker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Arrg!"
	.DB $4f
	.STRINGMAP pokemon, "Lost! Get lost!"
	.DB $58
_Route14Biker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "What, what, what?"
	.DB $4f
	.STRINGMAP pokemon, "What do you want?"
	.DB $57
_Route14Biker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Perfect! I need to"
	.DB $4f
	.STRINGMAP pokemon, "burn some time!"
	.DB $57
_Route14Biker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "What?"
	.DB $4f
	.STRINGMAP pokemon, "You!?"
	.DB $58
_Route14Biker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Raising #MON"
	.DB $4f
	.STRINGMAP pokemon, "is a drag, man."
	.DB $57
_Route14Biker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "We ride out here"
	.DB $4f
	.STRINGMAP pokemon, "because there's"
	.DB $55
	.STRINGMAP pokemon, "more room!"
	.DB $57
_Route14Biker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wipe out!"
	.DB $58
_Route14Biker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "It's cool you"
	.DB $4f
	.STRINGMAP pokemon, "made your #MON"
	.DB $55
	.STRINGMAP pokemon, "so strong!"
	.DB $51
	.STRINGMAP pokemon, "Might is right!"
	.DB $4f
	.STRINGMAP pokemon, "And you know it!"
	.DB $57
_Route14Biker4BattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON fight?"
	.DB $4f
	.STRINGMAP pokemon, "Cool! Rumble!"
	.DB $57
_Route14Biker4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Blown"
	.DB $4f
	.STRINGMAP pokemon, "away!"
	.DB $58
_Route14Biker4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You know who'd"
	.DB $4f
	.STRINGMAP pokemon, "win, you and me"
	.DB $55
	.STRINGMAP pokemon, "one on one!"
	.DB $57
_Route14SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 14"
	.DB $4f
	.STRINGMAP pokemon, "West to FUCHSIA"
	.DB $55
	.STRINGMAP pokemon, "CITY"
	.DB $57

; text/Route15.asm
_Route15CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Let me try out the"
	.DB $4f
	.STRINGMAP pokemon, "#MON I just"
	.DB $55
	.STRINGMAP pokemon, "got in a trade!"
	.DB $57
_Route15CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Not"
	.DB $4f
	.STRINGMAP pokemon, "good enough!"
	.DB $58
_Route15CooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You can't change"
	.DB $4f
	.STRINGMAP pokemon, "the nickname of"
	.DB $55
	.STRINGMAP pokemon, "any #MON you"
	.DB $55
	.STRINGMAP pokemon, "get in a trade."
	.DB $51
	.STRINGMAP pokemon, "Only the Original"
	.DB $4f
	.STRINGMAP pokemon, "Trainer can."
	.DB $57
_Route15CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "You look gentle,"
	.DB $4f
	.STRINGMAP pokemon, "so I think I can"
	.DB $55
	.STRINGMAP pokemon, "beat you!"
	.DB $57
_Route15CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "No,"
	.DB $4f
	.STRINGMAP pokemon, "wrong!"
	.DB $58
_Route15CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm afraid of"
	.DB $4f
	.STRINGMAP pokemon, "BIKERs, they look"
	.DB $55
	.STRINGMAP pokemon, "so ugly and mean!"
	.DB $57
_Route15CooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "When I whistle, I"
	.DB $4f
	.STRINGMAP pokemon, "can summon bird"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_Route15CooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ow!"
	.DB $4f
	.STRINGMAP pokemon, "That's tragic!"
	.DB $58
_Route15CooltrainerM1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Maybe I'm not cut"
	.DB $4f
	.STRINGMAP pokemon, "out for battles."
	.DB $57
_Route15CooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hmm? My birds are"
	.DB $4f
	.STRINGMAP pokemon, "shivering! You're"
	.DB $55
	.STRINGMAP pokemon, "good, aren't you?"
	.DB $57
_Route15CooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Just"
	.DB $4f
	.STRINGMAP pokemon, "as I thought!"
	.DB $58
_Route15CooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Did you know moves"
	.DB $4f
	.STRINGMAP pokemon, "like EARTHQUAKE"
	.DB $55
	.STRINGMAP pokemon, "don't have any"
	.DB $55
	.STRINGMAP pokemon, "effect on birds?"
	.DB $57
_Route15Beauty1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh, you're a"
	.DB $4f
	.STRINGMAP pokemon, "little cutie!"
	.DB $57
_Route15Beauty1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You looked"
	.DB $4f
	.STRINGMAP pokemon, "so cute too!"
	.DB $58
_Route15Beauty1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I forgive you!"
	.DB $4f
	.STRINGMAP pokemon, "I can take it!"
	.DB $57
_Route15Beauty2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I raise #MON"
	.DB $4f
	.STRINGMAP pokemon, "because I live"
	.DB $55
	.STRINGMAP pokemon, "alone!"
	.DB $57
_Route15Beauty2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I didn't"
	.DB $4f
	.STRINGMAP pokemon, "ask for this!"
	.DB $58
_Route15Beauty2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I just like going"
	.DB $4f
	.STRINGMAP pokemon, "home to be with"
	.DB $55
	.STRINGMAP pokemon, "my #MON!"
	.DB $57
_Route15Biker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey kid! C'mon!"
	.DB $4f
	.STRINGMAP pokemon, "I just got these!"
	.DB $57
_Route15Biker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Why"
	.DB $4f
	.STRINGMAP pokemon, "not?"
	.DB $58
_Route15Biker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You only live"
	.DB $4f
	.STRINGMAP pokemon, "once, so I live"
	.DB $55
	.STRINGMAP pokemon, "as an outlaw!"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET RULES!"
	.DB $57
_Route15Biker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Fork over all your"
	.DB $4f
	.STRINGMAP pokemon, "cash when you"
	.DB $55
	.STRINGMAP pokemon, "lose to me, kid!"
	.DB $57
_Route15Biker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "That"
	.DB $4f
	.STRINGMAP pokemon, "can't be true!"
	.DB $58
_Route15Biker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I was just joking"
	.DB $4f
	.STRINGMAP pokemon, "about the money!"
	.DB $57
_Route15CooltrainerF3BattleText::
	.DB $00
	.STRINGMAP pokemon, "What's cool?"
	.DB $4f
	.STRINGMAP pokemon, "Trading #MON!"
	.DB $57
_Route15CooltrainerF3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "said trade!"
	.DB $58
_Route15CooltrainerF3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I trade #MON"
	.DB $4f
	.STRINGMAP pokemon, "with my friends!"
	.DB $57
_Route15CooltrainerF4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Want to play with"
	.DB $4f
	.STRINGMAP pokemon, "my #MON?"
	.DB $57
_Route15CooltrainerF4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I was"
	.DB $4f
	.STRINGMAP pokemon, "too impatient!"
	.DB $58
_Route15CooltrainerF4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'll go train with"
	.DB $4f
	.STRINGMAP pokemon, "weaker people.@"
	.DB $50
_Route15SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 15"
	.DB $4f
	.STRINGMAP pokemon, "West to FUCHSIA"
	.DB $55
	.STRINGMAP pokemon, "CITY"
	.DB $57

; text/Route16.asm
_Route16Biker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "What do you want?"
	.DB $57
_Route16Biker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Don't you"
	.DB $4f
	.STRINGMAP pokemon, "dare laugh!"
	.DB $58
_Route16Biker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "We like just"
	.DB $4f
	.STRINGMAP pokemon, "hanging here,"
	.DB $55
	.STRINGMAP pokemon, "what's it to you?"
	.DB $57
_Route16Biker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Nice BIKE!"
	.DB $4f
	.STRINGMAP pokemon, "Hand it over!"
	.DB $57
_Route16Biker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Knock"
	.DB $4f
	.STRINGMAP pokemon, "out!"
	.DB $58
_Route16Biker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Forget it, who"
	.DB $4f
	.STRINGMAP pokemon, "needs your BIKE!"
	.DB $57
_Route16Biker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Come out and play,"
	.DB $4f
	.STRINGMAP pokemon, "little mouse!"
	.DB $57
_Route16Biker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "little rat!"
	.DB $58
_Route16Biker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I hate losing!"
	.DB $4f
	.STRINGMAP pokemon, "Get away from me!"
	.DB $57
_Route16biker4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey, you just"
	.DB $4f
	.STRINGMAP pokemon, "bumped me!"
	.DB $57
_Route16Biker4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Kaboom!"
	.DB $58
_Route16Biker4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You can also get"
	.DB $4f
	.STRINGMAP pokemon, "to FUCHSIA from"
	.DB $55
	.STRINGMAP pokemon, "VERMILION using a"
	.DB $55
	.STRINGMAP pokemon, "coastal road."
	.DB $57
_Route16Biker5BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm feeling"
	.DB $4f
	.STRINGMAP pokemon, "hungry and mean!"
	.DB $57
_Route16Biker5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Bad,"
	.DB $4f
	.STRINGMAP pokemon, "bad, bad!"
	.DB $58
_Route16Biker5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I like my #MON"
	.DB $4f
	.STRINGMAP pokemon, "ferocious! They"
	.DB $55
	.STRINGMAP pokemon, "tear up enemies!"
	.DB $57
_Route16Biker6BattleText::
	.DB $00
	.STRINGMAP pokemon, "Sure, I'll go!"
	.DB $57
_Route16Biker6EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Don't make"
	.DB $4f
	.STRINGMAP pokemon, "me mad!"
	.DB $58
_Route16Biker6AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I like harassing"
	.DB $4f
	.STRINGMAP pokemon, "people with my"
	.DB $55
	.STRINGMAP pokemon, "vicious #MON!"
	.DB $57
_Route16Text7::
	.DB $00
	.STRINGMAP pokemon, "A sleeping #MON"
	.DB $4f
	.STRINGMAP pokemon, "blocks the way!"
	.DB $57
_Route16SnorlaxWokeUpText::
	.DB $00
	.STRINGMAP pokemon, "SNORLAX woke up!"
	.DB $51
	.STRINGMAP pokemon, "It attacked in a"
	.DB $4f
	.STRINGMAP pokemon, "grumpy rage!"
	.DB $57
_Route16SnorlaxReturnedToMountainsText::
	.DB $00
	.STRINGMAP pokemon, "With a big yawn,"
	.DB $4f
	.STRINGMAP pokemon, "SNORLAX returned"
	.DB $55
	.STRINGMAP pokemon, "to the mountains!"
	.DB $57
_Route16CyclingRoadSignText::
	.DB $00
	.STRINGMAP pokemon, "Enjoy the slope!"
	.DB $4f
	.STRINGMAP pokemon, "CYCLING ROAD"
	.DB $57
_Route16SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 16"
	.DB $4f
	.STRINGMAP pokemon, "CELADON CITY -"
	.DB $55
	.STRINGMAP pokemon, "FUCHSIA CITY"
	.DB $57

; text/Route17.asm
_Route17Biker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "There's no money"
	.DB $4f
	.STRINGMAP pokemon, "in fighting kids!"
	.DB $57
_Route17Biker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Burned"
	.DB $4f
	.STRINGMAP pokemon, "out!"
	.DB $58
_Route17Biker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Good stuff is"
	.DB $4f
	.STRINGMAP pokemon, "lying around on"
	.DB $55
	.STRINGMAP pokemon, "CYCLING ROAD!"
	.DB $57
_Route17Biker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "What do you want,"
	.DB $4f
	.STRINGMAP pokemon, "kiddo?"
	.DB $57
_Route17Biker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whoo!"
	.DB $58
_Route17Biker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I could belly-"
	.DB $4f
	.STRINGMAP pokemon, "bump you outta"
	.DB $55
	.STRINGMAP pokemon, "here!"
	.DB $57
_Route17Biker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "You heading to"
	.DB $4f
	.STRINGMAP pokemon, "FUCHSIA?"
	.DB $57
_Route17Biker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Crash and"
	.DB $4f
	.STRINGMAP pokemon, "burn!"
	.DB $58
_Route17Biker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I love racing"
	.DB $4f
	.STRINGMAP pokemon, "downhill!"
	.DB $57
_Route17Biker4BattleText::
	.DB $00
	.STRINGMAP pokemon, "We're BIKERs!"
	.DB $4f
	.STRINGMAP pokemon, "Highway stars!"
	.DB $57
_Route17Biker4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Smoked!"
	.DB $58
_Route17Biker4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you looking"
	.DB $4f
	.STRINGMAP pokemon, "for adventure?"
	.DB $57
_Route17Biker5BattleText::
	.DB $00
	.STRINGMAP pokemon, "Let VOLTORB"
	.DB $4f
	.STRINGMAP pokemon, "electrify you!"
	.DB $57
_Route17Biker5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Grounded"
	.DB $4f
	.STRINGMAP pokemon, "out!"
	.DB $58
_Route17Biker5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I got my VOLTORB"
	.DB $4f
	.STRINGMAP pokemon, "at the abandoned"
	.DB $55
	.STRINGMAP pokemon, "POWER PLANT."
	.DB $57
_Route17Biker6BattleText::
	.DB $00
	.STRINGMAP pokemon, "My #MON won't"
	.DB $4f
	.STRINGMAP pokemon, "evolve! Why?"
	.DB $57
_Route17Biker6EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Why,"
	.DB $4f
	.STRINGMAP pokemon, "you!"
	.DB $58
_Route17Biker6AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Maybe some #MON"
	.DB $4f
	.STRINGMAP pokemon, "need element"
	.DB $55
	.STRINGMAP pokemon, "STONEs to evolve."
	.DB $57
_Route17Biker7BattleText::
	.DB $00
	.STRINGMAP pokemon, "I need a little"
	.DB $4f
	.STRINGMAP pokemon, "exercise!"
	.DB $57
_Route17Biker7EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whew!"
	.DB $4f
	.STRINGMAP pokemon, "Good workout!"
	.DB $58
_Route17Biker7AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm sure I lost"
	.DB $4f
	.STRINGMAP pokemon, "weight there!"
	.DB $57
_Route17Biker8BattleText::
	.DB $00
	.STRINGMAP pokemon, "Be a rebel!"
	.DB $57
_Route17Biker8EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Aaaargh!"
	.DB $58
_Route17Biker8AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Be ready to fight"
	.DB $4f
	.STRINGMAP pokemon, "for your beliefs!"
	.DB $57
_Route17Biker9BattleText::
	.DB $00
	.STRINGMAP pokemon, "Nice BIKE!"
	.DB $4f
	.STRINGMAP pokemon, "How's it handle?"
	.DB $57
_Route17Biker9EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Shoot!"
	.DB $58
_Route17Biker9AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The slope makes"
	.DB $4f
	.STRINGMAP pokemon, "it hard to steer!"
	.DB $57
_Route17Biker10BattleText::
	.DB $00
	.STRINGMAP pokemon, "Get lost kid!"
	.DB $4f
	.STRINGMAP pokemon, "I'm bushed!"
	.DB $57
_Route17Biker10EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you"
	.DB $4f
	.STRINGMAP pokemon, "satisfied?"
	.DB $58
_Route17Biker10AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I need to catch"
	.DB $4f
	.STRINGMAP pokemon, "a few Zs!"
	.DB $57
_Route17NoticeSign1Text::
	.DB $00
	.STRINGMAP pokemon, "It's a notice!"
	.DB $51
	.STRINGMAP pokemon, "Watch out for"
	.DB $4f
	.STRINGMAP pokemon, "discarded items!"
	.DB $57
_Route17TrainerTips1Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "All #MON are"
	.DB $4f
	.STRINGMAP pokemon, "unique."
	.DB $51
	.STRINGMAP pokemon, "Even #MON of"
	.DB $4f
	.STRINGMAP pokemon, "the same type and"
	.DB $55
	.STRINGMAP pokemon, "level grow at"
	.DB $55
	.STRINGMAP pokemon, "different rates."
	.DB $57
_Route17TrainerTips2Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Press the A or B"
	.DB $4f
	.STRINGMAP pokemon, "Button to stay in"
	.DB $55
	.STRINGMAP pokemon, "place while on a"
	.DB $55
	.STRINGMAP pokemon, "slope."
	.DB $57
_Route17SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 17"
	.DB $4f
	.STRINGMAP pokemon, "CELADON CITY -"
	.DB $55
	.STRINGMAP pokemon, "FUCHSIA CITY"
	.DB $57
_Route17NoticeSign2Text::
	.DB $00
	.STRINGMAP pokemon, "It's a notice!"
	.DB $51
	.STRINGMAP pokemon, "Don't throw the"
	.DB $4f
	.STRINGMAP pokemon, "game, throw #"
	.DB $55
	.STRINGMAP pokemon, "BALLs instead!"
	.DB $57
_Route17CyclingRoadEndsSignText::
	.DB $00
	.STRINGMAP pokemon, "CYCLING ROAD"
	.DB $4f
	.STRINGMAP pokemon, "Slope ends here!"
	.DB $57

; text/Route18.asm
_Route18CooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I always check"
	.DB $4f
	.STRINGMAP pokemon, "every grassy area"
	.DB $55
	.STRINGMAP pokemon, "for new #MON."
	.DB $57
_Route18CooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Tch!"
	.DB $58
_Route18CooltrainerM1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wish I had a"
	.DB $4f
	.STRINGMAP pokemon, "BIKE!"
	.DB $57
_Route18CooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Kurukkoo!"
	.DB $4f
	.STRINGMAP pokemon, "How do you like"
	.DB $55
	.STRINGMAP pokemon, "my bird call?"
	.DB $57
_Route18CooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "had to bug you!"
	.DB $58
_Route18CooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I also collect sea"
	.DB $4f
	.STRINGMAP pokemon, "#MON on"
	.DB $55
	.STRINGMAP pokemon, "weekends!"
	.DB $57
_Route18CooltrainerM3BattleText::
	.DB $00
	.STRINGMAP pokemon, "This is my turf!"
	.DB $4f
	.STRINGMAP pokemon, "Get out of here!"
	.DB $57
_Route18CooltrainerM3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Darn!"
	.DB $58
_Route18CooltrainerM3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "This is my fave"
	.DB $4f
	.STRINGMAP pokemon, "#MON hunting"
	.DB $55
	.STRINGMAP pokemon, "area!"
	.DB $57
_Route18SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 18"
	.DB $4f
	.STRINGMAP pokemon, "CELADON CITY -"
	.DB $55
	.STRINGMAP pokemon, "FUCHSIA CITY"
	.DB $57
_Route18CyclingRoadSignText::
	.DB $00
	.STRINGMAP pokemon, "CYCLING ROAD"
	.DB $4f
	.STRINGMAP pokemon, "No pedestrians"
	.DB $55
	.STRINGMAP pokemon, "permitted!"
	.DB $57

; text/Route19.asm
_Route19CooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Have to warm up"
	.DB $4f
	.STRINGMAP pokemon, "before my swim!"
	.DB $57
_Route19CooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "All"
	.DB $4f
	.STRINGMAP pokemon, "warmed up!"
	.DB $58
_Route19CooltrainerM1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Thanks, kid! I'm"
	.DB $4f
	.STRINGMAP pokemon, "ready for a swim!"
	.DB $57
_Route19CooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Wait! You'll have"
	.DB $4f
	.STRINGMAP pokemon, "a heart attack!"
	.DB $57
_Route19CooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ooh!"
	.DB $4f
	.STRINGMAP pokemon, "That's chilly!"
	.DB $58
_Route19CooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Watch out for"
	.DB $4f
	.STRINGMAP pokemon, "TENTACOOL!"
	.DB $57
_Route19Swimmer1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I love swimming!"
	.DB $4f
	.STRINGMAP pokemon, "What about you?"
	.DB $57
_Route19Swimmer1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Belly"
	.DB $4f
	.STRINGMAP pokemon, "flop!"
	.DB $58
_Route19Swimmer1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I can beat #MON"
	.DB $4f
	.STRINGMAP pokemon, "at swimming!"
	.DB $57
_Route19Swimmer2BattleText::
	.DB $00
	.STRINGMAP pokemon, "What's beyond the"
	.DB $4f
	.STRINGMAP pokemon, "horizon?"
	.DB $57
_Route19Swimmer2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Glub!"
	.DB $58
_Route19Swimmer2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I see a couple of"
	.DB $4f
	.STRINGMAP pokemon, "islands!"
	.DB $57
_Route19Swimmer3BattleText::
	.DB $00
	.STRINGMAP pokemon, "I tried diving"
	.DB $4f
	.STRINGMAP pokemon, "for #MON, but"
	.DB $55
	.STRINGMAP pokemon, "it was a no go!"
	.DB $57
_Route19Swimmer3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Help!"
	.DB $58
_Route19Swimmer3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You have to fish"
	.DB $4f
	.STRINGMAP pokemon, "for sea #MON!"
	.DB $57
_Route19Swimmer4BattleText::
	.DB $00
	.STRINGMAP pokemon, "I look at the"
	.DB $4f
	.STRINGMAP pokemon, "sea to forget!"
	.DB $57
_Route19Swimmer4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ooh!"
	.DB $4f
	.STRINGMAP pokemon, "Traumatic!"
	.DB $58
_Route19Swimmer4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm looking at the"
	.DB $4f
	.STRINGMAP pokemon, "sea to forget!"
	.DB $57
_Route19Swimmer5BattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh, I just love"
	.DB $4f
	.STRINGMAP pokemon, "your ride! Can I"
	.DB $55
	.STRINGMAP pokemon, "have it if I win?"
	.DB $57
_Route19Swimmer5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "I lost!"
	.DB $58
_Route19Swimmer5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "It's still a long"
	.DB $4f
	.STRINGMAP pokemon, "way to go to"
	.DB $55
	.STRINGMAP pokemon, "SEAFOAM ISLANDS."
	.DB $57
_Route19Swimmer6BattleText::
	.DB $00
	.STRINGMAP pokemon, "Swimming's great!"
	.DB $4f
	.STRINGMAP pokemon, "Sunburns aren't!"
	.DB $57
_Route19Swimmer6EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Shocker!"
	.DB $58
_Route19Swimmer6AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "My boy friend"
	.DB $4f
	.STRINGMAP pokemon, "wanted to swim to"
	.DB $55
	.STRINGMAP pokemon, "SEAFOAM ISLANDS."
	.DB $57
_Route19Swimmer7BattleText::
	.DB $00
	.STRINGMAP pokemon, "These waters are"
	.DB $4f
	.STRINGMAP pokemon, "treacherous!"
	.DB $57
_Route19Swimmer7EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ooh!"
	.DB $4f
	.STRINGMAP pokemon, "Dangerous!"
	.DB $58
_Route19Swimmer7AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I got a cramp!"
	.DB $4f
	.STRINGMAP pokemon, "Glub, glub..."
	.DB $57
_Route19Swimmer8BattleText::
	.DB $00
	.STRINGMAP pokemon, "I swam here, but"
	.DB $4f
	.STRINGMAP pokemon, "I'm tired."
	.DB $57
_Route19Swimmer8EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "exhausted..."
	.DB $58
_Route19Swimmer8AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "LAPRAS is so big,"
	.DB $4f
	.STRINGMAP pokemon, "it must keep you"
	.DB $55
	.STRINGMAP pokemon, "dry on water."
	.DB $57
_Route19SignText::
	.DB $00
	.STRINGMAP pokemon, "SEA ROUTE 19"
	.DB $4f
	.STRINGMAP pokemon, "FUCHSIA CITY -"
	.DB $55
	.STRINGMAP pokemon, "SEAFOAM ISLANDS"
	.DB $57

; text/Route20.asm
_Route20Swimmer1BattleText::
	.DB $00
	.STRINGMAP pokemon, "The water is"
	.DB $4f
	.STRINGMAP pokemon, "shallow here."
	.DB $57
_Route20Swimmer1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Splash!"
	.DB $58
_Route20Swimmer1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wish I could"
	.DB $4f
	.STRINGMAP pokemon, "ride my #MON."
	.DB $57
_Route20Swimmer2BattleText::
	.DB $00
	.STRINGMAP pokemon, "SEAFOAM is a"
	.DB $4f
	.STRINGMAP pokemon, "quiet getaway!"
	.DB $57
_Route20Swimmer2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Quit it!"
	.DB $58
_Route20Swimmer2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "There's a huge"
	.DB $4f
	.STRINGMAP pokemon, "cavern underneath"
	.DB $55
	.STRINGMAP pokemon, "this island."
	.DB $57
_Route20Swimmer3BattleText::
	.DB $00
	.STRINGMAP pokemon, "I love floating"
	.DB $4f
	.STRINGMAP pokemon, "with the fishes!"
	.DB $57
_Route20Swimmer3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Yowch!"
	.DB $58
_Route20Swimmer3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Want to float"
	.DB $4f
	.STRINGMAP pokemon, "with me?"
	.DB $57
_Route20Swimmer4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you on"
	.DB $4f
	.STRINGMAP pokemon, "vacation too?"
	.DB $57
_Route20Swimmer4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "No"
	.DB $4f
	.STRINGMAP pokemon, "mercy at all!"
	.DB $58
_Route20Swimmer4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "SEAFOAM used to"
	.DB $4f
	.STRINGMAP pokemon, "be one island!"
	.DB $57
_Route20Swimmer5BattleText::
	.DB $00
	.STRINGMAP pokemon, "Check out my buff"
	.DB $4f
	.STRINGMAP pokemon, "physique!"
	.DB $57
_Route20Swimmer5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wimpy!"
	.DB $58
_Route20Swimmer5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I should've been"
	.DB $4f
	.STRINGMAP pokemon, "buffing up my"
	.DB $55
	.STRINGMAP pokemon, "#MON, not me!"
	.DB $57
_Route20Swimmer6BattleText::
	.DB $00
	.STRINGMAP pokemon, "Why are you"
	.DB $4f
	.STRINGMAP pokemon, "riding a #MON?"
	.DB $55
	.STRINGMAP pokemon, "Can't you swim?"
	.DB $57
_Route20Swimmer6EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ouch!"
	.DB $4f
	.STRINGMAP pokemon, "Torpedoed!"
	.DB $58
_Route20Swimmer6AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Riding a #MON"
	.DB $4f
	.STRINGMAP pokemon, "sure looks fun!"
	.DB $57
_Route20CooltrainerMBattleText::
	.DB $00
	.STRINGMAP pokemon, "I rode my bird"
	.DB $4f
	.STRINGMAP pokemon, "#MON here!"
	.DB $57
_Route20CooltrainerMEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh"
	.DB $4f
	.STRINGMAP pokemon, "no!"
	.DB $58
_Route20CooltrainerMAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "My birds can't"
	.DB $4f
	.STRINGMAP pokemon, "FLY me back!"
	.DB $57
_Route20Swimmer7BattleText::
	.DB $00
	.STRINGMAP pokemon, "My boy friend gave"
	.DB $4f
	.STRINGMAP pokemon, "me big pearls!"
	.DB $57
_Route20Swimmer7EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Don't"
	.DB $4f
	.STRINGMAP pokemon, "touch my pearls!"
	.DB $58
_Route20Swimmer7AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Will my pearls"
	.DB $4f
	.STRINGMAP pokemon, "grow bigger"
	.DB $55
	.STRINGMAP pokemon, "inside CLOYSTER?"
	.DB $57
_Route20Swimmer8BattleText::
	.DB $00
	.STRINGMAP pokemon, "I swam here from"
	.DB $4f
	.STRINGMAP pokemon, "CINNABAR ISLAND!"
	.DB $57
_Route20Swimmer8EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "so disappointed!"
	.DB $58
_Route20Swimmer8AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON have"
	.DB $4f
	.STRINGMAP pokemon, "taken over an"
	.DB $55
	.STRINGMAP pokemon, "abandoned mansion"
	.DB $55
	.STRINGMAP pokemon, "on CINNABAR!"
	.DB $57
_Route20Swimmer9BattleText::
	.DB $00
	.STRINGMAP pokemon, "CINNABAR, in the"
	.DB $4f
	.STRINGMAP pokemon, "west, has a LAB"
	.DB $55
	.STRINGMAP pokemon, "for #MON."
	.DB $57
_Route20Swimmer9EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Wait!"
	.DB $58
_Route20Swimmer9AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "CINNABAR is a "
	.DB $4f
	.STRINGMAP pokemon, "volcanic island!"
	.DB $57
_Route20SeafoamIslandsSignText::
	.DB $00
	.STRINGMAP pokemon, "SEAFOAM ISLANDS"
	.DB $57

; text/Route21.asm
_Route21Fisher1BattleText::
	.DB $00
	.STRINGMAP pokemon, "You want to know"
	.DB $4f
	.STRINGMAP pokemon, "if the fish are"
	.DB $55
	.STRINGMAP pokemon, "biting?"
	.DB $57
_Route21Fisher1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Dang!"
	.DB $58
_Route21Fisher1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I can't catch"
	.DB $4f
	.STRINGMAP pokemon, "anything good!"
	.DB $57
_Route21Fisher2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I got a big haul!"
	.DB $4f
	.STRINGMAP pokemon, "Wanna go for it?"
	.DB $57
_Route21Fisher2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Darn"
	.DB $4f
	.STRINGMAP pokemon, "MAGIKARP!"
	.DB $58
_Route21Fisher2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I seem to only"
	.DB $4f
	.STRINGMAP pokemon, "catch MAGIKARP!"
	.DB $57
_Route21Swimmer1BattleText::
	.DB $00
	.STRINGMAP pokemon, "The sea cleanses"
	.DB $4f
	.STRINGMAP pokemon, "my body and soul!"
	.DB $57
_Route21Swimmer1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ayah!"
	.DB $58
_Route21Swimmer1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I like the"
	.DB $4f
	.STRINGMAP pokemon, "mountains too!"
	.DB $57
_Route21Swimmer2BattleText::
	.DB $00
	.STRINGMAP pokemon, "What's wrong with"
	.DB $4f
	.STRINGMAP pokemon, "me swimming?"
	.DB $57
_Route21Swimmer2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Cheap"
	.DB $4f
	.STRINGMAP pokemon, "shot!"
	.DB $58
_Route21Swimmer2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I look like what?"
	.DB $4f
	.STRINGMAP pokemon, "A studded inner"
	.DB $55
	.STRINGMAP pokemon, "tube? Get lost!"
	.DB $57
_Route21Swimmer3BattleText::
	.DB $00
	.STRINGMAP pokemon, "I caught all my"
	.DB $4f
	.STRINGMAP pokemon, "#MON at sea!"
	.DB $57
_Route21Swimmer3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Diver!!"
	.DB $4f
	.STRINGMAP pokemon, "Down!!"
	.DB $58
_Route21Swimmer3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Where'd you catch"
	.DB $4f
	.STRINGMAP pokemon, "your #MON?"
	.DB $57
_Route21Swimmer4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Right now, I'm in"
	.DB $4f
	.STRINGMAP pokemon, "a triathlon meet!"
	.DB $57
_Route21Swimmer4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Pant..."
	.DB $4f
	.STRINGMAP pokemon, "pant...pant..."
	.DB $58
_Route21Swimmer4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm beat!"
	.DB $4f
	.STRINGMAP pokemon, "But, I still have"
	.DB $55
	.STRINGMAP pokemon, "the bike race and"
	.DB $55
	.STRINGMAP pokemon, "marathon left!"
	.DB $57
_Route21Swimmer5BattleText::
	.DB $00
	.STRINGMAP pokemon, "Ahh! Feel the sun"
	.DB $4f
	.STRINGMAP pokemon, "and the wind!"
	.DB $57
_Route21Swimmer5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Yow!"
	.DB $4f
	.STRINGMAP pokemon, "I lost!"
	.DB $58
_Route21Swimmer5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm sunburnt to a"
	.DB $4f
	.STRINGMAP pokemon, "crisp!"
	.DB $57
_Route21Fisher3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey, don't scare"
	.DB $4f
	.STRINGMAP pokemon, "away the fish!"
	.DB $57
_Route21Fisher3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Sorry!"
	.DB $4f
	.STRINGMAP pokemon, "I didn't mean it!"
	.DB $58
_Route21Fisher3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I was just angry"
	.DB $4f
	.STRINGMAP pokemon, "that I couldn't"
	.DB $55
	.STRINGMAP pokemon, "catch anything."
	.DB $57
_Route21Fisher4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Keep me company"
	.DB $4f
	.STRINGMAP pokemon, "'til I get a hit!"
	.DB $57
_Route21Fisher4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "That"
	.DB $4f
	.STRINGMAP pokemon, "burned some time."
	.DB $58
_Route21Fisher4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh wait! I got a"
	.DB $4f
	.STRINGMAP pokemon, "bite! Yeah!"
	.DB $57

; text/Route22.asm
_Route22RivalBeforeBattleText1::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Hey!"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "You're going to"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE?"
	.DB $51
	.STRINGMAP pokemon, "Forget it! You"
	.DB $4f
	.STRINGMAP pokemon, "probably don't"
	.DB $55
	.STRINGMAP pokemon, "have any BADGEs!"
	.DB $51
	.STRINGMAP pokemon, "The guard won't"
	.DB $4f
	.STRINGMAP pokemon, "let you through!"
	.DB $51
	.STRINGMAP pokemon, "By the way, did"
	.DB $4f
	.STRINGMAP pokemon, "your #MON"
	.DB $55
	.STRINGMAP pokemon, "get any stronger?"
	.DB $57
_Route22RivalAfterBattleText1::
	.DB $00
	.STRINGMAP pokemon, "I heard #MON"
	.DB $4f
	.STRINGMAP pokemon, "LEAGUE has many"
	.DB $55
	.STRINGMAP pokemon, "tough trainers!"
	.DB $51
	.STRINGMAP pokemon, "I have to figure"
	.DB $4f
	.STRINGMAP pokemon, "out how to get"
	.DB $55
	.STRINGMAP pokemon, "past them!"
	.DB $51
	.STRINGMAP pokemon, "You should quit"
	.DB $4f
	.STRINGMAP pokemon, "dawdling and get"
	.DB $55
	.STRINGMAP pokemon, "a move on!"
	.DB $57
_Route22Rival1DefeatedText::
	.DB $00
	.STRINGMAP pokemon, "Awww!"
	.DB $4f
	.STRINGMAP pokemon, "You just lucked"
	.DB $55
	.STRINGMAP pokemon, "out!"
	.DB $58
_Route22Rival1VictoryText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: What?"
	.DB $4f
	.STRINGMAP pokemon, "Why do I have 2"
	.DB $55
	.STRINGMAP pokemon, "#MON?"
	.DB $51
	.STRINGMAP pokemon, "You should catch"
	.DB $55
	.STRINGMAP pokemon, "some more too!"
	.DB $58
_Route22RivalBeforeBattleText2::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: What?"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>! What a"
	.DB $55
	.STRINGMAP pokemon, "surprise to see"
	.DB $55
	.STRINGMAP pokemon, "you here!"
	.DB $51
	.STRINGMAP pokemon, "So you're going to"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE?"
	.DB $51
	.STRINGMAP pokemon, "You collected all"
	.DB $4f
	.STRINGMAP pokemon, "the BADGEs too?"
	.DB $55
	.STRINGMAP pokemon, "That's cool!"
	.DB $51
	.STRINGMAP pokemon, "Then I'll whip you"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER> as a"
	.DB $55
	.STRINGMAP pokemon, "warm up for"
	.DB $55
	.STRINGMAP pokemon, "#MON LEAGUE!"
	.DB $51
	.STRINGMAP pokemon, "Come on!"
	.DB $57
_Route22RivalAfterBattleText2::
	.DB $00
	.STRINGMAP pokemon, "That loosened me"
	.DB $4f
	.STRINGMAP pokemon, "up! I'm ready for"
	.DB $55
	.STRINGMAP pokemon, "#MON LEAGUE!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>, you need"
	.DB $4f
	.STRINGMAP pokemon, "more practice!"
	.DB $51
	.STRINGMAP pokemon, "But hey, you know"
	.DB $4f
	.STRINGMAP pokemon, "that! I'm out of"
	.DB $55
	.STRINGMAP pokemon, "here. Smell ya!"
	.DB $57
_Route22Rival2DefeatedText::
	.DB $00
	.STRINGMAP pokemon, "What!?"
	.DB $51
	.STRINGMAP pokemon, "I was just"
	.DB $4f
	.STRINGMAP pokemon, "careless!"
	.DB $58
_Route22Rival2VictoryText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Hahaha!"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>! That's"
	.DB $55
	.STRINGMAP pokemon, "your best? You're"
	.DB $55
	.STRINGMAP pokemon, "nowhere near as"
	.DB $55
	.STRINGMAP pokemon, "good as me, pal!"
	.DB $51
	.STRINGMAP pokemon, "Go train some"
	.DB $4f
	.STRINGMAP pokemon, "more! You loser!"
	.DB $58
_Route22PokemonLeagueSignText::
	.DB $00
	.STRINGMAP pokemon, "#MON LEAGUE"
	.DB $4f
	.STRINGMAP pokemon, "Front Gate"
	.DB $57

; text/Route23.asm
_Route23YouDontHaveTheBadgeYetText::
	.DB $00
	.STRINGMAP pokemon, "You can pass here"
	.DB $4f
	.STRINGMAP pokemon, "only if you have"
	.DB $55
	.STRINGMAP pokemon, "the @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "You don't have the"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " yet!"
	.DB $51
	.STRINGMAP pokemon, "You have to have"
	.DB $4f
	.STRINGMAP pokemon, "it to get to"
	.DB $55
	.STRINGMAP pokemon, "#MON LEAGUE!@"
	.DB $50
_Route23OhThatIsTheBadgeText::
	.DB $00
	.STRINGMAP pokemon, "You can pass here"
	.DB $4f
	.STRINGMAP pokemon, "only if you have"
	.DB $55
	.STRINGMAP pokemon, "the @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "Oh! That is the"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_Route23GoRightAheadText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "OK then! Please,"
	.DB $4f
	.STRINGMAP pokemon, "go right ahead!"
	.DB $57
_Route23VictoryRoadGateSignText::
	.DB $00
	.STRINGMAP pokemon, "VICTORY ROAD GATE"
	.DB $4f
	.STRINGMAP pokemon, "- #MON LEAGUE"
	.DB $57

; text/Route24.asm
_Route24CooltrainerM1YouBeatOurContestText::
	.DB $00
	.STRINGMAP pokemon, "Congratulations!"
	.DB $4f
	.STRINGMAP pokemon, "You beat our 5"
	.DB $55
	.STRINGMAP pokemon, "contest trainers!@"
	.DB $50
_Route24CooltrainerM1YouJustEarnedAPrizeText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "You just earned a"
	.DB $4f
	.STRINGMAP pokemon, "fabulous prize!"
	.DB $58
_Route24CooltrainerM1ReceivedNuggetText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "a @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_Route24CooltrainerM1NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "any room!"
	.DB $57
_Route24CooltrainerM1JoinTeamRocketText::
	.DB $00
	.STRINGMAP pokemon, "By the way, would"
	.DB $4f
	.STRINGMAP pokemon, "you like to join"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET?"
	.DB $51
	.STRINGMAP pokemon, "We're a group"
	.DB $4f
	.STRINGMAP pokemon, "dedicated to evil"
	.DB $55
	.STRINGMAP pokemon, "using #MON!"
	.DB $51
	.STRINGMAP pokemon, "Want to join?"
	.DB $51
	.STRINGMAP pokemon, "Are you sure?"
	.DB $51
	.STRINGMAP pokemon, "Come on, join us!"
	.DB $51
	.STRINGMAP pokemon, "I'm telling you"
	.DB $4f
	.STRINGMAP pokemon, "to join!"
	.DB $51
	.STRINGMAP pokemon, "OK, you need"
	.DB $4f
	.STRINGMAP pokemon, "convincing!"
	.DB $51
	.STRINGMAP pokemon, "I'll make you an"
	.DB $4f
	.STRINGMAP pokemon, "offer you can't"
	.DB $55
	.STRINGMAP pokemon, "refuse!"
	.DB $57
_Route24CooltrainerM1DefeatedText::
	.DB $00
	.STRINGMAP pokemon, "Arrgh!"
	.DB $4f
	.STRINGMAP pokemon, "You are good!"
	.DB $58
_Route24CooltrainerM1YouCouldBecomeATopLeaderText::
	.DB $00
	.STRINGMAP pokemon, "With your ability,"
	.DB $4f
	.STRINGMAP pokemon, "you could become"
	.DB $55
	.STRINGMAP pokemon, "a top leader in"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET!"
	.DB $57
_Route24CooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I saw your feat"
	.DB $4f
	.STRINGMAP pokemon, "from the grass!"
	.DB $57

Bank36TextEnd::
