; Generated by convert_text_bank.py from:
;   text/Daycare_2.asm
;   text/UndergroundPathRoute6.asm
;   text/UndergroundPathRoute7.asm
;   text/UndergroundPathRoute7Copy.asm
;   text/UndergroundPathRoute8.asm
;   text/RockTunnelPokecenter.asm
;   text/RockTunnel1F.asm
;   text/PowerPlant.asm
;   text/Route11Gate1F.asm
;   text/Route11Gate2F.asm
;   text/DiglettsCaveRoute11.asm
;   text/Route12Gate1F.asm
;   text/Route12Gate2F.asm
;   text/Route12SuperRodHouse.asm
;   text/Route15Gate1F.asm
;   text/Route15Gate2F.asm
;   text/Route16Gate1F.asm
;   text/Route16Gate2F.asm
;   text/Route16FlyHouse.asm
;   text/Route18Gate1F.asm
;   text/Route18Gate2F.asm
;   text/Route22Gate.asm
;   text/VictoryRoad2F.asm
;   text/BillsHouse.asm
;   text/Route1.asm
;   text/Route2.asm
;   text/Route3.asm
;   text/Route4.asm
;   text/Route5.asm
;   text/Route6.asm
;   text/Route7.asm
;   text/Route8.asm
;   text/Route9.asm
;   text/Route10.asm
;   text/Route11.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; text/Daycare_2.asm
_DaycareGentlemanAllRightThenText::
	.DB $00
	.STRINGMAP pokemon, "All right then,"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $50
_DaycareGentlemanComeAgainText::
	.DB $00
	.STRINGMAP pokemon, "come again."
	.DB $57
_DaycareGentlemanNoRoomForMonText::
	.DB $00
	.STRINGMAP pokemon, "You have no room"
	.DB $4f
	.STRINGMAP pokemon, "for this #MON!"
	.DB $57
_DaycareGentlemanOnlyHaveOneMonText::
	.DB $00
	.STRINGMAP pokemon, "You only have one"
	.DB $4f
	.STRINGMAP pokemon, "#MON with you."
	.DB $57
_DaycareGentlemanCantAcceptMonWithHMText::
	.DB $00
	.STRINGMAP pokemon, "I can't accept a"
	.DB $4f
	.STRINGMAP pokemon, "#MON that"
	.DB $55
	.STRINGMAP pokemon, "knows an HM move."
	.DB $57
_DaycareGentlemanHeresYourMonText::
	.DB $00
	.STRINGMAP pokemon, "Thank you! Here's"
	.DB $4f
	.STRINGMAP pokemon, "your #MON!"
	.DB $58
_DaycareGentlemanNotEnoughMoneyText::
	.DB $00
	.STRINGMAP pokemon, "Hey, you don't"
	.DB $4f
	.STRINGMAP pokemon, "have enough ¥!"
	.DB $57

; text/UndergroundPathRoute6.asm
_UndergroundPathRoute6GirlText::
	.DB $00
	.STRINGMAP pokemon, "People often lose"
	.DB $4f
	.STRINGMAP pokemon, "things in that"
	.DB $55
	.STRINGMAP pokemon, "UNDERGROUND PATH."
	.DB $57

; text/UndergroundPathRoute7.asm
_UndergroundPathRoute7MiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "I heard a sleepy"
	.DB $4f
	.STRINGMAP pokemon, "#MON appeared"
	.DB $55
	.STRINGMAP pokemon, "near CELADON CITY."
	.DB $57

; text/UndergroundPathRoute7Copy.asm
_UndergroundPathRoute7CopyUnusedGirlText::
	.DB $00
	.STRINGMAP pokemon, "I want to shop at"
	.DB $4f
	.STRINGMAP pokemon, "the dept. store"
	.DB $55
	.STRINGMAP pokemon, "in CELADON but..."
	.DB $51
	.STRINGMAP pokemon, "There are so many"
	.DB $4f
	.STRINGMAP pokemon, "rough looking"
	.DB $55
	.STRINGMAP pokemon, "people there."
	.DB $57
_UndergroundPathRoute7CopyUnusedTeamRocketHadAHideoutText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET had a"
	.DB $4f
	.STRINGMAP pokemon, "secret hideout in"
	.DB $55
	.STRINGMAP pokemon, "CELADON CITY?"
	.DB $57
_UndergroundPathRoute7CopyUnusedMiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "You're here to"
	.DB $4f
	.STRINGMAP pokemon, "shop in CELADON?"
	.DB $51
	.STRINGMAP pokemon, "Just step outside"
	.DB $4f
	.STRINGMAP pokemon, "and head west!"
	.DB $57
_UndergroundPathRoute7CopyUnusedGoesUnderSaffronText::
	.DB $00
	.STRINGMAP pokemon, "The UNDERGROUND"
	.DB $4f
	.STRINGMAP pokemon, "PATH goes beneath"
	.DB $55
	.STRINGMAP pokemon, "SAFFRON and leads"
	.DB $55
	.STRINGMAP pokemon, "to LAVENDER."
	.DB $51
	.STRINGMAP pokemon, "If you're heading"
	.DB $4f
	.STRINGMAP pokemon, "to CERULEAN, go"
	.DB $55
	.STRINGMAP pokemon, "to the building"
	.DB $55
	.STRINGMAP pokemon, "across the road."
	.DB $57

; text/UndergroundPathRoute8.asm
_UndergroundPathRoute8GirlText::
	.DB $00
	.STRINGMAP pokemon, "The dept. store"
	.DB $4f
	.STRINGMAP pokemon, "in CELADON has a"
	.DB $55
	.STRINGMAP pokemon, "great selection!"
	.DB $57

; text/RockTunnelPokecenter.asm
_RockTunnelPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "The element types"
	.DB $4f
	.STRINGMAP pokemon, "of #MON make"
	.DB $55
	.STRINGMAP pokemon, "them stronger"
	.DB $55
	.STRINGMAP pokemon, "than some types"
	.DB $55
	.STRINGMAP pokemon, "and weaker than"
	.DB $55
	.STRINGMAP pokemon, "others!"
	.DB $57
_RockTunnelPokecenterFisherText::
	.DB $00
	.STRINGMAP pokemon, "I sold a useless"
	.DB $4f
	.STRINGMAP pokemon, "NUGGET for ¥5000!"
	.DB $57

; text/RockTunnel1F.asm
_RockTunnel1FHiker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "This tunnel goes"
	.DB $4f
	.STRINGMAP pokemon, "a long way, kid!"
	.DB $57
_RockTunnel1FHiker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Doh!"
	.DB $4f
	.STRINGMAP pokemon, "You win!"
	.DB $58
_RockTunnel1FHiker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Watch for ONIX!"
	.DB $4f
	.STRINGMAP pokemon, "It can put the"
	.DB $55
	.STRINGMAP pokemon, "squeeze on you!"
	.DB $57
_RockTunnel1FHiker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hmm. Maybe I'm"
	.DB $4f
	.STRINGMAP pokemon, "lost in here..."
	.DB $57
_RockTunnel1FHiker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ease up!"
	.DB $4f
	.STRINGMAP pokemon, "What am I doing?"
	.DB $55
	.STRINGMAP pokemon, "Which way is out?"
	.DB $58
_RockTunnel1FHiker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "That sleeping"
	.DB $4f
	.STRINGMAP pokemon, "#MON on ROUTE"
	.DB $55
	.STRINGMAP pokemon, "12 forced me to"
	.DB $55
	.STRINGMAP pokemon, "take this detour."
	.DB $57
_RockTunnel1FHiker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Outsiders like"
	.DB $4f
	.STRINGMAP pokemon, "you need to show"
	.DB $55
	.STRINGMAP pokemon, "me some respect!"
	.DB $57
_RockTunnel1FHiker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I give!"
	.DB $58
_RockTunnel1FHiker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're talented"
	.DB $4f
	.STRINGMAP pokemon, "enough to hike!"
	.DB $57
_RockTunnel1FSuperNerdBattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON fight!"
	.DB $4f
	.STRINGMAP pokemon, "Ready, go!"
	.DB $57
_RockTunnel1FSuperNerdEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Game"
	.DB $4f
	.STRINGMAP pokemon, "over!"
	.DB $58
_RockTunnel1FSuperNerdAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh well, I'll get"
	.DB $4f
	.STRINGMAP pokemon, "a ZUBAT as I go!"
	.DB $57
_RockTunnel1FCooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Eek! Don't try"
	.DB $4f
	.STRINGMAP pokemon, "anything funny in"
	.DB $55
	.STRINGMAP pokemon, "the dark!"
	.DB $57
_RockTunnel1FCooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "It"
	.DB $4f
	.STRINGMAP pokemon, "was too dark!"
	.DB $58
_RockTunnel1FCooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I saw a MACHOP"
	.DB $4f
	.STRINGMAP pokemon, "in this tunnel!"
	.DB $57
_RockTunnel1FCooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I came this far"
	.DB $4f
	.STRINGMAP pokemon, "for #MON!"
	.DB $57
_RockTunnel1FCooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "out of #MON!"
	.DB $58
_RockTunnel1FCooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You looked cute"
	.DB $4f
	.STRINGMAP pokemon, "and harmless!"
	.DB $57
_RockTunnel1FCooltrainerF3BattleText::
	.DB $00
	.STRINGMAP pokemon, "You have #MON!"
	.DB $4f
	.STRINGMAP pokemon, "Let's start!"
	.DB $57
_RockTunnel1FCooltrainerF3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "play hard!"
	.DB $58
_RockTunnel1FCooltrainerF3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whew! I'm all"
	.DB $4f
	.STRINGMAP pokemon, "sweaty now!"
	.DB $57
_RockTunnel1FSignText::
	.DB $00
	.STRINGMAP pokemon, "ROCK TUNNEL"
	.DB $4f
	.STRINGMAP pokemon, "CERULEAN CITY -"
	.DB $55
	.STRINGMAP pokemon, "LAVENDER TOWN"
	.DB $57

; text/PowerPlant.asm
_PowerPlantVoltorbBattleText::
	.DB $00
	.STRINGMAP pokemon, "Bzzzt!"
	.DB $57
_PowerPlantZapdosBattleText::
	.DB $00
	.STRINGMAP pokemon, "Gyaoo!@"
	.DB $50

; text/Route11Gate1F.asm
_Route11Gate1FGuardText::
	.DB $00
	.STRINGMAP pokemon, "When you catch"
	.DB $4f
	.STRINGMAP pokemon, "lots of #MON,"
	.DB $55
	.STRINGMAP pokemon, "isn't it hard to"
	.DB $55
	.STRINGMAP pokemon, "think up names?"
	.DB $51
	.STRINGMAP pokemon, "In LAVENDER TOWN,"
	.DB $4f
	.STRINGMAP pokemon, "there's a man who"
	.DB $55
	.STRINGMAP pokemon, "rates #MON"
	.DB $55
	.STRINGMAP pokemon, "nicknames."
	.DB $51
	.STRINGMAP pokemon, "He'll help you"
	.DB $4f
	.STRINGMAP pokemon, "rename them too!"
	.DB $57

; text/Route11Gate2F.asm
_Route11Gate2FOaksAideItemfinderDescriptionText::
	.DB $00
	.STRINGMAP pokemon, "There are items on"
	.DB $4f
	.STRINGMAP pokemon, "the ground that"
	.DB $55
	.STRINGMAP pokemon, "can't be seen."
	.DB $51
	.STRINGMAP pokemon, "ITEMFINDER will"
	.DB $4f
	.STRINGMAP pokemon, "detect an item"
	.DB $55
	.STRINGMAP pokemon, "close to you."
	.DB $51
	.STRINGMAP pokemon, "It can't pinpoint"
	.DB $4f
	.STRINGMAP pokemon, "it, so you have"
	.DB $55
	.STRINGMAP pokemon, "to look yourself!"
	.DB $57
_Route11Gate2FLeftBinocularsSnorlaxText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "A big #MON is"
	.DB $4f
	.STRINGMAP pokemon, "asleep on a road!"
	.DB $57
_Route11Gate2FLeftBinocularsNoSnorlaxText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "It's a beautiful"
	.DB $4f
	.STRINGMAP pokemon, "view!"
	.DB $57
_Route11Gate2FRightBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "The only way to"
	.DB $4f
	.STRINGMAP pokemon, "get from CERULEAN"
	.DB $55
	.STRINGMAP pokemon, "CITY to LAVENDER"
	.DB $55
	.STRINGMAP pokemon, "is by way of the"
	.DB $55
	.STRINGMAP pokemon, "ROCK TUNNEL."
	.DB $57

; text/DiglettsCaveRoute11.asm
_DiglettsCaveRoute11GamblerText::
	.DB $00
	.STRINGMAP pokemon, "What a surprise!"
	.DB $4f
	.STRINGMAP pokemon, "DIGLETTs dug this"
	.DB $55
	.STRINGMAP pokemon, "long tunnel!"
	.DB $51
	.STRINGMAP pokemon, "It goes right to"
	.DB $4f
	.STRINGMAP pokemon, "VIRIDIAN CITY!"
	.DB $57

; text/Route12Gate1F.asm
_Route12Gate1FGuardText::
	.DB $00
	.STRINGMAP pokemon, "There's a lookout"
	.DB $4f
	.STRINGMAP pokemon, "spot upstairs."
	.DB $57

; text/Route12Gate2F.asm
_Route12Gate2FBrunetteGirlYouCanHaveThisText::
	.DB $00
	.STRINGMAP pokemon, "My #MON's"
	.DB $4f
	.STRINGMAP pokemon, "ashes are stored"
	.DB $55
	.STRINGMAP pokemon, "in #MON TOWER."
	.DB $51
	.STRINGMAP pokemon, "You can have this"
	.DB $4f
	.STRINGMAP pokemon, "TM. I don't need"
	.DB $55
	.STRINGMAP pokemon, "it any more..."
	.DB $58
_Route12Gate2FBrunetteGirlReceivedTM39Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "TM39!@"
	.DB $50
_Route12Gate2FBrunetteGirlTM39ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "TM39 is a move"
	.DB $4f
	.STRINGMAP pokemon, "called SWIFT."
	.DB $51
	.STRINGMAP pokemon, "It's very accurate,"
	.DB $4f
	.STRINGMAP pokemon, "so use it during"
	.DB $55
	.STRINGMAP pokemon, "battles you can't"
	.DB $55
	.STRINGMAP pokemon, "afford to lose."
	.DB $57
_Route12Gate2FBrunetteGirlTM39NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "room for this."
	.DB $57
_Route12Gate2FLeftBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "A man fishing!"
	.DB $57
_Route12Gate2FRightBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "It's #MON TOWER!"
	.DB $57

; text/Route12SuperRodHouse.asm
_Route12SuperRodHouseFishingGuruDoYouLikeToFishText::
	.DB $00
	.STRINGMAP pokemon, "I'm the FISHING"
	.DB $4f
	.STRINGMAP pokemon, "GURU's brother!"
	.DB $51
	.STRINGMAP pokemon, "I simply Looove"
	.DB $4f
	.STRINGMAP pokemon, "fishing!"
	.DB $51
	.STRINGMAP pokemon, "Do you like to"
	.DB $4f
	.STRINGMAP pokemon, "fish?"
	.DB $57
_Route12SuperRodHouseFishingGuruReceivedSuperRodText::
	.DB $00
	.STRINGMAP pokemon, "Grand! I like"
	.DB $4f
	.STRINGMAP pokemon, "your style!"
	.DB $51
	.STRINGMAP pokemon, "Take this and"
	.DB $4f
	.STRINGMAP pokemon, "fish, young one!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "a @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_Route12SuperRodHouseFishingGuruFishingWayOfLifeText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "Fishing is a way"
	.DB $4f
	.STRINGMAP pokemon, "of life!"
	.DB $51
	.STRINGMAP pokemon, "From the seas to"
	.DB $4f
	.STRINGMAP pokemon, "rivers, go out"
	.DB $55
	.STRINGMAP pokemon, "and land the big"
	.DB $55
	.STRINGMAP pokemon, "one!"
	.DB $57
_Route12SuperRodHouseFishingGuruThatsDisappointingText::
	.DB $00
	.STRINGMAP pokemon, "Oh... That's so"
	.DB $4f
	.STRINGMAP pokemon, "disappointing..."
	.DB $57
_Route12SuperRodHouseFishingGuruTryFishingText::
	.DB $00
	.STRINGMAP pokemon, "Hello there,"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "Use the SUPER ROD"
	.DB $4f
	.STRINGMAP pokemon, "in any water!"
	.DB $55
	.STRINGMAP pokemon, "You can catch"
	.DB $55
	.STRINGMAP pokemon, "different kinds"
	.DB $55
	.STRINGMAP pokemon, "of #MON."
	.DB $51
	.STRINGMAP pokemon, "Try fishing"
	.DB $4f
	.STRINGMAP pokemon, "wherever you can!"
	.DB $57
_Route12SuperRodHouseFishingGuruNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "Oh no!"
	.DB $51
	.STRINGMAP pokemon, "I had a gift for"
	.DB $4f
	.STRINGMAP pokemon, "you, but you have"
	.DB $55
	.STRINGMAP pokemon, "no room for it!"
	.DB $57

; text/Route15Gate1F.asm
_Route15Gate1FGuardText::
	.DB $00
	.STRINGMAP pokemon, "Are you working"
	.DB $4f
	.STRINGMAP pokemon, "on a #DEX?"
	.DB $51
	.STRINGMAP pokemon, "PROF.OAK's AIDE"
	.DB $4f
	.STRINGMAP pokemon, "came by here."
	.DB $57

; text/Route15Gate2F.asm
_Route15Gate2FOaksAideExpAllText::
	.DB $00
	.STRINGMAP pokemon, "EXP.ALL gives"
	.DB $4f
	.STRINGMAP pokemon, "EXP points to all"
	.DB $55
	.STRINGMAP pokemon, "the #MON with"
	.DB $55
	.STRINGMAP pokemon, "you, even if they"
	.DB $55
	.STRINGMAP pokemon, "don't fight."
	.DB $51
	.STRINGMAP pokemon, "It does, however,"
	.DB $4f
	.STRINGMAP pokemon, "reduce the amount"
	.DB $55
	.STRINGMAP pokemon, "of EXP for each"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $51
	.STRINGMAP pokemon, "If you don't need"
	.DB $4f
	.STRINGMAP pokemon, "it, you should "
	.DB $55
	.STRINGMAP pokemon, "store it via PC."
	.DB $57
_Route15Gate2FBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "It looks like a"
	.DB $4f
	.STRINGMAP pokemon, "small island!"
	.DB $57

; text/Route16Gate1F.asm
_Route16Gate1FGuardNoPedestriansAllowedText::
	.DB $00
	.STRINGMAP pokemon, "No pedestrians"
	.DB $4f
	.STRINGMAP pokemon, "are allowed on"
	.DB $55
	.STRINGMAP pokemon, "CYCLING ROAD!"
	.DB $57
_Route16Gate1FGuardCyclingRoadExplanationText::
	.DB $00
	.STRINGMAP pokemon, "CYCLING ROAD is a"
	.DB $4f
	.STRINGMAP pokemon, "downhill course"
	.DB $55
	.STRINGMAP pokemon, "by the sea. It's"
	.DB $55
	.STRINGMAP pokemon, "a great ride."
	.DB $57
_Route16Gate1FGuardWaitUpText::
	.DB $00
	.STRINGMAP pokemon, "Excuse me! Wait"
	.DB $4f
	.STRINGMAP pokemon, "up please!"
	.DB $57
_Route16Gate1FGamblerText::
	.DB $00
	.STRINGMAP pokemon, "How'd you get in?"
	.DB $4f
	.STRINGMAP pokemon, "Good effort!"
	.DB $57

; text/Route16Gate2F.asm
_Route16Gate2FLittleBoyText::
	.DB $00
	.STRINGMAP pokemon, "I'm going for a"
	.DB $4f
	.STRINGMAP pokemon, "ride with my girl"
	.DB $55
	.STRINGMAP pokemon, "friend!"
	.DB $57
_Route16Gate2FLittleGirlText::
	.DB $00
	.STRINGMAP pokemon, "We're going"
	.DB $4f
	.STRINGMAP pokemon, "riding together!"
	.DB $57
_Route16Gate2FLeftBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "It's CELADON DEPT."
	.DB $4f
	.STRINGMAP pokemon, "STORE!"
	.DB $57
_Route16Gate2FRightBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "There's a long"
	.DB $4f
	.STRINGMAP pokemon, "path over water!"
	.DB $57

; text/Route16FlyHouse.asm
_Route16FlyHouseBrunetteGirlText::
	.DB $00
	.STRINGMAP pokemon, "Oh, you found my"
	.DB $4f
	.STRINGMAP pokemon, "secret retreat!"
	.DB $51
	.STRINGMAP pokemon, "Please don't tell"
	.DB $4f
	.STRINGMAP pokemon, "anyone I'm here."
	.DB $55
	.STRINGMAP pokemon, "I'll make it up"
	.DB $55
	.STRINGMAP pokemon, "to you with this!"
	.DB $58
_Route16FlyHouseBrunetteGirlReceivedHM02Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "HM02!@"
	.DB $50
_Route16FlyHouseBrunetteGirlHM02ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "HM02 is FLY."
	.DB $4f
	.STRINGMAP pokemon, "It will take you"
	.DB $55
	.STRINGMAP pokemon, "back to any town."
	.DB $51
	.STRINGMAP pokemon, "Put it to good"
	.DB $4f
	.STRINGMAP pokemon, "use!"
	.DB $57
_Route16FlyHouseBrunetteGirlHM02NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You don't have any"
	.DB $4f
	.STRINGMAP pokemon, "room for this."
	.DB $57
_Route16FlyHouseFearowText::
	.DB $00
	.STRINGMAP pokemon, "FEAROW: Kyueen!"
	.DB $57

; text/Route18Gate1F.asm
_Route18Gate1FGuardYouNeedABicycleText::
	.DB $00
	.STRINGMAP pokemon, "You need a BICYCLE"
	.DB $4f
	.STRINGMAP pokemon, "for CYCLING ROAD!"
	.DB $57
_Route18Gate1FGuardCyclingRoadUphillText::
	.DB $00
	.STRINGMAP pokemon, "CYCLING ROAD is"
	.DB $4f
	.STRINGMAP pokemon, "all uphill from"
	.DB $55
	.STRINGMAP pokemon, "here."
	.DB $57
_Route18Gate1FGuardExcuseMeText::
	.DB $00
	.STRINGMAP pokemon, "Excuse me!"
	.DB $57

; text/Route18Gate2F.asm
_Route18Gate2FLeftBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "PALLET TOWN is in"
	.DB $4f
	.STRINGMAP pokemon, "the west!"
	.DB $57
_Route18Gate2FRightBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars."
	.DB $51
	.STRINGMAP pokemon, "There are people"
	.DB $4f
	.STRINGMAP pokemon, "swimming!"
	.DB $57

; text/Route22Gate.asm
_Route22GateGuardNoBoulderbadgeText::
	.DB $00
	.STRINGMAP pokemon, "Only truly skilled"
	.DB $4f
	.STRINGMAP pokemon, "trainers are"
	.DB $55
	.STRINGMAP pokemon, "allowed through."
	.DB $51
	.STRINGMAP pokemon, "You don't have the"
	.DB $4f
	.STRINGMAP pokemon, "BOULDERBADGE yet!@"
	.DB $50
_Route22GateGuardICantLetYouPassText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "The rules are"
	.DB $4f
	.STRINGMAP pokemon, "rules. I can't"
	.DB $55
	.STRINGMAP pokemon, "let you pass."
	.DB $57
_Route22GateGuardGoRightAheadText::
	.DB $00
	.STRINGMAP pokemon, "Oh! That is the"
	.DB $4f
	.STRINGMAP pokemon, "BOULDERBADGE!"
	.DB $55
	.STRINGMAP pokemon, "Go right ahead!@"
	.DB $50

; text/VictoryRoad2F.asm
_VictoryRoad2FMoltresBattleText::
	.DB $00
	.STRINGMAP pokemon, "Gyaoo!@"
	.DB $50
_VictoryRoad2FHikerBattleText::
	.DB $00
	.STRINGMAP pokemon, "VICTORY ROAD is"
	.DB $4f
	.STRINGMAP pokemon, "the final test"
	.DB $55
	.STRINGMAP pokemon, "for trainers!"
	.DB $57
_VictoryRoad2FHikerEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Aiyah!"
	.DB $58
_VictoryRoad2FHikerAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If you get stuck,"
	.DB $4f
	.STRINGMAP pokemon, "try moving some"
	.DB $55
	.STRINGMAP pokemon, "boulders around!"
	.DB $57
_VictoryRoad2FSuperNerd1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Ah, so you wish"
	.DB $4f
	.STRINGMAP pokemon, "to challenge the"
	.DB $55
	.STRINGMAP pokemon, "ELITE FOUR?"
	.DB $57
_VictoryRoad2FSuperNerd1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "got me!"
	.DB $58
_VictoryRoad2FSuperNerd1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL> also came"
	.DB $4f
	.STRINGMAP pokemon, "through here!"
	.DB $57
_VictoryRoad2FCooltrainerMBattleText::
	.DB $00
	.STRINGMAP pokemon, "Come on!"
	.DB $4f
	.STRINGMAP pokemon, "I'll whip you!"
	.DB $57
_VictoryRoad2FCooltrainerMEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I got"
	.DB $4f
	.STRINGMAP pokemon, "whipped!"
	.DB $58
_VictoryRoad2FCooltrainerMAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You earned the"
	.DB $4f
	.STRINGMAP pokemon, "right to be on"
	.DB $55
	.STRINGMAP pokemon, "VICTORY ROAD!"
	.DB $57
_VictoryRoad2FSuperNerd2BattleText::
	.DB $00
	.STRINGMAP pokemon, "If you can get"
	.DB $4f
	.STRINGMAP pokemon, "through here, you"
	.DB $55
	.STRINGMAP pokemon, "can go meet the"
	.DB $55
	.STRINGMAP pokemon, "ELITE FOUR!"
	.DB $57
_VictoryRoad2FSuperNerd2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "No!"
	.DB $4f
	.STRINGMAP pokemon, "Unbelievable!"
	.DB $58
_VictoryRoad2FSuperNerd2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I can beat you"
	.DB $4f
	.STRINGMAP pokemon, "when it comes to"
	.DB $55
	.STRINGMAP pokemon, "knowledge about"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_VictoryRoad2FSuperNerd3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Is VICTORY ROAD"
	.DB $4f
	.STRINGMAP pokemon, "too tough?"
	.DB $57
_VictoryRoad2FSuperNerd3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Well"
	.DB $4f
	.STRINGMAP pokemon, "done!"
	.DB $58
_VictoryRoad2FSuperNerd3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Many trainers give"
	.DB $4f
	.STRINGMAP pokemon, "up the challenge"
	.DB $55
	.STRINGMAP pokemon, "here."
	.DB $57

; text/BillsHouse.asm
_BillsHouseBillImNotAPokemonText::
	.DB $00
	.STRINGMAP pokemon, "Hiya! I'm a"
	.DB $4f
	.STRINGMAP pokemon, "#MON..."
	.DB $55
	.STRINGMAP pokemon, "...No I'm not!"
	.DB $51
	.STRINGMAP pokemon, "Call me BILL!"
	.DB $4f
	.STRINGMAP pokemon, "I'm a true blue"
	.DB $55
	.STRINGMAP pokemon, "#MANIAC! Hey!"
	.DB $55
	.STRINGMAP pokemon, "What's with that"
	.DB $55
	.STRINGMAP pokemon, "skeptical look?"
	.DB $51
	.STRINGMAP pokemon, "I'm not joshing"
	.DB $4f
	.STRINGMAP pokemon, "you, I screwed up"
	.DB $55
	.STRINGMAP pokemon, "an experiment and"
	.DB $55
	.STRINGMAP pokemon, "got combined with"
	.DB $55
	.STRINGMAP pokemon, "a #MON!"
	.DB $51
	.STRINGMAP pokemon, "So, how about it?"
	.DB $4f
	.STRINGMAP pokemon, "Help me out here!"
	.DB $57
_BillsHouseBillUseSeparationSystemText::
	.DB $00
	.STRINGMAP pokemon, "When I'm in the"
	.DB $4f
	.STRINGMAP pokemon, "TELEPORTER, go to"
	.DB $55
	.STRINGMAP pokemon, "my PC and run the"
	.DB $55
	.STRINGMAP pokemon, "Cell Separation"
	.DB $55
	.STRINGMAP pokemon, "System!"
	.DB $57
_BillsHouseBillNoYouGottaHelpText::
	.DB $00
	.STRINGMAP pokemon, "No!? Come on, you"
	.DB $4f
	.STRINGMAP pokemon, "gotta help a guy"
	.DB $55
	.STRINGMAP pokemon, "in deep trouble!"
	.DB $51
	.STRINGMAP pokemon, "What do you say,"
	.DB $4f
	.STRINGMAP pokemon, "chief? Please?"
	.DB $55
	.STRINGMAP pokemon, "OK? All right!"
	.DB $58
_BillsHouseBillThankYouText::
	.DB $00
	.STRINGMAP pokemon, "BILL: Yeehah!"
	.DB $4f
	.STRINGMAP pokemon, "Thanks, bud! I"
	.DB $55
	.STRINGMAP pokemon, "owe you one!"
	.DB $51
	.STRINGMAP pokemon, "So, did you come"
	.DB $4f
	.STRINGMAP pokemon, "to see my #MON"
	.DB $55
	.STRINGMAP pokemon, "collection?"
	.DB $55
	.STRINGMAP pokemon, "You didn't?"
	.DB $55
	.STRINGMAP pokemon, "That's a bummer."
	.DB $51
	.STRINGMAP pokemon, "I've got to thank"
	.DB $4f
	.STRINGMAP pokemon, "you... Oh here,"
	.DB $55
	.STRINGMAP pokemon, "maybe this'll do."
	.DB $58
_SSTicketReceivedText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "an @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_SSTicketNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You've got too"
	.DB $4f
	.STRINGMAP pokemon, "much stuff, bud!"
	.DB $57
_BillsHouseBillWhyDontYouGoInsteadOfMeText::
	.DB $00
	.STRINGMAP pokemon, "That cruise ship,"
	.DB $4f
	.STRINGMAP pokemon, "S.S.ANNE, is in"
	.DB $55
	.STRINGMAP pokemon, "VERMILION CITY."
	.DB $55
	.STRINGMAP pokemon, "Its passengers"
	.DB $55
	.STRINGMAP pokemon, "are all trainers!"
	.DB $51
	.STRINGMAP pokemon, "They invited me"
	.DB $4f
	.STRINGMAP pokemon, "to their party,"
	.DB $55
	.STRINGMAP pokemon, "but I can't stand"
	.DB $55
	.STRINGMAP pokemon, "fancy do's. Why"
	.DB $55
	.STRINGMAP pokemon, "don't you go"
	.DB $55
	.STRINGMAP pokemon, "instead of me?"
	.DB $57
_BillsHouseBillCheckOutMyRarePokemonText::
	.DB $00
	.STRINGMAP pokemon, "BILL: Look, bud,"
	.DB $4f
	.STRINGMAP pokemon, "just check out"
	.DB $55
	.STRINGMAP pokemon, "some of my rare"
	.DB $55
	.STRINGMAP pokemon, "#MON on my PC!"
	.DB $57

; text/Route1.asm
_Route1Youngster1MartSampleText::
	.DB $00
	.STRINGMAP pokemon, "Hi! I work at a"
	.DB $4f
	.STRINGMAP pokemon, "#MON MART."
	.DB $51
	.STRINGMAP pokemon, "It's a convenient"
	.DB $4f
	.STRINGMAP pokemon, "shop, so please"
	.DB $55
	.STRINGMAP pokemon, "visit us in"
	.DB $55
	.STRINGMAP pokemon, "VIRIDIAN CITY."
	.DB $51
	.STRINGMAP pokemon, "I know, I'll give"
	.DB $4f
	.STRINGMAP pokemon, "you a sample!"
	.DB $55
	.STRINGMAP pokemon, "Here you go!"
	.DB $58
_Route1Youngster1GotPotionText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_Route1Youngster1AlsoGotPokeballsText::
	.DB $00
	.STRINGMAP pokemon, "We also carry"
	.DB $4f
	.STRINGMAP pokemon, "# BALLs for"
	.DB $55
	.STRINGMAP pokemon, "catching #MON!"
	.DB $57
_Route1Youngster1NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You have too much"
	.DB $4f
	.STRINGMAP pokemon, "stuff with you!"
	.DB $57
_Route1Youngster2Text::
	.DB $00
	.STRINGMAP pokemon, "See those ledges"
	.DB $4f
	.STRINGMAP pokemon, "along the road?"
	.DB $51
	.STRINGMAP pokemon, "It's a bit scary,"
	.DB $4f
	.STRINGMAP pokemon, "but you can jump"
	.DB $55
	.STRINGMAP pokemon, "from them."
	.DB $51
	.STRINGMAP pokemon, "You can get back"
	.DB $4f
	.STRINGMAP pokemon, "to PALLET TOWN"
	.DB $55
	.STRINGMAP pokemon, "quicker that way."
	.DB $57
_Route1SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 1"
	.DB $4f
	.STRINGMAP pokemon, "PALLET TOWN -"
	.DB $55
	.STRINGMAP pokemon, "VIRIDIAN CITY"
	.DB $57

; text/Route2.asm
_Route2SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 2"
	.DB $4f
	.STRINGMAP pokemon, "VIRIDIAN CITY -"
	.DB $55
	.STRINGMAP pokemon, "PEWTER CITY"
	.DB $57
_Route2DiglettsCaveSignText::
	.DB $00
	.STRINGMAP pokemon, "DIGLETT's CAVE"
	.DB $57

; text/Route3.asm
_Route3Text1::
	.DB $00
	.STRINGMAP pokemon, "Whew... I better"
	.DB $4f
	.STRINGMAP pokemon, "take a rest..."
	.DB $55
	.STRINGMAP pokemon, "Groan..."
	.DB $51
	.STRINGMAP pokemon, "That tunnel from"
	.DB $4f
	.STRINGMAP pokemon, "CERULEAN takes a"
	.DB $55
	.STRINGMAP pokemon, "lot out of you!"
	.DB $57
_Route3Youngster1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey! I met you in"
	.DB $4f
	.STRINGMAP pokemon, "VIRIDIAN FOREST!"
	.DB $57
_Route3Youngster1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "beat me again!"
	.DB $58
_Route3Youngster1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "There are other"
	.DB $4f
	.STRINGMAP pokemon, "kinds of #MON"
	.DB $55
	.STRINGMAP pokemon, "than those found"
	.DB $55
	.STRINGMAP pokemon, "in the forest!"
	.DB $57
_Route3Youngster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hi! I like shorts!"
	.DB $4f
	.STRINGMAP pokemon, "They're comfy and"
	.DB $55
	.STRINGMAP pokemon, "easy to wear!"
	.DB $57
_Route3Youngster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I don't"
	.DB $4f
	.STRINGMAP pokemon, "believe it!"
	.DB $58
_Route3Youngster2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you storing"
	.DB $4f
	.STRINGMAP pokemon, "your #MON on"
	.DB $55
	.STRINGMAP pokemon, "PC? Each BOX can"
	.DB $55
	.STRINGMAP pokemon, "hold 20 #MON!"
	.DB $57
_Route3CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "You looked at me,"
	.DB $4f
	.STRINGMAP pokemon, "didn't you?"
	.DB $57
_Route3CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're"
	.DB $4f
	.STRINGMAP pokemon, "mean!"
	.DB $58
_Route3CooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Quit staring if"
	.DB $4f
	.STRINGMAP pokemon, "you don't want to"
	.DB $55
	.STRINGMAP pokemon, "fight!"
	.DB $57
_Route3Youngster3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you a trainer?"
	.DB $4f
	.STRINGMAP pokemon, "Let's fight!"
	.DB $57
_Route3Youngster3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "If I"
	.DB $4f
	.STRINGMAP pokemon, "had new #MON I"
	.DB $55
	.STRINGMAP pokemon, "would've won!"
	.DB $58
_Route3Youngster3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If a #MON BOX"
	.DB $4f
	.STRINGMAP pokemon, "on the PC gets"
	.DB $55
	.STRINGMAP pokemon, "full, just switch"
	.DB $55
	.STRINGMAP pokemon, "to another BOX!"
	.DB $57
_Route3CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "That look you"
	.DB $4f
	.STRINGMAP pokemon, "gave me, it's so"
	.DB $55
	.STRINGMAP pokemon, "intriguing!"
	.DB $57
_Route3CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Be nice!"
	.DB $58
_Route3CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Avoid fights by"
	.DB $4f
	.STRINGMAP pokemon, "not letting"
	.DB $55
	.STRINGMAP pokemon, "people see you!"
	.DB $57
_Route3Youngster4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey! You're not"
	.DB $4f
	.STRINGMAP pokemon, "wearing shorts!"
	.DB $57
_Route3Youngster4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Lost!"
	.DB $4f
	.STRINGMAP pokemon, "Lost! Lost!"
	.DB $58
_Route3Youngster4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I always wear"
	.DB $4f
	.STRINGMAP pokemon, "shorts, even in"
	.DB $55
	.STRINGMAP pokemon, "winter!"
	.DB $57
_Route3Youngster5BattleText::
	.DB $00
	.STRINGMAP pokemon, "You can fight my"
	.DB $4f
	.STRINGMAP pokemon, "new #MON!"
	.DB $57
_Route3Youngster5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Done"
	.DB $4f
	.STRINGMAP pokemon, "like dinner!"
	.DB $58
_Route3Youngster5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Trained #MON"
	.DB $4f
	.STRINGMAP pokemon, "are stronger than"
	.DB $55
	.STRINGMAP pokemon, "the wild ones!"
	.DB $57
_Route3CooltrainerF3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Eek! Did you"
	.DB $4f
	.STRINGMAP pokemon, "touch me?"
	.DB $57
_Route3CooltrainerF3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "That's it?"
	.DB $58
_Route3CooltrainerF3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 4 is at the"
	.DB $4f
	.STRINGMAP pokemon, "foot of MT.MOON."
	.DB $57
_Route3SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 3"
	.DB $4f
	.STRINGMAP pokemon, "MT.MOON AHEAD"
	.DB $57

; text/Route4.asm
_Route4CooltrainerF1Text::
	.DB $00
	.STRINGMAP pokemon, "Ouch! I tripped"
	.DB $4f
	.STRINGMAP pokemon, "over a rocky"
	.DB $55
	.STRINGMAP pokemon, "#MON, GEODUDE!"
	.DB $57
_Route4CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I came to get my"
	.DB $4f
	.STRINGMAP pokemon, "mushroom #MON!"
	.DB $57
_Route4CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh! My cute"
	.DB $4f
	.STRINGMAP pokemon, "mushroom #MON!"
	.DB $58
_Route4CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "There might not"
	.DB $4f
	.STRINGMAP pokemon, "be any more"
	.DB $55
	.STRINGMAP pokemon, "mushrooms here."
	.DB $51
	.STRINGMAP pokemon, "I think I got"
	.DB $4f
	.STRINGMAP pokemon, "them all."
	.DB $57
_Route4MtMoonSignText::
	.DB $00
	.STRINGMAP pokemon, "MT.MOON"
	.DB $4f
	.STRINGMAP pokemon, "Tunnel Entrance"
	.DB $57
_Route4SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 4"
	.DB $4f
	.STRINGMAP pokemon, "MT.MOON -"
	.DB $55
	.STRINGMAP pokemon, "CERULEAN CITY"
	.DB $57

; text/Route5.asm
_Route5UndergroundPathSignText::
	.DB $00
	.STRINGMAP pokemon, "UNDERGROUND PATH"
	.DB $4f
	.STRINGMAP pokemon, "CERULEAN CITY -"
	.DB $55
	.STRINGMAP pokemon, "VERMILION CITY"
	.DB $57

; text/Route6.asm
_Route6CooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Who's there?"
	.DB $4f
	.STRINGMAP pokemon, "Quit listening in"
	.DB $55
	.STRINGMAP pokemon, "on us!"
	.DB $57
_Route6CooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "just can't win!"
	.DB $58
_Route6CooltrainerAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whisper..."
	.DB $4f
	.STRINGMAP pokemon, "whisper..."
	.DB $57
_Route6CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Excuse me! This"
	.DB $4f
	.STRINGMAP pokemon, "is a private"
	.DB $55
	.STRINGMAP pokemon, "conversation!"
	.DB $57
_Route6CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ugh!"
	.DB $4f
	.STRINGMAP pokemon, "I hate losing!"
	.DB $58
_Route6Youngster1BattleText::
	.DB $00
	.STRINGMAP pokemon, "There aren't many"
	.DB $4f
	.STRINGMAP pokemon, "bugs out here."
	.DB $57
_Route6Youngster1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "No!"
	.DB $4f
	.STRINGMAP pokemon, "You're kidding!"
	.DB $58
_Route6Youngster1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I like bugs, so"
	.DB $4f
	.STRINGMAP pokemon, "I'm going back to"
	.DB $55
	.STRINGMAP pokemon, "VIRIDIAN FOREST."
	.DB $57
_Route6CooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Huh? You want"
	.DB $4f
	.STRINGMAP pokemon, "to talk to me?"
	.DB $57
_Route6CooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "didn't start it!"
	.DB $58
_Route6CooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I should carry"
	.DB $4f
	.STRINGMAP pokemon, "more #MON with"
	.DB $55
	.STRINGMAP pokemon, "me for safety."
	.DB $57
_Route6CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Me? Well, OK."
	.DB $4f
	.STRINGMAP pokemon, "I'll play!"
	.DB $57
_Route6CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Just"
	.DB $4f
	.STRINGMAP pokemon, "didn't work!"
	.DB $58
_Route6CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I want to get"
	.DB $4f
	.STRINGMAP pokemon, "stronger! What's"
	.DB $55
	.STRINGMAP pokemon, "your secret?"
	.DB $57
_Route6Youngster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I've never seen"
	.DB $4f
	.STRINGMAP pokemon, "you around!"
	.DB $55
	.STRINGMAP pokemon, "Are you good?"
	.DB $57
_Route6Youngster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "are too good!"
	.DB $58
_Route6Youngster2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Are my #MON"
	.DB $4f
	.STRINGMAP pokemon, "weak? Or, am I"
	.DB $55
	.STRINGMAP pokemon, "just bad?"
	.DB $57
_Route6UndergroundPathSignText::
	.DB $00
	.STRINGMAP pokemon, "UNDERGROUND PATH"
	.DB $4f
	.STRINGMAP pokemon, "CERULEAN CITY -"
	.DB $55
	.STRINGMAP pokemon, "VERMILION CITY"
	.DB $57

; text/Route7.asm
_Route7UndergroundPathSignText::
	.DB $00
	.STRINGMAP pokemon, "UNDERGROUND PATH"
	.DB $4f
	.STRINGMAP pokemon, "CELADON CITY -"
	.DB $55
	.STRINGMAP pokemon, "LAVENDER TOWN"
	.DB $57

; text/Route8.asm
_Route8SuperNerd1BattleText::
	.DB $00
	.STRINGMAP pokemon, "You look good at"
	.DB $4f
	.STRINGMAP pokemon, "#MON, but"
	.DB $55
	.STRINGMAP pokemon, "how's your chem?"
	.DB $57
_Route8SuperNerd1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ow!"
	.DB $4f
	.STRINGMAP pokemon, "Meltdown!"
	.DB $58
_Route8SuperNerd1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I am better at"
	.DB $4f
	.STRINGMAP pokemon, "school than this!"
	.DB $57
_Route8Gambler1BattleText::
	.DB $00
	.STRINGMAP pokemon, "All right! Let's"
	.DB $4f
	.STRINGMAP pokemon, "roll the dice!"
	.DB $57
_Route8Gambler1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Drat!"
	.DB $4f
	.STRINGMAP pokemon, "Came up short!"
	.DB $58
_Route8Gambler1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Lady Luck's not"
	.DB $4f
	.STRINGMAP pokemon, "with me today!"
	.DB $57
_Route8SuperNerd2BattleText::
	.DB $00
	.STRINGMAP pokemon, "You need strategy"
	.DB $4f
	.STRINGMAP pokemon, "to win at this!"
	.DB $57
_Route8SuperNerd2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "It's"
	.DB $4f
	.STRINGMAP pokemon, "not logical!"
	.DB $58
_Route8SuperNerd2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Go with GRIMER"
	.DB $4f
	.STRINGMAP pokemon, "first...and..."
	.DB $55
	.STRINGMAP pokemon, "...and...then..."
	.DB $57
_Route8CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I like NIDORAN, so"
	.DB $4f
	.STRINGMAP pokemon, "I collect them!"
	.DB $57
_Route8CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Why? Why??"
	.DB $58
_Route8CooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "When #MON grow"
	.DB $4f
	.STRINGMAP pokemon, "up they get ugly!"
	.DB $55
	.STRINGMAP pokemon, "They shouldn't"
	.DB $55
	.STRINGMAP pokemon, "evolve!"
	.DB $57
_Route8SuperNerd3BattleText::
	.DB $00
	.STRINGMAP pokemon, "School is fun, but"
	.DB $4f
	.STRINGMAP pokemon, "so are #MON."
	.DB $57
_Route8SuperNerd3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'll"
	.DB $4f
	.STRINGMAP pokemon, "stay with school."
	.DB $58
_Route8SuperNerd3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "We're stuck here"
	.DB $4f
	.STRINGMAP pokemon, "because of the"
	.DB $55
	.STRINGMAP pokemon, "gates at SAFFRON."
	.DB $57
_Route8CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "MEOWTH is so cute,"
	.DB $4f
	.STRINGMAP pokemon, "meow, meow, meow!"
	.DB $57
_Route8CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Meow!"
	.DB $58
_Route8CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I think PIDGEY"
	.DB $4f
	.STRINGMAP pokemon, "and RATTATA"
	.DB $55
	.STRINGMAP pokemon, "are cute too!"
	.DB $57
_Route8CooltrainerF3BattleText::
	.DB $00
	.STRINGMAP pokemon, "We must look"
	.DB $4f
	.STRINGMAP pokemon, "silly standing"
	.DB $55
	.STRINGMAP pokemon, "here like this!"
	.DB $57
_Route8CooltrainerF3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Look what"
	.DB $4f
	.STRINGMAP pokemon, "you did!"
	.DB $58
_Route8CooltrainerF3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "SAFFRON's gate"
	.DB $4f
	.STRINGMAP pokemon, "keeper won't let"
	.DB $55
	.STRINGMAP pokemon, "us through."
	.DB $55
	.STRINGMAP pokemon, "He's so mean!"
	.DB $57
_Route8Gambler2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm a rambling,"
	.DB $4f
	.STRINGMAP pokemon, "gambling dude!"
	.DB $57
_Route8Gambler2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Missed"
	.DB $4f
	.STRINGMAP pokemon, "the big score!"
	.DB $58
_Route8Gambler2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Gambling and"
	.DB $4f
	.STRINGMAP pokemon, "#MON are like"
	.DB $55
	.STRINGMAP pokemon, "eating peanuts!"
	.DB $55
	.STRINGMAP pokemon, "Just can't stop!"
	.DB $57
_Route8CooltrainerF4BattleText::
	.DB $00
	.STRINGMAP pokemon, "What's a cute,"
	.DB $4f
	.STRINGMAP pokemon, "round and fluffy"
	.DB $55
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_Route8CooltrainerF4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Stop!"
	.DB $51
	.STRINGMAP pokemon, "Don't be so mean"
	.DB $4f
	.STRINGMAP pokemon, "to my CLEFAIRY!"
	.DB $58
_Route8CooltrainerF4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I heard that"
	.DB $4f
	.STRINGMAP pokemon, "CLEFAIRY evolves"
	.DB $55
	.STRINGMAP pokemon, "when it's exposed"
	.DB $55
	.STRINGMAP pokemon, "to a MOON STONE."
	.DB $57
_Route8UndergroundSignText::
	.DB $00
	.STRINGMAP pokemon, "UNDERGROUND PATH"
	.DB $4f
	.STRINGMAP pokemon, "CELADON CITY -"
	.DB $55
	.STRINGMAP pokemon, "LAVENDER TOWN"
	.DB $57

; text/Route9.asm
_Route9CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "You have #MON"
	.DB $4f
	.STRINGMAP pokemon, "with you!"
	.DB $55
	.STRINGMAP pokemon, "You're mine!"
	.DB $57
_Route9CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "deceived me!"
	.DB $58
_Route9CooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You need light to"
	.DB $4f
	.STRINGMAP pokemon, "get through that"
	.DB $55
	.STRINGMAP pokemon, "dark tunnel ahead."
	.DB $57
_Route9CooltrainerM1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Who's that walking"
	.DB $4f
	.STRINGMAP pokemon, "with those good"
	.DB $55
	.STRINGMAP pokemon, "looking #MON?"
	.DB $57
_Route9CooltrainerM1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Out"
	.DB $4f
	.STRINGMAP pokemon, "like a light!"
	.DB $58
_Route9CooltrainerM1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Keep walking!"
	.DB $57
_Route9CooltrainerM2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm taking ROCK"
	.DB $4f
	.STRINGMAP pokemon, "TUNNEL to go to"
	.DB $55
	.STRINGMAP pokemon, "LAVENDER..."
	.DB $57
_Route9CooltrainerM2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Can't"
	.DB $4f
	.STRINGMAP pokemon, "measure up!"
	.DB $58
_Route9CooltrainerM2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you off to"
	.DB $4f
	.STRINGMAP pokemon, "ROCK TUNNEL too?"
	.DB $57
_Route9CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Don't you dare"
	.DB $4f
	.STRINGMAP pokemon, "condescend me!"
	.DB $57
_Route9CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "No!"
	.DB $4f
	.STRINGMAP pokemon, "You're too much!"
	.DB $58
_Route9CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're obviously"
	.DB $4f
	.STRINGMAP pokemon, "talented! Good"
	.DB $55
	.STRINGMAP pokemon, "luck to you!"
	.DB $57
_Route9Hiker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Bwahaha!"
	.DB $4f
	.STRINGMAP pokemon, "Great! I was"
	.DB $55
	.STRINGMAP pokemon, "bored, eh!"
	.DB $57
_Route9Hiker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Keep it"
	.DB $4f
	.STRINGMAP pokemon, "coming, eh!"
	.DB $51
	.STRINGMAP pokemon, "Oh wait. I'm out"
	.DB $4f
	.STRINGMAP pokemon, "of #MON!"
	.DB $58
_Route9Hiker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You sure had guts"
	.DB $4f
	.STRINGMAP pokemon, "standing up to me"
	.DB $55
	.STRINGMAP pokemon, "there, eh?"
	.DB $57
_Route9Hiker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hahaha!"
	.DB $4f
	.STRINGMAP pokemon, "Aren't you a"
	.DB $55
	.STRINGMAP pokemon, "little toughie!"
	.DB $57
_Route9Hiker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "What's"
	.DB $4f
	.STRINGMAP pokemon, "that?"
	.DB $58
_Route9Hiker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hahaha! Kids"
	.DB $4f
	.STRINGMAP pokemon, "should be tough!"
	.DB $57
_Route9Youngster1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I got up early"
	.DB $4f
	.STRINGMAP pokemon, "every day to"
	.DB $55
	.STRINGMAP pokemon, "raise my #MON"
	.DB $55
	.STRINGMAP pokemon, "from cocoons!"
	.DB $57
_Route9Youngster1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "WHAT?"
	.DB $51
	.STRINGMAP pokemon, "What a total"
	.DB $4f
	.STRINGMAP pokemon, "waste of time!"
	.DB $58
_Route9Youngster1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I have to collect"
	.DB $4f
	.STRINGMAP pokemon, "more than bugs to"
	.DB $55
	.STRINGMAP pokemon, "get stronger..."
	.DB $57
_Route9Hiker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hahahaha!"
	.DB $4f
	.STRINGMAP pokemon, "Come on, dude!"
	.DB $57
_Route9Hiker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hahahaha!"
	.DB $4f
	.STRINGMAP pokemon, "You beat me fair!"
	.DB $58
_Route9Hiker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hahahaha!"
	.DB $4f
	.STRINGMAP pokemon, "Us hearty guys"
	.DB $55
	.STRINGMAP pokemon, "always laugh!"
	.DB $57
_Route9Youngster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Go, my super bug"
	.DB $4f
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_Route9Youngster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "My"
	.DB $4f
	.STRINGMAP pokemon, "bugs..."
	.DB $58
_Route9Youngster2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If you don't like"
	.DB $4f
	.STRINGMAP pokemon, "bug #MON, you"
	.DB $55
	.STRINGMAP pokemon, "bug me!"
	.DB $57
_Route9SignText::
	.DB $00
	.STRINGMAP pokemon, "ROUTE 9"
	.DB $4f
	.STRINGMAP pokemon, "CERULEAN CITY-"
	.DB $55
	.STRINGMAP pokemon, "ROCK TUNNEL"
	.DB $57

; text/Route10.asm
_Route10SuperNerd1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Wow, are you a"
	.DB $4f
	.STRINGMAP pokemon, "#MANIAC too?"
	.DB $55
	.STRINGMAP pokemon, "Want to see my"
	.DB $55
	.STRINGMAP pokemon, "collection?"
	.DB $57
_Route10SuperNerd1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Humph."
	.DB $4f
	.STRINGMAP pokemon, "I'm not angry!"
	.DB $58
_Route10SuperNerd1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I have more rare"
	.DB $4f
	.STRINGMAP pokemon, "#MON at home!"
	.DB $57
_Route10Hiker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Ha-hahah-ah-ha!"
	.DB $57
_Route10Hiker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ha-haha!"
	.DB $4f
	.STRINGMAP pokemon, "Not laughing!"
	.DB $55
	.STRINGMAP pokemon, "Ha-hay fever!"
	.DB $55
	.STRINGMAP pokemon, "Haha-ha-choo!"
	.DB $58
_Route10Hiker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Haha-ha-choo!"
	.DB $4f
	.STRINGMAP pokemon, "Ha-choo!"
	.DB $55
	.STRINGMAP pokemon, "Snort! Snivel!"
	.DB $57
_Route10SuperNerd2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hi kid, want to"
	.DB $4f
	.STRINGMAP pokemon, "see my #MON?"
	.DB $57
_Route10SuperNerd2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh no!"
	.DB $4f
	.STRINGMAP pokemon, "My #MON!"
	.DB $58
_Route10SuperNerd2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I don't like you"
	.DB $4f
	.STRINGMAP pokemon, "for beating me!"
	.DB $57
_Route10CooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I've been to a"
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM a few"
	.DB $55
	.STRINGMAP pokemon, "times. But, I"
	.DB $55
	.STRINGMAP pokemon, "lost each time."
	.DB $57
_Route10CooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ohh!"
	.DB $4f
	.STRINGMAP pokemon, "Blew it again!"
	.DB $58
_Route10CooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I noticed some"
	.DB $4f
	.STRINGMAP pokemon, "#MANIACs"
	.DB $55
	.STRINGMAP pokemon, "prowling around."
	.DB $57
_Route10Hiker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Ah! This mountain"
	.DB $4f
	.STRINGMAP pokemon, "air is delicious!"
	.DB $57
_Route10Hiker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "That"
	.DB $4f
	.STRINGMAP pokemon, "cleared my head!"
	.DB $58
_Route10Hiker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I feel bloated on"
	.DB $4f
	.STRINGMAP pokemon, "mountain air!"
	.DB $57
_Route10CooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm feeling a bit"
	.DB $4f
	.STRINGMAP pokemon, "faint from this"
	.DB $55
	.STRINGMAP pokemon, "tough hike."
	.DB $57
_Route10CooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "not up to it!"
	.DB $58
_Route10CooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The #MON here"
	.DB $4f
	.STRINGMAP pokemon, "are so chunky!"
	.DB $55
	.STRINGMAP pokemon, "There should be a"
	.DB $55
	.STRINGMAP pokemon, "pink one with a"
	.DB $55
	.STRINGMAP pokemon, "floral pattern!"
	.DB $57
_Route10RockTunnelSignText::
	.DB $00
	.STRINGMAP pokemon, "ROCK TUNNEL"
	.DB $57
_Route10PowerPlantSignText::
	.DB $00
	.STRINGMAP pokemon, "POWER PLANT"
	.DB $57

; text/Route11.asm
_Route11Gambler1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Win, lose or draw!"
	.DB $57
_Route11Gambler1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Atcha!"
	.DB $4f
	.STRINGMAP pokemon, "Didn't go my way!"
	.DB $58
_Route11Gambler1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON is life!"
	.DB $4f
	.STRINGMAP pokemon, "And to live is to"
	.DB $55
	.STRINGMAP pokemon, "gamble!"
	.DB $57
_Route11Gambler2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Competition! I"
	.DB $4f
	.STRINGMAP pokemon, "can't get enough!"
	.DB $57
_Route11Gambler2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I had"
	.DB $4f
	.STRINGMAP pokemon, "a chance!"
	.DB $58
_Route11Gambler2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You can't be a"
	.DB $4f
	.STRINGMAP pokemon, "coward in the"
	.DB $55
	.STRINGMAP pokemon, "world of #MON!"
	.DB $57
_Route11Youngster1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Let's go, but"
	.DB $4f
	.STRINGMAP pokemon, "don't cheat!"
	.DB $57
_Route11Youngster1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Huh?"
	.DB $4f
	.STRINGMAP pokemon, "That's not right!"
	.DB $58
_Route11Youngster1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I did my best! I"
	.DB $4f
	.STRINGMAP pokemon, "have no regrets!"
	.DB $57
_Route11SuperNerd1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Careful!"
	.DB $4f
	.STRINGMAP pokemon, "I'm laying down"
	.DB $55
	.STRINGMAP pokemon, "some cables!"
	.DB $57
_Route11SuperNerd1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "That"
	.DB $4f
	.STRINGMAP pokemon, "was electric!"
	.DB $58
_Route11SuperNerd1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Spread the word"
	.DB $4f
	.STRINGMAP pokemon, "to save energy!"
	.DB $57
_Route11Youngster2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I just became a"
	.DB $4f
	.STRINGMAP pokemon, "trainer! But, I"
	.DB $55
	.STRINGMAP pokemon, "think I can win!"
	.DB $57
_Route11Youngster2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "My"
	.DB $4f
	.STRINGMAP pokemon, "#MON couldn't!"
	.DB $58
_Route11Youngster2AfterBattleText5::
	.DB $00
	.STRINGMAP pokemon, "What do you want?"
	.DB $4f
	.STRINGMAP pokemon, "Leave me alone!"
	.DB $57
_Route11Gambler3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Fwahaha! I have"
	.DB $4f
	.STRINGMAP pokemon, "never lost!"
	.DB $57
_Route11Gambler3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "My"
	.DB $4f
	.STRINGMAP pokemon, "first loss!"
	.DB $58
_Route11Gambler3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Luck of the draw!"
	.DB $4f
	.STRINGMAP pokemon, "Just luck!"
	.DB $57
_Route11Gambler4BattleText::
	.DB $00
	.STRINGMAP pokemon, "I have never won"
	.DB $4f
	.STRINGMAP pokemon, "before..."
	.DB $57
_Route11Gambler4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I saw"
	.DB $4f
	.STRINGMAP pokemon, "this coming..."
	.DB $58
_Route11Gambler4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "It's just luck."
	.DB $4f
	.STRINGMAP pokemon, "Luck of the draw."
	.DB $57
_Route11Youngster3BattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm the best in"
	.DB $4f
	.STRINGMAP pokemon, "my class!"
	.DB $57
_Route11Youngster3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Darn!"
	.DB $4f
	.STRINGMAP pokemon, "I need to make my"
	.DB $55
	.STRINGMAP pokemon, "#MON stronger!"
	.DB $58
_Route11Youngster3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "There's a fat"
	.DB $4f
	.STRINGMAP pokemon, "#MON that"
	.DB $55
	.STRINGMAP pokemon, "comes down from"
	.DB $55
	.STRINGMAP pokemon, "the mountains."
	.DB $51
	.STRINGMAP pokemon, "It's strong if"
	.DB $4f
	.STRINGMAP pokemon, "you can get it."
	.DB $57
_Route11SuperNerd2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Watch out for"
	.DB $4f
	.STRINGMAP pokemon, "live wires!"
	.DB $57

Bank35TextEnd::
