; Generated by convert_text_bank.py from:
;   text/SilphCo5F_2.asm
;   text/SilphCo6F.asm
;   text/SilphCo7F.asm
;   text/SilphCo8F.asm
;   text/SilphCo9F.asm
;   text/SilphCo10F.asm
;   text/SilphCo11F.asm
;   text/PokemonMansion2F.asm
;   text/PokemonMansion3F.asm
;   text/PokemonMansionB1F.asm
;   text/SafariZoneEast.asm
;   text/SafariZoneNorth.asm
;   text/SafariZoneWest.asm
;   text/SafariZoneCenter.asm
;   text/SafariZoneCenterRestHouse.asm
;   text/SafariZoneSecretHouse.asm
;   text/SafariZoneWestRestHouse.asm
;   text/SafariZoneEastRestHouse.asm
;   text/SafariZoneNorthRestHouse.asm
;   text/CeruleanCaveB1F.asm
;   text/VictoryRoad1F.asm
;   text/LancesRoom.asm
;   text/HallOfFame.asm
;   text/ChampionsRoom.asm
;   text/LoreleisRoom.asm
;   text/BrunosRoom.asm
;   text/AgathasRoom.asm
;   text/RockTunnelB1F.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; text/SilphCo5F_2.asm
_SilphCo5FRockerEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh"
	.DB $4f
	.STRINGMAP pokemon, "goodness!"
	.DB $58
_SilphCo5FRockerAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're only on 5F."
	.DB $4f
	.STRINGMAP pokemon, "It's a long way"
	.DB $55
	.STRINGMAP pokemon, "to my BOSS!"
	.DB $57
_SilphCo5FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Show TEAM ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "a little respect!"
	.DB $57
_SilphCo5FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Cough..."
	.DB $4f
	.STRINGMAP pokemon, "Cough..."
	.DB $58
_SilphCo5FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Which reminds me."
	.DB $51
	.STRINGMAP pokemon, "KOFFING evolves"
	.DB $4f
	.STRINGMAP pokemon, "into WEEZING!"
	.DB $57
_SilphCo5FPokemonReport1Text::
	.DB $00
	.STRINGMAP pokemon, "It's a #MON"
	.DB $4f
	.STRINGMAP pokemon, "REPORT!"
	.DB $51
	.STRINGMAP pokemon, "#MON LAB"
	.DB $4f
	.STRINGMAP pokemon, "created PORYGON,"
	.DB $55
	.STRINGMAP pokemon, "the first virtual"
	.DB $55
	.STRINGMAP pokemon, "reality #MON."
	.DB $57
_SilphCo5FPokemonReport2Text::
	.DB $00
	.STRINGMAP pokemon, "It's a #MON"
	.DB $4f
	.STRINGMAP pokemon, "REPORT!"
	.DB $51
	.STRINGMAP pokemon, "Over 160 #MON"
	.DB $4f
	.STRINGMAP pokemon, "techniques have"
	.DB $55
	.STRINGMAP pokemon, "been confirmed."
	.DB $57
_SilphCo5FPokemonReport3Text::
	.DB $00
	.STRINGMAP pokemon, "It's a #MON"
	.DB $4f
	.STRINGMAP pokemon, "REPORT!"
	.DB $51
	.STRINGMAP pokemon, "4 #MON evolve"
	.DB $4f
	.STRINGMAP pokemon, "only when traded"
	.DB $55
	.STRINGMAP pokemon, "by link-cable."
	.DB $57

; text/SilphCo6F.asm
_SilphCo6FSilphWorkerM1TookOverTheBuildingText::
	.DB $00
	.STRINGMAP pokemon, "The ROCKETs came"
	.DB $4f
	.STRINGMAP pokemon, "and took over the"
	.DB $55
	.STRINGMAP pokemon, "building!"
	.DB $57
_SilphCo6FSilphWorkerM1BackToWorkText::
	.DB $00
	.STRINGMAP pokemon, "Well, better get"
	.DB $4f
	.STRINGMAP pokemon, "back to work!"
	.DB $57
_SilphCo6FSilphWorkerMHelpMePleaseText::
	.DB $00
	.STRINGMAP pokemon, "Oh dear, oh dear."
	.DB $4f
	.STRINGMAP pokemon, "Help me please!"
	.DB $57
_SilphCo6FSilphWorkerMWeGotEngagedText::
	.DB $00
	.STRINGMAP pokemon, "We got engaged!"
	.DB $4f
	.STRINGMAP pokemon, "Heheh!"
	.DB $57
_SilphCo6FSilphWorkerF1SuchACowardText::
	.DB $00
	.STRINGMAP pokemon, "Look at him! He's"
	.DB $4f
	.STRINGMAP pokemon, "such a coward!"
	.DB $57
_SilphCo6FSilphWorkerF1HaveToMarryHimText::
	.DB $00
	.STRINGMAP pokemon, "I feel so sorry"
	.DB $4f
	.STRINGMAP pokemon, "for him, I have"
	.DB $55
	.STRINGMAP pokemon, "to marry him!"
	.DB $57
_SilphCo6FSilphWorkerF2TeamRocketConquerWorldText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET is"
	.DB $4f
	.STRINGMAP pokemon, "trying to conquer"
	.DB $55
	.STRINGMAP pokemon, "the world with"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_SilphCo6FSilphWorkerF2TeamRocketRanText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET ran"
	.DB $4f
	.STRINGMAP pokemon, "because of you!"
	.DB $57
_SilphCo6FSilphWorkerM3TargetedSilphText::
	.DB $00
	.STRINGMAP pokemon, "They must have"
	.DB $4f
	.STRINGMAP pokemon, "targeted SILPH"
	.DB $55
	.STRINGMAP pokemon, "for our #MON"
	.DB $55
	.STRINGMAP pokemon, "products."
	.DB $57
_SilphCo6FSilphWorkerM3WorkForSilphText::
	.DB $00
	.STRINGMAP pokemon, "Come work for"
	.DB $4f
	.STRINGMAP pokemon, "SILPH when you"
	.DB $55
	.STRINGMAP pokemon, "get older!"
	.DB $57
_SilphCo6FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "I am one of the 4"
	.DB $4f
	.STRINGMAP pokemon, "ROCKET BROTHERS!"
	.DB $57
_SilphCo6FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Flame"
	.DB $4f
	.STRINGMAP pokemon, "out!"
	.DB $58
_SilphCo6FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "No matter!"
	.DB $4f
	.STRINGMAP pokemon, "My brothers will"
	.DB $55
	.STRINGMAP pokemon, "avenge me!"
	.DB $57
_SilphCo6FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "That rotten"
	.DB $4f
	.STRINGMAP pokemon, "PRESIDENT!"
	.DB $51
	.STRINGMAP pokemon, "He shouldn't have"
	.DB $4f
	.STRINGMAP pokemon, "sent me to the"
	.DB $55
	.STRINGMAP pokemon, "TIKSI BRANCH!"
	.DB $57
_SilphCo6FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Shoot!"
	.DB $58
_SilphCo6FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "TIKSI BRANCH?"
	.DB $4f
	.STRINGMAP pokemon, "It's in Russian"
	.DB $55
	.STRINGMAP pokemon, "no man's land!"
	.DB $57
_SilphCo6FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "You dare betray"
	.DB $4f
	.STRINGMAP pokemon, "TEAM ROCKET?"
	.DB $57
_SilphCo6FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "traitor!"
	.DB $58
_SilphCo6FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If you stand for"
	.DB $4f
	.STRINGMAP pokemon, "justice, you"
	.DB $55
	.STRINGMAP pokemon, "betray evil!"
	.DB $57

; text/SilphCo7F.asm
_SilphCo7FSilphWorkerM1HaveThisPokemonText::
	.DB $00
	.STRINGMAP pokemon, "Oh! Hi! You're"
	.DB $4f
	.STRINGMAP pokemon, "not a ROCKET! You"
	.DB $55
	.STRINGMAP pokemon, "came to save us?"
	.DB $55
	.STRINGMAP pokemon, "Why, thank you!"
	.DB $51
	.STRINGMAP pokemon, "I want you to"
	.DB $4f
	.STRINGMAP pokemon, "have this #MON"
	.DB $55
	.STRINGMAP pokemon, "for saving us."
	.DB $58
_SilphCo7FSilphWorkerM1LaprasDescriptionText::
	.DB $00
	.STRINGMAP pokemon, "It's LAPRAS. It's"
	.DB $4f
	.STRINGMAP pokemon, "very intelligent."
	.DB $51
	.STRINGMAP pokemon, "We kept it in our"
	.DB $4f
	.STRINGMAP pokemon, "lab, but it will"
	.DB $55
	.STRINGMAP pokemon, "be much better"
	.DB $55
	.STRINGMAP pokemon, "off with you!"
	.DB $51
	.STRINGMAP pokemon, "I think you will"
	.DB $4f
	.STRINGMAP pokemon, "be a good trainer"
	.DB $55
	.STRINGMAP pokemon, "for LAPRAS!"
	.DB $51
	.STRINGMAP pokemon, "It's a good"
	.DB $4f
	.STRINGMAP pokemon, "swimmer. It'll"
	.DB $55
	.STRINGMAP pokemon, "give you a lift!"
	.DB $57
_SilphCo7FSilphWorkerM1IsOurPresidentOkText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET's"
	.DB $4f
	.STRINGMAP pokemon, "BOSS went to the"
	.DB $55
	.STRINGMAP pokemon, "boardroom! Is our"
	.DB $55
	.STRINGMAP pokemon, "PRESIDENT OK?"
	.DB $57
_SilphCo7FSilphWorkerM1SavedText::
	.DB $00
	.STRINGMAP pokemon, "Saved at last!"
	.DB $4f
	.STRINGMAP pokemon, "Thank you!"
	.DB $57
_SilphCo7FSilphWorkerM2AfterTheMasterBallText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET was"
	.DB $4f
	.STRINGMAP pokemon, "after the MASTER"
	.DB $55
	.STRINGMAP pokemon, "BALL which will"
	.DB $55
	.STRINGMAP pokemon, "catch any #MON!"
	.DB $57
_SilphCo7FSilphWorkerM2CancelledMasterBallText::
	.DB $00
	.STRINGMAP pokemon, "We canceled the"
	.DB $4f
	.STRINGMAP pokemon, "MASTER BALL"
	.DB $55
	.STRINGMAP pokemon, "project because"
	.DB $55
	.STRINGMAP pokemon, "of TEAM ROCKET."
	.DB $57
_SilphCo7FSilphWorkerM3ItWouldBeBadText::
	.DB $00
	.STRINGMAP pokemon, "It would be bad"
	.DB $4f
	.STRINGMAP pokemon, "if TEAM ROCKET"
	.DB $55
	.STRINGMAP pokemon, "took over SILPH"
	.DB $55
	.STRINGMAP pokemon, "or our #MON!"
	.DB $57
_SilphCo7FSilphWorkerM3YouChasedOffTeamRocketText::
	.DB $00
	.STRINGMAP pokemon, "Wow! You chased"
	.DB $4f
	.STRINGMAP pokemon, "off TEAM ROCKET"
	.DB $55
	.STRINGMAP pokemon, "all by yourself?"
	.DB $57
_SilphCo7FSilphWorkerM4ItsReallyDangerousHereText::
	.DB $00
	.STRINGMAP pokemon, "You! It's really"
	.DB $4f
	.STRINGMAP pokemon, "dangerous here!"
	.DB $55
	.STRINGMAP pokemon, "You came to save"
	.DB $55
	.STRINGMAP pokemon, "me? You can't!"
	.DB $57
_SilphCo7FSilphWorkerM4SafeAtLastText::
	.DB $00
	.STRINGMAP pokemon, "Safe at last!"
	.DB $4f
	.STRINGMAP pokemon, "Oh thank you!"
	.DB $57
_SilphCo7FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh ho! I smell a"
	.DB $4f
	.STRINGMAP pokemon, "little rat!"
	.DB $57
_SilphCo7FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Lights"
	.DB $4f
	.STRINGMAP pokemon, "out!"
	.DB $58
_SilphCo7FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You won't find my"
	.DB $4f
	.STRINGMAP pokemon, "BOSS by just"
	.DB $55
	.STRINGMAP pokemon, "scurrying around!"
	.DB $57
_SilphCo7FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "Heheh!"
	.DB $51
	.STRINGMAP pokemon, "You mistook me for"
	.DB $4f
	.STRINGMAP pokemon, "a SILPH worker?"
	.DB $57
_SilphCo7FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "done!"
	.DB $58
_SilphCo7FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Despite your age,"
	.DB $4f
	.STRINGMAP pokemon, "you are a skilled"
	.DB $55
	.STRINGMAP pokemon, "trainer!"
	.DB $57
_SilphCo7FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I am one of the 4"
	.DB $4f
	.STRINGMAP pokemon, "ROCKET BROTHERS!"
	.DB $57
_SilphCo7FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Aack!"
	.DB $4f
	.STRINGMAP pokemon, "Brothers, I lost!"
	.DB $58
_SilphCo7FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Doesn't matter."
	.DB $4f
	.STRINGMAP pokemon, "My brothers will"
	.DB $55
	.STRINGMAP pokemon, "repay the favor!"
	.DB $57
_SilphCo7FRocket3BattleText::
	.DB $00
	.STRINGMAP pokemon, "A child intruder?"
	.DB $4f
	.STRINGMAP pokemon, "That must be you!"
	.DB $57
_SilphCo7FRocket3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Fine!"
	.DB $4f
	.STRINGMAP pokemon, "I lost!"
	.DB $58
_SilphCo7FRocket3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Go on home"
	.DB $4f
	.STRINGMAP pokemon, "before my BOSS"
	.DB $55
	.STRINGMAP pokemon, "gets ticked off!"
	.DB $57
_SilphCo7FRivalText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: What"
	.DB $4f
	.STRINGMAP pokemon, "kept you <PLAYER>?"
	.DB $57
_SilphCo7FRivalWaitedHereText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Hahaha!"
	.DB $4f
	.STRINGMAP pokemon, "I thought you'd"
	.DB $55
	.STRINGMAP pokemon, "turn up if I"
	.DB $55
	.STRINGMAP pokemon, "waited here!"
	.DB $51
	.STRINGMAP pokemon, "I guess TEAM"
	.DB $4f
	.STRINGMAP pokemon, "ROCKET slowed you"
	.DB $55
	.STRINGMAP pokemon, "down! Not that I"
	.DB $55
	.STRINGMAP pokemon, "care!"
	.DB $51
	.STRINGMAP pokemon, "I saw you in"
	.DB $4f
	.STRINGMAP pokemon, "SAFFRON, so I"
	.DB $55
	.STRINGMAP pokemon, "decided to see if"
	.DB $55
	.STRINGMAP pokemon, "you got better!"
	.DB $57
_SilphCo7FRivalDefeatedText::
	.DB $00
	.STRINGMAP pokemon, "Oh ho!"
	.DB $4f
	.STRINGMAP pokemon, "So, you are ready"
	.DB $55
	.STRINGMAP pokemon, "for BOSS ROCKET!"
	.DB $58
_SilphCo7FRivalVictoryText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: How can"
	.DB $4f
	.STRINGMAP pokemon, "I put this?"
	.DB $51
	.STRINGMAP pokemon, "You're not good"
	.DB $4f
	.STRINGMAP pokemon, "enough to play"
	.DB $55
	.STRINGMAP pokemon, "with us big boys!"
	.DB $58
_SilphCo7FRivalGoodLuckToYouText::
	.DB $00
	.STRINGMAP pokemon, "Well, <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "I'm moving on up"
	.DB $4f
	.STRINGMAP pokemon, "and ahead!"
	.DB $51
	.STRINGMAP pokemon, "By checking my"
	.DB $4f
	.STRINGMAP pokemon, "#DEX, I'm"
	.DB $55
	.STRINGMAP pokemon, "starting to see"
	.DB $55
	.STRINGMAP pokemon, "what's strong and"
	.DB $55
	.STRINGMAP pokemon, "how they evolve!"
	.DB $51
	.STRINGMAP pokemon, "I'm going to the"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE"
	.DB $55
	.STRINGMAP pokemon, "to boot out the"
	.DB $55
	.STRINGMAP pokemon, "ELITE FOUR!"
	.DB $51
	.STRINGMAP pokemon, "I'll become the"
	.DB $4f
	.STRINGMAP pokemon, "world's most"
	.DB $55
	.STRINGMAP pokemon, "powerful trainer!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>, well"
	.DB $4f
	.STRINGMAP pokemon, "good luck to you!"
	.DB $55
	.STRINGMAP pokemon, "Don't sweat it!"
	.DB $55
	.STRINGMAP pokemon, "Smell ya!"
	.DB $57

; text/SilphCo8F.asm
_SilphCo8FSilphWorkerMSilphIsFinishedText::
	.DB $00
	.STRINGMAP pokemon, "I wonder if SILPH"
	.DB $4f
	.STRINGMAP pokemon, "is finished..."
	.DB $57
_SilphCo8FSilphWorkerMThanksForSavingUsText::
	.DB $00
	.STRINGMAP pokemon, "Thanks for saving"
	.DB $4f
	.STRINGMAP pokemon, "us!"
	.DB $57
_SilphCo8FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "That's as far as"
	.DB $4f
	.STRINGMAP pokemon, "you'll go!"
	.DB $57
_SilphCo8FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Not"
	.DB $4f
	.STRINGMAP pokemon, "enough grit!"
	.DB $58
_SilphCo8FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If you don't turn"
	.DB $4f
	.STRINGMAP pokemon, "back, I'll call"
	.DB $55
	.STRINGMAP pokemon, "for backup!"
	.DB $57
_SilphCo8FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're causing us"
	.DB $4f
	.STRINGMAP pokemon, "problems!"
	.DB $57
_SilphCo8FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Huh?"
	.DB $4f
	.STRINGMAP pokemon, "I lost?"
	.DB $58
_SilphCo8FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "So, what do you"
	.DB $4f
	.STRINGMAP pokemon, "think of SILPH"
	.DB $55
	.STRINGMAP pokemon, "BUILDING's maze?"
	.DB $57
_SilphCo8FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I am one of the 4"
	.DB $4f
	.STRINGMAP pokemon, "ROCKET BROTHERS!"
	.DB $57
_SilphCo8FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whoo!"
	.DB $4f
	.STRINGMAP pokemon, "Oh brothers!"
	.DB $58
_SilphCo8FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'll leave you up"
	.DB $4f
	.STRINGMAP pokemon, "to my brothers!"
	.DB $57

; text/SilphCo9F.asm
SilphCo9FNurseYouLookTiredText::
	.DB $00
	.STRINGMAP pokemon, "You look tired!"
	.DB $4f
	.STRINGMAP pokemon, "You should take a"
	.DB $55
	.STRINGMAP pokemon, "quick nap!"
	.DB $58
SilphCo9FNurseDontGiveUpText::
	.DB $00
	.STRINGMAP pokemon, "Don't give up!"
	.DB $57
SilphCo9FNurseThankYouText::
	.DB $00
	.STRINGMAP pokemon, "Thank you so"
	.DB $4f
	.STRINGMAP pokemon, "much!"
	.DB $57
_SilphCo9FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Your #MON seem"
	.DB $4f
	.STRINGMAP pokemon, "to adore you, kid!"
	.DB $57
_SilphCo9FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ghaaah!"
	.DB $58
_SilphCo9FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "If I had started"
	.DB $4f
	.STRINGMAP pokemon, "as a trainer at"
	.DB $55
	.STRINGMAP pokemon, "your age..."
	.DB $57
_SilphCo9FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "Your #MON have"
	.DB $4f
	.STRINGMAP pokemon, "weak points! I"
	.DB $55
	.STRINGMAP pokemon, "can nail them!"
	.DB $57
_SilphCo9FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "hammered me!"
	.DB $58
_SilphCo9FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Exploiting weak"
	.DB $4f
	.STRINGMAP pokemon, "spots does work!"
	.DB $55
	.STRINGMAP pokemon, "Think about"
	.DB $55
	.STRINGMAP pokemon, "element types!"
	.DB $57
_SilphCo9FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I am one of the 4"
	.DB $4f
	.STRINGMAP pokemon, "ROCKET BROTHERS!"
	.DB $57
_SilphCo9FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Warg!"
	.DB $4f
	.STRINGMAP pokemon, "Brothers, I lost!"
	.DB $58
_SilphCo9FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "My brothers will"
	.DB $4f
	.STRINGMAP pokemon, "avenge me!"
	.DB $57

; text/SilphCo10F.asm
_SilphCo10FSilphWorkerFImScaredText::
	.DB $00
	.STRINGMAP pokemon, "Waaaaa!"
	.DB $55
	.STRINGMAP pokemon, "I'm scared!"
	.DB $57
_SilphCo10FSilphWorkerFQuietAboutMyCryingText::
	.DB $00
	.STRINGMAP pokemon, "Please keep quiet"
	.DB $4f
	.STRINGMAP pokemon, "about my crying!"
	.DB $57
_SilphCo10FRocketBattleText::
	.DB $00
	.STRINGMAP pokemon, "Welcome to the"
	.DB $4f
	.STRINGMAP pokemon, "10F! So good of"
	.DB $55
	.STRINGMAP pokemon, "you to join me!"
	.DB $57
_SilphCo10FRocketEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm"
	.DB $4f
	.STRINGMAP pokemon, "stunned!"
	.DB $58
_SilphCo10FRocketAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Nice try, but the"
	.DB $4f
	.STRINGMAP pokemon, "boardroom is up"
	.DB $55
	.STRINGMAP pokemon, "one more floor!"
	.DB $57
_SilphCo10FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "Enough of your"
	.DB $4f
	.STRINGMAP pokemon, "silly games!"
	.DB $57
_SilphCo10FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "No"
	.DB $4f
	.STRINGMAP pokemon, "continues left!"
	.DB $58
_SilphCo10FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Are you satisfied"
	.DB $4f
	.STRINGMAP pokemon, "with beating me?"
	.DB $55
	.STRINGMAP pokemon, "Then go on home!"
	.DB $57

; text/SilphCo11F.asm
_SilphCo11FSilphPresidentText::
	.DB $00
	.STRINGMAP pokemon, "PRESIDENT: Thank"
	.DB $4f
	.STRINGMAP pokemon, "you for saving"
	.DB $55
	.STRINGMAP pokemon, "SILPH!"
	.DB $51
	.STRINGMAP pokemon, "I will never"
	.DB $4f
	.STRINGMAP pokemon, "forget you saved"
	.DB $55
	.STRINGMAP pokemon, "us in our moment"
	.DB $55
	.STRINGMAP pokemon, "of peril!"
	.DB $51
	.STRINGMAP pokemon, "I have to thank"
	.DB $4f
	.STRINGMAP pokemon, "you in some way!"
	.DB $51
	.STRINGMAP pokemon, "Because I am rich,"
	.DB $4f
	.STRINGMAP pokemon, "I can give you"
	.DB $55
	.STRINGMAP pokemon, "anything!"
	.DB $51
	.STRINGMAP pokemon, "Here, maybe this"
	.DB $4f
	.STRINGMAP pokemon, "will do!"
	.DB $58
_SilphCo11FSilphPresidentReceivedMasterBallText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got a"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_SilphCo11FSilphPresidentMasterBallDescriptionText::
	.DB $00
	.STRINGMAP pokemon, "PRESIDENT: You"
	.DB $4f
	.STRINGMAP pokemon, "can't buy that"
	.DB $55
	.STRINGMAP pokemon, "anywhere!"
	.DB $51
	.STRINGMAP pokemon, "It's our secret"
	.DB $4f
	.STRINGMAP pokemon, "prototype MASTER"
	.DB $55
	.STRINGMAP pokemon, "BALL!"
	.DB $51
	.STRINGMAP pokemon, "It will catch any"
	.DB $4f
	.STRINGMAP pokemon, "#MON without"
	.DB $55
	.STRINGMAP pokemon, "fail!"
	.DB $51
	.STRINGMAP pokemon, "You should be"
	.DB $4f
	.STRINGMAP pokemon, "quiet about using"
	.DB $55
	.STRINGMAP pokemon, "it, though."
	.DB $57
_SilphCo11FSilphPresidentNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You have no"
	.DB $4f
	.STRINGMAP pokemon, "room for this."
	.DB $57
_SilphCo11FBeautyText::
	.DB $00
	.STRINGMAP pokemon, "SECRETARY: Thank"
	.DB $4f
	.STRINGMAP pokemon, "you for rescuing"
	.DB $55
	.STRINGMAP pokemon, "all of us!"
	.DB $51
	.STRINGMAP pokemon, "We admire your"
	.DB $4f
	.STRINGMAP pokemon, "courage."
	.DB $57
_SilphCo11FGiovanniText::
	.DB $00
	.STRINGMAP pokemon, "Ah <PLAYER>!"
	.DB $4f
	.STRINGMAP pokemon, "So we meet again!"
	.DB $51
	.STRINGMAP pokemon, "The PRESIDENT and"
	.DB $4f
	.STRINGMAP pokemon, "I are discussing"
	.DB $55
	.STRINGMAP pokemon, "a vital business"
	.DB $55
	.STRINGMAP pokemon, "proposition."
	.DB $51
	.STRINGMAP pokemon, "Keep your nose"
	.DB $4f
	.STRINGMAP pokemon, "out of grown-up"
	.DB $55
	.STRINGMAP pokemon, "matters..."
	.DB $51
	.STRINGMAP pokemon, "Or, experience a"
	.DB $4f
	.STRINGMAP pokemon, "world of pain!"
	.DB $57
_SilphCo10FGiovanniILostAgainText::
	.DB $00
	.STRINGMAP pokemon, "Arrgh!!"
	.DB $4f
	.STRINGMAP pokemon, "I lost again!?"
	.DB $58
_SilphCo11FGiovanniYouRuinedOurPlansText::
	.DB $00
	.STRINGMAP pokemon, "Blast it all!"
	.DB $4f
	.STRINGMAP pokemon, "You ruined our"
	.DB $55
	.STRINGMAP pokemon, "plans for SILPH!"
	.DB $51
	.STRINGMAP pokemon, "But, TEAM ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "will never fall!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>! Never"
	.DB $4f
	.STRINGMAP pokemon, "forget that all"
	.DB $55
	.STRINGMAP pokemon, "#MON exist"
	.DB $55
	.STRINGMAP pokemon, "for TEAM ROCKET!"
	.DB $51
	.STRINGMAP pokemon, "I must go, but I"
	.DB $4f
	.STRINGMAP pokemon, "shall return!"
	.DB $57
_SilphCo11FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Stop right there!"
	.DB $4f
	.STRINGMAP pokemon, "Don't you move!"
	.DB $57
_SilphCo11FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Don't..."
	.DB $4f
	.STRINGMAP pokemon, "Please!"
	.DB $58
_SilphCo11FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "So, you want to"
	.DB $4f
	.STRINGMAP pokemon, "see my BOSS?"
	.DB $57
_SilphCo11FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Halt! Do you have"
	.DB $4f
	.STRINGMAP pokemon, "an appointment"
	.DB $55
	.STRINGMAP pokemon, "with my BOSS?"
	.DB $57
_SilphCo11FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Gaah!"
	.DB $4f
	.STRINGMAP pokemon, "Demolished!"
	.DB $58
_SilphCo11FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Watch your step,"
	.DB $4f
	.STRINGMAP pokemon, "my BOSS likes his"
	.DB $55
	.STRINGMAP pokemon, "#MON tough!"
	.DB $57
_SilphCo10FPorygonText::
	.DB $00
	.STRINGMAP pokemon, "The monitor has"
	.DB $4f
	.STRINGMAP pokemon, "#MON on it!"
	.DB $57

; text/PokemonMansion2F.asm
_PokemonMansion2FSuperNerdBattleText::
	.DB $00
	.STRINGMAP pokemon, "I can't get out!"
	.DB $4f
	.STRINGMAP pokemon, "This old place is"
	.DB $55
	.STRINGMAP pokemon, "one big puzzle!"
	.DB $57
_PokemonMansion2FSuperNerdEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh no!"
	.DB $4f
	.STRINGMAP pokemon, "My bag of loot!"
	.DB $58
_PokemonMansion2FSuperNerdAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Switches open and"
	.DB $4f
	.STRINGMAP pokemon, "close alternating"
	.DB $55
	.STRINGMAP pokemon, "sets of doors!"
	.DB $57
_PokemonMansion2FDiary1Text::
	.DB $00
	.STRINGMAP pokemon, "Diary: July 5"
	.DB $4f
	.STRINGMAP pokemon, "Guyana,"
	.DB $55
	.STRINGMAP pokemon, "South America"
	.DB $51
	.STRINGMAP pokemon, "A new #MON was"
	.DB $4f
	.STRINGMAP pokemon, "discovered deep"
	.DB $55
	.STRINGMAP pokemon, "in the jungle."
	.DB $57
_PokemonMansion2FDiary2Text::
	.DB $00
	.STRINGMAP pokemon, "Diary: July 10"
	.DB $4f
	.STRINGMAP pokemon, "We christened the"
	.DB $55
	.STRINGMAP pokemon, "newly discovered"
	.DB $55
	.STRINGMAP pokemon, "#MON, MEW."
	.DB $57
_PokemonMansion2FSwitchText::
	.DB $00
	.STRINGMAP pokemon, "A secret switch!"
	.DB $51
	.STRINGMAP pokemon, "Press it?"
	.DB $57
_PokemonMansion2FSwitchPressedText::
	.DB $00
	.STRINGMAP pokemon, "Who wouldn't?"
	.DB $58
_PokemonMansion2FSwitchNotPressedText::
	.DB $00
	.STRINGMAP pokemon, "Not quite yet!"
	.DB $57

; text/PokemonMansion3F.asm
_PokemonMansion3FSuperNerdBattleText::
	.DB $00
	.STRINGMAP pokemon, "This place is"
	.DB $4f
	.STRINGMAP pokemon, "like, huge!"
	.DB $57
_PokemonMansion3FSuperNerdEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ayah!"
	.DB $58
_PokemonMansion3FSuperNerdAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wonder where"
	.DB $4f
	.STRINGMAP pokemon, "my partner went."
	.DB $57
_PokemonMansion3FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "My mentor once"
	.DB $4f
	.STRINGMAP pokemon, "lived here."
	.DB $57
_PokemonMansion3FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whew!"
	.DB $4f
	.STRINGMAP pokemon, "Overwhelming!"
	.DB $58
_PokemonMansion3FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "So, you're stuck?"
	.DB $4f
	.STRINGMAP pokemon, "Try jumping off"
	.DB $55
	.STRINGMAP pokemon, "over there!"
	.DB $57
_PokemonMansion3FDiaryText::
	.DB $00
	.STRINGMAP pokemon, "Diary: Feb. 6"
	.DB $4f
	.STRINGMAP pokemon, "MEW gave birth."
	.DB $51
	.STRINGMAP pokemon, "We named the"
	.DB $4f
	.STRINGMAP pokemon, "newborn MEWTWO."
	.DB $57

; text/PokemonMansionB1F.asm
_PokemonMansionB1FBurglarBattleText::
	.DB $00
	.STRINGMAP pokemon, "Uh-oh. Where am"
	.DB $4f
	.STRINGMAP pokemon, "I now?"
	.DB $57
_PokemonMansionB1FBurglarEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Awooh!"
	.DB $58
_PokemonMansionB1FBurglarAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You can find stuff"
	.DB $4f
	.STRINGMAP pokemon, "lying around."
	.DB $57
_PokemonMansionB1FScientistBattleText::
	.DB $00
	.STRINGMAP pokemon, "This place is"
	.DB $4f
	.STRINGMAP pokemon, "ideal for a lab."
	.DB $57
_PokemonMansionB1FScientistEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "What"
	.DB $4f
	.STRINGMAP pokemon, "was that for?"
	.DB $58
_PokemonMansionB1FScientistAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I like it here!"
	.DB $4f
	.STRINGMAP pokemon, "It's conducive to"
	.DB $55
	.STRINGMAP pokemon, "my studies!"
	.DB $57
_PokemonMansionB1FDiaryText::
	.DB $00
	.STRINGMAP pokemon, "Diary; Sept. 1"
	.DB $4f
	.STRINGMAP pokemon, "MEWTWO is far too"
	.DB $55
	.STRINGMAP pokemon, "powerful."
	.DB $51
	.STRINGMAP pokemon, "We have failed to"
	.DB $4f
	.STRINGMAP pokemon, "curb its vicious"
	.DB $55
	.STRINGMAP pokemon, "tendencies..."
	.DB $57

; text/SafariZoneEast.asm
_SafariZoneEastRestHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "REST HOUSE"
	.DB $57
_SafariZoneEastTrainerTipsText::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "The remaining time"
	.DB $4f
	.STRINGMAP pokemon, "declines only"
	.DB $55
	.STRINGMAP pokemon, "while you walk!"
	.DB $57
_SafariZoneEastSignText::
	.DB $00
	.STRINGMAP pokemon, "CENTER AREA"
	.DB $4f
	.STRINGMAP pokemon, "NORTH: AREA 2"
	.DB $57

; text/SafariZoneNorth.asm
_SafariZoneNorthRestHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "REST HOUSE"
	.DB $57
_SafariZoneNorthTrainerTips1Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "The SECRET HOUSE"
	.DB $4f
	.STRINGMAP pokemon, "is still ahead!"
	.DB $57
_SafariZoneNorthSignText::
	.DB $00
	.STRINGMAP pokemon, "AREA 2"
	.DB $57
_SafariZoneNorthTrainerTips2Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "#MON hide in"
	.DB $4f
	.STRINGMAP pokemon, "tall grass!"
	.DB $51
	.STRINGMAP pokemon, "Zigzag through"
	.DB $4f
	.STRINGMAP pokemon, "grassy areas to"
	.DB $55
	.STRINGMAP pokemon, "flush them out."
	.DB $57
_SafariZoneNorthTrainerTips3Text::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Win a free HM for"
	.DB $4f
	.STRINGMAP pokemon, "finding the"
	.DB $55
	.STRINGMAP pokemon, "SECRET HOUSE!"
	.DB $57

; text/SafariZoneWest.asm
_SafariZoneWestRestHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "REST HOUSE"
	.DB $57
_SafariZoneWestFindWardensTeethSignText::
	.DB $00
	.STRINGMAP pokemon, "REQUEST NOTICE"
	.DB $51
	.STRINGMAP pokemon, "Please find the"
	.DB $4f
	.STRINGMAP pokemon, "SAFARI WARDEN's"
	.DB $55
	.STRINGMAP pokemon, "lost GOLD TEETH."
	.DB $55
	.STRINGMAP pokemon, "They're around"
	.DB $55
	.STRINGMAP pokemon, "here somewhere."
	.DB $51
	.STRINGMAP pokemon, "Reward offered!"
	.DB $4f
	.STRINGMAP pokemon, "Contact: WARDEN"
	.DB $57
_SafariZoneWestTrainerTipsText::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Zone Exploration"
	.DB $4f
	.STRINGMAP pokemon, "Campaign!"
	.DB $51
	.STRINGMAP pokemon, "The Search for"
	.DB $4f
	.STRINGMAP pokemon, "the SECRET HOUSE!"
	.DB $57
_SafariZoneWestSignText::
	.DB $00
	.STRINGMAP pokemon, "AREA 3"
	.DB $4f
	.STRINGMAP pokemon, "EAST: CENTER AREA"
	.DB $57

; text/SafariZoneCenter.asm
_SafariZoneCenterRestHouseSignText::
	.DB $00
	.STRINGMAP pokemon, "REST HOUSE"
	.DB $57
_SafariZoneCenterTrainerTipsSignText::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Press the START"
	.DB $4f
	.STRINGMAP pokemon, "Button to check"
	.DB $55
	.STRINGMAP pokemon, "remaining time!"
	.DB $57

; text/SafariZoneCenterRestHouse.asm
_SafariZoneCenterRestHouseGirlText::
	.DB $00
	.STRINGMAP pokemon, "SARA: Where did"
	.DB $4f
	.STRINGMAP pokemon, "my boy friend,"
	.DB $55
	.STRINGMAP pokemon, "ERIK, go?"
	.DB $57
_SafariZoneCenterRestHouseScientistText::
	.DB $00
	.STRINGMAP pokemon, "I'm catching"
	.DB $4f
	.STRINGMAP pokemon, "#MON to take"
	.DB $55
	.STRINGMAP pokemon, "home as gifts!"
	.DB $57

; text/SafariZoneSecretHouse.asm
_SafariZoneSecretHouseFishingGuruYouHaveWonText::
	.DB $00
	.STRINGMAP pokemon, "Ah! Finally!"
	.DB $51
	.STRINGMAP pokemon, "You're the first"
	.DB $4f
	.STRINGMAP pokemon, "person to reach"
	.DB $55
	.STRINGMAP pokemon, "the SECRET HOUSE!"
	.DB $51
	.STRINGMAP pokemon, "I was getting"
	.DB $4f
	.STRINGMAP pokemon, "worried that no"
	.DB $55
	.STRINGMAP pokemon, "one would win our"
	.DB $55
	.STRINGMAP pokemon, "campaign prize."
	.DB $51
	.STRINGMAP pokemon, "Congratulations!"
	.DB $4f
	.STRINGMAP pokemon, "You have won!"
	.DB $58
_SafariZoneSecretHouseFishingGuruReceivedHM03Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_SafariZoneSecretHouseFishingGuruHM03ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "HM03 is SURF!"
	.DB $51
	.STRINGMAP pokemon, "#MON will be"
	.DB $4f
	.STRINGMAP pokemon, "able to ferry you"
	.DB $55
	.STRINGMAP pokemon, "across water!"
	.DB $51
	.STRINGMAP pokemon, "And, this HM isn't"
	.DB $4f
	.STRINGMAP pokemon, "disposable! You"
	.DB $55
	.STRINGMAP pokemon, "can use it over"
	.DB $55
	.STRINGMAP pokemon, "and over!"
	.DB $51
	.STRINGMAP pokemon, "You're super lucky"
	.DB $4f
	.STRINGMAP pokemon, "for winning this"
	.DB $55
	.STRINGMAP pokemon, "fabulous prize!"
	.DB $57
_SafariZoneSecretHouseFishingGuruHM03NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "room for this"
	.DB $55
	.STRINGMAP pokemon, "fabulous prize!"
	.DB $57

; text/SafariZoneWestRestHouse.asm
_SafariZoneWestRestHouseScientistText::
	.DB $00
	.STRINGMAP pokemon, "Tossing ROCKs at"
	.DB $4f
	.STRINGMAP pokemon, "#MON might"
	.DB $55
	.STRINGMAP pokemon, "make them run,"
	.DB $55
	.STRINGMAP pokemon, "but they'll be"
	.DB $55
	.STRINGMAP pokemon, "easier to catch."
	.DB $57
_SafariZoneWestRestHouseCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "Using BAIT will"
	.DB $4f
	.STRINGMAP pokemon, "make #MON"
	.DB $55
	.STRINGMAP pokemon, "easier to catch."
	.DB $57
_SafariZoneWestRestHouseSilphWorkerFText::
	.DB $00
	.STRINGMAP pokemon, "I hiked a lot, but"
	.DB $4f
	.STRINGMAP pokemon, "I didn't see any"
	.DB $55
	.STRINGMAP pokemon, "#MON I wanted."
	.DB $57

; text/SafariZoneEastRestHouse.asm
_SafariZoneEastRestHouseScientistText::
	.DB $00
	.STRINGMAP pokemon, "How many did you"
	.DB $4f
	.STRINGMAP pokemon, "catch? I'm bushed"
	.DB $55
	.STRINGMAP pokemon, "from the work!"
	.DB $57
_SafariZoneEastRestHouseRockerText::
	.DB $00
	.STRINGMAP pokemon, "I caught a"
	.DB $4f
	.STRINGMAP pokemon, "CHANSEY!"
	.DB $51
	.STRINGMAP pokemon, "That makes this"
	.DB $4f
	.STRINGMAP pokemon, "all worthwhile!"
	.DB $57
_SafariZoneEastRestHouseSilphWorkerMText::
	.DB $00
	.STRINGMAP pokemon, "Whew! I'm tired"
	.DB $4f
	.STRINGMAP pokemon, "from all the fun!"
	.DB $57

; text/SafariZoneNorthRestHouse.asm
_SafariZoneNorthRestHouseScientistText::
	.DB $00
	.STRINGMAP pokemon, "You can keep any"
	.DB $4f
	.STRINGMAP pokemon, "item you find on"
	.DB $55
	.STRINGMAP pokemon, "the ground here."
	.DB $51
	.STRINGMAP pokemon, "But, you'll run"
	.DB $4f
	.STRINGMAP pokemon, "out of time if"
	.DB $55
	.STRINGMAP pokemon, "you try for all"
	.DB $55
	.STRINGMAP pokemon, "of them at once!"
	.DB $57
_SafariZoneNorthRestHouseSafariZoneWorkerText::
	.DB $00
	.STRINGMAP pokemon, "Go to the deepest"
	.DB $4f
	.STRINGMAP pokemon, "part of the"
	.DB $55
	.STRINGMAP pokemon, "SAFARI ZONE. You"
	.DB $55
	.STRINGMAP pokemon, "will win a prize!"
	.DB $57
_SafariZoneNorthRestHouseGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "My EEVEE evolved"
	.DB $4f
	.STRINGMAP pokemon, "into FLAREON!"
	.DB $51
	.STRINGMAP pokemon, "But, a friend's"
	.DB $4f
	.STRINGMAP pokemon, "EEVEE turned into"
	.DB $55
	.STRINGMAP pokemon, "a VAPOREON!"
	.DB $55
	.STRINGMAP pokemon, "I wonder why?"
	.DB $57

; text/CeruleanCaveB1F.asm
_MewtwoBattleText::
	.DB $00
	.STRINGMAP pokemon, "Mew!@"
	.DB $50

; text/VictoryRoad1F.asm
_VictoryRoad1FCooltrainerFBattleText::
	.DB $00
	.STRINGMAP pokemon, "I wonder if you"
	.DB $4f
	.STRINGMAP pokemon, "are good enough"
	.DB $55
	.STRINGMAP pokemon, "for me!"
	.DB $57
_VictoryRoad1FCooltrainerFEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "lost out!"
	.DB $58
_VictoryRoad1FCooltrainerFAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I never wanted to"
	.DB $4f
	.STRINGMAP pokemon, "lose to anybody!"
	.DB $57
_VictoryRoad1FCooltrainerMBattleText::
	.DB $00
	.STRINGMAP pokemon, "I can see you're"
	.DB $4f
	.STRINGMAP pokemon, "good! Let me see"
	.DB $55
	.STRINGMAP pokemon, "exactly how good!"
	.DB $57
_VictoryRoad1FCooltrainerMEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I"
	.DB $4f
	.STRINGMAP pokemon, "had a chance..."
	.DB $58
_VictoryRoad1FCooltrainerMAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I concede, you're"
	.DB $4f
	.STRINGMAP pokemon, "better than me!"
	.DB $57

; text/LancesRoom.asm
_LancesRoomLanceBeforeBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ah! I heard about"
	.DB $4f
	.STRINGMAP pokemon, "you <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "I lead the ELITE"
	.DB $4f
	.STRINGMAP pokemon, "FOUR! You can"
	.DB $55
	.STRINGMAP pokemon, "call me LANCE the"
	.DB $55
	.STRINGMAP pokemon, "dragon trainer!"
	.DB $51
	.STRINGMAP pokemon, "You know that"
	.DB $4f
	.STRINGMAP pokemon, "dragons are"
	.DB $55
	.STRINGMAP pokemon, "mythical #MON!"
	.DB $51
	.STRINGMAP pokemon, "They're hard to"
	.DB $4f
	.STRINGMAP pokemon, "catch and raise,"
	.DB $55
	.STRINGMAP pokemon, "but their powers"
	.DB $55
	.STRINGMAP pokemon, "are superior!"
	.DB $51
	.STRINGMAP pokemon, "They're virtually"
	.DB $4f
	.STRINGMAP pokemon, "indestructible!"
	.DB $51
	.STRINGMAP pokemon, "Well, are you"
	.DB $4f
	.STRINGMAP pokemon, "ready to lose?"
	.DB $51
	.STRINGMAP pokemon, "Your LEAGUE"
	.DB $4f
	.STRINGMAP pokemon, "challenge ends"
	.DB $55
	.STRINGMAP pokemon, "with me, <PLAYER>!"
	.DB $57
_LancesRoomLanceEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "That's it!"
	.DB $51
	.STRINGMAP pokemon, "I hate to admit"
	.DB $4f
	.STRINGMAP pokemon, "it, but you are a"
	.DB $55
	.STRINGMAP pokemon, "#MON master!"
	.DB $58
_LancesRoomLanceAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I still can't"
	.DB $4f
	.STRINGMAP pokemon, "believe my"
	.DB $55
	.STRINGMAP pokemon, "dragons lost to"
	.DB $55
	.STRINGMAP pokemon, "you, <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "You are now the"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE"
	.DB $55
	.STRINGMAP pokemon, "champion!"
	.DB $51
	.STRINGMAP pokemon, "...Or, you would"
	.DB $4f
	.STRINGMAP pokemon, "have been, but"
	.DB $55
	.STRINGMAP pokemon, "you have one more"
	.DB $55
	.STRINGMAP pokemon, "challenge ahead."
	.DB $51
	.STRINGMAP pokemon, "You have to face"
	.DB $4f
	.STRINGMAP pokemon, "another trainer!"
	.DB $55
	.STRINGMAP pokemon, "His name is..."
	.DB $51
	.STRINGMAP pokemon, "<RIVAL>!"
	.DB $4f
	.STRINGMAP pokemon, "He beat the ELITE"
	.DB $55
	.STRINGMAP pokemon, "FOUR before you!"
	.DB $51
	.STRINGMAP pokemon, "He is the real"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE"
	.DB $55
	.STRINGMAP pokemon, "champion!@"
	.DB $50

; text/HallOfFame.asm
_HallOfFameOakText::
	.DB $00
	.STRINGMAP pokemon, "OAK: Er-hem!"
	.DB $4f
	.STRINGMAP pokemon, "Congratulations"
	.DB $55
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "This floor is the"
	.DB $4f
	.STRINGMAP pokemon, "#MON HALL OF"
	.DB $55
	.STRINGMAP pokemon, "FAME!"
	.DB $51
	.STRINGMAP pokemon, "#MON LEAGUE"
	.DB $4f
	.STRINGMAP pokemon, "champions are"
	.DB $55
	.STRINGMAP pokemon, "honored for their"
	.DB $55
	.STRINGMAP pokemon, "exploits here!"
	.DB $51
	.STRINGMAP pokemon, "Their #MON are"
	.DB $4f
	.STRINGMAP pokemon, "also recorded in"
	.DB $55
	.STRINGMAP pokemon, "the HALL OF FAME!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>! You have"
	.DB $4f
	.STRINGMAP pokemon, "endeavored hard"
	.DB $55
	.STRINGMAP pokemon, "to become the new"
	.DB $55
	.STRINGMAP pokemon, "LEAGUE champion!"
	.DB $51
	.STRINGMAP pokemon, "Congratulations,"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>, you and"
	.DB $55
	.STRINGMAP pokemon, "your #MON are"
	.DB $55
	.STRINGMAP pokemon, "HALL OF FAMERs!"
	.DB $57

; text/ChampionsRoom.asm
_ChampionsRoomRivalIntroText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Hey!"
	.DB $51
	.STRINGMAP pokemon, "I was looking"
	.DB $4f
	.STRINGMAP pokemon, "forward to seeing"
	.DB $55
	.STRINGMAP pokemon, "you, <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "My rival should"
	.DB $4f
	.STRINGMAP pokemon, "be strong to keep"
	.DB $55
	.STRINGMAP pokemon, "me sharp!"
	.DB $51
	.STRINGMAP pokemon, "While working on"
	.DB $4f
	.STRINGMAP pokemon, "#DEX, I looked"
	.DB $55
	.STRINGMAP pokemon, "all over for"
	.DB $55
	.STRINGMAP pokemon, "powerful #MON!"
	.DB $51
	.STRINGMAP pokemon, "Not only that, I"
	.DB $4f
	.STRINGMAP pokemon, "assembled teams"
	.DB $55
	.STRINGMAP pokemon, "that would beat"
	.DB $55
	.STRINGMAP pokemon, "any #MON type!"
	.DB $51
	.STRINGMAP pokemon, "And now!"
	.DB $51
	.STRINGMAP pokemon, "I'm the #MON"
	.DB $4f
	.STRINGMAP pokemon, "LEAGUE champion!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>! Do you"
	.DB $4f
	.STRINGMAP pokemon, "know what that"
	.DB $55
	.STRINGMAP pokemon, "means?"
	.DB $51
	.STRINGMAP pokemon, "I'll tell you!"
	.DB $51
	.STRINGMAP pokemon, "I am the most"
	.DB $4f
	.STRINGMAP pokemon, "powerful trainer"
	.DB $55
	.STRINGMAP pokemon, "in the world!"
	.DB $57
_RivalDefeatedText::
	.DB $00
	.STRINGMAP pokemon, "NO!"
	.DB $4f
	.STRINGMAP pokemon, "That can't be!"
	.DB $55
	.STRINGMAP pokemon, "You beat my best!"
	.DB $51
	.STRINGMAP pokemon, "After all that"
	.DB $4f
	.STRINGMAP pokemon, "work to become"
	.DB $55
	.STRINGMAP pokemon, "LEAGUE champ?"
	.DB $51
	.STRINGMAP pokemon, "My reign is over"
	.DB $4f
	.STRINGMAP pokemon, "already?"
	.DB $55
	.STRINGMAP pokemon, "It's not fair!"
	.DB $58
_RivalVictoryText::
	.DB $00
	.STRINGMAP pokemon, "Hahaha!"
	.DB $4f
	.STRINGMAP pokemon, "I won, I won!"
	.DB $51
	.STRINGMAP pokemon, "I'm too good for"
	.DB $4f
	.STRINGMAP pokemon, "you, <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "You did well to"
	.DB $4f
	.STRINGMAP pokemon, "even reach me,"
	.DB $55
	.STRINGMAP pokemon, "<RIVAL>, the"
	.DB $55
	.STRINGMAP pokemon, "#MON genius!"
	.DB $51
	.STRINGMAP pokemon, "Nice try, loser!"
	.DB $4f
	.STRINGMAP pokemon, "Hahaha!"
	.DB $58
_ChampionsRoomRivalAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Why?"
	.DB $4f
	.STRINGMAP pokemon, "Why did I lose?"
	.DB $51
	.STRINGMAP pokemon, "I never made any"
	.DB $4f
	.STRINGMAP pokemon, "mistakes raising"
	.DB $55
	.STRINGMAP pokemon, "my #MON..."
	.DB $51
	.STRINGMAP pokemon, "Darn it! You're"
	.DB $4f
	.STRINGMAP pokemon, "the new #MON"
	.DB $55
	.STRINGMAP pokemon, "LEAGUE champion!"
	.DB $51
	.STRINGMAP pokemon, "Although I don't"
	.DB $4f
	.STRINGMAP pokemon, "like to admit it."
	.DB $57
_ChampionsRoomOakText::
	.DB $00
	.STRINGMAP pokemon, "OAK: <PLAYER>!"
	.DB $57
_ChampionsRoomOakCongratulatesPlayerText::
	.DB $00
	.STRINGMAP pokemon, "OAK: So, you won!"
	.DB $4f
	.STRINGMAP pokemon, "Congratulations!"
	.DB $55
	.STRINGMAP pokemon, "You're the new"
	.DB $55
	.STRINGMAP pokemon, "#MON LEAGUE"
	.DB $55
	.STRINGMAP pokemon, "champion!"
	.DB $51
	.STRINGMAP pokemon, "You've grown up so"
	.DB $4f
	.STRINGMAP pokemon, "much since you"
	.DB $55
	.STRINGMAP pokemon, "first left with"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>, you have"
	.DB $4f
	.STRINGMAP pokemon, "come of age!"
	.DB $57
_ChampionsRoomOakDisappointedWithRivalText::
	.DB $00
	.STRINGMAP pokemon, "OAK: <RIVAL>! I'm"
	.DB $4f
	.STRINGMAP pokemon, "disappointed!"
	.DB $51
	.STRINGMAP pokemon, "I came when I"
	.DB $4f
	.STRINGMAP pokemon, "heard you beat"
	.DB $55
	.STRINGMAP pokemon, "the ELITE FOUR!"
	.DB $51
	.STRINGMAP pokemon, "But, when I got"
	.DB $4f
	.STRINGMAP pokemon, "here, you had"
	.DB $55
	.STRINGMAP pokemon, "already lost!"
	.DB $51
	.STRINGMAP pokemon, "<RIVAL>! Do you"
	.DB $4f
	.STRINGMAP pokemon, "understand why"
	.DB $55
	.STRINGMAP pokemon, "you lost?"
	.DB $51
	.STRINGMAP pokemon, "You have forgotten"
	.DB $4f
	.STRINGMAP pokemon, "to treat your"
	.DB $55
	.STRINGMAP pokemon, "#MON with"
	.DB $55
	.STRINGMAP pokemon, "trust and love!"
	.DB $51
	.STRINGMAP pokemon, "Without them, you"
	.DB $4f
	.STRINGMAP pokemon, "will never become"
	.DB $55
	.STRINGMAP pokemon, "a champ again!"
	.DB $57
_ChampionsRoomOakComeWithMeText::
	.DB $00
	.STRINGMAP pokemon, "OAK: <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "You understand"
	.DB $4f
	.STRINGMAP pokemon, "that your victory"
	.DB $55
	.STRINGMAP pokemon, "was not just your"
	.DB $55
	.STRINGMAP pokemon, "own doing!"
	.DB $51
	.STRINGMAP pokemon, "The bond you share"
	.DB $4f
	.STRINGMAP pokemon, "with your #MON"
	.DB $55
	.STRINGMAP pokemon, "is marvelous!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $4f
	.STRINGMAP pokemon, "Come with me!"
	.DB $57

; text/LoreleisRoom.asm
_LoreleisRoomLoreleiBeforeBattleText::
	.DB $00
	.STRINGMAP pokemon, "Welcome to"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE!"
	.DB $51
	.STRINGMAP pokemon, "I am LORELEI of"
	.DB $4f
	.STRINGMAP pokemon, "the ELITE FOUR!"
	.DB $51
	.STRINGMAP pokemon, "No one can best"
	.DB $4f
	.STRINGMAP pokemon, "me when it comes"
	.DB $55
	.STRINGMAP pokemon, "to icy #MON!"
	.DB $51
	.STRINGMAP pokemon, "Freezing moves"
	.DB $4f
	.STRINGMAP pokemon, "are powerful!"
	.DB $51
	.STRINGMAP pokemon, "Your #MON will"
	.DB $4f
	.STRINGMAP pokemon, "be at my mercy"
	.DB $55
	.STRINGMAP pokemon, "when they are"
	.DB $55
	.STRINGMAP pokemon, "frozen solid!"
	.DB $51
	.STRINGMAP pokemon, "Hahaha!"
	.DB $4f
	.STRINGMAP pokemon, "Are you ready?"
	.DB $57
_LoreleisRoomLoreleiEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "How"
	.DB $4f
	.STRINGMAP pokemon, "dare you!"
	.DB $58
_LoreleisRoomLoreleiAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're better"
	.DB $4f
	.STRINGMAP pokemon, "than I thought!"
	.DB $55
	.STRINGMAP pokemon, "Go on ahead!"
	.DB $51
	.STRINGMAP pokemon, "You only got a"
	.DB $4f
	.STRINGMAP pokemon, "taste of #MON"
	.DB $55
	.STRINGMAP pokemon, "LEAGUE power!"
	.DB $57
_LoreleisRoomLoreleiDontRunAwayText::
	.DB $00
	.STRINGMAP pokemon, "Someone's voice:"
	.DB $4f
	.STRINGMAP pokemon, "Don't run away!"
	.DB $57

; text/BrunosRoom.asm
_BrunoBeforeBattleText::
	.DB $00
	.STRINGMAP pokemon, "I am BRUNO of"
	.DB $4f
	.STRINGMAP pokemon, "the ELITE FOUR!"
	.DB $51
	.STRINGMAP pokemon, "Through rigorous"
	.DB $4f
	.STRINGMAP pokemon, "training, people"
	.DB $55
	.STRINGMAP pokemon, "and #MON can"
	.DB $55
	.STRINGMAP pokemon, "become stronger!"
	.DB $51
	.STRINGMAP pokemon, "I've weight"
	.DB $4f
	.STRINGMAP pokemon, "trained with"
	.DB $55
	.STRINGMAP pokemon, "my #MON!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "We will grind you"
	.DB $4f
	.STRINGMAP pokemon, "down with our"
	.DB $55
	.STRINGMAP pokemon, "superior power!"
	.DB $51
	.STRINGMAP pokemon, "Hoo hah!"
	.DB $57
_BrunoEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Why?"
	.DB $4f
	.STRINGMAP pokemon, "How could I lose?"
	.DB $58
_BrunoAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "My job is done!"
	.DB $4f
	.STRINGMAP pokemon, "Go face your next"
	.DB $55
	.STRINGMAP pokemon, "challenge!"
	.DB $57
_BrunosRoomBrunoDontRunAwayText::
	.DB $00
	.STRINGMAP pokemon, "Someone's voice:"
	.DB $4f
	.STRINGMAP pokemon, "Don't run away!"
	.DB $57

; text/AgathasRoom.asm
_AgathaBeforeBattleText::
	.DB $00
	.STRINGMAP pokemon, "I am AGATHA of"
	.DB $4f
	.STRINGMAP pokemon, "the ELITE FOUR!"
	.DB $51
	.STRINGMAP pokemon, "OAK's taken a lot"
	.DB $4f
	.STRINGMAP pokemon, "of interest in"
	.DB $55
	.STRINGMAP pokemon, "you, child!"
	.DB $51
	.STRINGMAP pokemon, "That old duff was"
	.DB $4f
	.STRINGMAP pokemon, "once tough and"
	.DB $55
	.STRINGMAP pokemon, "handsome! That"
	.DB $55
	.STRINGMAP pokemon, "was decades ago!"
	.DB $51
	.STRINGMAP pokemon, "Now he just wants"
	.DB $4f
	.STRINGMAP pokemon, "to fiddle with"
	.DB $55
	.STRINGMAP pokemon, "his #DEX! He's"
	.DB $55
	.STRINGMAP pokemon, "wrong! #MON"
	.DB $55
	.STRINGMAP pokemon, "are for fighting!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>! I'll show"
	.DB $4f
	.STRINGMAP pokemon, "you how a real"
	.DB $55
	.STRINGMAP pokemon, "trainer fights!"
	.DB $57
_AgathaEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh ho!"
	.DB $4f
	.STRINGMAP pokemon, "You're something"
	.DB $55
	.STRINGMAP pokemon, "special, child!"
	.DB $58
_AgathaAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You win! I see"
	.DB $4f
	.STRINGMAP pokemon, "what the old duff"
	.DB $55
	.STRINGMAP pokemon, "sees in you now!"
	.DB $51
	.STRINGMAP pokemon, "I have nothing"
	.DB $4f
	.STRINGMAP pokemon, "else to say! Run"
	.DB $55
	.STRINGMAP pokemon, "along now, child!"
	.DB $57
_AgathasRoomAgathaDontRunAwayText::
	.DB $00
	.STRINGMAP pokemon, "Someone's voice:"
	.DB $4f
	.STRINGMAP pokemon, "Don't run away!"
	.DB $57

; text/RockTunnelB1F.asm
_RockTunnelB1FCooltrainerF1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hikers leave twigs"
	.DB $4f
	.STRINGMAP pokemon, "as trail markers."
	.DB $57
_RockTunnelB1FCooltrainerF1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ohhh!"
	.DB $4f
	.STRINGMAP pokemon, "I did my best!"
	.DB $58
_RockTunnelB1FCooltrainerF1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I want to go "
	.DB $4f
	.STRINGMAP pokemon, "home!"
	.DB $57
_RockTunnelB1FHiker1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hahaha! Can you"
	.DB $4f
	.STRINGMAP pokemon, "beat my power?"
	.DB $57
_RockTunnelB1FHiker1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oops!"
	.DB $4f
	.STRINGMAP pokemon, "Out-muscled!"
	.DB $58
_RockTunnelB1FHiker1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I go for power"
	.DB $4f
	.STRINGMAP pokemon, "because I hate"
	.DB $55
	.STRINGMAP pokemon, "thinking!"
	.DB $57
_RockTunnelB1FSuperNerd1BattleText::
	.DB $00
	.STRINGMAP pokemon, "You have a"
	.DB $4f
	.STRINGMAP pokemon, "#DEX?"
	.DB $55
	.STRINGMAP pokemon, "I want one too!"
	.DB $57
_RockTunnelB1FSuperNerd1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Shoot!"
	.DB $4f
	.STRINGMAP pokemon, "I'm so jealous!"
	.DB $58
_RockTunnelB1FSuperNerd1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "When you finish"
	.DB $4f
	.STRINGMAP pokemon, "your #DEX, can"
	.DB $55
	.STRINGMAP pokemon, "I have it?"
	.DB $57
_RockTunnelB1FSuperNerd2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Do you know about"
	.DB $4f
	.STRINGMAP pokemon, "costume players?"
	.DB $57
_RockTunnelB1FSuperNerd2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Well,"
	.DB $4f
	.STRINGMAP pokemon, "that's that."
	.DB $58
_RockTunnelB1FSuperNerd2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Costume players"
	.DB $4f
	.STRINGMAP pokemon, "dress up as"
	.DB $55
	.STRINGMAP pokemon, "#MON for fun."
	.DB $57
_RockTunnelB1FHiker2BattleText::
	.DB $00
	.STRINGMAP pokemon, "My #MON"
	.DB $4f
	.STRINGMAP pokemon, "techniques will"
	.DB $55
	.STRINGMAP pokemon, "leave you crying!"
	.DB $57
_RockTunnelB1FHiker2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I give!"
	.DB $4f
	.STRINGMAP pokemon, "You're a better"
	.DB $55
	.STRINGMAP pokemon, "technician!"
	.DB $58
_RockTunnelB1FHiker2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "In mountains,"
	.DB $4f
	.STRINGMAP pokemon, "you'll often find"
	.DB $55
	.STRINGMAP pokemon, "rock-type #MON."
	.DB $57
_RockTunnelB1FCooltrainerF2BattleText::
	.DB $00
	.STRINGMAP pokemon, "I don't often"
	.DB $4f
	.STRINGMAP pokemon, "come here, but I"
	.DB $55
	.STRINGMAP pokemon, "will fight you."
	.DB $57
_RockTunnelB1FCooltrainerF2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Oh!"
	.DB $4f
	.STRINGMAP pokemon, "I lost!"
	.DB $58
_RockTunnelB1FCooltrainerF2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I like tiny"
	.DB $4f
	.STRINGMAP pokemon, "#MON, big ones"
	.DB $55
	.STRINGMAP pokemon, "are too scary!"
	.DB $57
_RockTunnelB1FHiker3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Hit me with your"
	.DB $4f
	.STRINGMAP pokemon, "best shot!"
	.DB $57
_RockTunnelB1FHiker3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Fired"
	.DB $4f
	.STRINGMAP pokemon, "away!"
	.DB $58

Bank33TextEnd::
