; Generated by convert_text_bank.py from:
;   text/PewterGym_2.asm
;   text/PewterNidoranHouse.asm
;   text/PewterMart.asm
;   text/PewterSpeechHouse.asm
;   text/PewterPokecenter.asm
;   text/CeruleanTrashedHouse.asm
;   text/CeruleanTradeHouse.asm
;   text/CeruleanPokecenter.asm
;   text/CeruleanGym.asm
;   text/BikeShop.asm
;   text/CeruleanMart.asm
;   text/CeruleanBadgeHouse.asm
;   text/LavenderPokecenter.asm
;   text/PokemonTower1F.asm
;   text/PokemonTower2F.asm
;   text/PokemonTower3F.asm
;   text/PokemonTower4F.asm
;   text/PokemonTower5F.asm
;   text/PokemonTower6F.asm
;   text/PokemonTower7F.asm
;   text/MrFujisHouse.asm
;   text/LavenderMart.asm
;   text/LavenderCuboneHouse.asm
;   text/NameRatersHouse.asm
;   text/VermilionPokecenter.asm
;   text/PokemonFanClub.asm
;   text/VermilionMart.asm
;   text/VermilionGym.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; text/PewterGym_2.asm
_PewterGymBrockPostBattleAdviceText::
	.DB $00
	.STRINGMAP pokemon, "There are all"
	.DB $4f
	.STRINGMAP pokemon, "kinds of trainers"
	.DB $55
	.STRINGMAP pokemon, "in the world!"
	.DB $51
	.STRINGMAP pokemon, "You appear to be"
	.DB $4f
	.STRINGMAP pokemon, "very gifted as a"
	.DB $55
	.STRINGMAP pokemon, "#MON trainer!"
	.DB $51
	.STRINGMAP pokemon, "Go to the GYM in"
	.DB $4f
	.STRINGMAP pokemon, "CERULEAN and test"
	.DB $55
	.STRINGMAP pokemon, "your abilities!"
	.DB $57
_PewterGymBrockWaitTakeThisText::
	.DB $00
	.STRINGMAP pokemon, "Wait! Take this"
	.DB $4f
	.STRINGMAP pokemon, "with you!"
	.DB $57
_PewterGymReceivedTM34Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "TM34!@"
	.DB $50
_TM34ExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "A TM contains a"
	.DB $4f
	.STRINGMAP pokemon, "technique that"
	.DB $55
	.STRINGMAP pokemon, "can be taught to"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $51
	.STRINGMAP pokemon, "A TM is good only"
	.DB $4f
	.STRINGMAP pokemon, "once! So when you"
	.DB $55
	.STRINGMAP pokemon, "use one to teach"
	.DB $55
	.STRINGMAP pokemon, "a new technique,"
	.DB $55
	.STRINGMAP pokemon, "pick the #MON"
	.DB $55
	.STRINGMAP pokemon, "carefully!"
	.DB $51
	.STRINGMAP pokemon, "TM34 contains"
	.DB $4f
	.STRINGMAP pokemon, "BIDE!"
	.DB $51
	.STRINGMAP pokemon, "Your #MON will"
	.DB $4f
	.STRINGMAP pokemon, "absorb damage in"
	.DB $55
	.STRINGMAP pokemon, "battle then pay"
	.DB $55
	.STRINGMAP pokemon, "it back double!"
	.DB $57
_PewterGymTM34NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "room for this!"
	.DB $57
_PewterGymBrockReceivedBoulderBadgeText::
	.DB $00
	.STRINGMAP pokemon, "I took"
	.DB $4f
	.STRINGMAP pokemon, "you for granted."
	.DB $51
	.STRINGMAP pokemon, "As proof of your"
	.DB $4f
	.STRINGMAP pokemon, "victory, here's"
	.DB $55
	.STRINGMAP pokemon, "the BOULDERBADGE!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "the BOULDERBADGE!@"
	.DB $50
_PewterGymBrockBoulderBadgeInfoText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "That's an official"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE"
	.DB $55
	.STRINGMAP pokemon, "BADGE!"
	.DB $51
	.STRINGMAP pokemon, "Its bearer's"
	.DB $4f
	.STRINGMAP pokemon, "#MON become"
	.DB $55
	.STRINGMAP pokemon, "more powerful!"
	.DB $51
	.STRINGMAP pokemon, "The technique"
	.DB $4f
	.STRINGMAP pokemon, "FLASH can now be"
	.DB $55
	.STRINGMAP pokemon, "used any time!"
	.DB $58
_PewterGymCooltrainerMBattleText::
	.DB $00
	.STRINGMAP pokemon, "Stop right there,"
	.DB $4f
	.STRINGMAP pokemon, "kid!"
	.DB $51
	.STRINGMAP pokemon, "You're still light"
	.DB $4f
	.STRINGMAP pokemon, "years from facing"
	.DB $55
	.STRINGMAP pokemon, "BROCK!"
	.DB $57
_PewterGymCooltrainerMEndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Darn!"
	.DB $51
	.STRINGMAP pokemon, "Light years isn't"
	.DB $4f
	.STRINGMAP pokemon, "time! It measures"
	.DB $55
	.STRINGMAP pokemon, "distance!"
	.DB $58
_PewterGymCooltrainerMAfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're pretty hot,"
	.DB $4f
	.STRINGMAP pokemon, "but not as hot"
	.DB $55
	.STRINGMAP pokemon, "as BROCK!"
	.DB $57
_PewterGymGuidePreAdviceText::
	.DB $00
	.STRINGMAP pokemon, "Hiya! I can tell"
	.DB $4f
	.STRINGMAP pokemon, "you have what it"
	.DB $55
	.STRINGMAP pokemon, "takes to become a"
	.DB $55
	.STRINGMAP pokemon, "#MON champ!"
	.DB $51
	.STRINGMAP pokemon, "I'm no trainer,"
	.DB $4f
	.STRINGMAP pokemon, "but I can tell"
	.DB $55
	.STRINGMAP pokemon, "you how to win!"
	.DB $51
	.STRINGMAP pokemon, "Let me take you"
	.DB $4f
	.STRINGMAP pokemon, "to the top!"
	.DB $57
_PewterGymGuideBeginAdviceText::
	.DB $00
	.STRINGMAP pokemon, "All right! Let's"
	.DB $4f
	.STRINGMAP pokemon, "get happening!"
	.DB $58
_PewterGymGuideAdviceText::
	.DB $00
	.STRINGMAP pokemon, "The 1st #MON"
	.DB $4f
	.STRINGMAP pokemon, "out in a match is"
	.DB $55
	.STRINGMAP pokemon, "at the top of the"
	.DB $55
	.STRINGMAP pokemon, "#MON LIST!"
	.DB $51
	.STRINGMAP pokemon, "By changing the"
	.DB $4f
	.STRINGMAP pokemon, "order of #MON,"
	.DB $55
	.STRINGMAP pokemon, "matches could be"
	.DB $55
	.STRINGMAP pokemon, "made easier!"
	.DB $57
_PewterGymGuideFreeServiceText::
	.DB $00
	.STRINGMAP pokemon, "It's a free"
	.DB $4f
	.STRINGMAP pokemon, "service! Let's"
	.DB $55
	.STRINGMAP pokemon, "get happening!"
	.DB $58
_PewterGymGuidePostBattleText::
	.DB $00
	.STRINGMAP pokemon, "Just as I thought!"
	.DB $4f
	.STRINGMAP pokemon, "You're #MON"
	.DB $55
	.STRINGMAP pokemon, "champ material!"
	.DB $57

; text/PewterNidoranHouse.asm
_PewterNidoranHouseNidoranText::
	.DB $00
	.STRINGMAP pokemon, "NIDORAN: Bowbow!@"
	.DB $50
_PewterNidoranHouseLittleBoyText::
	.DB $00
	.STRINGMAP pokemon, "NIDORAN sit!"
	.DB $57
_PewterNidoranHouseMiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "Our #MON's an"
	.DB $4f
	.STRINGMAP pokemon, "outsider, so it's"
	.DB $55
	.STRINGMAP pokemon, "hard to handle."
	.DB $51
	.STRINGMAP pokemon, "An outsider is a"
	.DB $4f
	.STRINGMAP pokemon, "#MON that you"
	.DB $55
	.STRINGMAP pokemon, "get in a trade."
	.DB $51
	.STRINGMAP pokemon, "It grows fast, but"
	.DB $4f
	.STRINGMAP pokemon, "it may ignore an"
	.DB $55
	.STRINGMAP pokemon, "unskilled trainer"
	.DB $55
	.STRINGMAP pokemon, "in battle!"
	.DB $51
	.STRINGMAP pokemon, "If only we had"
	.DB $4f
	.STRINGMAP pokemon, "some BADGEs..."
	.DB $57

; text/PewterMart.asm
_PewterMartYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "A shady, old man"
	.DB $4f
	.STRINGMAP pokemon, "got me to buy"
	.DB $55
	.STRINGMAP pokemon, "this really weird"
	.DB $55
	.STRINGMAP pokemon, "fish #MON!"
	.DB $51
	.STRINGMAP pokemon, "It's totally weak"
	.DB $4f
	.STRINGMAP pokemon, "and it cost ¥500!"
	.DB $57
_PewterMartSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "Good things can"
	.DB $4f
	.STRINGMAP pokemon, "happen if you"
	.DB $55
	.STRINGMAP pokemon, "raise #MON"
	.DB $55
	.STRINGMAP pokemon, "diligently, even"
	.DB $55
	.STRINGMAP pokemon, "the weak ones!"
	.DB $57

; text/PewterSpeechHouse.asm
_PewterSpeechHouseGamblerText::
	.DB $00
	.STRINGMAP pokemon, "#MON learn new"
	.DB $4f
	.STRINGMAP pokemon, "techniques as"
	.DB $55
	.STRINGMAP pokemon, "they grow!"
	.DB $51
	.STRINGMAP pokemon, "But, some moves"
	.DB $4f
	.STRINGMAP pokemon, "must be taught by"
	.DB $55
	.STRINGMAP pokemon, "the trainer!"
	.DB $57
_PewterSpeechHouseYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "#MON become"
	.DB $4f
	.STRINGMAP pokemon, "easier to catch"
	.DB $55
	.STRINGMAP pokemon, "when they are"
	.DB $55
	.STRINGMAP pokemon, "hurt or asleep!"
	.DB $51
	.STRINGMAP pokemon, "But, it's not a"
	.DB $4f
	.STRINGMAP pokemon, "sure thing!"
	.DB $57

; text/PewterPokecenter.asm
_PewterPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "What!?"
	.DB $51
	.STRINGMAP pokemon, "TEAM ROCKET is"
	.DB $4f
	.STRINGMAP pokemon, "at MT.MOON? Huh?"
	.DB $55
	.STRINGMAP pokemon, "I'm on the phone!"
	.DB $51
	.STRINGMAP pokemon, "Scram!"
	.DB $57
_PewterPokecenterJigglypuffText::
	.DB $00
	.STRINGMAP pokemon, "JIGGLYPUFF: Puu"
	.DB $4f
	.STRINGMAP pokemon, "pupuu!"
	.DB $57

; text/CeruleanTrashedHouse.asm
_CeruleanTrashedHouseFishingGuruTheyStoleATMText::
	.DB $00
	.STRINGMAP pokemon, "Those miserable"
	.DB $4f
	.STRINGMAP pokemon, "ROCKETs!"
	.DB $51
	.STRINGMAP pokemon, "Look what they"
	.DB $4f
	.STRINGMAP pokemon, "did here!"
	.DB $51
	.STRINGMAP pokemon, "They stole a TM"
	.DB $4f
	.STRINGMAP pokemon, "for teaching"
	.DB $55
	.STRINGMAP pokemon, "#MON how to"
	.DB $55
	.STRINGMAP pokemon, "DIG holes!"
	.DB $51
	.STRINGMAP pokemon, "That cost me a"
	.DB $4f
	.STRINGMAP pokemon, "bundle, it did!"
	.DB $57
_CeruleanTrashedHouseFishingGuruWhatsLostIsLostText::
	.DB $00
	.STRINGMAP pokemon, "I figure what's"
	.DB $4f
	.STRINGMAP pokemon, "lost is lost!"
	.DB $51
	.STRINGMAP pokemon, "I decided to teach"
	.DB $4f
	.STRINGMAP pokemon, "DIGLETT how to"
	.DB $55
	.STRINGMAP pokemon, "DIG without a TM!"
	.DB $57
_CeruleanTrashedHouseGirlText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET must"
	.DB $4f
	.STRINGMAP pokemon, "be trying to DIG"
	.DB $55
	.STRINGMAP pokemon, "their way into no"
	.DB $55
	.STRINGMAP pokemon, "good!"
	.DB $57
_CeruleanTrashedHouseWallHoleText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET left"
	.DB $4f
	.STRINGMAP pokemon, "a way out!"
	.DB $57

; text/CeruleanTradeHouse.asm
_CeruleanTradeHouseGrannyText::
	.DB $00
	.STRINGMAP pokemon, "My husband likes"
	.DB $4f
	.STRINGMAP pokemon, "trading #MON."
	.DB $51
	.STRINGMAP pokemon, "If you are a"
	.DB $4f
	.STRINGMAP pokemon, "collector, would"
	.DB $55
	.STRINGMAP pokemon, "you please trade"
	.DB $55
	.STRINGMAP pokemon, "with him?"
	.DB $57

; text/CeruleanPokecenter.asm
_CeruleanPokecenterSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "That BILL!"
	.DB $51
	.STRINGMAP pokemon, "I heard that"
	.DB $4f
	.STRINGMAP pokemon, "he'll do whatever"
	.DB $55
	.STRINGMAP pokemon, "it takes to get"
	.DB $55
	.STRINGMAP pokemon, "rare #MON!"
	.DB $57
_CeruleanPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "Have you heard"
	.DB $4f
	.STRINGMAP pokemon, "about BILL?"
	.DB $51
	.STRINGMAP pokemon, "Everyone calls"
	.DB $4f
	.STRINGMAP pokemon, "him a #MANIAC!"
	.DB $51
	.STRINGMAP pokemon, "I think people"
	.DB $4f
	.STRINGMAP pokemon, "are just jealous"
	.DB $55
	.STRINGMAP pokemon, "of BILL, though."
	.DB $51
	.STRINGMAP pokemon, "Who wouldn't want"
	.DB $4f
	.STRINGMAP pokemon, "to boast about"
	.DB $55
	.STRINGMAP pokemon, "their #MON?"
	.DB $57

; text/CeruleanGym.asm
_CeruleanGymMistyPreBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hi, you're a new"
	.DB $4f
	.STRINGMAP pokemon, "face!"
	.DB $51
	.STRINGMAP pokemon, "Trainers who want"
	.DB $4f
	.STRINGMAP pokemon, "to turn pro have"
	.DB $55
	.STRINGMAP pokemon, "to have a policy"
	.DB $55
	.STRINGMAP pokemon, "about #MON!"
	.DB $51
	.STRINGMAP pokemon, "What is your"
	.DB $4f
	.STRINGMAP pokemon, "approach when you"
	.DB $55
	.STRINGMAP pokemon, "catch #MON?"
	.DB $51
	.STRINGMAP pokemon, "My policy is an"
	.DB $4f
	.STRINGMAP pokemon, "all-out offensive"
	.DB $55
	.STRINGMAP pokemon, "with water-type"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_CeruleanGymMistyTM11ExplanationText::
	.DB $00
	.STRINGMAP pokemon, "TM11 teaches"
	.DB $4f
	.STRINGMAP pokemon, "BUBBLEBEAM!"
	.DB $51
	.STRINGMAP pokemon, "Use it on an"
	.DB $4f
	.STRINGMAP pokemon, "aquatic #MON!"
	.DB $57
_CeruleanGymMistyCascadeBadgeInfoText::
	.DB $00
	.STRINGMAP pokemon, "The CASCADEBADGE"
	.DB $4f
	.STRINGMAP pokemon, "makes all #MON"
	.DB $55
	.STRINGMAP pokemon, "up to L30 obey!"
	.DB $51
	.STRINGMAP pokemon, "That includes"
	.DB $4f
	.STRINGMAP pokemon, "even outsiders!"
	.DB $51
	.STRINGMAP pokemon, "There's more, you"
	.DB $4f
	.STRINGMAP pokemon, "can now use CUT"
	.DB $55
	.STRINGMAP pokemon, "any time!"
	.DB $51
	.STRINGMAP pokemon, "You can CUT down"
	.DB $4f
	.STRINGMAP pokemon, "small bushes to"
	.DB $55
	.STRINGMAP pokemon, "open new paths!"
	.DB $51
	.STRINGMAP pokemon, "You can also have"
	.DB $4f
	.STRINGMAP pokemon, "my favorite TM!"
	.DB $57
_CeruleanGymMistyReceivedTM11Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "TM11!@"
	.DB $50
_CeruleanGymMistyTM11NoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You better make"
	.DB $4f
	.STRINGMAP pokemon, "room for this!"
	.DB $57
_CeruleanGymMistyReceivedCascadeBadgeText::
	.DB $00
	.STRINGMAP pokemon, "Wow!"
	.DB $4f
	.STRINGMAP pokemon, "You're too much!"
	.DB $51
	.STRINGMAP pokemon, "All right!"
	.DB $51
	.STRINGMAP pokemon, "You can have the"
	.DB $4f
	.STRINGMAP pokemon, "CASCADEBADGE to"
	.DB $55
	.STRINGMAP pokemon, "show you beat me!@"
	.DB $50
_CeruleanGymBattleText1::
	.DB $00
	.STRINGMAP pokemon, "I'm more than good"
	.DB $4f
	.STRINGMAP pokemon, "enough for you!"
	.DB $51
	.STRINGMAP pokemon, "MISTY can wait!"
	.DB $57
_CeruleanGymEndBattleText1::
	.DB $00
	.STRINGMAP pokemon, "You"
	.DB $4f
	.STRINGMAP pokemon, "overwhelmed me!"
	.DB $58
_CeruleanGymAfterBattleText1::
	.DB $00
	.STRINGMAP pokemon, "You have to face"
	.DB $4f
	.STRINGMAP pokemon, "other trainers to"
	.DB $55
	.STRINGMAP pokemon, "find out how good"
	.DB $55
	.STRINGMAP pokemon, "you really are."
	.DB $57
_CeruleanGymBattleText2::
	.DB $00
	.STRINGMAP pokemon, "Splash!"
	.DB $51
	.STRINGMAP pokemon, "I'm first up!"
	.DB $4f
	.STRINGMAP pokemon, "Let's do it!"
	.DB $57
_CeruleanGymEndBattleText2::
	.DB $00
	.STRINGMAP pokemon, "That"
	.DB $4f
	.STRINGMAP pokemon, "can't be!"
	.DB $58
_CeruleanGymAfterBattleText2::
	.DB $00
	.STRINGMAP pokemon, "MISTY is going to"
	.DB $4f
	.STRINGMAP pokemon, "keep improving!"
	.DB $51
	.STRINGMAP pokemon, "She won't lose to"
	.DB $4f
	.STRINGMAP pokemon, "someone like you!"
	.DB $57
_CeruleanGymGymGuideChampInMakingText::
	.DB $00
	.STRINGMAP pokemon, "Yo! Champ in"
	.DB $4f
	.STRINGMAP pokemon, "making!"
	.DB $51
	.STRINGMAP pokemon, "Here's my advice!"
	.DB $51
	.STRINGMAP pokemon, "The LEADER, MISTY,"
	.DB $4f
	.STRINGMAP pokemon, "is a pro who uses"
	.DB $55
	.STRINGMAP pokemon, "water #MON!"
	.DB $51
	.STRINGMAP pokemon, "You can drain all"
	.DB $4f
	.STRINGMAP pokemon, "their water with"
	.DB $55
	.STRINGMAP pokemon, "plant #MON!"
	.DB $51
	.STRINGMAP pokemon, "Or, zap them with"
	.DB $4f
	.STRINGMAP pokemon, "electricity!"
	.DB $57
_CeruleanGymGymGuideBeatMistyText::
	.DB $00
	.STRINGMAP pokemon, "You beat MISTY!"
	.DB $4f
	.STRINGMAP pokemon, "What'd I tell ya?"
	.DB $51
	.STRINGMAP pokemon, "You and me kid,"
	.DB $4f
	.STRINGMAP pokemon, "we make a pretty"
	.DB $55
	.STRINGMAP pokemon, "darn good team!"
	.DB $57

; text/BikeShop.asm
_BikeShopClerkWelcomeText::
	.DB $00
	.STRINGMAP pokemon, "Hi! Welcome to"
	.DB $4f
	.STRINGMAP pokemon, "our BIKE SHOP."
	.DB $51
	.STRINGMAP pokemon, "Have we got just"
	.DB $4f
	.STRINGMAP pokemon, "the BIKE for you!"
	.DB $58
_BikeShopClerkDoYouLikeItText::
	.DB $00
	.STRINGMAP pokemon, "It's a cool BIKE!"
	.DB $4f
	.STRINGMAP pokemon, "Do you want it?"
	.DB $57
_BikeShopCantAffordText::
	.DB $00
	.STRINGMAP pokemon, "Sorry! You can't"
	.DB $4f
	.STRINGMAP pokemon, "afford it!"
	.DB $58
_BikeShopClerkOhThatsAVoucherText::
	.DB $00
	.STRINGMAP pokemon, "Oh, that's..."
	.DB $51
	.STRINGMAP pokemon, "A BIKE VOUCHER!"
	.DB $51
	.STRINGMAP pokemon, "OK! Here you go!"
	.DB $58
_BikeShopExchangedVoucherText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> exchanged"
	.DB $4f
	.STRINGMAP pokemon, "the BIKE VOUCHER"
	.DB $55
	.STRINGMAP pokemon, "for a BICYCLE.@"
	.DB $50
_BikeShopComeAgainText::
	.DB $00
	.STRINGMAP pokemon, "Come back again"
	.DB $4f
	.STRINGMAP pokemon, "some time!"
	.DB $57
_BikeShopClerkHowDoYouLikeYourBicycleText::
	.DB $00
	.STRINGMAP pokemon, "How do you like"
	.DB $4f
	.STRINGMAP pokemon, "your new BICYCLE?"
	.DB $51
	.STRINGMAP pokemon, "You can take it"
	.DB $4f
	.STRINGMAP pokemon, "on CYCLING ROAD"
	.DB $55
	.STRINGMAP pokemon, "and in caves!"
	.DB $57
_BikeShopBagFullText::
	.DB $00
	.STRINGMAP pokemon, "You better make"
	.DB $4f
	.STRINGMAP pokemon, "room for this!"
	.DB $57
_BikeShopMiddleAgedWomanText::
	.DB $00
	.STRINGMAP pokemon, "A plain city BIKE"
	.DB $4f
	.STRINGMAP pokemon, "is good enough"
	.DB $55
	.STRINGMAP pokemon, "for me!"
	.DB $51
	.STRINGMAP pokemon, "You can't put a"
	.DB $4f
	.STRINGMAP pokemon, "shopping basket"
	.DB $55
	.STRINGMAP pokemon, "on an MTB!"
	.DB $57
_BikeShopYoungsterTheseBikesAreExpensiveText::
	.DB $00
	.STRINGMAP pokemon, "These BIKEs are"
	.DB $4f
	.STRINGMAP pokemon, "cool, but they're"
	.DB $55
	.STRINGMAP pokemon, "way expensive!"
	.DB $57
_BikeShopYoungsterCoolBikeText::
	.DB $00
	.STRINGMAP pokemon, "Wow. Your BIKE is"
	.DB $4f
	.STRINGMAP pokemon, "really cool!"
	.DB $57

; text/CeruleanMart.asm
_CeruleanMartCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "Use REPEL to keep"
	.DB $4f
	.STRINGMAP pokemon, "bugs and weak"
	.DB $55
	.STRINGMAP pokemon, "#MON away."
	.DB $51
	.STRINGMAP pokemon, "Put your strongest"
	.DB $4f
	.STRINGMAP pokemon, "#MON at the"
	.DB $55
	.STRINGMAP pokemon, "top of the list"
	.DB $55
	.STRINGMAP pokemon, "for best results!"
	.DB $57
_CeruleanMartCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "Have you seen any"
	.DB $4f
	.STRINGMAP pokemon, "RARE CANDY?"
	.DB $51
	.STRINGMAP pokemon, "It's supposed to"
	.DB $4f
	.STRINGMAP pokemon, "make #MON go"
	.DB $55
	.STRINGMAP pokemon, "up one level!"
	.DB $57

; text/CeruleanBadgeHouse.asm
_CeruleanBadgeHouseMiddleAgedManText::
	.DB $00
	.STRINGMAP pokemon, "#MON BADGEs"
	.DB $4f
	.STRINGMAP pokemon, "are owned only by"
	.DB $55
	.STRINGMAP pokemon, "skilled trainers."
	.DB $51
	.STRINGMAP pokemon, "I see you have"
	.DB $4f
	.STRINGMAP pokemon, "at least one."
	.DB $51
	.STRINGMAP pokemon, "Those BADGEs have"
	.DB $4f
	.STRINGMAP pokemon, "amazing secrets!"
	.DB $58
_CeruleanBadgeHouseMiddleAgedManWhichBadgeText::
	.DB $00
	.STRINGMAP pokemon, "Now then..."
	.DB $51
	.STRINGMAP pokemon, "Which of the 8"
	.DB $4f
	.STRINGMAP pokemon, "BADGEs should I"
	.DB $55
	.STRINGMAP pokemon, "describe?"
	.DB $57
_CeruleanBadgeHouseMiddleAgedManVisitAnyTimeText::
	.DB $00
	.STRINGMAP pokemon, "Come visit me any"
	.DB $4f
	.STRINGMAP pokemon, "time you wish."
	.DB $57
_CeruleanBadgeHouseBoulderBadgeText::
	.DB $00
	.STRINGMAP pokemon, "The ATTACK of all"
	.DB $4f
	.STRINGMAP pokemon, "#MON increases"
	.DB $55
	.STRINGMAP pokemon, "a little bit."
	.DB $51
	.STRINGMAP pokemon, "It also lets you"
	.DB $4f
	.STRINGMAP pokemon, "use FLASH any"
	.DB $55
	.STRINGMAP pokemon, "time you desire."
	.DB $58
_CeruleanBadgeHouseCascadeBadgeText::
	.DB $00
	.STRINGMAP pokemon, "#MON up to L30"
	.DB $4f
	.STRINGMAP pokemon, "will obey you."
	.DB $51
	.STRINGMAP pokemon, "Any higher, they"
	.DB $4f
	.STRINGMAP pokemon, "become unruly!"
	.DB $51
	.STRINGMAP pokemon, "It also lets you"
	.DB $4f
	.STRINGMAP pokemon, "use CUT outside"
	.DB $55
	.STRINGMAP pokemon, "of battle."
	.DB $58
_CeruleanBadgeHouseThunderBadgeText::
	.DB $00
	.STRINGMAP pokemon, "The SPEED of all"
	.DB $4f
	.STRINGMAP pokemon, "#MON increases"
	.DB $55
	.STRINGMAP pokemon, "a little bit."
	.DB $51
	.STRINGMAP pokemon, "It also lets you"
	.DB $4f
	.STRINGMAP pokemon, "use FLY outside"
	.DB $55
	.STRINGMAP pokemon, "of battle."
	.DB $58
_CeruleanBadgeHouseRainbowBadgeText::
	.DB $00
	.STRINGMAP pokemon, "#MON up to L50"
	.DB $4f
	.STRINGMAP pokemon, "will obey you."
	.DB $51
	.STRINGMAP pokemon, "Any higher, they"
	.DB $4f
	.STRINGMAP pokemon, "become unruly!"
	.DB $51
	.STRINGMAP pokemon, "It also lets you"
	.DB $4f
	.STRINGMAP pokemon, "use STRENGTH out-"
	.DB $55
	.STRINGMAP pokemon, "side of battle."
	.DB $58
_CeruleanBadgeHouseSoulBadgeText::
	.DB $00
	.STRINGMAP pokemon, "The DEFENSE of all"
	.DB $4f
	.STRINGMAP pokemon, "#MON increases"
	.DB $55
	.STRINGMAP pokemon, "a little bit."
	.DB $51
	.STRINGMAP pokemon, "It also lets you"
	.DB $4f
	.STRINGMAP pokemon, "use SURF outside"
	.DB $55
	.STRINGMAP pokemon, "of battle."
	.DB $58
_CeruleanBadgeHouseMarshBadgeText::
	.DB $00
	.STRINGMAP pokemon, "#MON up to L70"
	.DB $4f
	.STRINGMAP pokemon, "will obey you."
	.DB $51
	.STRINGMAP pokemon, "Any higher, they"
	.DB $4f
	.STRINGMAP pokemon, "become unruly!"
	.DB $58
_CeruleanBadgeHouseVolcanoBadgeText::
	.DB $00
	.STRINGMAP pokemon, "Your #MON's"
	.DB $4f
	.STRINGMAP pokemon, "SPECIAL abilities"
	.DB $55
	.STRINGMAP pokemon, "increase a bit."
	.DB $58
_CeruleanBadgeHouseEarthBadgeText::
	.DB $00
	.STRINGMAP pokemon, "All #MON will"
	.DB $4f
	.STRINGMAP pokemon, "obey you!"
	.DB $58

; text/LavenderPokecenter.asm
_LavenderPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET will"
	.DB $4f
	.STRINGMAP pokemon, "do anything for"
	.DB $55
	.STRINGMAP pokemon, "the sake of gold!"
	.DB $57
_LavenderPokecenterLittleGirlText::
	.DB $00
	.STRINGMAP pokemon, "I saw CUBONE's"
	.DB $4f
	.STRINGMAP pokemon, "mother die trying"
	.DB $55
	.STRINGMAP pokemon, "to escape from"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET!"
	.DB $57

; text/PokemonTower1F.asm
_PokemonTower1FReceptionistText::
	.DB $00
	.STRINGMAP pokemon, "#MON TOWER was"
	.DB $4f
	.STRINGMAP pokemon, "erected in the"
	.DB $55
	.STRINGMAP pokemon, "memory of #MON"
	.DB $55
	.STRINGMAP pokemon, "that had died."
	.DB $57
_PokemonTower1FMiddleAgedWomanText::
	.DB $00
	.STRINGMAP pokemon, "Did you come to"
	.DB $4f
	.STRINGMAP pokemon, "pay respects?"
	.DB $55
	.STRINGMAP pokemon, "Bless you!"
	.DB $57
_PokemonTower1FBaldingGuyText::
	.DB $00
	.STRINGMAP pokemon, "I came to pray"
	.DB $4f
	.STRINGMAP pokemon, "for my CLEFAIRY."
	.DB $51
	.STRINGMAP pokemon, "Sniff! I can't"
	.DB $4f
	.STRINGMAP pokemon, "stop crying..."
	.DB $57
_PokemonTower1FGirlText::
	.DB $00
	.STRINGMAP pokemon, "My GROWLITHE..."
	.DB $4f
	.STRINGMAP pokemon, "Why did you die?"
	.DB $57
_PokemonTower1FChannelerText::
	.DB $00
	.STRINGMAP pokemon, "I am a CHANNELER!"
	.DB $4f
	.STRINGMAP pokemon, "There are spirits"
	.DB $55
	.STRINGMAP pokemon, "up to mischief!"
	.DB $57

; text/PokemonTower2F.asm
_PokemonTower2FRivalWhatBringsYouHereText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Hey,"
	.DB $4f
	.STRINGMAP pokemon, "<PLAYER>! What"
	.DB $55
	.STRINGMAP pokemon, "brings you here?"
	.DB $55
	.STRINGMAP pokemon, "Your #MON"
	.DB $55
	.STRINGMAP pokemon, "don't look dead!"
	.DB $51
	.STRINGMAP pokemon, "I can at least"
	.DB $4f
	.STRINGMAP pokemon, "make them faint!"
	.DB $55
	.STRINGMAP pokemon, "Let's go, pal!"
	.DB $57
_PokemonTower2FRivalDefeatedText::
	.DB $00
	.STRINGMAP pokemon, "What?"
	.DB $4f
	.STRINGMAP pokemon, "You stinker!"
	.DB $51
	.STRINGMAP pokemon, "I took it easy on"
	.DB $4f
	.STRINGMAP pokemon, "you too!"
	.DB $58
_PokemonTower2FRivalVictoryText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Well,"
	.DB $4f
	.STRINGMAP pokemon, "look at all your"
	.DB $55
	.STRINGMAP pokemon, "wimpy #MON!"
	.DB $51
	.STRINGMAP pokemon, "Toughen them up a"
	.DB $4f
	.STRINGMAP pokemon, "bit more!"
	.DB $58
_PokemonTower2FRivalHowsYourDexText::
	.DB $00
	.STRINGMAP pokemon, "How's your #DEX"
	.DB $4f
	.STRINGMAP pokemon, "coming, pal?"
	.DB $55
	.STRINGMAP pokemon, "I just caught a"
	.DB $55
	.STRINGMAP pokemon, "CUBONE!"
	.DB $51
	.STRINGMAP pokemon, "I can't find the"
	.DB $4f
	.STRINGMAP pokemon, "grown-up MAROWAK"
	.DB $55
	.STRINGMAP pokemon, "yet!"
	.DB $51
	.STRINGMAP pokemon, "I doubt there are"
	.DB $4f
	.STRINGMAP pokemon, "any left! Well, I"
	.DB $55
	.STRINGMAP pokemon, "better get going!"
	.DB $55
	.STRINGMAP pokemon, "I've got a lot to"
	.DB $55
	.STRINGMAP pokemon, "accomplish, pal!"
	.DB $51
	.STRINGMAP pokemon, "Smell ya later!"
	.DB $57
_PokemonTower2FChannelerText::
	.DB $00
	.STRINGMAP pokemon, "Even we could not"
	.DB $4f
	.STRINGMAP pokemon, "identify the"
	.DB $55
	.STRINGMAP pokemon, "wayward GHOSTs!"
	.DB $51
	.STRINGMAP pokemon, "A SILPH SCOPE"
	.DB $4f
	.STRINGMAP pokemon, "might be able to"
	.DB $55
	.STRINGMAP pokemon, "unmask them."
	.DB $57

; text/PokemonTower3F.asm
_PokemonTower3FChanneler1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Urrg...Awaa..."
	.DB $4f
	.STRINGMAP pokemon, "Huhu...graa.."
	.DB $57
_PokemonTower3FChanneler1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hwa!"
	.DB $4f
	.STRINGMAP pokemon, "I'm saved!"
	.DB $58
_PokemonTower3FChanneler1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "The GHOSTs can be"
	.DB $4f
	.STRINGMAP pokemon, "identified by the"
	.DB $55
	.STRINGMAP pokemon, "SILPH SCOPE."
	.DB $57
_PokemonTower3FChanneler2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Kekeke...."
	.DB $4f
	.STRINGMAP pokemon, "Kwaaah!"
	.DB $57
_PokemonTower3FChanneler2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hmm?"
	.DB $4f
	.STRINGMAP pokemon, "What am I doing?"
	.DB $58
_PokemonTower3FChanneler2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Sorry! I was"
	.DB $4f
	.STRINGMAP pokemon, "possessed!"
	.DB $57
_PokemonTower3FChanneler3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Be gone!"
	.DB $4f
	.STRINGMAP pokemon, "Evil spirit!"
	.DB $57
_PokemonTower3FChanneler3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whew!"
	.DB $4f
	.STRINGMAP pokemon, "The spirit left!"
	.DB $58
_PokemonTower3FChanneler3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "My friends were"
	.DB $4f
	.STRINGMAP pokemon, "possessed too!"
	.DB $57

; text/PokemonTower4F.asm
_PokemonTower4FChanneler1BattleText::
	.DB $00
	.STRINGMAP pokemon, "GHOST! No!"
	.DB $4f
	.STRINGMAP pokemon, "Kwaaah!"
	.DB $57
_PokemonTower4FChanneler1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Where"
	.DB $4f
	.STRINGMAP pokemon, "is the GHOST?"
	.DB $58
_PokemonTower4FChanneler1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I must have been"
	.DB $4f
	.STRINGMAP pokemon, "dreaming..."
	.DB $57
_PokemonTower4FChanneler2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Be cursed with"
	.DB $4f
	.STRINGMAP pokemon, "me! Kwaaah!"
	.DB $57
_PokemonTower4FChanneler2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "What!"
	.DB $58
_PokemonTower4FChanneler2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "We can't crack"
	.DB $4f
	.STRINGMAP pokemon, "the identity of"
	.DB $55
	.STRINGMAP pokemon, "the GHOSTs."
	.DB $57
_PokemonTower4FChanneler3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Huhuhu..."
	.DB $4f
	.STRINGMAP pokemon, "Beat me not!"
	.DB $57
_PokemonTower4FChanneler3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Huh?"
	.DB $4f
	.STRINGMAP pokemon, "Who? What?"
	.DB $58
_PokemonTower4FChanneler3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "May the departed"
	.DB $4f
	.STRINGMAP pokemon, "souls of #MON"
	.DB $55
	.STRINGMAP pokemon, "rest in peace..."
	.DB $57

; text/PokemonTower5F.asm
_PokemonTower5FChanneler1Text::
	.DB $00
	.STRINGMAP pokemon, "Come, child! I"
	.DB $4f
	.STRINGMAP pokemon, "sealed this space"
	.DB $55
	.STRINGMAP pokemon, "with white magic!"
	.DB $51
	.STRINGMAP pokemon, "You can rest here!"
	.DB $57
_PokemonTower5FChanneler2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Give...me..."
	.DB $4f
	.STRINGMAP pokemon, "your...soul..."
	.DB $57
_PokemonTower5FChanneler2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Gasp!"
	.DB $58
_PokemonTower5FChanneler2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I was under"
	.DB $4f
	.STRINGMAP pokemon, "possession!"
	.DB $57
_PokemonTower5FChanneler3BattleText::
	.DB $00
	.STRINGMAP pokemon, "You...shall..."
	.DB $4f
	.STRINGMAP pokemon, "join...us..."
	.DB $57
_PokemonTower5FChanneler3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "What"
	.DB $4f
	.STRINGMAP pokemon, "a nightmare!"
	.DB $58
_PokemonTower5FChanneler3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I was possessed!"
	.DB $57
_PokemonTower5FChanneler4BattleText::
	.DB $00
	.STRINGMAP pokemon, "Zombies!"
	.DB $57
_PokemonTower5FChanneler4EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Ha?"
	.DB $58
_PokemonTower5FChanneler4AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I regained my"
	.DB $4f
	.STRINGMAP pokemon, "senses!"
	.DB $57
_PokemonTower5FChanneler5BattleText::
	.DB $00
	.STRINGMAP pokemon, "Urgah..."
	.DB $4f
	.STRINGMAP pokemon, "Urff...."
	.DB $57
_PokemonTower5FChanneler5EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whoo!"
	.DB $58
_PokemonTower5FChanneler5AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I fell to evil"
	.DB $4f
	.STRINGMAP pokemon, "spirits despite"
	.DB $55
	.STRINGMAP pokemon, "my training!"
	.DB $57
_PokemonTower5FPurifiedZoneText::
	.DB $00
	.STRINGMAP pokemon, "Entered purified,"
	.DB $4f
	.STRINGMAP pokemon, "protected zone!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER>'s #MON"
	.DB $4f
	.STRINGMAP pokemon, "are fully healed!"
	.DB $57

; text/PokemonTower6F.asm
_PokemonTower6FGhostWasCubonesMotherText::
	.DB $00
	.STRINGMAP pokemon, "The GHOST was the"
	.DB $4f
	.STRINGMAP pokemon, "restless soul of"
	.DB $55
	.STRINGMAP pokemon, "CUBONE's mother!"
	.DB $57
_PokemonTower6FSoulWasCalmedText::
	.DB $00
	.STRINGMAP pokemon, "The mother's soul"
	.DB $4f
	.STRINGMAP pokemon, "was calmed."
	.DB $51
	.STRINGMAP pokemon, "It departed to"
	.DB $4f
	.STRINGMAP pokemon, "the afterlife!"
	.DB $57
_PokemonTower6FChanneler1BattleText::
	.DB $00
	.STRINGMAP pokemon, "Give...me..."
	.DB $4f
	.STRINGMAP pokemon, "blood..."
	.DB $57
_PokemonTower6FChanneler1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Groan!"
	.DB $58
_PokemonTower6FChanneler1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I feel anemic and"
	.DB $4f
	.STRINGMAP pokemon, "weak..."
	.DB $57
_PokemonTower6FChanneler2BattleText::
	.DB $00
	.STRINGMAP pokemon, "Urff... Kwaah!"
	.DB $57
_PokemonTower6FChanneler2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Some-"
	.DB $4f
	.STRINGMAP pokemon, "thing fell out!"
	.DB $58
_PokemonTower6FChanneler2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hair didn't fall"
	.DB $4f
	.STRINGMAP pokemon, "out! It was an"
	.DB $55
	.STRINGMAP pokemon, "evil spirit!"
	.DB $57
_PokemonTower6FChanneler3BattleText::
	.DB $00
	.STRINGMAP pokemon, "Ke..ke...ke..."
	.DB $4f
	.STRINGMAP pokemon, "ke..ke...ke!!"
	.DB $57
_PokemonTower6FChanneler3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Keee!"
	.DB $58
_PokemonTower6FChanneler3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "What's going on"
	.DB $4f
	.STRINGMAP pokemon, "here?"
	.DB $57
_PokemonTower6FBeGoneText::
	.DB $00
	.STRINGMAP pokemon, "Be gone..."
	.DB $4f
	.STRINGMAP pokemon, "Intruders..."
	.DB $57

; text/PokemonTower7F.asm
_PokemonTower7FMrFujiRescueText::
	.DB $00
	.STRINGMAP pokemon, "MR.FUJI: Heh? You"
	.DB $4f
	.STRINGMAP pokemon, "came to save me?"
	.DB $51
	.STRINGMAP pokemon, "Thank you. But, I"
	.DB $4f
	.STRINGMAP pokemon, "came here of my"
	.DB $55
	.STRINGMAP pokemon, "own free will."
	.DB $51
	.STRINGMAP pokemon, "I came to calm"
	.DB $4f
	.STRINGMAP pokemon, "the soul of"
	.DB $55
	.STRINGMAP pokemon, "CUBONE's mother."
	.DB $51
	.STRINGMAP pokemon, "I think MAROWAK's"
	.DB $4f
	.STRINGMAP pokemon, "spirit has gone"
	.DB $55
	.STRINGMAP pokemon, "to the afterlife."
	.DB $51
	.STRINGMAP pokemon, "I must thank you"
	.DB $4f
	.STRINGMAP pokemon, "for your kind"
	.DB $55
	.STRINGMAP pokemon, "concern!"
	.DB $51
	.STRINGMAP pokemon, "Follow me to my"
	.DB $4f
	.STRINGMAP pokemon, "home, #MON"
	.DB $55
	.STRINGMAP pokemon, "HOUSE at the foot"
	.DB $55
	.STRINGMAP pokemon, "of this tower."
	.DB $57
_PokemonTower7FRocket1BattleText::
	.DB $00
	.STRINGMAP pokemon, "What do you want?"
	.DB $4f
	.STRINGMAP pokemon, "Why are you here?"
	.DB $57
_PokemonTower7FRocket1EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "I give up!"
	.DB $58
_PokemonTower7FRocket1AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm not going to"
	.DB $4f
	.STRINGMAP pokemon, "forget this!"
	.DB $57
_PokemonTower7FRocket2BattleText::
	.DB $00
	.STRINGMAP pokemon, "This old guy came"
	.DB $4f
	.STRINGMAP pokemon, "and complained"
	.DB $55
	.STRINGMAP pokemon, "about us harming"
	.DB $55
	.STRINGMAP pokemon, "useless #MON!"
	.DB $51
	.STRINGMAP pokemon, "We're talking it"
	.DB $4f
	.STRINGMAP pokemon, "over as adults!"
	.DB $57
_PokemonTower7FRocket2EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Please!"
	.DB $4f
	.STRINGMAP pokemon, "No more!"
	.DB $58
_PokemonTower7FRocket2AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "#MON are only"
	.DB $4f
	.STRINGMAP pokemon, "good for making"
	.DB $55
	.STRINGMAP pokemon, "money!"
	.DB $51
	.STRINGMAP pokemon, "Stay out of our"
	.DB $4f
	.STRINGMAP pokemon, "business!"
	.DB $57
_PokemonTower7FRocket3BattleText::
	.DB $00
	.STRINGMAP pokemon, "You're not saving"
	.DB $4f
	.STRINGMAP pokemon, "anyone, kid!"
	.DB $57
_PokemonTower7FRocket3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Don't"
	.DB $4f
	.STRINGMAP pokemon, "fight us ROCKETs!"
	.DB $58
_PokemonTower7FRocket3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "You're not getting"
	.DB $4f
	.STRINGMAP pokemon, "away with this!"
	.DB $57

; text/MrFujisHouse.asm
_MrFujisHouseSuperNerdMrFujiIsntHereText::
	.DB $00
	.STRINGMAP pokemon, "That's odd, MR.FUJI"
	.DB $4f
	.STRINGMAP pokemon, "isn't here."
	.DB $55
	.STRINGMAP pokemon, "Where'd he go?"
	.DB $57
_MrFujisHouseSuperNerdMrFujiHadBeenPrayingText::
	.DB $00
	.STRINGMAP pokemon, "MR.FUJI had been"
	.DB $4f
	.STRINGMAP pokemon, "praying alone for"
	.DB $55
	.STRINGMAP pokemon, "CUBONE's mother."
	.DB $57
_MrFujisHouseLittleGirlThisIsMrFujisHouseText::
	.DB $00
	.STRINGMAP pokemon, "This is really"
	.DB $4f
	.STRINGMAP pokemon, "MR.FUJI's house."
	.DB $51
	.STRINGMAP pokemon, "He's really kind!"
	.DB $51
	.STRINGMAP pokemon, "He looks after"
	.DB $4f
	.STRINGMAP pokemon, "abandoned and"
	.DB $55
	.STRINGMAP pokemon, "orphaned #MON!"
	.DB $57
_MrFujisHouseLittleGirlPokemonAreNiceToHugText::
	.DB $00
	.STRINGMAP pokemon, "It's so warm!"
	.DB $4f
	.STRINGMAP pokemon, "#MON are so"
	.DB $55
	.STRINGMAP pokemon, "nice to hug!"
	.DB $57
_MrFujisHousePsyduckText::
	.DB $00
	.STRINGMAP pokemon, "PSYDUCK: Gwappa!@"
	.DB $50
_MrFujisHouseNidorinoText::
	.DB $00
	.STRINGMAP pokemon, "NIDORINO: Gaoo!@"
	.DB $50
_MrFujisHouseMrFujiIThinkThisMayHelpYourQuestText::
	.DB $00
	.STRINGMAP pokemon, "MR.FUJI: <PLAYER>."
	.DB $51
	.STRINGMAP pokemon, "Your #DEX quest"
	.DB $4f
	.STRINGMAP pokemon, "may fail without"
	.DB $55
	.STRINGMAP pokemon, "love for your"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $51
	.STRINGMAP pokemon, "I think this may"
	.DB $4f
	.STRINGMAP pokemon, "help your quest."
	.DB $58
_MrFujisHouseMrFujiReceivedPokeFluteText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "a @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_MrFujisHouseMrFujiPokeFluteExplanationText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "Upon hearing #"
	.DB $4f
	.STRINGMAP pokemon, "FLUTE, sleeping"
	.DB $55
	.STRINGMAP pokemon, "#MON will"
	.DB $55
	.STRINGMAP pokemon, "spring awake."
	.DB $51
	.STRINGMAP pokemon, "It works on all"
	.DB $4f
	.STRINGMAP pokemon, "sleeping #MON."
	.DB $57
_MrFujisHouseMrFujiPokeFluteNoRoomText::
	.DB $00
	.STRINGMAP pokemon, "You must make"
	.DB $4f
	.STRINGMAP pokemon, "room for this!"
	.DB $57
_MrFujisHouseMrFujiHasMyFluteHelpedYouText::
	.DB $00
	.STRINGMAP pokemon, "MR.FUJI: Has my"
	.DB $4f
	.STRINGMAP pokemon, "FLUTE helped you?"
	.DB $57
_MrFujisHouseMrFujiPokedexText::
	.DB $00
	.STRINGMAP pokemon, "#MON Monthly"
	.DB $4f
	.STRINGMAP pokemon, "Grand Prize"
	.DB $55
	.STRINGMAP pokemon, "Drawing!"
	.DB $51
	.STRINGMAP pokemon, "The application"
	.DB $4f
	.STRINGMAP pokemon, "form is..."
	.DB $51
	.STRINGMAP pokemon, "Gone! It's been"
	.DB $4f
	.STRINGMAP pokemon, "clipped out!"
	.DB $57

; text/LavenderMart.asm
_LavenderMartBaldingGuyText::
	.DB $00
	.STRINGMAP pokemon, "I'm searching for"
	.DB $4f
	.STRINGMAP pokemon, "items that raise"
	.DB $55
	.STRINGMAP pokemon, "the abilities of"
	.DB $55
	.STRINGMAP pokemon, "#MON during a"
	.DB $55
	.STRINGMAP pokemon, "single battle."
	.DB $51
	.STRINGMAP pokemon, "X ATTACK, X"
	.DB $4f
	.STRINGMAP pokemon, "DEFEND, X SPEED"
	.DB $55
	.STRINGMAP pokemon, "and X SPECIAL are"
	.DB $55
	.STRINGMAP pokemon, "what I'm after."
	.DB $51
	.STRINGMAP pokemon, "Do you know where"
	.DB $4f
	.STRINGMAP pokemon, "I can get them?"
	.DB $57
_LavenderMartCooltrainerMReviveText::
	.DB $00
	.STRINGMAP pokemon, "You know REVIVE?"
	.DB $4f
	.STRINGMAP pokemon, "It revives any"
	.DB $55
	.STRINGMAP pokemon, "fainted #MON!"
	.DB $57
_LavenderMartCooltrainerMNuggetText::
	.DB $00
	.STRINGMAP pokemon, "I found a NUGGET"
	.DB $4f
	.STRINGMAP pokemon, "in the mountains."
	.DB $51
	.STRINGMAP pokemon, "I thought it was"
	.DB $4f
	.STRINGMAP pokemon, "useless, but it"
	.DB $55
	.STRINGMAP pokemon, "sold for ¥5000!"
	.DB $57

; text/LavenderCuboneHouse.asm
_LavenderCuboneHouseCuboneText::
	.DB $00
	.STRINGMAP pokemon, "CUBONE: Kyarugoo!@"
	.DB $50
_LavenderCuboneHouseBrunetteGirlPoorCubonesMotherText::
	.DB $00
	.STRINGMAP pokemon, "I hate those"
	.DB $4f
	.STRINGMAP pokemon, "horrible ROCKETs!"
	.DB $51
	.STRINGMAP pokemon, "That poor CUBONE's"
	.DB $4f
	.STRINGMAP pokemon, "mother..."
	.DB $51
	.STRINGMAP pokemon, "It was killed"
	.DB $4f
	.STRINGMAP pokemon, "trying to escape"
	.DB $55
	.STRINGMAP pokemon, "from TEAM ROCKET!"
	.DB $57
_LavenderCuboneHouseBrunetteGirlGhostIsGoneText::
	.DB $00
	.STRINGMAP pokemon, "The GHOST of"
	.DB $4f
	.STRINGMAP pokemon, "#MON TOWER is"
	.DB $55
	.STRINGMAP pokemon, "gone!"
	.DB $51
	.STRINGMAP pokemon, "Someone must have"
	.DB $4f
	.STRINGMAP pokemon, "soothed its"
	.DB $55
	.STRINGMAP pokemon, "restless soul!"
	.DB $57

; text/NameRatersHouse.asm
_NameRatersHouseNameRaterWantMeToRateText::
	.DB $00
	.STRINGMAP pokemon, "Hello, hello!"
	.DB $4f
	.STRINGMAP pokemon, "I am the official"
	.DB $55
	.STRINGMAP pokemon, "NAME RATER!"
	.DB $51
	.STRINGMAP pokemon, "Want me to rate"
	.DB $4f
	.STRINGMAP pokemon, "the nicknames of"
	.DB $55
	.STRINGMAP pokemon, "your #MON?"
	.DB $57
_NameRatersHouseNameRaterWhichPokemonText::
	.DB $00
	.STRINGMAP pokemon, "Which #MON"
	.DB $4f
	.STRINGMAP pokemon, "should I look at?"
	.DB $58
_NameRatersHouseNameRaterGiveItANiceNameText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, ", is it?"
	.DB $4f
	.STRINGMAP pokemon, "That is a decent"
	.DB $55
	.STRINGMAP pokemon, "nickname!"
	.DB $51
	.STRINGMAP pokemon, "But, would you"
	.DB $4f
	.STRINGMAP pokemon, "like me to give"
	.DB $55
	.STRINGMAP pokemon, "it a nicer name?"
	.DB $51
	.STRINGMAP pokemon, "How about it?"
	.DB $57
_NameRatersHouseNameRaterWhatShouldWeNameItText::
	.DB $00
	.STRINGMAP pokemon, "Fine! What should"
	.DB $4f
	.STRINGMAP pokemon, "we name it?"
	.DB $58
_NameRatersHouseNameRaterPokemonHasBeenRenamedText::
	.DB $00
	.STRINGMAP pokemon, "OK! This #MON"
	.DB $4f
	.STRINGMAP pokemon, "has been renamed"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "That's a better"
	.DB $4f
	.STRINGMAP pokemon, "name than before!"
	.DB $57
_NameRatersHouseNameRaterComeAnyTimeYouLikeText::
	.DB $00
	.STRINGMAP pokemon, "Fine! Come any"
	.DB $4f
	.STRINGMAP pokemon, "time you like!"
	.DB $57
_NameRatersHouseNameRaterATrulyImpeccableNameText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, ", is it?"
	.DB $4f
	.STRINGMAP pokemon, "That is a truly"
	.DB $55
	.STRINGMAP pokemon, "impeccable name!"
	.DB $51
	.STRINGMAP pokemon, "Take good care of"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57

; text/VermilionPokecenter.asm
_VermilionPokecenterFishingGuruText::
	.DB $00
	.STRINGMAP pokemon, "Even if they are"
	.DB $4f
	.STRINGMAP pokemon, "the same level,"
	.DB $55
	.STRINGMAP pokemon, "#MON can have"
	.DB $55
	.STRINGMAP pokemon, "very different"
	.DB $55
	.STRINGMAP pokemon, "abilities."
	.DB $51
	.STRINGMAP pokemon, "A #MON raised"
	.DB $4f
	.STRINGMAP pokemon, "by a trainer is"
	.DB $55
	.STRINGMAP pokemon, "stronger than one"
	.DB $55
	.STRINGMAP pokemon, "in the wild."
	.DB $57
_VermilionPokecenterSailorText::
	.DB $00
	.STRINGMAP pokemon, "My #MON was"
	.DB $4f
	.STRINGMAP pokemon, "poisoned! It"
	.DB $55
	.STRINGMAP pokemon, "fainted while we"
	.DB $55
	.STRINGMAP pokemon, "were walking!"
	.DB $57

; text/PokemonFanClub.asm
_PokemonFanClubPikachuFanNormalText::
	.DB $00
	.STRINGMAP pokemon, "Won't you admire"
	.DB $4f
	.STRINGMAP pokemon, "my PIKACHU's"
	.DB $55
	.STRINGMAP pokemon, "adorable tail?"
	.DB $57
_PokemonFanClubPikachuFanBetterText::
	.DB $00
	.STRINGMAP pokemon, "Humph! My PIKACHU"
	.DB $4f
	.STRINGMAP pokemon, "is twice as cute"
	.DB $55
	.STRINGMAP pokemon, "as that one!"
	.DB $57
_PokemonFanClubSeelFanNormalText::
	.DB $00
	.STRINGMAP pokemon, "I just love my"
	.DB $4f
	.STRINGMAP pokemon, "SEEL!"
	.DB $51
	.STRINGMAP pokemon, "It squeals when I"
	.DB $4f
	.STRINGMAP pokemon, "hug it!"
	.DB $57
_PokemonFanClubSeelFanBetterText::
	.DB $00
	.STRINGMAP pokemon, "Oh dear!"
	.DB $51
	.STRINGMAP pokemon, "My SEEL is far"
	.DB $4f
	.STRINGMAP pokemon, "more attractive!"
	.DB $57
_PokemonFanClubPikachuText::
	.DB $00
	.STRINGMAP pokemon, "PIKACHU: Chu!"
	.DB $4f
	.STRINGMAP pokemon, "Pikachu!"
	.DB $57
_PokemonFanClubSeelText::
	.DB $00
	.STRINGMAP pokemon, "SEEL: Kyuoo!"
	.DB $57
_PokemonFanClubChairmanIntroText::
	.DB $00
	.STRINGMAP pokemon, "I chair the"
	.DB $4f
	.STRINGMAP pokemon, "#MON Fan Club!"
	.DB $51
	.STRINGMAP pokemon, "I have collected"
	.DB $4f
	.STRINGMAP pokemon, "over 100 #MON!"
	.DB $51
	.STRINGMAP pokemon, "I'm very fussy"
	.DB $4f
	.STRINGMAP pokemon, "when it comes to"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $51
	.STRINGMAP pokemon, "So..."
	.DB $51
	.STRINGMAP pokemon, "Did you come"
	.DB $4f
	.STRINGMAP pokemon, "visit to hear"
	.DB $55
	.STRINGMAP pokemon, "about my #MON?"
	.DB $57
_PokemonFanClubChairmanStoryText::
	.DB $00
	.STRINGMAP pokemon, "Good!"
	.DB $4f
	.STRINGMAP pokemon, "Then listen up!"
	.DB $51
	.STRINGMAP pokemon, "My favorite"
	.DB $4f
	.STRINGMAP pokemon, "RAPIDASH..."
	.DB $51
	.STRINGMAP pokemon, "It...cute..."
	.DB $4f
	.STRINGMAP pokemon, "lovely...smart..."
	.DB $55
	.STRINGMAP pokemon, "plus...amazing..."
	.DB $55
	.STRINGMAP pokemon, "you think so?..."
	.DB $55
	.STRINGMAP pokemon, "oh yes...it..."
	.DB $55
	.STRINGMAP pokemon, "stunning..."
	.DB $55
	.STRINGMAP pokemon, "kindly..."
	.DB $55
	.STRINGMAP pokemon, "love it!"
	.DB $51
	.STRINGMAP pokemon, "Hug it...when..."
	.DB $55
	.STRINGMAP pokemon, "sleeping...warm"
	.DB $55
	.STRINGMAP pokemon, "and cuddly..."
	.DB $55
	.STRINGMAP pokemon, "spectacular..."
	.DB $55
	.STRINGMAP pokemon, "ravishing..."
	.DB $55
	.STRINGMAP pokemon, "...Oops! Look at"
	.DB $55
	.STRINGMAP pokemon, "the time! I kept"
	.DB $55
	.STRINGMAP pokemon, "you too long!"
	.DB $51
	.STRINGMAP pokemon, "Thanks for hearing"
	.DB $4f
	.STRINGMAP pokemon, "me out! I want"
	.DB $55
	.STRINGMAP pokemon, "you to have this!"
	.DB $58
_PokemonFanClubReceivedBikeVoucherText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> received"
	.DB $4f
	.STRINGMAP pokemon, "a @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_PokemonFanClubExplainBikeVoucherText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "Exchange that for"
	.DB $4f
	.STRINGMAP pokemon, "a BICYCLE!"
	.DB $51
	.STRINGMAP pokemon, "Don't worry, my"
	.DB $4f
	.STRINGMAP pokemon, "FEAROW will FLY"
	.DB $55
	.STRINGMAP pokemon, "me anywhere!"
	.DB $51
	.STRINGMAP pokemon, "So, I don't need a"
	.DB $4f
	.STRINGMAP pokemon, "BICYCLE!"
	.DB $51
	.STRINGMAP pokemon, "I hope you like"
	.DB $4f
	.STRINGMAP pokemon, "cycling!"
	.DB $57
_PokemonFanClubNoStoryText::
	.DB $00
	.STRINGMAP pokemon, "Oh. Come back"
	.DB $4f
	.STRINGMAP pokemon, "when you want to"
	.DB $55
	.STRINGMAP pokemon, "hear my story!"
	.DB $57
_PokemonFanClubChairFinalText::
	.DB $00
	.STRINGMAP pokemon, "Hello, <PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "Did you come see"
	.DB $4f
	.STRINGMAP pokemon, "me about my"
	.DB $55
	.STRINGMAP pokemon, "#MON again?"
	.DB $51
	.STRINGMAP pokemon, "No? Too bad!"
	.DB $57
_PokemonFanClubBagFullText::
	.DB $00
	.STRINGMAP pokemon, "Make room for"
	.DB $4f
	.STRINGMAP pokemon, "this!"
	.DB $57
_PokemonFanClubReceptionistText::
	.DB $00
	.STRINGMAP pokemon, "Our Chairman is"
	.DB $4f
	.STRINGMAP pokemon, "very vocal about"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $57
_PokemonFanClubSign1Text::
	.DB $00
	.STRINGMAP pokemon, "Let's all listen"
	.DB $4f
	.STRINGMAP pokemon, "politely to other"
	.DB $55
	.STRINGMAP pokemon, "trainers!"
	.DB $57
_PokemonFanClubSign2Text::
	.DB $00
	.STRINGMAP pokemon, "If someone brags,"
	.DB $4f
	.STRINGMAP pokemon, "brag right back!"
	.DB $57

; text/VermilionMart.asm
_VermilionMartCooltrainerMText::
	.DB $00
	.STRINGMAP pokemon, "There are evil"
	.DB $4f
	.STRINGMAP pokemon, "people who will"
	.DB $55
	.STRINGMAP pokemon, "use #MON for"
	.DB $55
	.STRINGMAP pokemon, "criminal acts."
	.DB $51
	.STRINGMAP pokemon, "TEAM ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "traffics in rare"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $51
	.STRINGMAP pokemon, "They also abandon"
	.DB $4f
	.STRINGMAP pokemon, "#MON that they"
	.DB $55
	.STRINGMAP pokemon, "consider not to"
	.DB $55
	.STRINGMAP pokemon, "be popular or"
	.DB $55
	.STRINGMAP pokemon, "useful."
	.DB $57
_VermilionMartCooltrainerFText::
	.DB $00
	.STRINGMAP pokemon, "I think #MON"
	.DB $4f
	.STRINGMAP pokemon, "can be good or"
	.DB $55
	.STRINGMAP pokemon, "evil. It depends"
	.DB $55
	.STRINGMAP pokemon, "on the trainer."
	.DB $57

; text/VermilionGym.asm
_VermilionGymLTSurgePreBattleText::
	.DB $00
	.STRINGMAP pokemon, "Hey, kid! What do"
	.DB $4f
	.STRINGMAP pokemon, "you think you're"
	.DB $55
	.STRINGMAP pokemon, "doing here?"
	.DB $51
	.STRINGMAP pokemon, "You won't live"
	.DB $4f
	.STRINGMAP pokemon, "long in combat!"
	.DB $55
	.STRINGMAP pokemon, "That's for sure!"
	.DB $51
	.STRINGMAP pokemon, "I tell you kid,"
	.DB $4f
	.STRINGMAP pokemon, "electric #MON"
	.DB $55
	.STRINGMAP pokemon, "saved me during"
	.DB $55
	.STRINGMAP pokemon, "the war!"
	.DB $51
	.STRINGMAP pokemon, "They zapped my"
	.DB $4f
	.STRINGMAP pokemon, "enemies into"
	.DB $55
	.STRINGMAP pokemon, "paralysis!"
	.DB $51
	.STRINGMAP pokemon, "The same as I'll"
	.DB $4f
	.STRINGMAP pokemon, "do to you!"
	.DB $57

Bank38TextEnd::
