; Generated by convert_text_bank.py from:
;   text/RockTunnelB1F_2.asm
;   text/SeafoamIslandsB4F.asm
;   data/text/text_2.asm
;   text/DiglettsCaveRoute2.asm
;   text/ViridianForestNorthGate.asm
;   text/Route2TradeHouse.asm
;   text/Route2Gate.asm
;   text/ViridianForestSouthGate.asm
;   text/MtMoonPokecenter.asm
;   text/SaffronGates.asm
;   text/Daycare.asm
.STRINGMAPTABLE pokemon "wla/pokemon.tbl"

; text/RockTunnelB1F_2.asm
_RockTunnelB1FHiker3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'll raise my"
	.DB $4f
	.STRINGMAP pokemon, "#MON to beat"
	.DB $55
	.STRINGMAP pokemon, "yours, kid!"
	.DB $57
_RockTunnelB1FSuperNerd3BattleText::
	.DB $00
	.STRINGMAP pokemon, "I draw #MON"
	.DB $4f
	.STRINGMAP pokemon, "when I'm home."
	.DB $57
_RockTunnelB1FSuperNerd3EndBattleText::
	.DB $00
	.STRINGMAP pokemon, "Whew!"
	.DB $4f
	.STRINGMAP pokemon, "I'm exhausted!"
	.DB $58
_RockTunnelB1FSuperNerd3AfterBattleText::
	.DB $00
	.STRINGMAP pokemon, "I'm an artist,"
	.DB $4f
	.STRINGMAP pokemon, "not a fighter."
	.DB $57

; text/SeafoamIslandsB4F.asm
_SeafoamIslandsB4FArticunoBattleText::
	.DB $00
	.STRINGMAP pokemon, "Gyaoo!@"
	.DB $50
_SeafoamIslandsB4FBouldersSignText::
	.DB $00
	.STRINGMAP pokemon, "Boulders might"
	.DB $4f
	.STRINGMAP pokemon, "change the flow"
	.DB $55
	.STRINGMAP pokemon, "of water!"
	.DB $57
_SeafoamIslandsB4FDangerSignText::
	.DB $00
	.STRINGMAP pokemon, "DANGER"
	.DB $4f
	.STRINGMAP pokemon, "Fast current!"
	.DB $57

; data/text/text_2.asm
_AIBattleWithdrawText::
	.DB $01
	.DW wTrainerName
	.DB $00
	.STRINGMAP pokemon, " with-"
	.DB $4f
	.STRINGMAP pokemon, "drew @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_AIBattleUseItemText::
	.DB $01
	.DW wTrainerName
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "used @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $55
	.STRINGMAP pokemon, "on @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_TradeWentToText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " went"
	.DB $4f
	.STRINGMAP pokemon, "to @"
	.DB $01
	.DW wLinkEnemyTrainerName
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $57
_TradeForText::
	.DB $00
	.STRINGMAP pokemon, "For <PLAYER>'s"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, ","
	.DB $57
_TradeSendsText::
	.DB $01
	.DW wLinkEnemyTrainerName
	.DB $00
	.STRINGMAP pokemon, " sends"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $57
_TradeWavesFarewellText::
	.DB $01
	.DW wLinkEnemyTrainerName
	.DB $00
	.STRINGMAP pokemon, " waves"
	.DB $4f
	.STRINGMAP pokemon, "farewell as"
	.DB $57
_TradeTransferredText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " is"
	.DB $4f
	.STRINGMAP pokemon, "transferred."
	.DB $57
_TradeTakeCareText::
	.DB $00
	.STRINGMAP pokemon, "Take good care of"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $57
_TradeWillTradeText::
	.DB $01
	.DW wLinkEnemyTrainerName
	.DB $00
	.STRINGMAP pokemon, " will"
	.DB $4f
	.STRINGMAP pokemon, "trade @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $57
_TradeforText::
	.DB $00
	.STRINGMAP pokemon, "for <PLAYER>'s"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $57
_PlaySlotMachineText::
	.DB $00
	.STRINGMAP pokemon, "A slot machine!"
	.DB $4f
	.STRINGMAP pokemon, "Want to play?"
	.DB $57
_OutOfCoinsSlotMachineText::
	.DB $00
	.STRINGMAP pokemon, "Darn!"
	.DB $4f
	.STRINGMAP pokemon, "Ran out of coins!"
	.DB $57
_BetHowManySlotMachineText::
	.DB $00
	.STRINGMAP pokemon, "Bet how many"
	.DB $4f
	.STRINGMAP pokemon, "coins?"
	.DB $57
_StartSlotMachineText::
	.DB $00
	.STRINGMAP pokemon, "Start!"
	.DB $57
_NotEnoughCoinsSlotMachineText::
	.DB $00
	.STRINGMAP pokemon, "Not enough"
	.DB $4f
	.STRINGMAP pokemon, "coins!"
	.DB $58
_OneMoreGoSlotMachineText::
	.DB $00
	.STRINGMAP pokemon, "One more "
	.DB $4f
	.STRINGMAP pokemon, "go?"
	.DB $57
_LinedUpText::
	.DB $00
	.STRINGMAP pokemon, " lined up!"
	.DB $4f
	.STRINGMAP pokemon, "Scored @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " coins!"
	.DB $57
_NotThisTimeText::
	.DB $00
	.STRINGMAP pokemon, "Not this time!"
	.DB $58
_YeahText::
	.DB $00
	.STRINGMAP pokemon, "Yeah!@"
	.DB $50
_DexSeenOwnedText::
	.DB $00
	.STRINGMAP pokemon, "#DEX   Seen:@"
	.DB $09
	.DW wDexRatingNumMonsSeen
	.DB $13
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "         Owned:@"
	.DB $09
	.DW wDexRatingNumMonsOwned
	.DB $13
	.DB $50
_DexRatingText::
	.DB $00
	.STRINGMAP pokemon, "#DEX Rating<COLON>"
	.DB $57
_GymStatueText1::
	.DB $01
	.DW wGymCityName
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: @"
	.DB $01
	.DW wGymLeaderName
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "WINNING TRAINERS:"
	.DB $4f
	.STRINGMAP pokemon, "<RIVAL>"
	.DB $57
_GymStatueText2::
	.DB $01
	.DW wGymCityName
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "#MON GYM"
	.DB $55
	.STRINGMAP pokemon, "LEADER: @"
	.DB $01
	.DW wGymLeaderName
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "WINNING TRAINERS:"
	.DB $4f
	.STRINGMAP pokemon, "<RIVAL>"
	.DB $55
	.STRINGMAP pokemon, "<PLAYER>"
	.DB $57
_ViridianCityPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "#MON CENTERs"
	.DB $4f
	.STRINGMAP pokemon, "heal your tired,"
	.DB $55
	.STRINGMAP pokemon, "hurt or fainted"
	.DB $55
	.STRINGMAP pokemon, "#MON!"
	.DB $57
_PewterCityPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "Yawn!"
	.DB $51
	.STRINGMAP pokemon, "When JIGGLYPUFF"
	.DB $4f
	.STRINGMAP pokemon, "sings, #MON"
	.DB $55
	.STRINGMAP pokemon, "get drowsy..."
	.DB $51
	.STRINGMAP pokemon, "...Me too..."
	.DB $4f
	.STRINGMAP pokemon, "Snore..."
	.DB $57
_CeruleanPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "BILL has lots of"
	.DB $4f
	.STRINGMAP pokemon, "#MON!"
	.DB $51
	.STRINGMAP pokemon, "He collects rare"
	.DB $4f
	.STRINGMAP pokemon, "ones too!"
	.DB $57
_LavenderPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "CUBONEs wear"
	.DB $4f
	.STRINGMAP pokemon, "skulls, right?"
	.DB $51
	.STRINGMAP pokemon, "People will pay a"
	.DB $4f
	.STRINGMAP pokemon, "lot for one!"
	.DB $57
_MtMoonPokecenterBenchGuyText::
	.DB $00
	.STRINGMAP pokemon, "If you have too"
	.DB $4f
	.STRINGMAP pokemon, "many #MON, you"
	.DB $55
	.STRINGMAP pokemon, "should store them"
	.DB $55
	.STRINGMAP pokemon, "via PC!"
	.DB $57
_RockTunnelPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "I heard that"
	.DB $4f
	.STRINGMAP pokemon, "GHOSTs haunt"
	.DB $55
	.STRINGMAP pokemon, "LAVENDER TOWN!"
	.DB $57
_UnusedBenchGuyText1::
	.DB $00
	.STRINGMAP pokemon, "I wish I could"
	.DB $4f
	.STRINGMAP pokemon, "catch #MON."
	.DB $57
_UnusedBenchGuyText2::
	.DB $00
	.STRINGMAP pokemon, "I'm tired from"
	.DB $4f
	.STRINGMAP pokemon, "all the fun..."
	.DB $57
_UnusedBenchGuyText3::
	.DB $00
	.STRINGMAP pokemon, "SILPH's manager"
	.DB $4f
	.STRINGMAP pokemon, "is hiding in the"
	.DB $55
	.STRINGMAP pokemon, "SAFARI ZONE."
	.DB $57
_VermilionPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "It is true that a"
	.DB $4f
	.STRINGMAP pokemon, "higher level"
	.DB $55
	.STRINGMAP pokemon, "#MON will be"
	.DB $55
	.STRINGMAP pokemon, "more powerful..."
	.DB $51
	.STRINGMAP pokemon, "But, all #MON"
	.DB $4f
	.STRINGMAP pokemon, "will have weak"
	.DB $55
	.STRINGMAP pokemon, "points against"
	.DB $55
	.STRINGMAP pokemon, "specific types."
	.DB $51
	.STRINGMAP pokemon, "So, there is no"
	.DB $4f
	.STRINGMAP pokemon, "universally"
	.DB $55
	.STRINGMAP pokemon, "strong #MON."
	.DB $57
_CeladonCityPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "If I had a BIKE,"
	.DB $4f
	.STRINGMAP pokemon, "I would go to"
	.DB $55
	.STRINGMAP pokemon, "CYCLING ROAD!"
	.DB $57
_FuchsiaCityPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "If you're studying "
	.DB $4f
	.STRINGMAP pokemon, "#MON, visit"
	.DB $55
	.STRINGMAP pokemon, "the SAFARI ZONE."
	.DB $51
	.STRINGMAP pokemon, "It has all sorts"
	.DB $4f
	.STRINGMAP pokemon, "of rare #MON."
	.DB $57
_CinnabarPokecenterGuyText::
	.DB $00
	.STRINGMAP pokemon, "#MON can still"
	.DB $4f
	.STRINGMAP pokemon, "learn techniques"
	.DB $55
	.STRINGMAP pokemon, "after canceling"
	.DB $55
	.STRINGMAP pokemon, "evolution."
	.DB $51
	.STRINGMAP pokemon, "Evolution can wait"
	.DB $4f
	.STRINGMAP pokemon, "until new moves"
	.DB $55
	.STRINGMAP pokemon, "have been learned."
	.DB $57
_SaffronCityPokecenterGuyText1::
	.DB $00
	.STRINGMAP pokemon, "It would be great"
	.DB $4f
	.STRINGMAP pokemon, "if the ELITE FOUR"
	.DB $55
	.STRINGMAP pokemon, "came and stomped"
	.DB $55
	.STRINGMAP pokemon, "TEAM ROCKET!"
	.DB $57
_SaffronCityPokecenterGuyText2::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET took"
	.DB $4f
	.STRINGMAP pokemon, "off! We can go"
	.DB $55
	.STRINGMAP pokemon, "out safely again!"
	.DB $55
	.STRINGMAP pokemon, "That's great!"
	.DB $57
_CeladonCityHotelText::
	.DB $00
	.STRINGMAP pokemon, "My sis brought me"
	.DB $4f
	.STRINGMAP pokemon, "on this vacation!"
	.DB $57
_BookcaseText::
	.DB $00
	.STRINGMAP pokemon, "Crammed full of"
	.DB $4f
	.STRINGMAP pokemon, "#MON books!"
	.DB $57
_NewBicycleText::
	.DB $00
	.STRINGMAP pokemon, "A shiny new"
	.DB $4f
	.STRINGMAP pokemon, "BICYCLE!"
	.DB $57
_PushStartText::
	.DB $00
	.STRINGMAP pokemon, "Push START to"
	.DB $4f
	.STRINGMAP pokemon, "open the MENU!"
	.DB $57
_SaveOptionText::
	.DB $00
	.STRINGMAP pokemon, "The SAVE option is"
	.DB $4f
	.STRINGMAP pokemon, "on the MENU"
	.DB $55
	.STRINGMAP pokemon, "screen."
	.DB $57
_StrengthsAndWeaknessesText::
	.DB $00
	.STRINGMAP pokemon, "All #MON types"
	.DB $4f
	.STRINGMAP pokemon, "have strong and"
	.DB $55
	.STRINGMAP pokemon, "weak points"
	.DB $55
	.STRINGMAP pokemon, "against others."
	.DB $57
_TimesUpText::
	.DB $00
	.STRINGMAP pokemon, "PA: Ding-dong!"
	.DB $51
	.STRINGMAP pokemon, "Time's up!"
	.DB $58
_GameOverText::
	.DB $00
	.STRINGMAP pokemon, "PA: Your SAFARI"
	.DB $4f
	.STRINGMAP pokemon, "GAME is over!"
	.DB $57
_CinnabarGymQuizIntroText::
	.DB $00
	.STRINGMAP pokemon, "#MON Quiz!"
	.DB $51
	.STRINGMAP pokemon, "Get it right and"
	.DB $4f
	.STRINGMAP pokemon, "the door opens to"
	.DB $55
	.STRINGMAP pokemon, "the next room!"
	.DB $51
	.STRINGMAP pokemon, "Get it wrong and"
	.DB $4f
	.STRINGMAP pokemon, "face a trainer!"
	.DB $51
	.STRINGMAP pokemon, "If you want to"
	.DB $4f
	.STRINGMAP pokemon, "conserve your"
	.DB $55
	.STRINGMAP pokemon, "#MON for the"
	.DB $55
	.STRINGMAP pokemon, "GYM LEADER..."
	.DB $51
	.STRINGMAP pokemon, "Then get it right!"
	.DB $4f
	.STRINGMAP pokemon, "Here we go!"
	.DB $58
_CinnabarQuizQuestionsText1::
	.DB $00
	.STRINGMAP pokemon, "CATERPIE evolves"
	.DB $4f
	.STRINGMAP pokemon, "into BUTTERFREE?"
	.DB $57
_CinnabarQuizQuestionsText2::
	.DB $00
	.STRINGMAP pokemon, "There are 9"
	.DB $4f
	.STRINGMAP pokemon, "certified #MON"
	.DB $55
	.STRINGMAP pokemon, "LEAGUE BADGEs?"
	.DB $57
_CinnabarQuizQuestionsText3::
	.DB $00
	.STRINGMAP pokemon, "POLIWAG evolves 3"
	.DB $4f
	.STRINGMAP pokemon, "times?"
	.DB $57
_CinnabarQuizQuestionsText4::
	.DB $00
	.STRINGMAP pokemon, "Are thunder moves"
	.DB $4f
	.STRINGMAP pokemon, "effective against"
	.DB $55
	.STRINGMAP pokemon, "ground element-"
	.DB $55
	.STRINGMAP pokemon, "type #MON?"
	.DB $57
_CinnabarQuizQuestionsText5::
	.DB $00
	.STRINGMAP pokemon, "#MON of the"
	.DB $4f
	.STRINGMAP pokemon, "same kind and"
	.DB $55
	.STRINGMAP pokemon, "level are not"
	.DB $55
	.STRINGMAP pokemon, "identical?"
	.DB $57
_CinnabarQuizQuestionsText6::
	.DB $00
	.STRINGMAP pokemon, "TM28 contains"
	.DB $4f
	.STRINGMAP pokemon, "TOMBSTONER?"
	.DB $57
_CinnabarGymQuizCorrectText::
	.DB $00
	.STRINGMAP pokemon, "You're absolutely"
	.DB $4f
	.STRINGMAP pokemon, "correct!"
	.DB $51
	.STRINGMAP pokemon, "Go on through!@"
	.DB $50
_CinnabarGymQuizIncorrectText::
	.DB $00
	.STRINGMAP pokemon, "Sorry! Bad call!"
	.DB $58
_MagazinesText::
	.DB $00
	.STRINGMAP pokemon, "#MON magazines!"
	.DB $51
	.STRINGMAP pokemon, "#MON notebooks!"
	.DB $51
	.STRINGMAP pokemon, "#MON graphs!"
	.DB $57
_BillsHouseMonitorText::
	.DB $00
	.STRINGMAP pokemon, "TELEPORTER is"
	.DB $4f
	.STRINGMAP pokemon, "displayed on the"
	.DB $55
	.STRINGMAP pokemon, "PC monitor."
	.DB $57
_BillsHouseInitiatedText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> initiated"
	.DB $4f
	.STRINGMAP pokemon, "TELEPORTER's Cell"
	.DB $55
	.STRINGMAP pokemon, "Separator!@"
	.DB $50
_BillsHousePokemonListText1::
	.DB $00
	.STRINGMAP pokemon, "BILL's favorite"
	.DB $4f
	.STRINGMAP pokemon, "#MON list!"
	.DB $58
_BillsHousePokemonListText2::
	.DB $00
	.STRINGMAP pokemon, "Which #MON do"
	.DB $4f
	.STRINGMAP pokemon, "you want to see?"
	.DB $57
_OakLabEmailText::
	.DB $00
	.STRINGMAP pokemon, "There's an e-mail"
	.DB $4f
	.STRINGMAP pokemon, "message here!"
	.DB $51
	.STRINGMAP pokemon, "..."
	.DB $51
	.STRINGMAP pokemon, "Calling all"
	.DB $4f
	.STRINGMAP pokemon, "#MON trainers!"
	.DB $51
	.STRINGMAP pokemon, "The elite trainers"
	.DB $4f
	.STRINGMAP pokemon, "of #MON LEAGUE"
	.DB $55
	.STRINGMAP pokemon, "are ready to take"
	.DB $55
	.STRINGMAP pokemon, "on all comers!"
	.DB $51
	.STRINGMAP pokemon, "Bring your best"
	.DB $4f
	.STRINGMAP pokemon, "#MON and see"
	.DB $55
	.STRINGMAP pokemon, "how you rate as a"
	.DB $55
	.STRINGMAP pokemon, "trainer!"
	.DB $51
	.STRINGMAP pokemon, "#MON LEAGUE HQ"
	.DB $4f
	.STRINGMAP pokemon, "INDIGO PLATEAU"
	.DB $51
	.STRINGMAP pokemon, "PS: PROF.OAK,"
	.DB $4f
	.STRINGMAP pokemon, "please visit us!"
	.DB $55
	.STRINGMAP pokemon, "..."
	.DB $57
_GameCornerCoinCaseText::
	.DB $00
	.STRINGMAP pokemon, "A COIN CASE is"
	.DB $4f
	.STRINGMAP pokemon, "required!"
	.DB $57
_GameCornerNoCoinsText::
	.DB $00
	.STRINGMAP pokemon, "You don't have"
	.DB $4f
	.STRINGMAP pokemon, "any coins!"
	.DB $57
_GameCornerOutOfOrderText::
	.DB $00
	.STRINGMAP pokemon, "OUT OF ORDER"
	.DB $4f
	.STRINGMAP pokemon, "This is broken."
	.DB $57
_GameCornerOutToLunchText::
	.DB $00
	.STRINGMAP pokemon, "OUT TO LUNCH"
	.DB $4f
	.STRINGMAP pokemon, "This is reserved."
	.DB $57
_GameCornerSomeonesKeysText::
	.DB $00
	.STRINGMAP pokemon, "Someone's keys!"
	.DB $4f
	.STRINGMAP pokemon, "They'll be back."
	.DB $57
_JustAMomentText::
	.DB $00
	.STRINGMAP pokemon, "Just a moment."
	.DB $57
TMNotebookText::
	.DB $00
	.STRINGMAP pokemon, "It's a pamphlet"
	.DB $4f
	.STRINGMAP pokemon, "on TMs."
	.DB $51
	.STRINGMAP pokemon, "..."
	.DB $51
	.STRINGMAP pokemon, "There are 50 TMs"
	.DB $4f
	.STRINGMAP pokemon, "in all."
	.DB $51
	.STRINGMAP pokemon, "There are also 5"
	.DB $4f
	.STRINGMAP pokemon, "HMs that can be"
	.DB $55
	.STRINGMAP pokemon, "used repeatedly."
	.DB $51
	.STRINGMAP pokemon, "SILPH CO.@"
	.DB $50
_TurnPageText::
	.DB $00
	.STRINGMAP pokemon, "Turn the page?"
	.DB $57
_ViridianSchoolNotebookText5::
	.DB $00
	.STRINGMAP pokemon, "GIRL: Hey! Don't"
	.DB $4f
	.STRINGMAP pokemon, "look at my notes!@"
	.DB $50
_ViridianSchoolNotebookText1::
	.DB $00
	.STRINGMAP pokemon, "Looked at the"
	.DB $4f
	.STRINGMAP pokemon, "notebook!"
	.DB $51
	.STRINGMAP pokemon, "First page..."
	.DB $51
	.STRINGMAP pokemon, "# BALLs are"
	.DB $4f
	.STRINGMAP pokemon, "used to catch"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $51
	.STRINGMAP pokemon, "Up to 6 #MON"
	.DB $4f
	.STRINGMAP pokemon, "can be carried."
	.DB $51
	.STRINGMAP pokemon, "People who raise"
	.DB $4f
	.STRINGMAP pokemon, "and make #MON"
	.DB $55
	.STRINGMAP pokemon, "fight are called"
	.DB $55
	.STRINGMAP pokemon, "#MON trainers."
	.DB $58
_ViridianSchoolNotebookText2::
	.DB $00
	.STRINGMAP pokemon, "Second page..."
	.DB $51
	.STRINGMAP pokemon, "A healthy #MON"
	.DB $4f
	.STRINGMAP pokemon, "may be hard to"
	.DB $55
	.STRINGMAP pokemon, "catch, so weaken"
	.DB $55
	.STRINGMAP pokemon, "it first!"
	.DB $51
	.STRINGMAP pokemon, "Poison, burns and"
	.DB $4f
	.STRINGMAP pokemon, "other damage are"
	.DB $55
	.STRINGMAP pokemon, "effective!"
	.DB $58
_ViridianSchoolNotebookText3::
	.DB $00
	.STRINGMAP pokemon, "Third page..."
	.DB $51
	.STRINGMAP pokemon, "#MON trainers"
	.DB $4f
	.STRINGMAP pokemon, "seek others to"
	.DB $55
	.STRINGMAP pokemon, "engage in #MON"
	.DB $55
	.STRINGMAP pokemon, "fights."
	.DB $51
	.STRINGMAP pokemon, "Battles are"
	.DB $4f
	.STRINGMAP pokemon, "constantly fought"
	.DB $55
	.STRINGMAP pokemon, "at #MON GYMs."
	.DB $58
_ViridianSchoolNotebookText4::
	.DB $00
	.STRINGMAP pokemon, "Fourth page..."
	.DB $51
	.STRINGMAP pokemon, "The goal for"
	.DB $4f
	.STRINGMAP pokemon, "#MON trainers"
	.DB $55
	.STRINGMAP pokemon, "is to beat the "
	.DB $55
	.STRINGMAP pokemon, "top 8 #MON"
	.DB $55
	.STRINGMAP pokemon, "GYM LEADERs."
	.DB $51
	.STRINGMAP pokemon, "Do so to earn the"
	.DB $4f
	.STRINGMAP pokemon, "right to face..."
	.DB $51
	.STRINGMAP pokemon, "The ELITE FOUR of"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE!"
	.DB $58
_EnemiesOnEverySideText::
	.DB $00
	.STRINGMAP pokemon, "Enemies on every"
	.DB $4f
	.STRINGMAP pokemon, "side!"
	.DB $57
_WhatGoesAroundComesAroundText::
	.DB $00
	.STRINGMAP pokemon, "What goes around"
	.DB $4f
	.STRINGMAP pokemon, "comes around!"
	.DB $57
_FightingDojoText::
	.DB $00
	.STRINGMAP pokemon, "FIGHTING DOJO"
	.DB $57
_IndigoPlateauHQText::
	.DB $00
	.STRINGMAP pokemon, "INDIGO PLATEAU"
	.DB $4f
	.STRINGMAP pokemon, "#MON LEAGUE HQ"
	.DB $57
_RedBedroomSNESText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> is"
	.DB $4f
	.STRINGMAP pokemon, "playing the SNES!"
	.DB $55
	.STRINGMAP pokemon, "...Okay!"
	.DB $55
	.STRINGMAP pokemon, "It's time to go!"
	.DB $57
_Route15UpstairsBinocularsText::
	.DB $00
	.STRINGMAP pokemon, "Looked into the"
	.DB $4f
	.STRINGMAP pokemon, "binoculars..."
	.DB $51
	.STRINGMAP pokemon, "A large, shining"
	.DB $4f
	.STRINGMAP pokemon, "bird is flying"
	.DB $55
	.STRINGMAP pokemon, "toward the sea."
	.DB $57
_AerodactylFossilText::
	.DB $00
	.STRINGMAP pokemon, "AERODACTYL Fossil"
	.DB $4f
	.STRINGMAP pokemon, "A primitive and"
	.DB $55
	.STRINGMAP pokemon, "rare #MON."
	.DB $57
_KabutopsFossilText::
	.DB $00
	.STRINGMAP pokemon, "KABUTOPS Fossil"
	.DB $4f
	.STRINGMAP pokemon, "A primitive and"
	.DB $55
	.STRINGMAP pokemon, "rare #MON."
	.DB $57
_LinkCableHelpText1::
	.DB $00
	.STRINGMAP pokemon, "TRAINER TIPS"
	.DB $51
	.STRINGMAP pokemon, "Using a Game Link"
	.DB $4f
	.STRINGMAP pokemon, "Cable"
	.DB $58
_LinkCableHelpText2::
	.DB $00
	.STRINGMAP pokemon, "Which heading do"
	.DB $4f
	.STRINGMAP pokemon, "you want to read?"
	.DB $57
_LinkCableInfoText1::
	.DB $00
	.STRINGMAP pokemon, "When you have"
	.DB $4f
	.STRINGMAP pokemon, "linked your GAME"
	.DB $55
	.STRINGMAP pokemon, "BOY with another"
	.DB $55
	.STRINGMAP pokemon, "GAME BOY, talk to"
	.DB $55
	.STRINGMAP pokemon, "the attendant on"
	.DB $55
	.STRINGMAP pokemon, "the right in any"
	.DB $55
	.STRINGMAP pokemon, "#MON CENTER."
	.DB $58
_LinkCableInfoText2::
	.DB $00
	.STRINGMAP pokemon, "COLOSSEUM lets"
	.DB $4f
	.STRINGMAP pokemon, "you play against"
	.DB $55
	.STRINGMAP pokemon, "a friend."
	.DB $58
_LinkCableInfoText3::
	.DB $00
	.STRINGMAP pokemon, "TRADE CENTER is"
	.DB $4f
	.STRINGMAP pokemon, "used for trading"
	.DB $55
	.STRINGMAP pokemon, "#MON."
	.DB $58
_ViridianSchoolBlackboardText1::
	.DB $00
	.STRINGMAP pokemon, "The blackboard"
	.DB $4f
	.STRINGMAP pokemon, "describes #MON"
	.DB $55
	.STRINGMAP pokemon, "STATUS changes"
	.DB $55
	.STRINGMAP pokemon, "during battles."
	.DB $58
_ViridianSchoolBlackboardText2::
	.DB $00
	.STRINGMAP pokemon, "Which heading do"
	.DB $4f
	.STRINGMAP pokemon, "you want to read?"
	.DB $57
_ViridianBlackboardSleepText::
	.DB $00
	.STRINGMAP pokemon, "A #MON can't"
	.DB $4f
	.STRINGMAP pokemon, "attack if it's"
	.DB $55
	.STRINGMAP pokemon, "asleep!"
	.DB $51
	.STRINGMAP pokemon, "#MON will stay"
	.DB $4f
	.STRINGMAP pokemon, "asleep even after"
	.DB $55
	.STRINGMAP pokemon, "battles."
	.DB $51
	.STRINGMAP pokemon, "Use AWAKENING to"
	.DB $4f
	.STRINGMAP pokemon, "wake them up!"
	.DB $58
_ViridianBlackboardPoisonText::
	.DB $00
	.STRINGMAP pokemon, "When poisoned, a"
	.DB $4f
	.STRINGMAP pokemon, "#MON's health"
	.DB $55
	.STRINGMAP pokemon, "steadily drops."
	.DB $51
	.STRINGMAP pokemon, "Poison lingers"
	.DB $4f
	.STRINGMAP pokemon, "after battles."
	.DB $51
	.STRINGMAP pokemon, "Use an ANTIDOTE"
	.DB $4f
	.STRINGMAP pokemon, "to cure poison!"
	.DB $58
_ViridianBlackboardPrlzText::
	.DB $00
	.STRINGMAP pokemon, "Paralysis could"
	.DB $4f
	.STRINGMAP pokemon, "make #MON"
	.DB $55
	.STRINGMAP pokemon, "moves misfire!"
	.DB $51
	.STRINGMAP pokemon, "Paralysis remains"
	.DB $4f
	.STRINGMAP pokemon, "after battles."
	.DB $51
	.STRINGMAP pokemon, "Use PARLYZ HEAL"
	.DB $4f
	.STRINGMAP pokemon, "for treatment!"
	.DB $58
_ViridianBlackboardBurnText::
	.DB $00
	.STRINGMAP pokemon, "A burn reduces"
	.DB $4f
	.STRINGMAP pokemon, "power and speed."
	.DB $55
	.STRINGMAP pokemon, "It also causes"
	.DB $55
	.STRINGMAP pokemon, "ongoing damage."
	.DB $51
	.STRINGMAP pokemon, "Burns remain"
	.DB $4f
	.STRINGMAP pokemon, "after battles."
	.DB $51
	.STRINGMAP pokemon, "Use BURN HEAL to"
	.DB $4f
	.STRINGMAP pokemon, "cure a burn!"
	.DB $58
_ViridianBlackboardFrozenText::
	.DB $00
	.STRINGMAP pokemon, "If frozen, a"
	.DB $4f
	.STRINGMAP pokemon, "#MON becomes"
	.DB $55
	.STRINGMAP pokemon, "totally immobile!"
	.DB $51
	.STRINGMAP pokemon, "It stays frozen"
	.DB $4f
	.STRINGMAP pokemon, "even after the"
	.DB $55
	.STRINGMAP pokemon, "battle ends."
	.DB $51
	.STRINGMAP pokemon, "Use ICE HEAL to"
	.DB $4f
	.STRINGMAP pokemon, "thaw out #MON!"
	.DB $58
_VermilionGymTrashText::
	.DB $00
	.STRINGMAP pokemon, "Nope, there's"
	.DB $4f
	.STRINGMAP pokemon, "only trash here."
	.DB $57
_VermilionGymTrashSuccessText1::
	.DB $00
	.STRINGMAP pokemon, "Hey! There's a"
	.DB $4f
	.STRINGMAP pokemon, "switch under the"
	.DB $55
	.STRINGMAP pokemon, "trash!"
	.DB $55
	.STRINGMAP pokemon, "Turn it on!"
	.DB $51
	.STRINGMAP pokemon, "The 1st electric"
	.DB $4f
	.STRINGMAP pokemon, "lock opened!@"
	.DB $50
_VermilionGymTrashSuccessText2::
	.DB $00
	.STRINGMAP pokemon, "Hey! There's"
	.DB $4f
	.STRINGMAP pokemon, "another switch"
	.DB $55
	.STRINGMAP pokemon, "under the trash!"
	.DB $55
	.STRINGMAP pokemon, "Turn it on!"
	.DB $58
_VermilionGymTrashSuccessText3::
	.DB $00
	.STRINGMAP pokemon, "The 2nd electric"
	.DB $4f
	.STRINGMAP pokemon, "lock opened!"
	.DB $51
	.STRINGMAP pokemon, "The motorized door"
	.DB $4f
	.STRINGMAP pokemon, "opened!@"
	.DB $50
_VermilionGymTrashFailText::
	.DB $00
	.STRINGMAP pokemon, "Nope! There's"
	.DB $4f
	.STRINGMAP pokemon, "only trash here."
	.DB $55
	.STRINGMAP pokemon, "Hey! The electric"
	.DB $55
	.STRINGMAP pokemon, "locks were reset!@"
	.DB $50
_FoundHiddenItemText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> found"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_HiddenItemBagFullText::
	.DB $00
	.STRINGMAP pokemon, "But, <PLAYER> has"
	.DB $4f
	.STRINGMAP pokemon, "no more room for"
	.DB $55
	.STRINGMAP pokemon, "other items!"
	.DB $57
_FoundHiddenCoinsText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> found"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $02
	.DW hCoins
	.DB $c2
	.DB $00
	.STRINGMAP pokemon, " coins!@"
	.DB $50
_FoundHiddenCoins2Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> found"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $02
	.DW hCoins
	.DB $c2
	.DB $00
	.STRINGMAP pokemon, " coins!@"
	.DB $50
_DroppedHiddenCoinsText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "Oops! Dropped"
	.DB $4f
	.STRINGMAP pokemon, "some coins!"
	.DB $57
_IndigoPlateauStatuesText1::
	.DB $00
	.STRINGMAP pokemon, "INDIGO PLATEAU"
	.DB $58
_IndigoPlateauStatuesText2::
	.DB $00
	.STRINGMAP pokemon, "The ultimate goal"
	.DB $4f
	.STRINGMAP pokemon, "of trainers!"
	.DB $55
	.STRINGMAP pokemon, "#MON LEAGUE HQ"
	.DB $57
_IndigoPlateauStatuesText3::
	.DB $00
	.STRINGMAP pokemon, "The highest"
	.DB $4f
	.STRINGMAP pokemon, "#MON authority"
	.DB $55
	.STRINGMAP pokemon, "#MON LEAGUE HQ"
	.DB $57
_PokemonBooksText::
	.DB $00
	.STRINGMAP pokemon, "Crammed full of"
	.DB $4f
	.STRINGMAP pokemon, "#MON books!"
	.DB $57
_DiglettSculptureText::
	.DB $00
	.STRINGMAP pokemon, "It's a sculpture"
	.DB $4f
	.STRINGMAP pokemon, "of DIGLETT."
	.DB $57
_ElevatorText::
	.DB $00
	.STRINGMAP pokemon, "This is an"
	.DB $4f
	.STRINGMAP pokemon, "elevator."
	.DB $57
_TownMapText::
	.DB $00
	.STRINGMAP pokemon, "A TOWN MAP.@"
	.DB $50
_PokemonStuffText::
	.DB $00
	.STRINGMAP pokemon, "Wow! Tons of"
	.DB $4f
	.STRINGMAP pokemon, "#MON stuff!"
	.DB $57
_OutOfSafariBallsText::
	.DB $00
	.STRINGMAP pokemon, "PA: Ding-dong!"
	.DB $51
	.STRINGMAP pokemon, "You are out of"
	.DB $4f
	.STRINGMAP pokemon, "SAFARI BALLs!"
	.DB $58
_WildRanText::
	.DB $00
	.STRINGMAP pokemon, "Wild @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "ran!"
	.DB $58
_EnemyRanText::
	.DB $00
	.STRINGMAP pokemon, "Enemy @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "ran!"
	.DB $58
_HurtByPoisonText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "hurt by poison!"
	.DB $58
_HurtByBurnText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "hurt by the burn!"
	.DB $58
_HurtByLeechSeedText::
	.DB $00
	.STRINGMAP pokemon, "LEECH SEED saps"
	.DB $4f
	.STRINGMAP pokemon, "<USER>!"
	.DB $58
_EnemyMonFaintedText::
	.DB $00
	.STRINGMAP pokemon, "Enemy @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "fainted!"
	.DB $58
_MoneyForWinningText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got ¥@"
	.DB $02
	.DW wAmountMoneyWon
	.DB $c3
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "for winning!"
	.DB $58
_TrainerDefeatedText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> defeated"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wTrainerName
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_PlayerMonFaintedText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "fainted!"
	.DB $58
_UseNextMonText::
	.DB $00
	.STRINGMAP pokemon, "Use next #MON?"
	.DB $57
_Rival1WinText::
	.DB $00
	.STRINGMAP pokemon, "<RIVAL>: Yeah! Am"
	.DB $4f
	.STRINGMAP pokemon, "I great or what?"
	.DB $58
_PlayerBlackedOutText2::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> is out of"
	.DB $4f
	.STRINGMAP pokemon, "useable #MON!"
	.DB $51
	.STRINGMAP pokemon, "<PLAYER> blacked"
	.DB $4f
	.STRINGMAP pokemon, "out!"
	.DB $58
_LinkBattleLostText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> lost to"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wTrainerName
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_TrainerAboutToUseText::
	.DB $01
	.DW wTrainerName
	.DB $00
	.STRINGMAP pokemon, " is"
	.DB $4f
	.STRINGMAP pokemon, "about to use"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "Will <PLAYER>"
	.DB $4f
	.STRINGMAP pokemon, "change #MON?"
	.DB $57
_TrainerSentOutText::
	.DB $01
	.DW wTrainerName
	.DB $00
	.STRINGMAP pokemon, " sent"
	.DB $4f
	.STRINGMAP pokemon, "out @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_NoWillText::
	.DB $00
	.STRINGMAP pokemon, "There's no will"
	.DB $4f
	.STRINGMAP pokemon, "to fight!"
	.DB $58
_CantEscapeText::
	.DB $00
	.STRINGMAP pokemon, "Can't escape!"
	.DB $58
_NoRunningText::
	.DB $00
	.STRINGMAP pokemon, "No! There's no"
	.DB $4f
	.STRINGMAP pokemon, "running from a"
	.DB $55
	.STRINGMAP pokemon, "trainer battle!"
	.DB $58
_GotAwayText::
	.DB $00
	.STRINGMAP pokemon, "Got away safely!"
	.DB $58
_ItemsCantBeUsedHereText::
	.DB $00
	.STRINGMAP pokemon, "Items can't be"
	.DB $4f
	.STRINGMAP pokemon, "used here."
	.DB $58
_AlreadyOutText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, " is"
	.DB $4f
	.STRINGMAP pokemon, "already out!"
	.DB $58
_MoveNoPPText::
	.DB $00
	.STRINGMAP pokemon, "No PP left for"
	.DB $4f
	.STRINGMAP pokemon, "this move!"
	.DB $58
_MoveDisabledText::
	.DB $00
	.STRINGMAP pokemon, "The move is"
	.DB $4f
	.STRINGMAP pokemon, "disabled!"
	.DB $58
_NoMovesLeftText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, " has no"
	.DB $4f
	.STRINGMAP pokemon, "moves left!"
	.DB $57
_MultiHitText::
	.DB $00
	.STRINGMAP pokemon, "Hit the enemy"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $09
	.DW wPlayerNumHits
	.DB $11
	.DB $00
	.STRINGMAP pokemon, " times!"
	.DB $58
_ScaredText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, " is too"
	.DB $4f
	.STRINGMAP pokemon, "scared to move!"
	.DB $58
_GetOutText::
	.DB $00
	.STRINGMAP pokemon, "GHOST: Get out..."
	.DB $4f
	.STRINGMAP pokemon, "Get out..."
	.DB $58
_FastAsleepText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "is fast asleep!"
	.DB $58
_WokeUpText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "woke up!"
	.DB $58
_IsFrozenText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "is frozen solid!"
	.DB $58
_FullyParalyzedText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "fully paralyzed!"
	.DB $58
_FlinchedText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "flinched!"
	.DB $58
_MustRechargeText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "must recharge!"
	.DB $58
_DisabledNoMoreText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "disabled no more!"
	.DB $58
_IsConfusedText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "is confused!"
	.DB $58
_HurtItselfText::
	.DB $00
	.STRINGMAP pokemon, "It hurt itself in"
	.DB $4f
	.STRINGMAP pokemon, "its confusion!"
	.DB $58
_ConfusedNoMoreText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "confused no more!"
	.DB $58
_SavingEnergyText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "is saving energy!"
	.DB $58
_UnleashedEnergyText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "unleashed energy!"
	.DB $58
_ThrashingAboutText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "thrashing about!"
	.DB $57
_AttackContinuesText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "attack continues!"
	.DB $57
_CantMoveText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "can't move!"
	.DB $58
_MoveIsDisabledText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " is"
	.DB $55
	.STRINGMAP pokemon, "disabled!"
	.DB $58
_ActorNameText::
	.DB $00
	.STRINGMAP pokemon, "<USER>@"
	.DB $50
_UsedMove1Text::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "used @"
	.DB $50
_UsedMove2Text::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "used @"
	.DB $50
_UsedInsteadText::
	.DB $00
	.STRINGMAP pokemon, "instead,"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $50
_MoveNameText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "@"
_EndUsedMove1Text::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_EndUsedMove2Text::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_EndUsedMove3Text::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_EndUsedMove4Text::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_EndUsedMove5Text::
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_AttackMissedText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "attack missed!"
	.DB $58
_KeptGoingAndCrashedText::
	.DB $00
	.STRINGMAP pokemon, "<USER>"
	.DB $4f
	.STRINGMAP pokemon, "kept going and"
	.DB $55
	.STRINGMAP pokemon, "crashed!"
	.DB $58
_UnaffectedText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>'s"
	.DB $4f
	.STRINGMAP pokemon, "unaffected!"
	.DB $58
_DoesntAffectMonText::
	.DB $00
	.STRINGMAP pokemon, "It doesn't affect"
	.DB $4f
	.STRINGMAP pokemon, "<TARGET>!"
	.DB $58
_CriticalHitText::
	.DB $00
	.STRINGMAP pokemon, "Critical hit!"
	.DB $58
_OHKOText::
	.DB $00
	.STRINGMAP pokemon, "One-hit KO!"
	.DB $58
_LoafingAroundText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, " is"
	.DB $4f
	.STRINGMAP pokemon, "loafing around."
	.DB $58
_BeganToNapText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, " began"
	.DB $4f
	.STRINGMAP pokemon, "to nap!"
	.DB $58
_WontObeyText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, " won't"
	.DB $4f
	.STRINGMAP pokemon, "obey!"
	.DB $58
_TurnedAwayText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, " turned"
	.DB $4f
	.STRINGMAP pokemon, "away!"
	.DB $58
_IgnoredOrdersText::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "ignored orders!"
	.DB $58
_SubstituteTookDamageText::
	.DB $00
	.STRINGMAP pokemon, "The SUBSTITUTE"
	.DB $4f
	.STRINGMAP pokemon, "took damage for"
	.DB $55
	.STRINGMAP pokemon, "<TARGET>!"
	.DB $58
_SubstituteBrokeText::
	.DB $00
	.STRINGMAP pokemon, "<TARGET>'s"
	.DB $4f
	.STRINGMAP pokemon, "SUBSTITUTE broke!"
	.DB $58
_BuildingRageText::
	.DB $00
	.STRINGMAP pokemon, "<USER>'s"
	.DB $4f
	.STRINGMAP pokemon, "RAGE is building!"
	.DB $58
_MirrorMoveFailedText::
	.DB $00
	.STRINGMAP pokemon, "The MIRROR MOVE"
	.DB $4e
	.STRINGMAP pokemon, "failed!"
	.DB $58
_HitXTimesText::
	.DB $00
	.STRINGMAP pokemon, "Hit @"
	.DB $09
	.DW wEnemyNumHits
	.DB $11
	.DB $00
	.STRINGMAP pokemon, " times!"
	.DB $58
_GainedText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " gained"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $50
_WithExpAllText::
	.DB $00
	.STRINGMAP pokemon, "with EXP.ALL,"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $50
_BoostedText::
	.DB $00
	.STRINGMAP pokemon, "a boosted"
	.DB $55
	.STRINGMAP pokemon, "@"
	.DB $50
_ExpPointsText::
	.DB $09
	.DW wExpAmountGained
	.DB $24
	.DB $00
	.STRINGMAP pokemon, " EXP. Points!"
	.DB $58
_GrewLevelText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " grew"
	.DB $4f
	.STRINGMAP pokemon, "to level @"
	.DB $09
	.DW wCurEnemyLevel
	.DB $13
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_WildMonAppearedText::
	.DB $00
	.STRINGMAP pokemon, "Wild @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "appeared!"
	.DB $58
_HookedMonAttackedText::
	.DB $00
	.STRINGMAP pokemon, "The hooked"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.DB $55
	.STRINGMAP pokemon, "attacked!"
	.DB $58
_EnemyAppearedText::
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "appeared!"
	.DB $58
_TrainerWantsToFightText::
	.DB $01
	.DW wTrainerName
	.DB $00
	.STRINGMAP pokemon, " wants"
	.DB $4f
	.STRINGMAP pokemon, "to fight!"
	.DB $58
_UnveiledGhostText::
	.DB $00
	.STRINGMAP pokemon, "SILPH SCOPE"
	.DB $4f
	.STRINGMAP pokemon, "unveiled the"
	.DB $55
	.STRINGMAP pokemon, "GHOST's identity!"
	.DB $58
_GhostCantBeIDdText::
	.DB $00
	.STRINGMAP pokemon, "Darn! The GHOST"
	.DB $4f
	.STRINGMAP pokemon, "can't be ID'd!"
	.DB $58
_GoText::
	.DB $00
	.STRINGMAP pokemon, "Go! @"
	.DB $50
_DoItText::
	.DB $00
	.STRINGMAP pokemon, "Do it! @"
	.DB $50
_GetmText::
	.DB $00
	.STRINGMAP pokemon, "Get'm! @"
	.DB $50
_EnemysWeakText::
	.DB $00
	.STRINGMAP pokemon, "The enemy's weak!"
	.DB $4f
	.STRINGMAP pokemon, "Get'm! @"
	.DB $50
_PlayerMon1Text::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_PlayerMon2Text::
	.DB $01
	.DW wBattleMonNick
	.DB $00
	.STRINGMAP pokemon, " @"
	.DB $50
_EnoughText::
	.DB $00
	.STRINGMAP pokemon, "enough!@"
	.DB $50
_OKExclamationText::
	.DB $00
	.STRINGMAP pokemon, "OK!@"
	.DB $50
_GoodText::
	.DB $00
	.STRINGMAP pokemon, "good!@"
	.DB $50
_ComeBackText::
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "Come back!"
	.DB $57
_SuperEffectiveText::
	.DB $00
	.STRINGMAP pokemon, "It's super"
	.DB $4f
	.STRINGMAP pokemon, "effective!"
	.DB $58
_NotVeryEffectiveText::
	.DB $00
	.STRINGMAP pokemon, "It's not very"
	.DB $4f
	.STRINGMAP pokemon, "effective..."
	.DB $58
_SafariZoneEatingText::
	.DB $00
	.STRINGMAP pokemon, "Wild @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "is eating!"
	.DB $58
_SafariZoneAngryText::
	.DB $00
	.STRINGMAP pokemon, "Wild @"
	.DB $01
	.DW wEnemyMonNick
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "is angry!"
	.DB $58
_PickUpPayDayMoneyText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> picked up"
	.DB $4f
	.STRINGMAP pokemon, "¥@"
	.DB $02
	.DW wTotalPayDayMoney
	.DB $c3
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_ClearSaveDataText::
	.DB $00
	.STRINGMAP pokemon, "Clear all saved"
	.DB $4f
	.STRINGMAP pokemon, "data?"
	.DB $57
_WhichFloorText::
	.DB $00
	.STRINGMAP pokemon, "Which floor do"
	.DB $4f
	.STRINGMAP pokemon, "you want? "
	.DB $57
_PartyMenuNormalText::
	.DB $00
	.STRINGMAP pokemon, "Choose a #MON."
	.DB $57
_PartyMenuItemUseText::
	.DB $00
	.STRINGMAP pokemon, "Use item on which"
	.DB $4f
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_PartyMenuBattleText::
	.DB $00
	.STRINGMAP pokemon, "Bring out which"
	.DB $4f
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_PartyMenuUseTMText::
	.DB $00
	.STRINGMAP pokemon, "Use TM on which"
	.DB $4f
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_PartyMenuSwapMonText::
	.DB $00
	.STRINGMAP pokemon, "Move #MON"
	.DB $4f
	.STRINGMAP pokemon, "where?"
	.DB $57
_PotionText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "recovered by @"
	.DB $09
	.DW wHPBarHPDifference
	.DB $23
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $57
_AntidoteText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $4f
	.STRINGMAP pokemon, "cured of poison!"
	.DB $57
_ParlyzHealText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "'s"
	.DB $4f
	.STRINGMAP pokemon, "rid of paralysis!"
	.DB $57
_BurnHealText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "'s"
	.DB $4f
	.STRINGMAP pokemon, "burn was healed!"
	.DB $57
_IceHealText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $4f
	.STRINGMAP pokemon, "defrosted!"
	.DB $57
_AwakeningText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "woke up!"
	.DB $57
_FullHealText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "'s"
	.DB $4f
	.STRINGMAP pokemon, "health returned!"
	.DB $57
_ReviveText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "is revitalized!"
	.DB $57
_RareCandyText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " grew"
	.DB $4f
	.STRINGMAP pokemon, "to level @"
	.DB $09
	.DW wCurEnemyLevel
	.DB $13
	.DB $00
	.STRINGMAP pokemon, "!@"
	.DB $50
_TurnedOnPC1Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> turned on"
	.DB $4f
	.STRINGMAP pokemon, "the PC."
	.DB $58
_AccessedBillsPCText::
	.DB $00
	.STRINGMAP pokemon, "Accessed BILL's"
	.DB $4f
	.STRINGMAP pokemon, "PC."
	.DB $51
	.STRINGMAP pokemon, "Accessed #MON"
	.DB $4f
	.STRINGMAP pokemon, "Storage System."
	.DB $58
_AccessedSomeonesPCText::
	.DB $00
	.STRINGMAP pokemon, "Accessed someone's"
	.DB $4f
	.STRINGMAP pokemon, "PC."
	.DB $51
	.STRINGMAP pokemon, "Accessed #MON"
	.DB $4f
	.STRINGMAP pokemon, "Storage System."
	.DB $58
_AccessedMyPCText::
	.DB $00
	.STRINGMAP pokemon, "Accessed my PC."
	.DB $51
	.STRINGMAP pokemon, "Accessed Item"
	.DB $4f
	.STRINGMAP pokemon, "Storage System."
	.DB $58
_TurnedOnPC2Text::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> turned on"
	.DB $4f
	.STRINGMAP pokemon, "the PC."
	.DB $58
_WhatDoYouWantText::
	.DB $00
	.STRINGMAP pokemon, "What do you want"
	.DB $4f
	.STRINGMAP pokemon, "to do?"
	.DB $57
_WhatToDepositText::
	.DB $00
	.STRINGMAP pokemon, "What do you want"
	.DB $4f
	.STRINGMAP pokemon, "to deposit?"
	.DB $57
_DepositHowManyText::
	.DB $00
	.STRINGMAP pokemon, "How many?"
	.DB $57
_ItemWasStoredText::
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $4f
	.STRINGMAP pokemon, "stored via PC."
	.DB $58
_NothingToDepositText::
	.DB $00
	.STRINGMAP pokemon, "You have nothing"
	.DB $4f
	.STRINGMAP pokemon, "to deposit."
	.DB $58
_NoRoomToStoreText::
	.DB $00
	.STRINGMAP pokemon, "No room left to"
	.DB $4f
	.STRINGMAP pokemon, "store items."
	.DB $58
_WhatToWithdrawText::
	.DB $00
	.STRINGMAP pokemon, "What do you want"
	.DB $4f
	.STRINGMAP pokemon, "to withdraw?"
	.DB $57
_WithdrawHowManyText::
	.DB $00
	.STRINGMAP pokemon, "How many?"
	.DB $57
_WithdrewItemText::
	.DB $00
	.STRINGMAP pokemon, "Withdrew"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $58
_NothingStoredText::
	.DB $00
	.STRINGMAP pokemon, "There is nothing"
	.DB $4f
	.STRINGMAP pokemon, "stored."
	.DB $58
_CantCarryMoreText::
	.DB $00
	.STRINGMAP pokemon, "You can't carry"
	.DB $4f
	.STRINGMAP pokemon, "any more items."
	.DB $58
_WhatToTossText::
	.DB $00
	.STRINGMAP pokemon, "What do you want"
	.DB $4f
	.STRINGMAP pokemon, "to toss away?"
	.DB $57
_TossHowManyText::
	.DB $00
	.STRINGMAP pokemon, "How many?"
	.DB $57
_AccessedHoFPCText::
	.DB $00
	.STRINGMAP pokemon, "Accessed #MON"
	.DB $4f
	.STRINGMAP pokemon, "LEAGUE's site."
	.DB $51
	.STRINGMAP pokemon, "Accessed the HALL"
	.DB $4f
	.STRINGMAP pokemon, "OF FAME List."
	.DB $58
_SwitchOnText::
	.DB $00
	.STRINGMAP pokemon, "Switch on!"
	.DB $58
_WhatText::
	.DB $00
	.STRINGMAP pokemon, "What?"
	.DB $57
_DepositWhichMonText::
	.DB $00
	.STRINGMAP pokemon, "Deposit which"
	.DB $4f
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_MonWasStoredText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $4f
	.STRINGMAP pokemon, "stored in Box @"
	.DB $01
	.DW wBoxNumString
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $58
_CantDepositLastMonText::
	.DB $00
	.STRINGMAP pokemon, "You can't deposit"
	.DB $4f
	.STRINGMAP pokemon, "the last #MON!"
	.DB $58
_BoxFullText::
	.DB $00
	.STRINGMAP pokemon, "Oops! This Box is"
	.DB $4f
	.STRINGMAP pokemon, "full of #MON."
	.DB $58
_MonIsTakenOutText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " is"
	.DB $4f
	.STRINGMAP pokemon, "taken out."
	.DB $55
	.STRINGMAP pokemon, "Got @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "."
	.DB $58
_NoMonText::
	.DB $00
	.STRINGMAP pokemon, "What? There are"
	.DB $4f
	.STRINGMAP pokemon, "no #MON here!"
	.DB $58
_CantTakeMonText::
	.DB $00
	.STRINGMAP pokemon, "You can't take"
	.DB $4f
	.STRINGMAP pokemon, "any more #MON."
	.DB $51
	.STRINGMAP pokemon, "Deposit #MON"
	.DB $4f
	.STRINGMAP pokemon, "first."
	.DB $58
_ReleaseWhichMonText::
	.DB $00
	.STRINGMAP pokemon, "Release which"
	.DB $4f
	.STRINGMAP pokemon, "#MON?"
	.DB $57
_OnceReleasedText::
	.DB $00
	.STRINGMAP pokemon, "Once released,"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " is"
	.DB $55
	.STRINGMAP pokemon, "gone forever. OK?"
	.DB $57
_MonWasReleasedText::
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, " was"
	.DB $4f
	.STRINGMAP pokemon, "released outside."
	.DB $55
	.STRINGMAP pokemon, "Bye @"
	.DB $01
	.DW wStringBuffer
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $58
_RequireCoinCaseText::
	.DB $00
	.STRINGMAP pokemon, "A COIN CASE is"
	.DB $4f
	.STRINGMAP pokemon, "required!@"
	.DB $50
_ExchangeCoinsForPrizesText::
	.DB $00
	.STRINGMAP pokemon, "We exchange your"
	.DB $4f
	.STRINGMAP pokemon, "coins for prizes."
	.DB $58
_WhichPrizeText::
	.DB $00
	.STRINGMAP pokemon, "Which prize do"
	.DB $4f
	.STRINGMAP pokemon, "you want?"
	.DB $57
_HereYouGoText::
	.DB $00
	.STRINGMAP pokemon, "Here you go!@"
	.DB $50
_SoYouWantPrizeText::
	.DB $00
	.STRINGMAP pokemon, "So, you want"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "?"
	.DB $57
_SorryNeedMoreCoinsText::
	.DB $00
	.STRINGMAP pokemon, "Sorry, you need"
	.DB $4f
	.STRINGMAP pokemon, "more coins.@"
	.DB $50
_OopsYouDontHaveEnoughRoomText::
	.DB $00
	.STRINGMAP pokemon, "Oops! You don't"
	.DB $4f
	.STRINGMAP pokemon, "have enough room.@"
	.DB $50
_OhFineThenText::
	.DB $00
	.STRINGMAP pokemon, "Oh, fine then.@"
	.DB $50
_GetDexRatedText::
	.DB $00
	.STRINGMAP pokemon, "Want to get your"
	.DB $4f
	.STRINGMAP pokemon, "#DEX rated?"
	.DB $57
_ClosedOaksPCText::
	.DB $00
	.STRINGMAP pokemon, "Closed link to"
	.DB $4f
	.STRINGMAP pokemon, "PROF.OAK's PC.@"
	.DB $50
_AccessedOaksPCText::
	.DB $00
	.STRINGMAP pokemon, "Accessed PROF."
	.DB $4f
	.STRINGMAP pokemon, "OAK's PC."
	.DB $51
	.STRINGMAP pokemon, "Accessed #DEX"
	.DB $4f
	.STRINGMAP pokemon, "Rating System."
	.DB $58
_WhereWouldYouLikeText::
	.DB $00
	.STRINGMAP pokemon, "Where would you"
	.DB $4f
	.STRINGMAP pokemon, "like to go?"
	.DB $57
_PleaseWaitText::
	.DB $00
	.STRINGMAP pokemon, "OK, please wait"
	.DB $4f
	.STRINGMAP pokemon, "just a moment."
	.DB $57
_LinkCanceledText::
	.DB $00
	.STRINGMAP pokemon, "The link was"
	.DB $4f
	.STRINGMAP pokemon, "canceled."
	.DB $57
_OakSpeechText1::
	.DB $00
	.STRINGMAP pokemon, "Hello there!"
	.DB $4f
	.STRINGMAP pokemon, "Welcome to the"
	.DB $55
	.STRINGMAP pokemon, "world of #MON!"
	.DB $51
	.STRINGMAP pokemon, "My name is OAK!"
	.DB $4f
	.STRINGMAP pokemon, "People call me"
	.DB $55
	.STRINGMAP pokemon, "the #MON PROF!"
	.DB $58
_OakSpeechText2A::
	.DB $00
	.STRINGMAP pokemon, "This world is"
	.DB $4f
	.STRINGMAP pokemon, "inhabited by"
	.DB $55
	.STRINGMAP pokemon, "creatures called"
	.DB $55
	.STRINGMAP pokemon, "#MON!@"
	.DB $50
_OakSpeechText2B::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "For some people,"
	.DB $4f
	.STRINGMAP pokemon, "#MON are"
	.DB $55
	.STRINGMAP pokemon, "pets. Others use"
	.DB $55
	.STRINGMAP pokemon, "them for fights."
	.DB $51
	.STRINGMAP pokemon, "Myself..."
	.DB $51
	.STRINGMAP pokemon, "I study #MON"
	.DB $4f
	.STRINGMAP pokemon, "as a profession."
	.DB $58
_IntroducePlayerText::
	.DB $00
	.STRINGMAP pokemon, "First, what is"
	.DB $4f
	.STRINGMAP pokemon, "your name?"
	.DB $58
_IntroduceRivalText::
	.DB $00
	.STRINGMAP pokemon, "This is my grand-"
	.DB $4f
	.STRINGMAP pokemon, "son. He's been"
	.DB $55
	.STRINGMAP pokemon, "your rival since"
	.DB $55
	.STRINGMAP pokemon, "you were a baby."
	.DB $51
	.STRINGMAP pokemon, "...Erm, what is"
	.DB $4f
	.STRINGMAP pokemon, "his name again?"
	.DB $58
_OakSpeechText3::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER>!"
	.DB $51
	.STRINGMAP pokemon, "Your very own"
	.DB $4f
	.STRINGMAP pokemon, "#MON legend is"
	.DB $55
	.STRINGMAP pokemon, "about to unfold!"
	.DB $51
	.STRINGMAP pokemon, "A world of dreams"
	.DB $4f
	.STRINGMAP pokemon, "and adventures"
	.DB $55
	.STRINGMAP pokemon, "with #MON"
	.DB $55
	.STRINGMAP pokemon, "awaits! Let's go!"
	.DB $57
_DoYouWantToNicknameText::
	.DB $00
	.STRINGMAP pokemon, "Do you want to"
	.DB $4f
	.STRINGMAP pokemon, "give a nickname"
	.DB $55
	.STRINGMAP pokemon, "to @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, "?"
	.DB $57
_YourNameIsText::
	.DB $00
	.STRINGMAP pokemon, "Right! So your"
	.DB $4f
	.STRINGMAP pokemon, "name is <PLAYER>!"
	.DB $58
_HisNameIsText::
	.DB $00
	.STRINGMAP pokemon, "That's right! I"
	.DB $4f
	.STRINGMAP pokemon, "remember now! His"
	.DB $55
	.STRINGMAP pokemon, "name is <RIVAL>!"
	.DB $58
_WillBeTradedText::
	.DB $01
	.DW wNameOfPlayerMonToBeTraded
	.DB $00
	.STRINGMAP pokemon, " and"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.STRINGMAP pokemon, " will"
	.DB $55
	.STRINGMAP pokemon, "be traded."
	.DB $57
_TextIDErrorText::
	.DB $09
	.DW hTextID
	.DB $12
	.DB $00
	.STRINGMAP pokemon, " ERROR."
	.DB $57
_ContCharText::
	.DB $00
	.STRINGMAP pokemon, "<_CONT>@"
	.DB $50

; text/DiglettsCaveRoute2.asm
_DiglettsCaveRoute2FishingGuruText::
	.DB $00
	.STRINGMAP pokemon, "I went to ROCK"
	.DB $4f
	.STRINGMAP pokemon, "TUNNEL, but it's"
	.DB $55
	.STRINGMAP pokemon, "dark and scary."
	.DB $51
	.STRINGMAP pokemon, "If a #MON's"
	.DB $4f
	.STRINGMAP pokemon, "FLASH could light"
	.DB $55
	.STRINGMAP pokemon, "it up..."
	.DB $57

; text/ViridianForestNorthGate.asm
_ViridianForestNorthGateSuperNerdText::
	.DB $00
	.STRINGMAP pokemon, "Many #MON live"
	.DB $4f
	.STRINGMAP pokemon, "only in forests "
	.DB $55
	.STRINGMAP pokemon, "and caves."
	.DB $51
	.STRINGMAP pokemon, "You need to look"
	.DB $4f
	.STRINGMAP pokemon, "everywhere to get"
	.DB $55
	.STRINGMAP pokemon, "different kinds!"
	.DB $57
_ViridianForestNorthGateGrampsText::
	.DB $00
	.STRINGMAP pokemon, "Have you noticed"
	.DB $4f
	.STRINGMAP pokemon, "the bushes on the"
	.DB $55
	.STRINGMAP pokemon, "roadside?"
	.DB $51
	.STRINGMAP pokemon, "They can be cut"
	.DB $4f
	.STRINGMAP pokemon, "down by a special"
	.DB $55
	.STRINGMAP pokemon, "#MON move."
	.DB $57

; text/Route2TradeHouse.asm
_Route2TradeHouseScientistText::
	.DB $00
	.STRINGMAP pokemon, "A fainted #MON"
	.DB $4f
	.STRINGMAP pokemon, "can't fight. But, "
	.DB $55
	.STRINGMAP pokemon, "it can still use "
	.DB $55
	.STRINGMAP pokemon, "moves like CUT!"
	.DB $57

; text/Route2Gate.asm
_Route2GateOaksAideFlashExplanationText::
	.DB $00
	.STRINGMAP pokemon, "The HM FLASH"
	.DB $4f
	.STRINGMAP pokemon, "lights even the"
	.DB $55
	.STRINGMAP pokemon, "darkest dungeons."
	.DB $57
_Route2GateYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "Once a #MON"
	.DB $4f
	.STRINGMAP pokemon, "learns FLASH, you"
	.DB $55
	.STRINGMAP pokemon, "can get through"
	.DB $55
	.STRINGMAP pokemon, "ROCK TUNNEL."
	.DB $57

; text/ViridianForestSouthGate.asm
_ViridianForestSouthGateGirlText::
	.DB $00
	.STRINGMAP pokemon, "Are you going to"
	.DB $4f
	.STRINGMAP pokemon, "VIRIDIAN FOREST?"
	.DB $55
	.STRINGMAP pokemon, "Be careful, it's"
	.DB $55
	.STRINGMAP pokemon, "a natural maze!"
	.DB $57
_ViridianForestSouthGateLittleGirlText::
	.DB $00
	.STRINGMAP pokemon, "RATTATA may be"
	.DB $4f
	.STRINGMAP pokemon, "small, but its"
	.DB $55
	.STRINGMAP pokemon, "bite is wicked!"
	.DB $55
	.STRINGMAP pokemon, "Did you get one?"
	.DB $57

; text/MtMoonPokecenter.asm
_MtMoonPokecenterYoungsterText::
	.DB $00
	.STRINGMAP pokemon, "I've 6 # BALLs"
	.DB $4f
	.STRINGMAP pokemon, "set in my belt."
	.DB $51
	.STRINGMAP pokemon, "At most, you can"
	.DB $4f
	.STRINGMAP pokemon, "carry 6 #MON."
	.DB $57
_MtMoonPokecenterGentlemanText::
	.DB $00
	.STRINGMAP pokemon, "TEAM ROCKET"
	.DB $4f
	.STRINGMAP pokemon, "attacks CERULEAN"
	.DB $55
	.STRINGMAP pokemon, "citizens..."
	.DB $51
	.STRINGMAP pokemon, "TEAM ROCKET is"
	.DB $4f
	.STRINGMAP pokemon, "always in the"
	.DB $55
	.STRINGMAP pokemon, "news!"
	.DB $57
_MtMoonPokecenterMagikarpSalesmanIGotADealText::
	.DB $00
	.STRINGMAP pokemon, "MAN: Hello, there!"
	.DB $4f
	.STRINGMAP pokemon, "Have I got a deal"
	.DB $55
	.STRINGMAP pokemon, "just for you!"
	.DB $51
	.STRINGMAP pokemon, "I'll let you have"
	.DB $4f
	.STRINGMAP pokemon, "a swell MAGIKARP"
	.DB $55
	.STRINGMAP pokemon, "for just ¥500!"
	.DB $55
	.STRINGMAP pokemon, "What do you say?"
	.DB $57
_MtMoonPokecenterMagikarpSalesmanNoText::
	.DB $00
	.STRINGMAP pokemon, "No? I'm only"
	.DB $4f
	.STRINGMAP pokemon, "doing this as a"
	.DB $55
	.STRINGMAP pokemon, "favor to you!"
	.DB $57
_MtMoonPokecenterMagikarpSalesmanNoMoneyText::
	.DB $00
	.STRINGMAP pokemon, "You'll need more"
	.DB $4f
	.STRINGMAP pokemon, "money than that!"
	.DB $57
_MtMoonPokecenterMagikarpSalesmanNoRefundsText::
	.DB $00
	.STRINGMAP pokemon, "MAN: Well, I don't"
	.DB $4f
	.STRINGMAP pokemon, "give refunds!"
	.DB $57
_MtMoonPokecenterClipboardText::
	.DB $00
	.DB $57

; text/SaffronGates.asm
_SaffronGateGuardGeeImThirstyText::
	.DB $00
	.STRINGMAP pokemon, "I'm on guard duty."
	.DB $4f
	.STRINGMAP pokemon, "Gee, I'm thirsty,"
	.DB $55
	.STRINGMAP pokemon, "though!"
	.DB $51
	.STRINGMAP pokemon, "Oh wait there,"
	.DB $4f
	.STRINGMAP pokemon, "the road's closed."
	.DB $57
_SaffronGateGuardImParchedText::
	.DB $00
	.STRINGMAP pokemon, "Whoa, boy!"
	.DB $4f
	.STRINGMAP pokemon, "I'm parched!"
	.DB $55
	.STRINGMAP pokemon, "..."
	.DB $55
	.STRINGMAP pokemon, "Huh? I can have"
	.DB $55
	.STRINGMAP pokemon, "this drink?"
	.DB $55
	.STRINGMAP pokemon, "Gee, thanks!@"
	.DB $50
_SaffronGateGuardYouCanGoOnThroughText::
	.DB $00
	.DB $51
	.STRINGMAP pokemon, "..."
	.DB $4f
	.STRINGMAP pokemon, "Glug glug..."
	.DB $55
	.STRINGMAP pokemon, "..."
	.DB $55
	.STRINGMAP pokemon, "Gulp..."
	.DB $55
	.STRINGMAP pokemon, "If you want to go"
	.DB $55
	.STRINGMAP pokemon, "to SAFFRON CITY..."
	.DB $55
	.STRINGMAP pokemon, "..."
	.DB $55
	.STRINGMAP pokemon, "You can go on"
	.DB $55
	.STRINGMAP pokemon, "through. I'll"
	.DB $55
	.STRINGMAP pokemon, "share this with"
	.DB $55
	.STRINGMAP pokemon, "the other guards!"
	.DB $57
_SaffronGateGuardThanksForTheDrinkText::
	.DB $00
	.STRINGMAP pokemon, "Hi, thanks for"
	.DB $4f
	.STRINGMAP pokemon, "the cool drinks!"
	.DB $57

; text/Daycare.asm
_DaycareGentlemanIntroText::
	.DB $00
	.STRINGMAP pokemon, "I run a DAYCARE."
	.DB $4f
	.STRINGMAP pokemon, "Would you like me"
	.DB $55
	.STRINGMAP pokemon, "to raise one of"
	.DB $55
	.STRINGMAP pokemon, "your #MON?"
	.DB $57
_DaycareGentlemanWhichMonText::
	.DB $00
	.STRINGMAP pokemon, "Which #MON"
	.DB $4f
	.STRINGMAP pokemon, "should I raise?"
	.DB $58
_DaycareGentlemanWillLookAfterMonText::
	.DB $00
	.STRINGMAP pokemon, "Fine, I'll look"
	.DB $4f
	.STRINGMAP pokemon, "after @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $55
	.STRINGMAP pokemon, "for a while."
	.DB $58
_DaycareGentlemanComeSeeMeInAWhileText::
	.DB $00
	.STRINGMAP pokemon, "Come see me in"
	.DB $4f
	.STRINGMAP pokemon, "a while."
	.DB $57
_DaycareGentlemanMonHasGrownText::
	.DB $00
	.STRINGMAP pokemon, "Your @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "has grown a lot!"
	.DB $51
	.STRINGMAP pokemon, "By level, it's"
	.DB $4f
	.STRINGMAP pokemon, "grown by @"
	.DB $09
	.DW wDayCareNumLevelsGrown
	.DB $13
	.DB $00
	.STRINGMAP pokemon, "!"
	.DB $51
	.STRINGMAP pokemon, "Aren't I great?"
	.DB $58
_DaycareGentlemanOweMoneyText::
	.DB $00
	.STRINGMAP pokemon, "You owe me ¥@"
	.DB $02
	.DW wDayCareTotalCost
	.DB $c2
	.DB $00
	.DB $4f
	.STRINGMAP pokemon, "for the return"
	.DB $55
	.STRINGMAP pokemon, "of this #MON."
	.DB $57
_DaycareGentlemanGotMonBackText::
	.DB $00
	.STRINGMAP pokemon, "<PLAYER> got"
	.DB $4f
	.STRINGMAP pokemon, "@"
	.DB $01
	.DW wDayCareMonName
	.DB $00
	.STRINGMAP pokemon, " back!"
	.DB $57
_DaycareGentlemanMonNeedsMoreTimeText::
	.DB $00
	.STRINGMAP pokemon, "Back already?"
	.DB $4f
	.STRINGMAP pokemon, "Your @"
	.DB $01
	.DW wNameBuffer
	.DB $00
	.DB $55
	.STRINGMAP pokemon, "needs some more"
	.DB $55
	.STRINGMAP pokemon, "time with me."
	.DB $58

Bank34TextEnd::
