FuchsiaBillsGrandpasHouse_Script:
	CALL $3C3C ; EnableAutoTextBoxDrawing
	RET
FuchsiaBillsGrandpasHouseScriptEnd:
.ASSERT FuchsiaBillsGrandpasHouseScriptEnd - FuchsiaBillsGrandpasHouse_Script == 4

FuchsiaBillsGrandpasHouse_TextPointers:
	.DW FuchsiaBillsGrandpasHouseMiddleAgedWomanText
	.DW FuchsiaBillsGrandpasHouseBillsGrandpaText
	.DW FuchsiaBillsGrandpasHouseYoungsterText
FuchsiaBillsGrandpasHouseTextPointersEnd:
.ASSERT FuchsiaBillsGrandpasHouseTextPointersEnd - FuchsiaBillsGrandpasHouse_TextPointers == 6
