#!/usr/bin/env python3
"""Convert a constrained RGBDS text section to native WLA-DX directives."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


LABEL_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):{1,2}$")
STRING_RE = re.compile(r'^\s*(text|next|line|para|cont)\s+"(.*)"$')
RAM_RE = re.compile(r"^\s*text_ram\s+([A-Za-z_][A-Za-z0-9_]*)$")
BCD_RE = re.compile(r"^\s*text_bcd\s+([A-Za-z_][A-Za-z0-9_]*),\s*([23])\s*\|\s*LEADING_ZEROES\s*\|\s*LEFT_ALIGN$")
DECIMAL_RE = re.compile(r"^\s*text_decimal\s+([A-Za-z_][A-Za-z0-9_]*),\s*([0-9]+),\s*([0-9]+)$")
STRING_COMMANDS = {"text": "$00", "next": "$4e", "line": "$4f", "para": "$51", "cont": "$55"}
BYTE_COMMANDS = {"done": "$57", "prompt": "$58", "text_start": "$00", "text_end": "$50"}


def strip_comment(raw: str) -> str:
    in_string = False
    for index, character in enumerate(raw):
        if character == '"':
            in_string = not in_string
        elif character == ";" and not in_string:
            return raw[:index]
    return raw


def convert(sources: list[Path], end_label: str) -> str:
    output = [
        "; Generated by convert_text_bank.py from:",
        *[f";   {source}" for source in sources],
        '.STRINGMAPTABLE pokemon "wla/pokemon.tbl"',
        "",
    ]
    labels = 0
    for source in sources:
        output.append(f"; {source}")
        skipping_vc = False
        for line_number, raw in enumerate(source.read_text().splitlines(), 1):
            active = strip_comment(raw)
            line = active.strip()
            if not line:
                continue
            if line.startswith("vc_patch"):
                continue
            if line == "IF DEF(_RED_VC) || DEF(_BLUE_VC)":
                skipping_vc = True
                continue
            if line == "ELSE" and skipping_vc:
                skipping_vc = False
                continue
            if line == "ENDC":
                skipping_vc = False
                continue
            if skipping_vc:
                continue
            label = LABEL_RE.fullmatch(line)
            if label:
                output.extend((f"{label.group(1)}::",))
                labels += 1
                continue
            string = STRING_RE.fullmatch(active)
            if string:
                command, value = string.groups()
                output.append(f"\t.DB {STRING_COMMANDS[command]}")
                output.append(f'\t.STRINGMAP pokemon, "{value}"')
                continue
            if line in BYTE_COMMANDS:
                output.append(f"\t.DB {BYTE_COMMANDS[line]}")
                continue
            ram = RAM_RE.fullmatch(line)
            if ram:
                output.extend(("\t.DB $01", f"\t.DW {ram.group(1)}"))
                continue
            bcd = BCD_RE.fullmatch(line)
            if bcd:
                output.extend(("\t.DB $02", f"\t.DW {bcd.group(1)}", f"\t.DB $c{bcd.group(2)}"))
                continue
            decimal = DECIMAL_RE.fullmatch(line)
            if decimal:
                address, byte_count, digit_count = decimal.groups()
                packed = (int(byte_count) << 4) | int(digit_count)
                output.extend(("\t.DB $09", f"\t.DW {address}", f"\t.DB ${packed:02x}"))
                continue
            raise ValueError(f"{source}:{line_number}: unsupported line: {raw}")
        output.append("")
    if labels == 0:
        raise ValueError("no text labels found")
    output.append(f"{end_label}::")
    return "\n".join(output) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("sources", nargs="+", type=Path)
    args = parser.parse_args()
    bank = re.search(r"bank(\d+)_", args.output.name)
    if not bank:
        raise ValueError(f"cannot derive bank number from {args.output}")
    args.output.write_text(convert(args.sources, f"Bank{int(bank.group(1))}TextEnd"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
