.BANK 23
.ORG $0000

; Data from 5C000 to 5FFFF (16384 bytes)
.INCLUDE "wla/banks/bank23_maps_15.asm"
.INCLUDE "wla/banks/bank23_starter_dex.asm"
.INCLUDE "wla/banks/bank23_museum_1f_header.asm"
.INCLUDE "wla/banks/bank23_museum_1f_script.asm"
.INCLUDE "wla/banks/bank23_museum_1f_script_pointers.asm"
.INCLUDE "wla/banks/bank23_museum_1f_default_script.asm"
.INCLUDE "wla/banks/bank23_museum_1f_text_pointers.asm"
.db $08, $FA, $61, $D3, $FE, $04, $20, $0A, $FA, $62, $D3
.db $FE, $0D, $CA, $F9, $41, $18, $1C, $FE, $03, $20, $08, $FA, $62, $D3, $FE, $0C
.db $CA, $F9, $41, $FA, $54, $D7, $CB, $47, $20, $10, $21, $3D, $42, $CD, $49, $3C
.db $C3, $17, $42, $FA, $54, $D7, $CB, $47, $28, $09, $21, $42, $42, $CD, $49, $3C
.db $C3, $17, $42, $3E, $13, $EA, $25, $D1, $CD, $E8, $30, $AF, $E0, $B4, $21, $1F
.db $42, $CD, $49, $3C, $CD, $EC, $35, $FA, $26, $CC, $A7, $20, $4D, $AF, $E0, $9F
.db $E0, $A0, $3E, $50, $E0, $A1, $CD, $A6, $35, $30, $09, $21, $29, $42, $CD, $49
.db $3C, $C3, $DA, $41, $21, $24, $42, $CD, $49, $3C, $21, $54, $D7, $CB, $C6, $AF
.db $EA, $3D, $CD, $EA, $3E, $CD, $3E, $50, $EA, $3F, $CD, $21, $3F, $CD, $11, $49
.db $D3, $0E, $03, $3E, $0C, $CD, $6D, $3E, $3E, $13, $EA, $25, $D1, $CD, $E8, $30
.db $3E, $B2, $CD, $40, $37, $CD, $48, $37, $18, $18, $21, $1A, $42, $CD, $49, $3C
.db $3E, $01, $EA, $38, $CD, $3E, $80, $EA, $D3, $CC, $CD, $86, $34, $CD, $29, $24
.db $18, $25, $3E, $01, $EA, $19, $D6, $18, $1E, $21, $2E, $42, $CD, $49, $3C, $CD
.db $EC, $35, $FA, $26, $CC, $FE, $00, $20, $08, $21, $33, $42, $CD, $49, $3C, $18
.db $06, $21, $38, $42, $CD, $49, $3C, $C3, $D7, $24, $17, $2C, $65, $25, $50, $17
.db $39, $65, $25, $50, $17, $72, $65, $25, $50, $17, $8A, $65, $25, $50, $17, $A7
.db $65, $25, $50, $17, $F1, $65, $25, $50, $17, $36, $66, $25, $50, $17, $57, $66
.db $25, $50, $17, $75, $66, $25, $50
.INCLUDE "wla/banks/bank23_museum_1f_gambler_text.asm"
.INCLUDE "wla/banks/bank23_museum_1f_scientist2_text.asm"
.INCLUDE "wla/banks/bank23_museum_1f_small_texts.asm"
.INCLUDE "wla/banks/bank23_museum_1f_object.asm"
.INCLUDE "wla/banks/bank23_museum_2f_header.asm"
.INCLUDE "wla/banks/bank23_museum_2f_dispatch.asm"
.INCLUDE "wla/banks/bank23_museum_2f_texts.asm"
.INCLUDE "wla/banks/bank23_museum_2f_object.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_header.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_dispatch.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_script_pointers.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_brock_post_battle.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_text_pointers.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_trainer_headers.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_brock_text.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_brock_text_records.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_cooltrainer_text.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_guide_text.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_object.asm"
.INCLUDE "wla/banks/bank23_pewter_gym_blocks.asm"
.INCLUDE "wla/banks/bank23_pewter_pokecenter_header.asm"
.INCLUDE "wla/banks/bank23_pewter_pokecenter_dispatch.asm"
.INCLUDE "wla/banks/bank23_pewter_pokecenter_small_texts.asm"
.INCLUDE "wla/banks/bank23_pewter_pokecenter_jigglypuff.asm"
.INCLUDE "wla/banks/bank23_pewter_pokecenter_receptionist.asm"
.INCLUDE "wla/banks/bank23_pewter_pokecenter_object.asm"
.INCLUDE "wla/banks/bank23_cerulean_pokecenter_header.asm"
.INCLUDE "wla/banks/bank23_cerulean_pokecenter_dispatch.asm"
.INCLUDE "wla/banks/bank23_cerulean_pokecenter_object.asm"
.INCLUDE "wla/banks/bank23_cerulean_pokecenter_blocks.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_header.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_dispatch.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_script_pointers.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_misty_post_battle.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_tables.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_misty_text.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_misty_records.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_trainer_texts.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_guide_text.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_object.asm"
.INCLUDE "wla/banks/bank23_cerulean_gym_blocks.asm"
.INCLUDE "wla/banks/bank23_cerulean_mart_header.asm"
.INCLUDE "wla/banks/bank23_cerulean_mart_dispatch.asm"
.INCLUDE "wla/banks/bank23_cerulean_mart_texts.asm"
.INCLUDE "wla/banks/bank23_cerulean_mart_object.asm"
.INCLUDE "wla/banks/bank23_lavender_pokecenter_header.asm"
.INCLUDE "wla/banks/bank23_lavender_pokecenter_dispatch.asm"
.INCLUDE "wla/banks/bank23_lavender_pokecenter_object.asm"
.INCLUDE "wla/banks/bank23_lavender_mart_header.asm"
.INCLUDE "wla/banks/bank23_lavender_mart_dispatch.asm"
.INCLUDE "wla/banks/bank23_lavender_mart_cooltrainer_text.asm"
.INCLUDE "wla/banks/bank23_lavender_mart_object.asm"
.INCLUDE "wla/banks/bank23_vermilion_pokecenter_header.asm"
.INCLUDE "wla/banks/bank23_vermilion_pokecenter_dispatch.asm"
.INCLUDE "wla/banks/bank23_vermilion_pokecenter_object.asm"
.INCLUDE "wla/banks/bank23_vermilion_mart_header.asm"
.INCLUDE "wla/banks/bank23_vermilion_mart_dispatch.asm"
.INCLUDE "wla/banks/bank23_vermilion_mart_texts.asm"
.INCLUDE "wla/banks/bank23_vermilion_mart_object.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_header.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_dispatch.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_battle_control.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_tables.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_surge_text.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_surge_records.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_trainer_texts.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_guide_text.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_object.asm"
.INCLUDE "wla/banks/bank23_vermilion_gym_blocks.asm"
.INCLUDE "wla/banks/bank23_copycats_house_2f_entry.asm"
.INCLUDE "wla/banks/bank23_copycats_house_2f_copycat_text.asm"
.INCLUDE "wla/banks/bank23_copycats_house_2f_room_texts.asm"
.INCLUDE "wla/banks/bank23_copycats_house_2f_object.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_entry.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_default.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_post_battle.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_tables.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_master_text.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_blackbelt_texts.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_prizes.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_object.asm"
.INCLUDE "wla/banks/bank23_fighting_dojo_blocks.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_entry.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_battle_control.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_tables.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_sabrina_text.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_sabrina_records.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_trainer_handlers.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_guide_text.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_trainer_records.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_object.asm"
.INCLUDE "wla/banks/bank23_saffron_gym_blocks.asm"
.INCLUDE "wla/banks/bank23_saffron_mart_header.asm"
.INCLUDE "wla/banks/bank23_saffron_mart_script.asm"
.INCLUDE "wla/banks/bank23_saffron_mart_text.asm"
.INCLUDE "wla/banks/bank23_saffron_mart_object.asm"
.INCLUDE "wla/banks/bank23_silph_co_1f_header.asm"
.INCLUDE "wla/banks/bank23_silph_co_1f_script.asm"
.INCLUDE "wla/banks/bank23_silph_co_1f_text.asm"
.INCLUDE "wla/banks/bank23_silph_co_1f_object.asm"
.INCLUDE "wla/banks/bank23_silph_co_1f_blocks.asm"
.INCLUDE "wla/banks/bank23_saffron_pokecenter_header.asm"
.INCLUDE "wla/banks/bank23_saffron_pokecenter_script.asm"
.INCLUDE "wla/banks/bank23_saffron_pokecenter_text.asm"
.INCLUDE "wla/banks/bank23_saffron_pokecenter_object.asm"
.INCLUDE "wla/banks/bank23_viridian_forest_north_gate.asm"
.INCLUDE "wla/banks/bank23_route2_gate.asm"
.INCLUDE "wla/banks/bank23_viridian_forest_south_gate.asm"
.INCLUDE "wla/banks/bank23_underground_path_route5.asm"
.INCLUDE "wla/banks/bank23_underground_path_route6.asm"
.INCLUDE "wla/banks/bank23_underground_path_route7.asm"
.INCLUDE "wla/banks/bank23_underground_path_route7_copy.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_entry.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_gate_callback.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_card_key.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_tables.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_nurse.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_trainer_handlers.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_trainer_records.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_object.asm"
.INCLUDE "wla/banks/bank23_silph_co_9f_blocks.asm"
.INCLUDE "wla/banks/bank23_victory_road_1f_entry.asm"
.INCLUDE "wla/banks/bank23_victory_road_1f_tables.asm"
.INCLUDE "wla/banks/bank23_victory_road_1f_text.asm"
.INCLUDE "wla/banks/bank23_victory_road_1f_object.asm"
.INCLUDE "wla/banks/bank23_victory_road_1f_blocks.asm"
.INCLUDE "wla/banks/bank23_hidden_events_3.asm"
.dsb 8427, $00
