; Constants required to lay out the native RAM object.
; These values mirror the authoritative definitions under constants/ while
; those shared files are being converted to WLA-DX expression syntax.
.DEFINE NUM_CHANNELS 8
.DEFINE NUM_SPRITESTATEDATA_STRUCTS 16
.DEFINE OAM_COUNT 40
.DEFINE OBJ_SIZE 4

.DEFINE TILE_SIZE 16
.DEFINE SCREEN_WIDTH 20
.DEFINE SCREEN_AREA 360
.DEFINE TILEMAP_WIDTH 32
.DEFINE TILEMAP_AREA 1024
.DEFINE SURROUNDING_WIDTH 24
.DEFINE SURROUNDING_HEIGHT 20
.DEFINE PIC_SIZE 49
.DEFINE SPRITEBUFFERSIZE 392

.DEFINE NUM_MOVES 4
.DEFINE NUM_STATS 5
.DEFINE PARTY_LENGTH 6
.DEFINE MONS_PER_BOX 20
.DEFINE NUM_BOXES 12
.DEFINE PARTYMON_STRUCT_LENGTH 44
.DEFINE HOF_TEAM 96
.DEFINE HOF_TEAM_CAPACITY 50

.DEFINE NUM_POKEMON 151
.DEFINE NUM_EVENTS $a00
.DEFINE NUM_TMS 50
.DEFINE NUM_HMS 5
.DEFINE NUM_EVOS_IN_BUFFER 3
.DEFINE NUM_BADGES 8
.DEFINE NUM_CITY_MAPS 11

.DEFINE NAME_LENGTH 11
.DEFINE ITEM_NAME_LENGTH 13
.DEFINE MOVE_NAME_LENGTH 14
.DEFINE GYM_CITY_LENGTH 17
.DEFINE NAME_BUFFER_LENGTH 20
.DEFINE MOVE_LENGTH 6
.DEFINE BAG_ITEM_CAPACITY 20
.DEFINE PC_ITEM_CAPACITY 50

.DEFINE MAX_WARP_EVENTS 32
.DEFINE MAX_BG_EVENTS 16
.DEFINE MAX_OBJECT_EVENTS 16
.DEFINE MAX_HIDDEN_ITEMS 112
.DEFINE MAX_HIDDEN_COINS 16
.DEFINE SPRITE_SET_LENGTH 11
.DEFINE WILDDATA_LENGTH 21
.DEFINE SERIAL_NO_DATA_BYTE $fe
