; These are all the asm constants needed to make the red_vc patch.

; [FPA 001 Begin]
.DEFINE M_CHAR $8c EXPORT
.DEFINE E_CHAR $84 EXPORT
.DEFINE G_CHAR $86 EXPORT
.DEFINE A_CHAR $80 EXPORT
.DEFINE P_CHAR $8f EXPORT
.DEFINE S_CHAR $92 EXPORT
.DEFINE L_CHAR $8b EXPORT
.DEFINE F_CHAR $85 EXPORT
.DEFINE D_CHAR $83 EXPORT
.DEFINE X_CHAR $97 EXPORT
.EXPORT MEGA_PUNCH

; [FPA 002 Begin]
.DEFINE U_CHAR $94 EXPORT
.DEFINE I_CHAR $88 EXPORT
.EXPORT GUILLOTINE

; [FPA 003 Begin]
.DEFINE K_CHAR $8a EXPORT
.EXPORT MEGA_KICK

; [FPA 004 Begin]
.DEFINE B_CHAR $81 EXPORT
.EXPORT BUBBLEBEAM

; [FPA 005 Begin]
.DEFINE H_CHAR $87 EXPORT
.DEFINE Y_CHAR $98 EXPORT
.EXPORT HYPER_BEAM

; [FPA 006 Begin]
.DEFINE T_CHAR $93 EXPORT
.DEFINE N_CHAR $8d EXPORT
.EXPORT THUNDERBOLT

; [FPA 007 Begin]
.DEFINE R_CHAR $91 EXPORT
.EXPORT REFLECT

; [FPA 008 Begin]
.EXPORT DREAM_EATER

; [FPA 008 End]
.DEFINE Z_CHAR $99 EXPORT
.EXPORT BLIZZARD

; [FPA 009 Begin]
.DEFINE O_CHAR $8e EXPORT
.EXPORT SPORE

; [FPA 010 Begin]
.DEFINE C_CHAR $82 EXPORT
.EXPORT ROCK_SLIDE

; [FPA 010 End]
.EXPORT SELFDESTRUCT
.EXPORT EXPLOSION

; [FPA conf Begin]
.EXPORT CONFUSION

; [FPA phy Begin]
.EXPORT PSYCHIC_M
