; performs the appropriate action when the player uses the gameboy on the table in the Colosseum or Trade Center
; In the Colosseum, it starts a battle. In the Trade Center, it displays the trade selection screen.
; Before doing either action, it swaps random numbers, trainer names and party data with the other gameboy.
CableClub_DoBattleOrTrade:
	ld c, 80
	call DelayFrames
	call ClearScreen
	call UpdateSprites
	call LoadFontTilePatterns
	call LoadHpBarAndStatusTilePatterns
	call LoadTrainerInfoTextBoxTiles
	hlcoord 3, 8
	ld b, 2
	ld c, 12
	call CableClub_TextBoxBorder
	hlcoord 4, 10
	ld de, PleaseWaitString
	call PlaceString
	ld hl, wPlayerNumHits
	xor a
	ld [hli], a
	ld [hl], $50
	; fall through

; This is called after completing a trade.
CableClub_DoBattleOrTradeAgain:
	ld hl, wSerialPlayerDataBlock
	ld a, SERIAL_PREAMBLE_BYTE
	ld b, 6
CableClub_DoBattleOrTradeAgain.writePlayerDataBlockPreambleLoop
	ld [hli], a
	dec b
	jr nz, CableClub_DoBattleOrTradeAgain.writePlayerDataBlockPreambleLoop
	ld hl, wSerialRandomNumberListBlock
	ld a, SERIAL_PREAMBLE_BYTE
	ld b, 7
CableClub_DoBattleOrTradeAgain.writeRandomNumberListPreambleLoop
	ld [hli], a
	dec b
	jr nz, CableClub_DoBattleOrTradeAgain.writeRandomNumberListPreambleLoop
	ld b, 10
CableClub_DoBattleOrTradeAgain.generateRandomNumberListLoop
	call Random
	cp SERIAL_PREAMBLE_BYTE ; all the random numbers have to be less than the preamble byte
	jr nc, CableClub_DoBattleOrTradeAgain.generateRandomNumberListLoop
	ld [hli], a
	dec b
	jr nz, CableClub_DoBattleOrTradeAgain.generateRandomNumberListLoop
	ld hl, wSerialPartyMonsPatchList
	ld a, SERIAL_PREAMBLE_BYTE
	ld [hli], a
	ld [hli], a
	ld [hli], a
	ld b, $c8
	xor a
CableClub_DoBattleOrTradeAgain.zeroPlayerDataPatchListLoop
	ld [hli], a
	dec b
	jr nz, CableClub_DoBattleOrTradeAgain.zeroPlayerDataPatchListLoop
	ld hl, wLinkEnemyTrainerName
	ld bc, wTrainerHeaderPtr - wLinkEnemyTrainerName
CableClub_DoBattleOrTradeAgain.zeroEnemyPartyLoop
	xor a
	ld [hli], a
	dec bc
	ld a, b
	or c
	jr nz, CableClub_DoBattleOrTradeAgain.zeroEnemyPartyLoop
	ld hl, wPartyMons - 1
	ld de, wSerialPartyMonsPatchList + 10
	ld bc, 0
CableClub_DoBattleOrTradeAgain.patchPartyMonsLoop
	inc c
	ld a, c
	cp SERIAL_PREAMBLE_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.startPatchListPart2
	ld a, b
	dec a ; are we in part 2 of the patch list?
	jr nz, CableClub_DoBattleOrTradeAgain.checkPlayerDataByte ; jump if in part 1
; if we're in part 2
	ld a, c
	cp (wPartyMonOT - (wPartyMons - 1)) - (SERIAL_PREAMBLE_BYTE - 1)
	jr z, CableClub_DoBattleOrTradeAgain.finishedPatchingPlayerData
CableClub_DoBattleOrTradeAgain.checkPlayerDataByte
	inc hl
	ld a, [hl]
	cp SERIAL_NO_DATA_BYTE
	jr nz, CableClub_DoBattleOrTradeAgain.patchPartyMonsLoop
; if the player data byte matches SERIAL_NO_DATA_BYTE, patch it with $FF and record the offset in the patch list
	ld a, c
	ld [de], a
	inc de
	ld [hl], $ff
	jr CableClub_DoBattleOrTradeAgain.patchPartyMonsLoop
CableClub_DoBattleOrTradeAgain.startPatchListPart2
	ld a, SERIAL_PATCH_LIST_PART_TERMINATOR
	ld [de], a ; end of part 1
	inc de
	lb "bc", 1, 0
	jr CableClub_DoBattleOrTradeAgain.patchPartyMonsLoop
CableClub_DoBattleOrTradeAgain.finishedPatchingPlayerData
	ld a, SERIAL_PATCH_LIST_PART_TERMINATOR
	ld [de], a ; end of part 2
	call Serial_SyncAndExchangeNybble
	ldh a, [lobyte(hSerialConnectionStatus)]
	cp USING_INTERNAL_CLOCK
	jr nz, CableClub_DoBattleOrTradeAgain.skipSendingTwoZeroBytes
; if using internal clock
; send two zero bytes for syncing purposes?
	call Delay3
	xor a
	ldh [lobyte(hSerialSendData)], a
	ld a, SC_START | SC_INTERNAL
	ldh [lobyte(rSC)], a
	call DelayFrame
	xor a
	ldh [lobyte(hSerialSendData)], a
	ld a, SC_START | SC_INTERNAL
	ldh [lobyte(rSC)], a
CableClub_DoBattleOrTradeAgain.skipSendingTwoZeroBytes
	call Delay3
	ld a, IE_SERIAL
	ldh [lobyte(rIE)], a
	ld hl, wSerialRandomNumberListBlock
	ld de, wSerialOtherGameboyRandomNumberListBlock
	ld bc, SERIAL_RN_PREAMBLE_LENGTH + SERIAL_RNS_LENGTH
	vc_hook Wireless_ExchangeBytes_RNG_state_unknown_Type5
	call Serial_ExchangeBytes
	ld a, SERIAL_NO_DATA_BYTE
	ld [de], a
	ld hl, wSerialPlayerDataBlock
	ld de, wSerialEnemyDataBlock
	ld bc, SERIAL_PREAMBLE_LENGTH + NAME_LENGTH + 1 + PARTY_LENGTH + 1 + (PARTYMON_STRUCT_LENGTH + NAME_LENGTH * 2) * PARTY_LENGTH + 3
	vc_hook Wireless_ExchangeBytes_party_structs
	call Serial_ExchangeBytes
	ld a, SERIAL_NO_DATA_BYTE
	ld [de], a
	ld hl, wSerialPartyMonsPatchList
	ld de, wSerialEnemyMonsPatchList
	ld bc, 200
	vc_hook Wireless_ExchangeBytes_patch_lists
	call Serial_ExchangeBytes
	ld a, IE_SERIAL | IE_TIMER | IE_VBLANK
	ldh [lobyte(rIE)], a
	ld a, SFX_STOP_ALL_MUSIC
	call PlaySound
	ldh a, [lobyte(hSerialConnectionStatus)]
	cp USING_INTERNAL_CLOCK
	jr z, CableClub_DoBattleOrTradeAgain.skipCopyingRandomNumberList ; the list generated by the gameboy clocking the connection is used by both gameboys
	ld hl, wSerialOtherGameboyRandomNumberListBlock
CableClub_DoBattleOrTradeAgain.findStartOfRandomNumberListLoop
	ld a, [hli]
	and a
	jr z, CableClub_DoBattleOrTradeAgain.findStartOfRandomNumberListLoop
	cp SERIAL_PREAMBLE_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.findStartOfRandomNumberListLoop
	cp SERIAL_NO_DATA_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.findStartOfRandomNumberListLoop
	dec hl
	ld de, wLinkBattleRandomNumberList
	ld c, 10
CableClub_DoBattleOrTradeAgain.copyRandomNumberListLoop
	ld a, [hli]
	cp SERIAL_NO_DATA_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.copyRandomNumberListLoop
	ld [de], a
	inc de
	dec c
	jr nz, CableClub_DoBattleOrTradeAgain.copyRandomNumberListLoop
CableClub_DoBattleOrTradeAgain.skipCopyingRandomNumberList
	ld hl, wSerialEnemyDataBlock + 3
CableClub_DoBattleOrTradeAgain.findStartOfEnemyNameLoop
	ld a, [hli]
	and a
	jr z, CableClub_DoBattleOrTradeAgain.findStartOfEnemyNameLoop
	cp SERIAL_PREAMBLE_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.findStartOfEnemyNameLoop
	cp SERIAL_NO_DATA_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.findStartOfEnemyNameLoop
	dec hl
	ld de, wLinkEnemyTrainerName
	ld c, NAME_LENGTH
CableClub_DoBattleOrTradeAgain.copyEnemyNameLoop
	ld a, [hli]
	cp SERIAL_NO_DATA_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.copyEnemyNameLoop
	ld [de], a
	inc de
	dec c
	jr nz, CableClub_DoBattleOrTradeAgain.copyEnemyNameLoop
	ld de, wEnemyPartyCount
	ld bc, wTrainerHeaderPtr - wEnemyPartyCount
CableClub_DoBattleOrTradeAgain.copyEnemyPartyLoop
	ld a, [hli]
	cp SERIAL_NO_DATA_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.copyEnemyPartyLoop
	ld [de], a
	inc de
	dec bc
	ld a, b
	or c
	jr nz, CableClub_DoBattleOrTradeAgain.copyEnemyPartyLoop
	ld de, wSerialPartyMonsPatchList
	ld hl, wPartyMons
	ld c, 2 ; patch list has 2 parts
CableClub_DoBattleOrTradeAgain.unpatchPartyMonsLoop
	ld a, [de]
	inc de
	and a
	jr z, CableClub_DoBattleOrTradeAgain.unpatchPartyMonsLoop
	cp SERIAL_PREAMBLE_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.unpatchPartyMonsLoop
	cp SERIAL_NO_DATA_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.unpatchPartyMonsLoop
	cp SERIAL_PATCH_LIST_PART_TERMINATOR
	jr z, CableClub_DoBattleOrTradeAgain.finishedPartyMonsPatchListPart
	push hl
	push bc
	ld b, 0
	dec a
	ld c, a
	add hl, bc
	ld a, SERIAL_NO_DATA_BYTE
	ld [hl], a
	pop bc
	pop hl
	jr CableClub_DoBattleOrTradeAgain.unpatchPartyMonsLoop
CableClub_DoBattleOrTradeAgain.finishedPartyMonsPatchListPart
	ld hl, wPartyMons + (SERIAL_PREAMBLE_BYTE - 1)
	dec c ; is there another part?
	jr nz, CableClub_DoBattleOrTradeAgain.unpatchPartyMonsLoop
	ld de, wSerialEnemyMonsPatchList
	ld hl, wEnemyMons
	ld c, 2 ; patch list has 2 parts
CableClub_DoBattleOrTradeAgain.unpatchEnemyMonsLoop
	ld a, [de]
	inc de
	and a
	jr z, CableClub_DoBattleOrTradeAgain.unpatchEnemyMonsLoop
	cp SERIAL_PREAMBLE_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.unpatchEnemyMonsLoop
	cp SERIAL_NO_DATA_BYTE
	jr z, CableClub_DoBattleOrTradeAgain.unpatchEnemyMonsLoop
	cp SERIAL_PATCH_LIST_PART_TERMINATOR
	jr z, CableClub_DoBattleOrTradeAgain.finishedEnemyMonsPatchListPart
	push hl
	push bc
	ld b, 0
	dec a
	ld c, a
	add hl, bc
	ld a, SERIAL_NO_DATA_BYTE
	ld [hl], a
	pop bc
	pop hl
	jr CableClub_DoBattleOrTradeAgain.unpatchEnemyMonsLoop
CableClub_DoBattleOrTradeAgain.finishedEnemyMonsPatchListPart
	ld hl, wEnemyMons + (SERIAL_PREAMBLE_BYTE - 1)
	dec c
	jr nz, CableClub_DoBattleOrTradeAgain.unpatchEnemyMonsLoop
	ld a, lobyte(wEnemyMonOT)
	ld [wUnusedNamePointer], a
	ld a, hibyte(wEnemyMonOT)
	ld [wUnusedNamePointer + 1], a
	xor a
	ld [wTradeCenterPointerTableIndex], a
	ld a, SFX_STOP_ALL_MUSIC
	call PlaySound
	ldh a, [lobyte(hSerialConnectionStatus)]
	cp USING_INTERNAL_CLOCK
	ld c, 66
	call z, DelayFrames ; delay if using internal clock
	ld a, [wLinkState]
	cp LINK_STATE_START_BATTLE
	ld a, LINK_STATE_TRADING
	ld [wLinkState], a
	jr nz, CableClub_DoBattleOrTradeAgain.trading
	ld a, LINK_STATE_BATTLING
	ld [wLinkState], a
	ld a, OPP_RIVAL1
	ld [wCurOpponent], a
	call ClearScreen
	call Delay3
	ld hl, wOptions
	res BIT_BATTLE_ANIMATION, [hl]
	predef InitOpponent
	predef HealParty
	jp ReturnToCableClubRoom
CableClub_DoBattleOrTradeAgain.trading
	ld c, bank(Music_GameCorner)
	ld a, MUSIC_GAME_CORNER
	call PlayMusic
	jr CallCurrentTradeCenterFunction

PleaseWaitString:
		.STRINGMAP pokemon, "PLEASE WAIT!@"

CallCurrentTradeCenterFunction:
	ld hl, TradeCenterPointerTable
	ld b, 0
	ld a, [wTradeCenterPointerTableIndex]
	cp $ff
	jp z, DisplayTitleScreen
	add a
	ld c, a
	add hl, bc
	ld a, [hli]
	ld h, [hl]
	ld l, a
	jp hl

TradeCenter_SelectMon:
	call ClearScreen
	call LoadTrainerInfoTextBoxTiles
	call TradeCenter_DrawPartyLists
	call TradeCenter_DrawCancelBox
	xor a
	ld hl, wSerialSyncAndExchangeNybbleReceiveData
	ld [hli], a
	ld [hli], a
	ld [hli], a
	ld [hl], a
	ld [wMenuWatchMovingOutOfBounds], a
	ld [wCurrentMenuItem], a
	ld [wLastMenuItem], a
	ld [wMenuJoypadPollCount], a
	inc a
	ld [wSerialExchangeNybbleSendData], a
	jp TradeCenter_SelectMon.playerMonMenu
TradeCenter_SelectMon.enemyMonMenu
	xor a
	ld [wMenuWatchMovingOutOfBounds], a
	inc a
	ld [wWhichTradeMonSelectionMenu], a
	ld a, PAD_DOWN | PAD_LEFT | PAD_A
	ld [wMenuWatchedKeys], a
	ld a, [wEnemyPartyCount]
	ld [wMaxMenuItem], a
	ld a, 9
	ld [wTopMenuItemY], a
	ld a, 1
	ld [wTopMenuItemX], a
TradeCenter_SelectMon.enemyMonMenu_HandleInput
	ld hl, hUILayoutFlags
	set BIT_DOUBLE_SPACED_MENU, [hl]
	call HandleMenuInput
	ld hl, hUILayoutFlags
	res BIT_DOUBLE_SPACED_MENU, [hl]
	and a
	jp z, TradeCenter_SelectMon.getNewInput
	bit B_PAD_A, a
	jr z, TradeCenter_SelectMon.enemyMonMenu_ANotPressed
; if A button pressed
	ld a, [wMaxMenuItem]
	ld c, a
	ld a, [wCurrentMenuItem]
	cp c
	jr c, TradeCenter_SelectMon.displayEnemyMonStats
	ld a, [wMaxMenuItem]
	dec a
	ld [wCurrentMenuItem], a
TradeCenter_SelectMon.displayEnemyMonStats
	ld a, INIT_ENEMYOT_LIST
	ld [wInitListType], a
	callfar InitList ; the list isn't used
	ld hl, wEnemyMons
	call TradeCenter_DisplayStats
	jp TradeCenter_SelectMon.getNewInput
TradeCenter_SelectMon.enemyMonMenu_ANotPressed
	bit B_PAD_LEFT, a
	jr z, TradeCenter_SelectMon.enemyMonMenu_LeftNotPressed
; if Left pressed, switch back to the player mon menu
	xor a ; player mon menu
	ld [wWhichTradeMonSelectionMenu], a
	ld a, [wMenuCursorLocation]
	ld l, a
	ld a, [wMenuCursorLocation + 1]
	ld h, a
	ld a, [wTileBehindCursor]
	ld [hl], a
	ld a, [wCurrentMenuItem]
	ld b, a
	ld a, [wPartyCount]
	dec a
	cp b
	jr nc, TradeCenter_SelectMon.playerMonMenu
	ld [wCurrentMenuItem], a
	jr TradeCenter_SelectMon.playerMonMenu
TradeCenter_SelectMon.enemyMonMenu_LeftNotPressed
	bit B_PAD_DOWN, a
	jp z, TradeCenter_SelectMon.getNewInput
	jp TradeCenter_SelectMon.selectedCancelMenuItem ; jump if Down pressed
TradeCenter_SelectMon.playerMonMenu
	xor a ; player mon menu
	ld [wWhichTradeMonSelectionMenu], a
	ld [wMenuWatchMovingOutOfBounds], a
	ld a, PAD_DOWN | PAD_RIGHT | PAD_A
	ld [wMenuWatchedKeys], a
	ld a, [wPartyCount]
	ld [wMaxMenuItem], a
	ld a, 1
	ld [wTopMenuItemY], a
	ld a, 1
	ld [wTopMenuItemX], a
	hlcoord 1, 1
	lb "bc", 6, 1
	call ClearScreenArea
TradeCenter_SelectMon.playerMonMenu_HandleInput
	ld hl, hUILayoutFlags
	set BIT_DOUBLE_SPACED_MENU, [hl]
	call HandleMenuInput
	ld hl, hUILayoutFlags
	res BIT_DOUBLE_SPACED_MENU, [hl]
	and a ; was anything pressed?
	jr nz, TradeCenter_SelectMon.playerMonMenu_SomethingPressed
	jp TradeCenter_SelectMon.getNewInput
TradeCenter_SelectMon.playerMonMenu_SomethingPressed
	bit B_PAD_A, a
	jr z, TradeCenter_SelectMon.playerMonMenu_ANotPressed
	jp TradeCenter_SelectMon.chosePlayerMon ; jump if A button pressed
; unreachable code
	ld a, INIT_PLAYEROT_LIST
	ld [wInitListType], a
	callfar InitList ; the list isn't used
	call TradeCenter_DisplayStats
	jp TradeCenter_SelectMon.getNewInput
TradeCenter_SelectMon.playerMonMenu_ANotPressed
	bit B_PAD_RIGHT, a
	jr z, TradeCenter_SelectMon.playerMonMenu_RightNotPressed
; if Right pressed, switch to the enemy mon menu
	ld a, $1 ; enemy mon menu
	ld [wWhichTradeMonSelectionMenu], a
	ld a, [wMenuCursorLocation]
	ld l, a
	ld a, [wMenuCursorLocation + 1]
	ld h, a
	ld a, [wTileBehindCursor]
	ld [hl], a
	ld a, [wCurrentMenuItem]
	ld b, a
	ld a, [wEnemyPartyCount]
	dec a
	cp b
	jr nc, TradeCenter_SelectMon.notPastLastEnemyMon
; when switching to the enemy mon menu, if the menu selection would be past the last enemy mon, select the last enemy mon
	ld [wCurrentMenuItem], a
TradeCenter_SelectMon.notPastLastEnemyMon
	jp TradeCenter_SelectMon.enemyMonMenu
TradeCenter_SelectMon.playerMonMenu_RightNotPressed
	bit B_PAD_DOWN, a
	jr z, TradeCenter_SelectMon.getNewInput
	jp TradeCenter_SelectMon.selectedCancelMenuItem ; jump if Down pressed
TradeCenter_SelectMon.getNewInput
	ld a, [wWhichTradeMonSelectionMenu]
	and a
	jp z, TradeCenter_SelectMon.playerMonMenu_HandleInput
	jp TradeCenter_SelectMon.enemyMonMenu_HandleInput
TradeCenter_SelectMon.chosePlayerMon
	call SaveScreenTilesToBuffer1
	call PlaceUnfilledArrowMenuCursor
	ld a, [wMaxMenuItem]
	ld c, a
	ld a, [wCurrentMenuItem]
	cp c
	jr c, TradeCenter_SelectMon.displayStatsTradeMenu
	ld a, [wMaxMenuItem]
	dec a
TradeCenter_SelectMon.displayStatsTradeMenu
	push af
	hlcoord 0, 14
	ld b, 2
	ld c, 18
	call CableClub_TextBoxBorder
	hlcoord 2, 16
	ld de, TradeCenter_SelectMon.statsTrade
	call PlaceString
	xor a
	ld [wCurrentMenuItem], a
	ld [wLastMenuItem], a
	ld [wMenuJoypadPollCount], a
	ld [wMaxMenuItem], a
	ld a, 16
	ld [wTopMenuItemY], a
TradeCenter_SelectMon.selectStatsMenuItem
	ld a, $7f
	ldcoord_a 11, 16
	ld a, PAD_RIGHT | PAD_B | PAD_A
	ld [wMenuWatchedKeys], a
	ld a, 1
	ld [wTopMenuItemX], a
	call HandleMenuInput
	bit B_PAD_RIGHT, a
	jr nz, TradeCenter_SelectMon.selectTradeMenuItem
	bit B_PAD_B, a
	jr z, TradeCenter_SelectMon.displayPlayerMonStats
TradeCenter_SelectMon.cancelPlayerMonChoice
	pop af
	ld [wCurrentMenuItem], a
	call LoadScreenTilesFromBuffer1
	jp TradeCenter_SelectMon.playerMonMenu
TradeCenter_SelectMon.selectTradeMenuItem
	ld a, $7f
	ldcoord_a 1, 16
	ld a, PAD_LEFT | PAD_B | PAD_A
	ld [wMenuWatchedKeys], a
	ld a, 11
	ld [wTopMenuItemX], a
	call HandleMenuInput
	bit B_PAD_LEFT, a
	jr nz, TradeCenter_SelectMon.selectStatsMenuItem
	bit B_PAD_B, a
	jr nz, TradeCenter_SelectMon.cancelPlayerMonChoice
	jr TradeCenter_SelectMon.choseTrade
TradeCenter_SelectMon.displayPlayerMonStats
	pop af
	ld [wCurrentMenuItem], a
	ld a, INIT_PLAYEROT_LIST
	ld [wInitListType], a
	callfar InitList ; the list isn't used
	call TradeCenter_DisplayStats
	call LoadScreenTilesFromBuffer1
	jp TradeCenter_SelectMon.playerMonMenu
TradeCenter_SelectMon.choseTrade
	call PlaceUnfilledArrowMenuCursor
	pop af
	ld [wCurrentMenuItem], a
	ld [wTradingWhichPlayerMon], a
	ld [wSerialExchangeNybbleSendData], a
	call Serial_PrintWaitingTextAndSyncAndExchangeNybble
	ld a, [wSerialSyncAndExchangeNybbleReceiveData]
	cp $f
	jp z, CallCurrentTradeCenterFunction ; go back to the beginning of the trade selection menu if the other person cancelled
	ld [wTradingWhichEnemyMon], a
	call TradeCenter_PlaceSelectedEnemyMonMenuCursor
	ld a, $1 ; TradeCenter_Trade
	ld [wTradeCenterPointerTableIndex], a
	jp CallCurrentTradeCenterFunction
TradeCenter_SelectMon.statsTrade
		.STRINGMAP pokemon, "STATS     TRADE@"
TradeCenter_SelectMon.selectedCancelMenuItem
	ld a, [wCurrentMenuItem]
	ld b, a
	ld a, [wMaxMenuItem]
	cp b
	jp nz, TradeCenter_SelectMon.getNewInput
	ld a, [wMenuCursorLocation]
	ld l, a
	ld a, [wMenuCursorLocation + 1]
	ld h, a
	ld a, $7f
	ld [hl], a
TradeCenter_SelectMon.cancelMenuItem_Loop
	ld a, $ed ; filled arrow cursor
	ldcoord_a 1, 16
TradeCenter_SelectMon.cancelMenuItem_JoypadLoop
	call JoypadLowSensitivity
	ldh a, [lobyte(hJoy5)]
	and a ; pressed anything?
	jr z, TradeCenter_SelectMon.cancelMenuItem_JoypadLoop
	bit B_PAD_A, a
	jr nz, TradeCenter_SelectMon.cancelMenuItem_APressed
	bit B_PAD_UP, a
	jr z, TradeCenter_SelectMon.cancelMenuItem_JoypadLoop
; if Up pressed
	ld a, $7f
	ldcoord_a 1, 16
	ld a, [wPartyCount]
	dec a
	ld [wCurrentMenuItem], a
	jp TradeCenter_SelectMon.playerMonMenu
TradeCenter_SelectMon.cancelMenuItem_APressed
	ld a, $ec ; unfilled arrow cursor
	ldcoord_a 1, 16
	ld a, $f
	ld [wSerialExchangeNybbleSendData], a
	call Serial_PrintWaitingTextAndSyncAndExchangeNybble
	ld a, [wSerialSyncAndExchangeNybbleReceiveData]
	cp $f ; did the other person choose Cancel too?
	jr nz, TradeCenter_SelectMon.cancelMenuItem_Loop
	; fall through

ReturnToCableClubRoom:
	call GBPalWhiteOutWithDelay3
	ld hl, wFontLoaded
	ld a, [hl]
	push af
	push hl
	res BIT_FONT_LOADED, [hl]
	xor a
	ld [wStatusFlags3], a ; clears BIT_INIT_TRADE_CENTER_FACING
	dec a
	ld [wDestinationWarpID], a
	call LoadMapData
	farcall ClearVariablesOnEnterMap
	pop hl
	pop af
	ld [hl], a
	call GBFadeInFromWhite
	ret

TradeCenter_DrawCancelBox:
	hlcoord 11, 15
	ld a, $7e
	ld bc, 2 * SCREEN_WIDTH + 9
	call FillMemory
	hlcoord 0, 15
	ld b, 1
	ld c, 9
	call CableClub_TextBoxBorder
	hlcoord 2, 16
	ld de, CancelTextString
	jp PlaceString

CancelTextString:
		.STRINGMAP pokemon, "CANCEL@"

TradeCenter_PlaceSelectedEnemyMonMenuCursor:
	ld a, [wSerialSyncAndExchangeNybbleReceiveData]
	hlcoord 1, 9
	ld bc, SCREEN_WIDTH
	call AddNTimes
	ld [hl], $ec ; cursor
	ret

TradeCenter_DisplayStats:
	ld a, [wCurrentMenuItem]
	ld [wWhichPokemon], a
	predef StatusScreen
	predef StatusScreen2
	call GBPalNormal
	call LoadTrainerInfoTextBoxTiles
	call TradeCenter_DrawPartyLists
	jp TradeCenter_DrawCancelBox

TradeCenter_DrawPartyLists:
	hlcoord 0, 0
	ld b, 6
	ld c, 18
	call CableClub_TextBoxBorder
	hlcoord 0, 8
	ld b, 6
	ld c, 18
	call CableClub_TextBoxBorder
	hlcoord 5, 0
	ld de, wPlayerName
	call PlaceString
	hlcoord 5, 8
	ld de, wLinkEnemyTrainerName
	call PlaceString
	hlcoord 2, 1
	ld de, wPartySpecies
	call TradeCenter_PrintPartyListNames
	hlcoord 2, 9
	ld de, wEnemyPartySpecies
	; fall through

TradeCenter_PrintPartyListNames:
	ld c, $0
TradeCenter_PrintPartyListNames.loop
	ld a, [de]
	cp $ff
	ret z
	ld [wNamedObjectIndex], a
	push bc
	push hl
	push de
	push hl
	ld a, c
	ldh [lobyte(hPastLeadingZeros)], a
	call GetMonName
	pop hl
	call PlaceString
	pop de
	inc de
	pop hl
	ld bc, SCREEN_WIDTH
	add hl, bc
	pop bc
	inc c
	jr TradeCenter_PrintPartyListNames.loop

TradeCenter_Trade:
	ld c, 100
	call DelayFrames
	xor a
	ld [wSerialExchangeNybbleSendData + 1], a ; unnecessary
	ld [wSerialExchangeNybbleReceiveData], a
	ld [wMenuWatchMovingOutOfBounds], a
	ld [wMenuJoypadPollCount], a
	hlcoord 0, 12
	ld b, 4
	ld c, 18
	call CableClub_TextBoxBorder
	ld a, [wTradingWhichPlayerMon]
	ld hl, wPartySpecies
	ld c, a
	ld b, 0
	add hl, bc
	ld a, [hl]
	ld [wNamedObjectIndex], a
	call GetMonName
	ld hl, wNameBuffer
	ld de, wNameOfPlayerMonToBeTraded
	ld bc, NAME_LENGTH
	call CopyData
	ld a, [wTradingWhichEnemyMon]
	ld hl, wEnemyPartySpecies
	ld c, a
	ld b, 0
	add hl, bc
	ld a, [hl]
	ld [wNamedObjectIndex], a
	call GetMonName
	ld hl, WillBeTradedText
	bccoord 1, 14
	call TextCommandProcessor
	call SaveScreenTilesToBuffer1
	hlcoord 10, 7
	lb "bc", 8, 11
	ld a, TRADE_CANCEL_MENU
	ld [wTwoOptionMenuID], a
	ld a, TWO_OPTION_MENU
	ld [wTextBoxID], a
	call DisplayTextBoxID
	call LoadScreenTilesFromBuffer1
	ld a, [wCurrentMenuItem]
	and a
	jr z, TradeCenter_Trade.tradeConfirmed
; if trade cancelled
	ld a, $1
	ld [wSerialExchangeNybbleSendData], a
	hlcoord 0, 12
	ld b, 4
	ld c, 18
	call CableClub_TextBoxBorder
	hlcoord 1, 14
	ld de, TradeCanceled
	call PlaceString
	call Serial_PrintWaitingTextAndSyncAndExchangeNybble
	jp TradeCenter_Trade.tradeCancelled
TradeCenter_Trade.tradeConfirmed
	ld a, $2
	ld [wSerialExchangeNybbleSendData], a
	call Serial_PrintWaitingTextAndSyncAndExchangeNybble
	ld a, [wSerialSyncAndExchangeNybbleReceiveData]
	dec a ; did the other person cancel?
	jr nz, TradeCenter_Trade.doTrade
; if the other person cancelled
	hlcoord 0, 12
	ld b, 4
	ld c, 18
	call CableClub_TextBoxBorder
	hlcoord 1, 14
	ld de, TradeCanceled
	call PlaceString
	jp TradeCenter_Trade.tradeCancelled
TradeCenter_Trade.doTrade
	ld a, [wTradingWhichPlayerMon]
	ld hl, wPartyMonOT
	call SkipFixedLengthTextEntries
	ld de, wTradedPlayerMonOT
	ld bc, NAME_LENGTH
	call CopyData
	ld hl, wPartyMon1Species
	ld a, [wTradingWhichPlayerMon]
	ld bc, PARTYMON_STRUCT_LENGTH
	call AddNTimes
	ld bc, MON_OTID
	add hl, bc
	ld a, [hli]
	ld [wTradedPlayerMonOTID], a
	ld a, [hl]
	ld [wTradedPlayerMonOTID + 1], a
	ld a, [wTradingWhichEnemyMon]
	ld hl, wEnemyMonOT
	call SkipFixedLengthTextEntries
	ld de, wTradedEnemyMonOT
	ld bc, NAME_LENGTH
	call CopyData
	ld hl, wEnemyMons
	ld a, [wTradingWhichEnemyMon]
	ld bc, PARTYMON_STRUCT_LENGTH
	call AddNTimes
	ld bc, MON_OTID
	add hl, bc
	ld a, [hli]
	ld [wTradedEnemyMonOTID], a
	ld a, [hl]
	ld [wTradedEnemyMonOTID + 1], a
	ld a, [wTradingWhichPlayerMon]
	ld [wWhichPokemon], a
	ld hl, wPartySpecies
	ld b, 0
	ld c, a
	add hl, bc
	ld a, [hl]
	ld [wTradedPlayerMonSpecies], a
	xor a
	ld [wRemoveMonFromBox], a
	call RemovePokemon
	ld a, [wTradingWhichEnemyMon]
	ld c, a
	ld [wWhichPokemon], a
	ld hl, wEnemyPartySpecies
	ld d, 0
	ld e, a
	add hl, de
	ld a, [hl]
	ld [wCurPartySpecies], a
	ld hl, wEnemyMons
	ld a, c
	ld bc, PARTYMON_STRUCT_LENGTH
	call AddNTimes
	ld de, wLoadedMon
	ld bc, PARTYMON_STRUCT_LENGTH
	call CopyData
	call AddEnemyMonToPlayerParty
	ld a, [wPartyCount]
	dec a
	ld [wWhichPokemon], a
	ld a, TRUE
	ld [wForceEvolution], a
	ld a, [wTradingWhichEnemyMon]
	ld hl, wEnemyPartySpecies
	ld b, 0
	ld c, a
	add hl, bc
	ld a, [hl]
	ld [wTradedEnemyMonSpecies], a
	ld a, 10
	ld [wAudioFadeOutControl], a
	ld a, bank(Music_SafariZone)
	ld [wAudioSavedROMBank], a
	ld a, MUSIC_SAFARI_ZONE
	ld [wNewSoundID], a
	call PlaySound
	ld c, 100
	call DelayFrames
	call ClearScreen
	call LoadHpBarAndStatusTilePatterns
	xor a
	ld [wUnusedFlag], a
	ldh a, [lobyte(hSerialConnectionStatus)]
	cp USING_EXTERNAL_CLOCK
	jr z, TradeCenter_Trade.usingExternalClock
	predef InternalClockTradeAnim
	jr TradeCenter_Trade.tradeCompleted
TradeCenter_Trade.usingExternalClock
	predef ExternalClockTradeAnim
TradeCenter_Trade.tradeCompleted
	callfar TryEvolvingMon
	call ClearScreen
	call LoadTrainerInfoTextBoxTiles
	call Serial_PrintWaitingTextAndSyncAndExchangeNybble
	ld c, 40
	call DelayFrames
	hlcoord 0, 12
	ld b, 4
	ld c, 18
	call CableClub_TextBoxBorder
	hlcoord 1, 14
	ld de, TradeCompleted
	call PlaceString
	predef SavePartyAndDexData ; this allows reset into Pokecenter
	vc_hook Trade_save_game_end
	ld c, 50
	call DelayFrames
	xor a
	ld [wTradeCenterPointerTableIndex], a
	jp CableClub_DoBattleOrTradeAgain
TradeCenter_Trade.tradeCancelled
	ld c, 100
	call DelayFrames
	xor a ; TradeCenter_SelectMon
	ld [wTradeCenterPointerTableIndex], a
	jp CallCurrentTradeCenterFunction

WillBeTradedText:
	text_far WLA_GLOBAL_WillBeTradedText
	text_end

TradeCompleted:
		.STRINGMAP pokemon, "Trade completed!@"

TradeCanceled:
		.STRINGMAP pokemon, "Too bad! The trade"
	next "was canceled!@"

TradeCenterPointerTable:
	.DW TradeCenter_SelectMon
	.DW TradeCenter_Trade

CableClub_Run:
	ld a, [wLinkState]
	cp LINK_STATE_START_TRADE
	jr z, CableClub_Run.doBattleOrTrade
	cp LINK_STATE_START_BATTLE
	jr z, CableClub_Run.doBattleOrTrade
	cp LINK_STATE_RESET ; this is never used
	ret nz
	predef EmptyFunc
	jp Init
CableClub_Run.doBattleOrTrade
	call CableClub_DoBattleOrTrade
	ld hl, Club_GFX
	ld a, h
	ld [wTilesetGfxPtr + 1], a
	ld a, l
	ld [wTilesetGfxPtr], a
	ld a, bank(Club_GFX)
	ld [wTilesetBank], a
	ld hl, Club_Coll
	ld a, h
	ld [wTilesetCollisionPtr + 1], a
	ld a, l
	ld [wTilesetCollisionPtr], a
	xor a
	ld [wGrassRate], a
	inc a ; LINK_STATE_IN_CABLE_CLUB
	ld [wLinkState], a
	ldh [lobyte(hJoy5)], a
	ld a, 10
	ld [wAudioFadeOutControl], a
	ld a, bank(Music_Celadon)
	ld [wAudioSavedROMBank], a
	ld a, MUSIC_CELADON
	ld [wNewSoundID], a
	jp PlaySound

EmptyFunc:
	ret

Diploma_TextBoxBorder:
	call GetPredefRegisters

; b = height
; c = width
CableClub_TextBoxBorder:
	push hl
	ld a, $78 ; border upper left corner tile
	ld [hli], a
	inc a ; border top horizontal line tile
	call CableClub_DrawHorizontalLine
	inc a ; border upper right corner tile
	ld [hl], a
	pop hl
	ld de, 20
	add hl, de
CableClub_TextBoxBorder.loop
	push hl
	ld a, $7b ; border left vertical line tile
	ld [hli], a
	ld a, $7f
	call CableClub_DrawHorizontalLine
	ld [hl], $77 ; border right vertical line tile
	pop hl
	ld de, 20
	add hl, de
	dec b
	jr nz, CableClub_TextBoxBorder.loop
	ld a, $7c ; border lower left corner tile
	ld [hli], a
	ld a, $76 ; border bottom horizontal line tile
	call CableClub_DrawHorizontalLine
	ld [hl], $7d ; border lower right corner tile
	ret

; c = width
CableClub_DrawHorizontalLine:
	ld d, c
CableClub_DrawHorizontalLine.loop
	ld [hli], a
	dec d
	jr nz, CableClub_DrawHorizontalLine.loop
	ret

LoadTrainerInfoTextBoxTiles:
	ld de, TrainerInfoTextBoxTileGraphics
	ld hl, vChars2 + TILE_SIZE * $76
	lb "bc", bank(TrainerInfoTextBoxTileGraphics), (TrainerInfoTextBoxTileGraphicsEnd - TrainerInfoTextBoxTileGraphics) / TILE_SIZE
	jp CopyVideoData
