CeruleanTrashedHouse_Script:
	call EnableAutoTextBoxDrawing
	ret

CeruleanTrashedHouse_TextPointers:
	def_text_pointers
	dw_const CeruleanTrashedHouseFishingGuruText, TEXT_CERULEANTRASHEDHOUSE_FISHING_GURU
	dw_const CeruleanTrashedHouseGirlText,        TEXT_CERULEANTRASHEDHOUSE_GIRL
	dw_const CeruleanTrashedHouseWallHoleText,    TEXT_CERULEANTRASHEDHOUSE_WALL_HOLE

CeruleanTrashedHouseFishingGuruText:
	text_asm
	ld b, TM_DIG
	predef GetQuantityOfItemInBag
	and b
	jr z, CeruleanTrashedHouseFishingGuruText.no_dig_tm
	ld hl, CeruleanTrashedHouseFishingGuruText.WhatsLostIsLostText
	call PrintText
	jr CeruleanTrashedHouseFishingGuruText.done
CeruleanTrashedHouseFishingGuruText.no_dig_tm
	ld hl, CeruleanTrashedHouseFishingGuruText.TheyStoleATMText
	call PrintText
CeruleanTrashedHouseFishingGuruText.done
	jp TextScriptEnd

CeruleanTrashedHouseFishingGuruText.TheyStoleATMText:
	text_far WLA_GLOBAL_CeruleanTrashedHouseFishingGuruTheyStoleATMText
	text_end

CeruleanTrashedHouseFishingGuruText.WhatsLostIsLostText:
	text_far WLA_GLOBAL_CeruleanTrashedHouseFishingGuruWhatsLostIsLostText
	text_end

CeruleanTrashedHouseGirlText:
	text_far WLA_GLOBAL_CeruleanTrashedHouseGirlText
	text_end

CeruleanTrashedHouseWallHoleText:
	text_far WLA_GLOBAL_CeruleanTrashedHouseWallHoleText
	text_end
