CinnabarLabMetronomeRoom_Script:
	jp EnableAutoTextBoxDrawing

CinnabarLabMetronomeRoom_TextPointers:
	def_text_pointers
	dw_const CinnabarLabMetronomeRoomScientist1Text, TEXT_CINNABARLABMETRONOMEROOM_SCIENTIST1
	dw_const CinnabarLabMetronomeRoomScientist2Text, TEXT_CINNABARLABMETRONOMEROOM_SCIENTIST2
	dw_const CinnabarLabMetronomeRoomPCText,         TEXT_CINNABARLABMETRONOMEROOM_PC_KEYBOARD
	dw_const CinnabarLabMetronomeRoomPCText,         TEXT_CINNABARLABMETRONOMEROOM_PC_MONITOR
	dw_const CinnabarLabMetronomeRoomAmberPipeText,  TEXT_CINNABARLABMETRONOMEROOM_AMBER_PIPE

CinnabarLabMetronomeRoomScientist1Text:
	text_asm
	CheckEvent EVENT_GOT_TM35
	jr nz, CinnabarLabMetronomeRoomScientist1Text.got_item
	ld hl, CinnabarLabMetronomeRoomScientist1Text.Text
	call PrintText
	lb "bc", TM_METRONOME, 1
	call GiveItem
	jr nc, CinnabarLabMetronomeRoomScientist1Text.bag_full
	ld hl, CinnabarLabMetronomeRoomScientist1Text.ReceivedTM35Text
	call PrintText
	SetEvent EVENT_GOT_TM35
	jr CinnabarLabMetronomeRoomScientist1Text.done
CinnabarLabMetronomeRoomScientist1Text.bag_full
	ld hl, CinnabarLabMetronomeRoomScientist1Text.TM35NoRoomText
	call PrintText
	jr CinnabarLabMetronomeRoomScientist1Text.done
CinnabarLabMetronomeRoomScientist1Text.got_item
	ld hl, CinnabarLabMetronomeRoomScientist1Text.TM35ExplanationText
	call PrintText
CinnabarLabMetronomeRoomScientist1Text.done
	jp TextScriptEnd

CinnabarLabMetronomeRoomScientist1Text.Text:
	text_far WLA_GLOBAL_CinnabarLabMetronomeRoomScientist1Text
	text_end

CinnabarLabMetronomeRoomScientist1Text.ReceivedTM35Text:
	text_far WLA_GLOBAL_CinnabarLabMetronomeRoomScientist1ReceivedTM35Text
	sound_get_item_1
	text_end

CinnabarLabMetronomeRoomScientist1Text.TM35ExplanationText:
	text_far WLA_GLOBAL_CinnabarLabMetronomeRoomScientist1TM35ExplanationText
	text_end

CinnabarLabMetronomeRoomScientist1Text.TM35NoRoomText:
	text_far WLA_GLOBAL_CinnabarLabMetronomeRoomScientist1TM35NoRoomText
	text_end

CinnabarLabMetronomeRoomScientist2Text:
	text_far WLA_GLOBAL_CinnabarLabMetronomeRoomScientist2Text
	text_end

CinnabarLabMetronomeRoomPCText:
	text_far WLA_GLOBAL_CinnabarLabMetronomeRoomPCText
	text_end

CinnabarLabMetronomeRoomAmberPipeText:
	text_far WLA_GLOBAL_CinnabarLabMetronomeRoomAmberPipeText
	text_end
