LavenderCuboneHouse_Script:
	call EnableAutoTextBoxDrawing
	ret

LavenderCuboneHouse_TextPointers:
	def_text_pointers
	dw_const LavenderCuboneHouseCuboneText,       TEXT_LAVENDERCUBONEHOUSE_CUBONE
	dw_const LavenderCuboneHouseBrunetteGirlText, TEXT_LAVENDERCUBONEHOUSE_BRUNETTE_GIRL

LavenderCuboneHouseCuboneText:
	text_far WLA_GLOBAL_LavenderCuboneHouseCuboneText
	text_asm
	ld a, CUBONE
	call PlayCry
	jp TextScriptEnd

LavenderCuboneHouseBrunetteGirlText:
	text_asm
	CheckEvent EVENT_RESCUED_MR_FUJI
	jr nz, LavenderCuboneHouseBrunetteGirlText.rescued_mr_fuji
	ld hl, LavenderCuboneHouseBrunetteGirlText.PoorCubonesMotherText
	call PrintText
	jr LavenderCuboneHouseBrunetteGirlText.done
LavenderCuboneHouseBrunetteGirlText.rescued_mr_fuji
	ld hl, LavenderCuboneHouseBrunetteGirlText.TheGhostIsGoneText
	call PrintText
LavenderCuboneHouseBrunetteGirlText.done
	jp TextScriptEnd

LavenderCuboneHouseBrunetteGirlText.PoorCubonesMotherText:
	text_far WLA_GLOBAL_LavenderCuboneHouseBrunetteGirlPoorCubonesMotherText
	text_end

LavenderCuboneHouseBrunetteGirlText.TheGhostIsGoneText:
	text_far WLA_GLOBAL_LavenderCuboneHouseBrunetteGirlGhostIsGoneText
	text_end
