Route12SuperRodHouse_Script:
	jp EnableAutoTextBoxDrawing

Route12SuperRodHouse_TextPointers:
	def_text_pointers
	dw_const Route12SuperRodHouseFishingGuruText, TEXT_ROUTE12SUPERRODHOUSE_FISHING_GURU

Route12SuperRodHouseFishingGuruText:
	text_asm
	ld a, [wStatusFlags1]
	bit BIT_GOT_SUPER_ROD, a
	jr nz, Route12SuperRodHouseFishingGuruText.got_item
	ld hl, Route12SuperRodHouseFishingGuruText.DoYouLikeToFishText
	call PrintText
	call YesNoChoice
	ld a, [wCurrentMenuItem]
	and a
	jr nz, Route12SuperRodHouseFishingGuruText.refused
	lb "bc", SUPER_ROD, 1
	call GiveItem
	jr nc, Route12SuperRodHouseFishingGuruText.bag_full
	ld hl, wStatusFlags1
	set BIT_GOT_SUPER_ROD, [hl]
	ld hl, Route12SuperRodHouseFishingGuruText.ReceivedSuperRodText
	jr Route12SuperRodHouseFishingGuruText.done
Route12SuperRodHouseFishingGuruText.bag_full
	ld hl, Route12SuperRodHouseFishingGuruText.NoRoomText
	jr Route12SuperRodHouseFishingGuruText.done
Route12SuperRodHouseFishingGuruText.refused
	ld hl, Route12SuperRodHouseFishingGuruText.ThatsDisappointingText
	jr Route12SuperRodHouseFishingGuruText.done
Route12SuperRodHouseFishingGuruText.got_item
	ld hl, Route12SuperRodHouseFishingGuruText.TryFishingText
Route12SuperRodHouseFishingGuruText.done
	call PrintText
	jp TextScriptEnd

Route12SuperRodHouseFishingGuruText.DoYouLikeToFishText:
	text_far WLA_GLOBAL_Route12SuperRodHouseFishingGuruDoYouLikeToFishText
	text_end

Route12SuperRodHouseFishingGuruText.ReceivedSuperRodText:
	text_far WLA_GLOBAL_Route12SuperRodHouseFishingGuruReceivedSuperRodText
	sound_get_item_1
	text_far WLA_GLOBAL_Route12SuperRodHouseFishingGuruFishingWayOfLifeText
	text_end

Route12SuperRodHouseFishingGuruText.ThatsDisappointingText:
	text_far WLA_GLOBAL_Route12SuperRodHouseFishingGuruThatsDisappointingText
	text_end

Route12SuperRodHouseFishingGuruText.TryFishingText:
	text_far WLA_GLOBAL_Route12SuperRodHouseFishingGuruTryFishingText
	text_end

Route12SuperRodHouseFishingGuruText.NoRoomText:
	text_far WLA_GLOBAL_Route12SuperRodHouseFishingGuruNoRoomText
	text_end
