SafariZoneWestRestHouse_Script:
	call EnableAutoTextBoxDrawing
	ret

SafariZoneWestRestHouse_TextPointers:
	def_text_pointers
	dw_const SafariZoneWestRestHouseScientistText,    TEXT_SAFARIZONEWESTRESTHOUSE_SCIENTIST
	dw_const SafariZoneWestRestHouseCooltrainerMText, TEXT_SAFARIZONEWESTRESTHOUSE_COOLTRAINER_M
	dw_const SafariZoneWestRestHouseSilphWorkerFText, TEXT_SAFARIZONEWESTRESTHOUSE_SILPH_WORKER_F

SafariZoneWestRestHouseScientistText:
	text_far WLA_GLOBAL_SafariZoneWestRestHouseScientistText
	text_end

SafariZoneWestRestHouseCooltrainerMText:
	text_far WLA_GLOBAL_SafariZoneWestRestHouseCooltrainerMText
	text_end

SafariZoneWestRestHouseSilphWorkerFText:
	text_far WLA_GLOBAL_SafariZoneWestRestHouseSilphWorkerFText
	text_end
