SafariZoneCenterRestHouse_Script:
	jp EnableAutoTextBoxDrawing

SafariZoneCenterRestHouse_TextPointers:
	def_text_pointers
	dw_const SafariZoneCenterRestHouseGirlText,      TEXT_SAFARIZONECENTERRESTHOUSE_GIRL
	dw_const SafariZoneCenterRestHouseScientistText, TEXT_SAFARIZONECENTERRESTHOUSE_SCIENTIST

SafariZoneCenterRestHouseGirlText:
	text_far WLA_GLOBAL_SafariZoneCenterRestHouseGirlText
	text_end

SafariZoneCenterRestHouseScientistText:
	text_far WLA_GLOBAL_SafariZoneCenterRestHouseScientistText
	text_end
