SafariZoneSecretHouse_Script:
	jp EnableAutoTextBoxDrawing

SafariZoneSecretHouse_TextPointers:
	def_text_pointers
	dw_const SafariZoneSecretHouseFishingGuruText, TEXT_SAFARIZONESECRETHOUSE_FISHING_GURU

SafariZoneSecretHouseFishingGuruText:
	text_asm
	CheckEvent EVENT_GOT_HM03
	jr nz, SafariZoneSecretHouseFishingGuruText.got_item
	ld hl, SafariZoneSecretHouseFishingGuruText.YouHaveWonText
	call PrintText
	lb "bc", HM_SURF, 1
	call GiveItem
	jr nc, SafariZoneSecretHouseFishingGuruText.bag_full
	ld hl, SafariZoneSecretHouseFishingGuruText.ReceivedHM03Text
	call PrintText
	SetEvent EVENT_GOT_HM03
	jr SafariZoneSecretHouseFishingGuruText.done
SafariZoneSecretHouseFishingGuruText.bag_full
	ld hl, SafariZoneSecretHouseFishingGuruText.HM03NoRoomText
	call PrintText
	jr SafariZoneSecretHouseFishingGuruText.done
SafariZoneSecretHouseFishingGuruText.got_item
	ld hl, SafariZoneSecretHouseFishingGuruText.HM03ExplanationText
	call PrintText
SafariZoneSecretHouseFishingGuruText.done
	jp TextScriptEnd

SafariZoneSecretHouseFishingGuruText.YouHaveWonText:
	text_far WLA_GLOBAL_SafariZoneSecretHouseFishingGuruYouHaveWonText
	text_end

SafariZoneSecretHouseFishingGuruText.ReceivedHM03Text:
	text_far WLA_GLOBAL_SafariZoneSecretHouseFishingGuruReceivedHM03Text
	sound_get_item_1
	text_end

SafariZoneSecretHouseFishingGuruText.HM03ExplanationText:
	text_far WLA_GLOBAL_SafariZoneSecretHouseFishingGuruHM03ExplanationText
	text_end

SafariZoneSecretHouseFishingGuruText.HM03NoRoomText:
	text_far WLA_GLOBAL_SafariZoneSecretHouseFishingGuruHM03NoRoomText
	text_end
