VermilionOldRodHouse_Script:
	jp EnableAutoTextBoxDrawing

VermilionOldRodHouse_TextPointers:
	def_text_pointers
	dw_const VermilionOldRodHouseFishingGuruText, TEXT_VERMILIONOLDRODHOUSE_FISHING_GURU

VermilionOldRodHouseFishingGuruText:
	text_asm
	ld a, [wStatusFlags1]
	bit BIT_GOT_OLD_ROD, a
	jr nz, VermilionOldRodHouseFishingGuruText.got_old_rod
	ld hl, VermilionOldRodHouseFishingGuruText.DoYouLikeToFishText
	call PrintText
	call YesNoChoice
	ld a, [wCurrentMenuItem]
	and a
	jr nz, VermilionOldRodHouseFishingGuruText.refused
	lb "bc", OLD_ROD, 1
	call GiveItem
	jr nc, VermilionOldRodHouseFishingGuruText.bag_full
	ld hl, wStatusFlags1
	set BIT_GOT_OLD_ROD, [hl]
	ld hl, VermilionOldRodHouseFishingGuruText.TakeThisText
	jr VermilionOldRodHouseFishingGuruText.print_text
VermilionOldRodHouseFishingGuruText.bag_full
	ld hl, VermilionOldRodHouseFishingGuruText.NoRoomText
	jr VermilionOldRodHouseFishingGuruText.print_text
VermilionOldRodHouseFishingGuruText.refused
	ld hl, VermilionOldRodHouseFishingGuruText.ThatsSoDisappointingText
	jr VermilionOldRodHouseFishingGuruText.print_text
VermilionOldRodHouseFishingGuruText.got_old_rod
	ld hl, VermilionOldRodHouseFishingGuruText.HowAreTheFishBitingText
VermilionOldRodHouseFishingGuruText.print_text
	call PrintText
	jp TextScriptEnd

VermilionOldRodHouseFishingGuruText.DoYouLikeToFishText:
	text_far WLA_GLOBAL_VermilionOldRodHouseFishingGuruDoYouLikeToFishText
	text_end

VermilionOldRodHouseFishingGuruText.TakeThisText:
	text_far WLA_GLOBAL_VermilionOldRodHouseFishingGuruTakeThisText
	sound_get_item_1
	text_far WLA_GLOBAL_VermilionOldRodHouseFishingGuruFishingIsAWayOfLifeText
	text_end

VermilionOldRodHouseFishingGuruText.ThatsSoDisappointingText:
	text_far WLA_GLOBAL_VermilionOldRodHouseFishingGuruThatsSoDisappointingText
	text_end

VermilionOldRodHouseFishingGuruText.HowAreTheFishBitingText:
	text_far WLA_GLOBAL_VermilionOldRodHouseFishingGuruHowAreTheFishBitingText
	text_end

VermilionOldRodHouseFishingGuruText.NoRoomText:
	text_far WLA_GLOBAL_VermilionOldRodHouseFishingGuruNoRoomText
	text_end
