ViridianForestSouthGate_Script:
	jp EnableAutoTextBoxDrawing

ViridianForestSouthGate_TextPointers:
	def_text_pointers
	dw_const ViridianForestSouthGateGirlText,       TEXT_VIRIDIANFORESTSOUTHGATE_GIRL
	dw_const ViridianForestSouthGateLittleGirlText, TEXT_VIRIDIANFORESTSOUTHGATE_LITTLE_GIRL

ViridianForestSouthGateGirlText:
	text_far WLA_GLOBAL_ViridianForestSouthGateGirlText
	text_end

ViridianForestSouthGateLittleGirlText:
	text_far WLA_GLOBAL_ViridianForestSouthGateLittleGirlText
	text_end
